import type { SupportedLocale } from "@/lib/market/registry";

export type AboutMessages = Readonly<{
  metadataTitle: string;
  metadataDescription: string;
  eyebrow: string;
  titleLead: string;
  titleEmphasis: string;
  introduction: string;
  partsTitle: string;
  parts: readonly [Readonly<{ title: string; body: string }>, Readonly<{ title: string; body: string }>, Readonly<{ title: string; body: string }>];
  partsNote: string;
  fundingTitle: string;
  fundingBody: string;
  disclosureLink: string;
  separationTitle: string;
  separationPoints: readonly [string, string, string];
  boundariesLabel: string;
  boundariesTitle: string;
  boundaries: readonly [string, string, string];
}>;

const catalog: Record<SupportedLocale, AboutMessages> = {
  "en-GB": {
    metadataTitle: "About B4GAMBLE | Learn, Reflect, Compare",
    metadataDescription: "How B4GAMBLE puts education before comparison and keeps Programme reflection separate from commercial information.",
    eyebrow: "About B4GAMBLE", titleLead: "Built to be", titleEmphasis: "on your side.",
    introduction: "A product about gambling should put the person first. We explain evidence and material terms, support self-directed control, and keep those jobs honestly separated.",
    partsTitle: "One product. Three parts.",
    parts: [
      { title: "The Programme", body: "A free-to-use, self-directed 10-step Programme. Programme data is not used for commercial targeting, offers or rankings." },
      { title: "Research & education", body: "Reviews identify their evidence and limitations; guides explain material terms in plain language." },
      { title: "Commercial discovery", body: "Best Offers, Casinos and Bonuses are clearly labelled commercial pages for adults who have decided to compare published records." },
    ],
    partsNote: "There is no forced path between them. You can use a review, the Programme or both. Protected areas do not become acquisition funnels.",
    fundingTitle: "How we make money", fundingBody: "When an independently authorised commercial link is available and used, B4GAMBLE may earn commission. Affiliate compensation does not determine Editor Score or natural editorial ranking.", disclosureLink: "Full affiliate disclosure →",
    separationTitle: "What stays separate", separationPoints: ["Commercial availability does not set editorial scores.", "Programme and Help data never feeds offers or rankings.", "Protected Help contains no casino, bonus or affiliate actions."],
    boundariesLabel: "What B4GAMBLE is not", boundariesTitle: "Clear lines, kept.", boundaries: ["Not a casino. We never take bets or hold your money.", "Not a therapy service. The Programme does not diagnose or treat.", "Not a claim of availability. Missing jurisdiction, publication or commercial evidence fails closed."],
  },
  "de-DE": {
    metadataTitle: "Über B4GAMBLE | Lernen, reflektieren, vergleichen", metadataDescription: "Wie B4GAMBLE Bildung vor Vergleich stellt und Programm-Reflexion von kommerziellen Informationen trennt.",
    eyebrow: "Über B4GAMBLE", titleLead: "Entwickelt, um", titleEmphasis: "auf deiner Seite zu sein.", introduction: "Ein Produkt über Glücksspiel sollte den Menschen zuerst sehen. Wir erklären Nachweise und wesentliche Bedingungen, unterstützen selbstbestimmte Kontrolle und trennen diese Aufgaben klar.", partsTitle: "Ein Produkt. Drei Bereiche.",
    parts: [{ title: "Das Programm", body: "Ein kostenlos nutzbares, selbstbestimmtes 10-Schritte-Programm. Programmdaten werden nicht für kommerzielle Zielgruppen, Angebote oder Rankings verwendet." }, { title: "Recherche & Bildung", body: "Bewertungen nennen ihre Nachweise und Grenzen; Leitfäden erklären wesentliche Bedingungen verständlich." }, { title: "Kommerzielle Suche", body: "Beste Angebote, Casinos und Boni sind klar gekennzeichnete kommerzielle Seiten für Erwachsene, die veröffentlichte Einträge vergleichen möchten." }],
    partsNote: "Es gibt keinen erzwungenen Weg zwischen ihnen. Du kannst eine Bewertung, das Programm oder beides nutzen. Geschützte Bereiche werden nicht zu Werbetrichtern.", fundingTitle: "Wie wir uns finanzieren", fundingBody: "Wenn ein unabhängig autorisierter kommerzieller Link verfügbar ist und genutzt wird, kann B4GAMBLE eine Provision erhalten. Affiliate-Vergütung bestimmt weder Editor Score noch die natürliche redaktionelle Rangfolge.", disclosureLink: "Vollständiger Affiliate-Hinweis →", separationTitle: "Was getrennt bleibt", separationPoints: ["Kommerzielle Verfügbarkeit bestimmt keine redaktionellen Bewertungen.", "Programm- und Hilfedaten fließen nie in Angebote oder Rankings ein.", "Geschützte Hilfe enthält keine Casino-, Bonus- oder Affiliate-Aktionen."], boundariesLabel: "Was B4GAMBLE nicht ist", boundariesTitle: "Klare Grenzen, eingehalten.", boundaries: ["Kein Casino. Wir nehmen keine Einsätze an und verwahren kein Geld.", "Kein Therapieangebot. Das Programm diagnostiziert oder behandelt nicht.", "Keine Verfügbarkeitszusage. Fehlende Zuständigkeits-, Veröffentlichungs- oder kommerzielle Nachweise bleiben gesperrt."],
  },
  "it-IT": {
    metadataTitle: "Chi è B4GAMBLE | Impara, rifletti, confronta", metadataDescription: "Come B4GAMBLE mette l'educazione prima del confronto e separa le riflessioni del Programma dalle informazioni commerciali.",
    eyebrow: "Chi è B4GAMBLE", titleLead: "Creato per essere", titleEmphasis: "dalla tua parte.", introduction: "Un prodotto sul gioco d'azzardo deve mettere prima la persona. Spieghiamo prove e condizioni rilevanti, sosteniamo il controllo autonomo e manteniamo queste funzioni chiaramente separate.", partsTitle: "Un prodotto. Tre aree.",
    parts: [{ title: "Il Programma", body: "Un Programma autonomo in 10 passi, gratuito da usare. I dati del Programma non vengono usati per targeting commerciale, offerte o classifiche." }, { title: "Ricerca e formazione", body: "Le recensioni indicano prove e limiti; le guide spiegano in modo semplice le condizioni rilevanti." }, { title: "Scoperta commerciale", body: "Migliori offerte, Casinò e Bonus sono pagine commerciali chiaramente indicate per adulti che hanno deciso di confrontare dati pubblicati." }],
    partsNote: "Non esiste un percorso obbligato. Puoi usare una recensione, il Programma o entrambi. Le aree protette non diventano canali di acquisizione.", fundingTitle: "Come ci finanziamo", fundingBody: "Quando un link commerciale autorizzato in modo indipendente è disponibile e viene usato, B4GAMBLE può ricevere una commissione. Il compenso affiliato non determina l'Editor Score né l'ordine editoriale naturale.", disclosureLink: "Informativa affiliati completa →", separationTitle: "Cosa resta separato", separationPoints: ["La disponibilità commerciale non determina i punteggi editoriali.", "I dati di Programma e Aiuto non alimentano offerte o classifiche.", "L'Aiuto protetto non contiene azioni di casinò, bonus o affiliazione."], boundariesLabel: "Cosa non è B4GAMBLE", boundariesTitle: "Confini chiari, rispettati.", boundaries: ["Non è un casinò. Non accettiamo scommesse né custodiamo denaro.", "Non è un servizio terapeutico. Il Programma non diagnostica né cura.", "Non è una promessa di disponibilità. Se mancano prove giurisdizionali, editoriali o commerciali, l'accesso resta chiuso."],
  },
  "es-ES": {
    metadataTitle: "Acerca de B4GAMBLE | Aprende, reflexiona, compara", metadataDescription: "Cómo B4GAMBLE antepone la educación a la comparación y separa la reflexión del Programa de la información comercial.",
    eyebrow: "Acerca de B4GAMBLE", titleLead: "Creado para estar", titleEmphasis: "de tu lado.", introduction: "Un producto sobre juego debe poner primero a la persona. Explicamos pruebas y condiciones relevantes, apoyamos el control autodirigido y mantenemos estas funciones claramente separadas.", partsTitle: "Un producto. Tres áreas.",
    parts: [{ title: "El Programa", body: "Un Programa autodirigido de 10 pasos y de uso gratuito. Los datos del Programa no se usan para segmentación comercial, ofertas ni clasificaciones." }, { title: "Investigación y educación", body: "Las reseñas identifican sus pruebas y límites; las guías explican las condiciones relevantes con claridad." }, { title: "Descubrimiento comercial", body: "Mejores ofertas, Casinos y Bonos son páginas comerciales claramente indicadas para adultos que han decidido comparar registros publicados." }],
    partsNote: "No hay un recorrido obligatorio. Puedes usar una reseña, el Programa o ambos. Las áreas protegidas no se convierten en embudos comerciales.", fundingTitle: "Cómo nos financiamos", fundingBody: "Cuando existe y se utiliza un enlace comercial autorizado de forma independiente, B4GAMBLE puede recibir una comisión. La compensación de afiliación no determina el Editor Score ni el orden editorial natural.", disclosureLink: "Divulgación de afiliación completa →", separationTitle: "Lo que permanece separado", separationPoints: ["La disponibilidad comercial no determina las puntuaciones editoriales.", "Los datos del Programa y de Ayuda nunca alimentan ofertas ni clasificaciones.", "La Ayuda protegida no contiene acciones de casino, bonos o afiliación."], boundariesLabel: "Lo que B4GAMBLE no es", boundariesTitle: "Límites claros, respetados.", boundaries: ["No es un casino. Nunca aceptamos apuestas ni guardamos tu dinero.", "No es un servicio terapéutico. El Programa no diagnostica ni trata.", "No es una afirmación de disponibilidad. La falta de pruebas jurisdiccionales, editoriales o comerciales cierra el acceso."],
  },
  "pt-PT": {
    metadataTitle: "Sobre a B4GAMBLE | Aprender, refletir, comparar", metadataDescription: "Como a B4GAMBLE coloca a educação antes da comparação e separa a reflexão do Programa da informação comercial.",
    eyebrow: "Sobre a B4GAMBLE", titleLead: "Criado para estar", titleEmphasis: "do teu lado.", introduction: "Um produto sobre jogo deve colocar a pessoa em primeiro lugar. Explicamos provas e condições relevantes, apoiamos o controlo autónomo e mantemos estas funções claramente separadas.", partsTitle: "Um produto. Três áreas.",
    parts: [{ title: "O Programa", body: "Um Programa autónomo de 10 passos, gratuito para utilizar. Os dados do Programa não são usados para segmentação comercial, ofertas ou classificações." }, { title: "Investigação e educação", body: "As análises identificam as provas e limitações; os guias explicam claramente as condições relevantes." }, { title: "Descoberta comercial", body: "Melhores Ofertas, Casinos e Bónus são páginas comerciais claramente identificadas para adultos que decidiram comparar registos publicados." }],
    partsNote: "Não existe um percurso obrigatório. Podes usar uma análise, o Programa ou ambos. As áreas protegidas não se tornam canais de aquisição.", fundingTitle: "Como nos financiamos", fundingBody: "Quando existe e é utilizada uma ligação comercial autorizada de forma independente, a B4GAMBLE pode receber uma comissão. A remuneração de afiliado não determina o Editor Score nem a ordem editorial natural.", disclosureLink: "Divulgação de afiliados completa →", separationTitle: "O que permanece separado", separationPoints: ["A disponibilidade comercial não determina as pontuações editoriais.", "Os dados do Programa e da Ajuda nunca alimentam ofertas ou classificações.", "A Ajuda protegida não contém ações de casino, bónus ou afiliados."], boundariesLabel: "O que a B4GAMBLE não é", boundariesTitle: "Limites claros, mantidos.", boundaries: ["Não é um casino. Nunca aceitamos apostas nem guardamos o teu dinheiro.", "Não é um serviço de terapia. O Programa não diagnostica nem trata.", "Não é uma afirmação de disponibilidade. Sem provas jurisdicionais, editoriais ou comerciais, o acesso permanece fechado."],
  },
  "el-GR": {
    metadataTitle: "Σχετικά με το B4GAMBLE | Μάθε, σκέψου, σύγκρινε", metadataDescription: "Πώς το B4GAMBLE βάζει την εκπαίδευση πριν από τη σύγκριση και διαχωρίζει το Πρόγραμμα από τις εμπορικές πληροφορίες.",
    eyebrow: "Σχετικά με το B4GAMBLE", titleLead: "Δημιουργήθηκε για να είναι", titleEmphasis: "στο πλευρό σου.", introduction: "Ένα προϊόν για τα τυχερά παιχνίδια πρέπει να βάζει πρώτα τον άνθρωπο. Εξηγούμε τα στοιχεία και τους ουσιώδεις όρους, στηρίζουμε τον αυτοκαθοδηγούμενο έλεγχο και κρατάμε αυτούς τους ρόλους σαφώς χωριστούς.", partsTitle: "Ένα προϊόν. Τρεις τομείς.",
    parts: [{ title: "Το Πρόγραμμα", body: "Ένα δωρεάν, αυτοκαθοδηγούμενο Πρόγραμμα 10 βημάτων. Τα δεδομένα του Προγράμματος δεν χρησιμοποιούνται για εμπορική στόχευση, προσφορές ή κατατάξεις." }, { title: "Έρευνα και εκπαίδευση", body: "Οι αξιολογήσεις αναφέρουν τα στοιχεία και τους περιορισμούς τους· οι οδηγοί εξηγούν απλά τους ουσιώδεις όρους." }, { title: "Εμπορική αναζήτηση", body: "Οι Καλύτερες Προσφορές, τα Καζίνο και τα Μπόνους είναι σαφώς επισημασμένες εμπορικές σελίδες για ενήλικες που επέλεξαν να συγκρίνουν δημοσιευμένα στοιχεία." }],
    partsNote: "Δεν υπάρχει υποχρεωτική διαδρομή μεταξύ τους. Μπορείς να χρησιμοποιήσεις μια αξιολόγηση, το Πρόγραμμα ή και τα δύο. Οι προστατευμένοι χώροι δεν γίνονται εμπορικές διοχετεύσεις.", fundingTitle: "Πώς χρηματοδοτούμαστε", fundingBody: "Όταν υπάρχει και χρησιμοποιείται ένας ανεξάρτητα εγκεκριμένος εμπορικός σύνδεσμος, το B4GAMBLE μπορεί να λάβει προμήθεια. Η αμοιβή συνεργάτη δεν καθορίζει το Editor Score ή τη φυσική συντακτική κατάταξη.", disclosureLink: "Πλήρης γνωστοποίηση συνεργατών →", separationTitle: "Τι παραμένει χωριστό", separationPoints: ["Η εμπορική διαθεσιμότητα δεν καθορίζει τις συντακτικές βαθμολογίες.", "Τα δεδομένα Προγράμματος και Βοήθειας δεν τροφοδοτούν προσφορές ή κατατάξεις.", "Η Προστατευμένη Βοήθεια δεν περιέχει ενέργειες καζίνο, μπόνους ή συνεργατών."], boundariesLabel: "Τι δεν είναι το B4GAMBLE", boundariesTitle: "Σαφή όρια, που τηρούνται.", boundaries: ["Δεν είναι καζίνο. Δεν δεχόμαστε στοιχήματα ούτε κρατάμε χρήματα.", "Δεν είναι υπηρεσία θεραπείας. Το Πρόγραμμα δεν κάνει διάγνωση ή θεραπεία.", "Δεν είναι δήλωση διαθεσιμότητας. Η έλλειψη δικαιοδοτικών, εκδοτικών ή εμπορικών στοιχείων κλείνει την πρόσβαση."],
  },
  "nl-NL": {
    metadataTitle: "Over B4GAMBLE | Leren, nadenken, vergelijken", metadataDescription: "Hoe B4GAMBLE educatie vóór vergelijking plaatst en reflectie in het Programma scheidt van commerciële informatie.",
    eyebrow: "Over B4GAMBLE", titleLead: "Gebouwd om", titleEmphasis: "aan jouw kant te staan.", introduction: "Een product over gokken moet de mens vooropstellen. We leggen bewijs en belangrijke voorwaarden uit, ondersteunen zelfgestuurde controle en houden deze functies duidelijk gescheiden.", partsTitle: "Eén product. Drie gebieden.",
    parts: [{ title: "Het Programma", body: "Een gratis te gebruiken, zelfgestuurd Programma in 10 stappen. Programmagegevens worden niet gebruikt voor commerciële targeting, aanbiedingen of ranglijsten." }, { title: "Onderzoek en educatie", body: "Recensies benoemen hun bewijs en beperkingen; gidsen leggen belangrijke voorwaarden helder uit." }, { title: "Commerciële ontdekking", body: "Beste Aanbiedingen, Casino's en Bonussen zijn duidelijk gemarkeerde commerciële pagina's voor volwassenen die gepubliceerde gegevens willen vergelijken." }],
    partsNote: "Er is geen verplicht pad. Je kunt een recensie, het Programma of beide gebruiken. Beschermde gebieden worden geen commerciële trechters.", fundingTitle: "Hoe we geld verdienen", fundingBody: "Wanneer een onafhankelijk toegestane commerciële link beschikbaar is en wordt gebruikt, kan B4GAMBLE commissie ontvangen. Affiliatevergoeding bepaalt niet de Editor Score of de natuurlijke redactionele rangschikking.", disclosureLink: "Volledige affiliateverklaring →", separationTitle: "Wat gescheiden blijft", separationPoints: ["Commerciële beschikbaarheid bepaalt geen redactionele scores.", "Programma- en Helpgegevens voeden nooit aanbiedingen of ranglijsten.", "Beschermde Help bevat geen casino-, bonus- of affiliateacties."], boundariesLabel: "Wat B4GAMBLE niet is", boundariesTitle: "Duidelijke grenzen, bewaakt.", boundaries: ["Geen casino. We nemen geen weddenschappen aan en bewaren je geld niet.", "Geen therapieservice. Het Programma diagnosticeert of behandelt niet.", "Geen beschikbaarheidsclaim. Ontbrekend juridisch, publicatie- of commercieel bewijs houdt toegang gesloten."],
  },
  "sv-SE": {
    metadataTitle: "Om B4GAMBLE | Lär, reflektera, jämför", metadataDescription: "Så sätter B4GAMBLE utbildning före jämförelse och skiljer reflektion i Programmet från kommersiell information.",
    eyebrow: "Om B4GAMBLE", titleLead: "Byggt för att vara", titleEmphasis: "på din sida.", introduction: "En produkt om spel ska sätta människan först. Vi förklarar evidens och väsentliga villkor, stödjer självstyrd kontroll och håller dessa uppgifter tydligt åtskilda.", partsTitle: "En produkt. Tre områden.",
    parts: [{ title: "Programmet", body: "Ett kostnadsfritt, självstyrt Program i 10 steg. Programdata används inte för kommersiell målgruppsstyrning, erbjudanden eller rankningar." }, { title: "Research och utbildning", body: "Recensioner anger sin evidens och sina begränsningar; guider förklarar väsentliga villkor tydligt." }, { title: "Kommersiell upptäckt", body: "Bästa Erbjudanden, Casinon och Bonusar är tydligt märkta kommersiella sidor för vuxna som valt att jämföra publicerade uppgifter." }],
    partsNote: "Det finns ingen tvingande väg mellan dem. Du kan använda en recension, Programmet eller båda. Skyddade områden blir inte försäljningstrattar.", fundingTitle: "Så finansieras vi", fundingBody: "När en separat godkänd kommersiell länk finns och används kan B4GAMBLE få provision. Affiliateersättning avgör inte Editor Score eller den naturliga redaktionella rankningen.", disclosureLink: "Fullständig affiliateinformation →", separationTitle: "Det som hålls åtskilt", separationPoints: ["Kommersiell tillgänglighet avgör inte redaktionella poäng.", "Program- och Hjälpdata används aldrig för erbjudanden eller rankningar.", "Skyddad Hjälp innehåller inga casino-, bonus- eller affiliateåtgärder."], boundariesLabel: "Vad B4GAMBLE inte är", boundariesTitle: "Tydliga gränser, bevarade.", boundaries: ["Inte ett casino. Vi tar inte emot insatser eller håller dina pengar.", "Inte en terapitjänst. Programmet diagnostiserar eller behandlar inte.", "Inte ett tillgänglighetslöfte. Saknad jurisdiktions-, publicerings- eller kommersiell evidens stänger åtkomsten."],
  },
  "da-DK": {
    metadataTitle: "Om B4GAMBLE | Lær, reflektér, sammenlign", metadataDescription: "Sådan sætter B4GAMBLE uddannelse før sammenligning og adskiller refleksion i Programmet fra kommerciel information.",
    eyebrow: "Om B4GAMBLE", titleLead: "Bygget til at være", titleEmphasis: "på din side.", introduction: "Et produkt om spil skal sætte mennesket først. Vi forklarer evidens og væsentlige vilkår, støtter selvstyret kontrol og holder disse opgaver tydeligt adskilt.", partsTitle: "Ét produkt. Tre områder.",
    parts: [{ title: "Programmet", body: "Et gratis, selvstyret Program i 10 trin. Programdata bruges ikke til kommerciel målretning, tilbud eller rangeringer." }, { title: "Research og uddannelse", body: "Anmeldelser angiver deres evidens og begrænsninger; guider forklarer væsentlige vilkår klart." }, { title: "Kommerciel opdagelse", body: "Bedste Tilbud, Casinoer og Bonusser er tydeligt mærkede kommercielle sider for voksne, der har valgt at sammenligne offentliggjorte oplysninger." }],
    partsNote: "Der er ingen tvungen vej mellem dem. Du kan bruge en anmeldelse, Programmet eller begge dele. Beskyttede områder bliver ikke salgstragte.", fundingTitle: "Sådan finansieres vi", fundingBody: "Når et særskilt godkendt kommercielt link findes og bruges, kan B4GAMBLE modtage provision. Affiliatebetaling bestemmer ikke Editor Score eller den naturlige redaktionelle rangering.", disclosureLink: "Fuld affiliateoplysning →", separationTitle: "Det der forbliver adskilt", separationPoints: ["Kommerciel tilgængelighed bestemmer ikke redaktionelle scorer.", "Program- og Hjælpedata bruges aldrig til tilbud eller rangeringer.", "Beskyttet Hjælp indeholder ingen casino-, bonus- eller affiliatehandlinger."], boundariesLabel: "Hvad B4GAMBLE ikke er", boundariesTitle: "Klare grænser, fastholdt.", boundaries: ["Ikke et casino. Vi modtager ikke indsatser og opbevarer ikke dine penge.", "Ikke en terapitjeneste. Programmet diagnosticerer eller behandler ikke.", "Ikke en påstand om tilgængelighed. Manglende jurisdiktions-, publicerings- eller kommerciel evidens lukker adgangen."],
  },
  "fi-FI": {
    metadataTitle: "Tietoa B4GAMBLEsta | Opi, pohdi, vertaile", metadataDescription: "Näin B4GAMBLE asettaa koulutuksen vertailun edelle ja erottaa Ohjelman pohdinnat kaupallisesta tiedosta.",
    eyebrow: "Tietoa B4GAMBLEsta", titleLead: "Rakennettu olemaan", titleEmphasis: "sinun puolellasi.", introduction: "Rahapelaamista käsittelevän tuotteen tulee asettaa ihminen etusijalle. Selitämme näytön ja olennaiset ehdot, tuemme omaehtoista hallintaa ja pidämme tehtävät selvästi erillään.", partsTitle: "Yksi tuote. Kolme aluetta.",
    parts: [{ title: "Ohjelma", body: "Maksuton, omaehtoinen 10 vaiheen Ohjelma. Ohjelman tietoja ei käytetä kaupalliseen kohdentamiseen, tarjouksiin tai sijoituksiin." }, { title: "Tutkimus ja koulutus", body: "Arviot kertovat näyttönsä ja rajoituksensa; oppaat selittävät olennaiset ehdot selkeästi." }, { title: "Kaupallinen vertailu", body: "Parhaat Tarjoukset, Kasinot ja Bonukset ovat selvästi merkittyjä kaupallisia sivuja aikuisille, jotka ovat päättäneet vertailla julkaistuja tietoja." }],
    partsNote: "Niiden välillä ei ole pakotettua polkua. Voit käyttää arviota, Ohjelmaa tai molempia. Suojatuista alueista ei tehdä myyntipolkuja.", fundingTitle: "Miten rahoitamme toimintamme", fundingBody: "Kun erikseen valtuutettu kaupallinen linkki on saatavilla ja sitä käytetään, B4GAMBLE voi saada palkkion. Kumppanikorvaus ei määrää Editor Scorea eikä luonnollista toimituksellista järjestystä.", disclosureLink: "Täydellinen kumppanuusseloste →", separationTitle: "Mikä pysyy erillään", separationPoints: ["Kaupallinen saatavuus ei määrää toimituksellisia pisteitä.", "Ohjelman ja Ohjeen tietoja ei käytetä tarjouksiin tai sijoituksiin.", "Suojattu Ohje ei sisällä kasino-, bonus- tai kumppanitoimintoja."], boundariesLabel: "Mitä B4GAMBLE ei ole", boundariesTitle: "Selkeät rajat, pidettyinä.", boundaries: ["Ei kasino. Emme ota vastaan panoksia tai säilytä rahojasi.", "Ei terapiapalvelu. Ohjelma ei diagnosoi eikä hoida.", "Ei saatavuusväite. Puuttuva lainkäyttö-, julkaisu- tai kaupallinen näyttö sulkee toiminnon."],
  },
  "nb-NO": {
    metadataTitle: "Om B4GAMBLE | Lær, reflekter, sammenlign", metadataDescription: "Slik setter B4GAMBLE læring foran sammenligning og skiller refleksjon i Programmet fra kommersiell informasjon.",
    eyebrow: "Om B4GAMBLE", titleLead: "Bygget for å være", titleEmphasis: "på din side.", introduction: "Et produkt om pengespill skal sette mennesket først. Vi forklarer evidens og vesentlige vilkår, støtter selvstyrt kontroll og holder disse oppgavene tydelig atskilt.", partsTitle: "Ett produkt. Tre områder.",
    parts: [{ title: "Programmet", body: "Et gratis, selvstyrt Program i 10 trinn. Programdata brukes ikke til kommersiell målretting, tilbud eller rangeringer." }, { title: "Research og læring", body: "Anmeldelser oppgir evidens og begrensninger; veiledninger forklarer vesentlige vilkår tydelig." }, { title: "Kommersiell utforskning", body: "Beste Tilbud, Kasinoer og Bonuser er tydelig merkede kommersielle sider for voksne som har valgt å sammenligne publiserte opplysninger." }],
    partsNote: "Det finnes ingen tvungen vei mellom dem. Du kan bruke en anmeldelse, Programmet eller begge. Beskyttede områder blir ikke salgstrakter.", fundingTitle: "Slik finansieres vi", fundingBody: "Når en særskilt godkjent kommersiell lenke finnes og brukes, kan B4GAMBLE motta provisjon. Affiliatebetaling bestemmer ikke Editor Score eller den naturlige redaksjonelle rangeringen.", disclosureLink: "Full affiliateopplysning →", separationTitle: "Det som forblir atskilt", separationPoints: ["Kommersiell tilgjengelighet bestemmer ikke redaksjonelle poeng.", "Program- og Hjelpedata brukes aldri til tilbud eller rangeringer.", "Beskyttet Hjelp inneholder ingen kasino-, bonus- eller affiliatehandlinger."], boundariesLabel: "Hva B4GAMBLE ikke er", boundariesTitle: "Tydelige grenser, holdt.", boundaries: ["Ikke et kasino. Vi tar ikke imot innsatser eller oppbevarer pengene dine.", "Ikke en terapitjeneste. Programmet diagnostiserer eller behandler ikke.", "Ikke en påstand om tilgjengelighet. Manglende jurisdiksjons-, publiserings- eller kommersiell evidens stenger tilgangen."],
  },
  "en-CA": {} as AboutMessages,
  "fr-CA": {} as AboutMessages,
};

// Canada is architecture-ready but outside the required European publication
// tranche. Keep deterministic content without exposing an incomplete body.
catalog["en-CA"] = catalog["en-GB"];
catalog["fr-CA"] = catalog["en-GB"];

export function aboutMessages(locale: SupportedLocale) {
  return catalog[locale];
}
