import type { SupportedLocale } from "@/lib/market/registry";

type EuropeanLocale = Exclude<SupportedLocale, "en-CA" | "fr-CA" | "es-PE">;

export type ContactMessages = Readonly<{
  metadataTitle: string;
  metadataDescription: string;
  eyebrow: string;
  titleLead: string;
  titleEmphasis: string;
  heroCopy: string;
  optionsLabel: string;
  otherWays: string;
  emailTitle: string;
  correctionsTitle: string;
  correctionsCopy: string;
  helpTitle: string;
  helpCopy: string;
  helpAction: string;
  responseTitle: string;
  responseCopy: string;
  formLabel: string;
  noScriptTitle: string;
  noScriptLead: string;
  noScriptPrivacy: string;
  nameLabel: string;
  nameAria: string;
  namePlaceholder: string;
  nameHint: string;
  nameError: string;
  emailLabel: string;
  emailPlaceholder: string;
  emailHint: string;
  emailError: string;
  subjectLabel: string;
  subjectPlaceholder: string;
  subjectHint: string;
  subjectError: string;
  messageLabel: string;
  messagePlaceholder: string;
  messageHint: string;
  messageError: string;
  honeypotLabel: string;
  sensitiveWarning: string;
  privacyNotice: string;
  sentTitle: string;
  sentCopy: string;
  failureTitle: string;
  failureCopy: string;
  sending: string;
  submit: string;
  formNote: string;
}>;

const catalog: Record<EuropeanLocale, ContactMessages> = {
  "en-GB": {
    metadataTitle: "Contact B4GAMBLE | Support and enquiries", metadataDescription: "Contact B4GAMBLE about the website, technical issues, editorial feedback or business enquiries.", eyebrow: "Contact", titleLead: "Talk", titleEmphasis: "to us.", heroCopy: "Corrections, questions and disagreements are welcome. We'll reply when the team has reviewed your message.", optionsLabel: "Contact options", otherWays: "Other ways to reach us", emailTitle: "Email", correctionsTitle: "Corrections", correctionsCopy: "Spotted an error in a review? Mark the subject “Correction” so the editorial team can review and date any published change.", helpTitle: "Need support, not customer service?", helpCopy: "Protected Help is commercial-free and confidential.", helpAction: "Open Help →", responseTitle: "Response time", responseCopy: "Response times vary. If you need immediate gambling support, use Protected Help and its independent support routes.", formLabel: "General contact", noScriptTitle: "Email us directly.", noScriptLead: "The form needs JavaScript. You can still email us directly.", noScriptPrivacy: "Read our Privacy Notice.", nameLabel: "Your name", nameAria: "Name (optional)", namePlaceholder: "How should we address you?", nameHint: "Name is optional; up to 100 characters.", nameError: "Enter a plain-text name of no more than 100 characters, or leave this field empty.", emailLabel: "Email", emailPlaceholder: "Where we reply", emailHint: "Used only to handle your enquiry.", emailError: "Enter a valid email address of no more than 254 characters.", subjectLabel: "Subject", subjectPlaceholder: "A few words", subjectHint: "Up to 160 characters.", subjectError: "Enter a plain-text subject of no more than 160 characters.", messageLabel: "Message", messagePlaceholder: "What's on your mind?", messageHint: "10–4,000 characters.", messageError: "Enter a message of between 10 and 4,000 supported characters.", honeypotLabel: "Company website", sensitiveWarning: "Please do not include passwords, payment details or private Programme answers in this form.", privacyNotice: "Privacy Notice: we use the information you submit only to handle your enquiry and protect the form from abuse.", sentTitle: "Message sent.", sentCopy: "We received your enquiry.", failureTitle: "We couldn't send your message.", failureCopy: "Please try again or email us directly.", sending: "Sending…", submit: "Send message", formNote: "Contact details are used to handle your enquiry and protect the form from abuse. Messages do not feed offers or rankings.",
  },
  "de-DE": {
    metadataTitle: "B4GAMBLE kontaktieren | Support und Anfragen", metadataDescription: "Kontaktiere B4GAMBLE zu Website, technischen Problemen, redaktionellem Feedback oder geschäftlichen Anfragen.", eyebrow: "Kontakt", titleLead: "Sprich", titleEmphasis: "mit uns.", heroCopy: "Korrekturen, Fragen und Widerspruch sind willkommen. Wir antworten, sobald das Team deine Nachricht geprüft hat.", optionsLabel: "Kontaktmöglichkeiten", otherWays: "Weitere Kontaktmöglichkeiten", emailTitle: "E-Mail", correctionsTitle: "Korrekturen", correctionsCopy: "Du hast einen Fehler in einer Bewertung entdeckt? Schreibe „Korrektur“ in den Betreff, damit das Redaktionsteam eine veröffentlichte Änderung prüfen und datieren kann.", helpTitle: "Du brauchst Unterstützung statt Kundenservice?", helpCopy: "Die geschützte Hilfe ist werbefrei und vertraulich.", helpAction: "Hilfe öffnen →", responseTitle: "Antwortzeit", responseCopy: "Antwortzeiten variieren. Wenn du sofortige Unterstützung wegen Glücksspiels brauchst, nutze die geschützte Hilfe und ihre unabhängigen Unterstützungswege.", formLabel: "Allgemeiner Kontakt", noScriptTitle: "Schreib uns direkt per E-Mail.", noScriptLead: "Das Formular benötigt JavaScript. Du kannst uns weiterhin direkt per E-Mail schreiben.", noScriptPrivacy: "Lies unseren Datenschutzhinweis.", nameLabel: "Dein Name", nameAria: "Dein Name (optional)", namePlaceholder: "Wie sollen wir dich ansprechen?", nameHint: "Der Name ist optional; maximal 100 Zeichen.", nameError: "Gib einen Namen als Klartext mit höchstens 100 Zeichen ein oder lasse das Feld leer.", emailLabel: "E-Mail", emailPlaceholder: "Adresse für unsere Antwort", emailHint: "Wird nur zur Bearbeitung deiner Anfrage verwendet.", emailError: "Gib eine gültige E-Mail-Adresse mit höchstens 254 Zeichen ein.", subjectLabel: "Betreff", subjectPlaceholder: "Ein paar Worte", subjectHint: "Maximal 160 Zeichen.", subjectError: "Gib einen Betreff als Klartext mit höchstens 160 Zeichen ein.", messageLabel: "Nachricht", messagePlaceholder: "Was möchtest du uns mitteilen?", messageHint: "10–4.000 Zeichen.", messageError: "Gib eine Nachricht mit 10 bis 4.000 unterstützten Zeichen ein.", honeypotLabel: "Unternehmenswebsite", sensitiveWarning: "Bitte gib hier keine Passwörter, Zahlungsdaten oder privaten Programm-Antworten an.", privacyNotice: "Datenschutzhinweis: Wir verwenden deine Angaben nur zur Bearbeitung der Anfrage und zum Schutz des Formulars vor Missbrauch.", sentTitle: "Nachricht gesendet.", sentCopy: "Wir haben deine Anfrage erhalten.", failureTitle: "Deine Nachricht konnte nicht gesendet werden.", failureCopy: "Versuche es erneut oder schreibe uns direkt per E-Mail.", sending: "Wird gesendet…", submit: "Nachricht senden", formNote: "Kontaktdaten werden zur Bearbeitung deiner Anfrage und zum Schutz vor Missbrauch verwendet. Nachrichten fließen nicht in Angebote oder Rankings ein.",
  },
  "it-IT": {
    metadataTitle: "Contatta B4GAMBLE | Assistenza e richieste", metadataDescription: "Contatta B4GAMBLE per il sito, problemi tecnici, feedback editoriale o richieste commerciali.", eyebrow: "Contatti", titleLead: "Parla", titleEmphasis: "con noi.", heroCopy: "Correzioni, domande e opinioni diverse sono benvenute. Risponderemo dopo che il team avrà esaminato il messaggio.", optionsLabel: "Opzioni di contatto", otherWays: "Altri modi per contattarci", emailTitle: "Email", correctionsTitle: "Correzioni", correctionsCopy: "Hai notato un errore in una recensione? Indica “Correzione” nell'oggetto, così la redazione potrà verificare e datare ogni modifica pubblicata.", helpTitle: "Cerchi supporto, non assistenza clienti?", helpCopy: "L'Aiuto protetto è privo di contenuti commerciali e riservato.", helpAction: "Apri Aiuto →", responseTitle: "Tempi di risposta", responseCopy: "I tempi di risposta variano. Se ti serve supporto immediato per il gioco d'azzardo, usa l'Aiuto protetto e i suoi percorsi di supporto indipendenti.", formLabel: "Contatto generale", noScriptTitle: "Scrivici direttamente via email.", noScriptLead: "Il modulo richiede JavaScript. Puoi comunque scriverci direttamente via email.", noScriptPrivacy: "Leggi la nostra Informativa sulla privacy.", nameLabel: "Il tuo nome", nameAria: "Nome (facoltativo)", namePlaceholder: "Come possiamo chiamarti?", nameHint: "Il nome è facoltativo; massimo 100 caratteri.", nameError: "Inserisci un nome in testo semplice di massimo 100 caratteri oppure lascia vuoto il campo.", emailLabel: "Email", emailPlaceholder: "Dove possiamo rispondere", emailHint: "Usata solo per gestire la richiesta.", emailError: "Inserisci un indirizzo email valido di massimo 254 caratteri.", subjectLabel: "Oggetto", subjectPlaceholder: "Poche parole", subjectHint: "Massimo 160 caratteri.", subjectError: "Inserisci un oggetto in testo semplice di massimo 160 caratteri.", messageLabel: "Messaggio", messagePlaceholder: "Cosa vuoi comunicarci?", messageHint: "10–4.000 caratteri.", messageError: "Inserisci un messaggio tra 10 e 4.000 caratteri supportati.", honeypotLabel: "Sito web aziendale", sensitiveWarning: "Non inserire password, dati di pagamento o risposte private del Programma.", privacyNotice: "Informativa privacy: usiamo i dati inviati solo per gestire la richiesta e proteggere il modulo dagli abusi.", sentTitle: "Messaggio inviato.", sentCopy: "Abbiamo ricevuto la tua richiesta.", failureTitle: "Non è stato possibile inviare il messaggio.", failureCopy: "Riprova oppure scrivici direttamente via email.", sending: "Invio in corso…", submit: "Invia messaggio", formNote: "I dati di contatto servono a gestire la richiesta e proteggere il modulo dagli abusi. I messaggi non alimentano offerte o classifiche.",
  },
  "es-ES": {
    metadataTitle: "Contacta con B4GAMBLE | Ayuda y consultas", metadataDescription: "Contacta con B4GAMBLE sobre el sitio, problemas técnicos, comentarios editoriales o consultas comerciales.", eyebrow: "Contacto", titleLead: "Habla", titleEmphasis: "con nosotros.", heroCopy: "Agradecemos correcciones, preguntas y desacuerdos. Responderemos cuando el equipo haya revisado tu mensaje.", optionsLabel: "Opciones de contacto", otherWays: "Otras formas de contacto", emailTitle: "Correo electrónico", correctionsTitle: "Correcciones", correctionsCopy: "¿Has visto un error en una reseña? Indica “Corrección” en el asunto para que el equipo editorial pueda revisar y fechar cualquier cambio publicado.", helpTitle: "¿Necesitas apoyo y no atención al cliente?", helpCopy: "La Ayuda protegida es confidencial y no contiene contenido comercial.", helpAction: "Abrir Ayuda →", responseTitle: "Tiempo de respuesta", responseCopy: "Los tiempos de respuesta varían. Si necesitas apoyo inmediato relacionado con el juego, utiliza la Ayuda protegida y sus vías de apoyo independientes.", formLabel: "Contacto general", noScriptTitle: "Escríbenos directamente.", noScriptLead: "El formulario necesita JavaScript. También puedes escribirnos directamente por correo electrónico.", noScriptPrivacy: "Lee nuestro Aviso de privacidad.", nameLabel: "Tu nombre", nameAria: "Nombre (opcional)", namePlaceholder: "¿Cómo debemos dirigirnos a ti?", nameHint: "El nombre es opcional; máximo 100 caracteres.", nameError: "Introduce un nombre en texto sencillo de hasta 100 caracteres o deja el campo vacío.", emailLabel: "Correo electrónico", emailPlaceholder: "Dónde responderemos", emailHint: "Solo se usa para gestionar tu consulta.", emailError: "Introduce una dirección de correo válida de hasta 254 caracteres.", subjectLabel: "Asunto", subjectPlaceholder: "Unas palabras", subjectHint: "Máximo 160 caracteres.", subjectError: "Introduce un asunto en texto sencillo de hasta 160 caracteres.", messageLabel: "Mensaje", messagePlaceholder: "¿Qué quieres contarnos?", messageHint: "10–4.000 caracteres.", messageError: "Introduce un mensaje de entre 10 y 4.000 caracteres admitidos.", honeypotLabel: "Sitio web de la empresa", sensitiveWarning: "No incluyas contraseñas, datos de pago ni respuestas privadas del Programa.", privacyNotice: "Aviso de privacidad: usamos la información enviada solo para gestionar la consulta y proteger el formulario frente a abusos.", sentTitle: "Mensaje enviado.", sentCopy: "Hemos recibido tu consulta.", failureTitle: "No hemos podido enviar tu mensaje.", failureCopy: "Inténtalo de nuevo o escríbenos directamente por correo electrónico.", sending: "Enviando…", submit: "Enviar mensaje", formNote: "Los datos de contacto se usan para gestionar tu consulta y proteger el formulario. Los mensajes no alimentan ofertas ni clasificaciones.",
  },
  "pt-PT": {
    metadataTitle: "Contactar a B4GAMBLE | Apoio e pedidos", metadataDescription: "Contacta a B4GAMBLE sobre o site, problemas técnicos, comentários editoriais ou questões comerciais.", eyebrow: "Contacto", titleLead: "Fala", titleEmphasis: "connosco.", heroCopy: "Correções, perguntas e discordâncias são bem-vindas. Responderemos depois de a equipa analisar a tua mensagem.", optionsLabel: "Opções de contacto", otherWays: "Outras formas de contacto", emailTitle: "Email", correctionsTitle: "Correções", correctionsCopy: "Encontraste um erro numa análise? Escreve “Correção” no assunto para a equipa editorial rever e datar qualquer alteração publicada.", helpTitle: "Precisas de apoio, não de atendimento ao cliente?", helpCopy: "A Ajuda protegida é confidencial e não contém conteúdo comercial.", helpAction: "Abrir Ajuda →", responseTitle: "Tempo de resposta", responseCopy: "Os tempos de resposta variam. Se precisares de apoio imediato relacionado com jogo, usa a Ajuda protegida e os seus percursos independentes.", formLabel: "Contacto geral", noScriptTitle: "Envia-nos um email diretamente.", noScriptLead: "O formulário precisa de JavaScript. Podes continuar a enviar-nos um email diretamente.", noScriptPrivacy: "Lê o nosso Aviso de Privacidade.", nameLabel: "O teu nome", nameAria: "Nome (opcional)", namePlaceholder: "Como devemos tratar-te?", nameHint: "O nome é opcional; até 100 caracteres.", nameError: "Introduz um nome em texto simples com até 100 caracteres ou deixa o campo vazio.", emailLabel: "Email", emailPlaceholder: "Onde responderemos", emailHint: "Usado apenas para tratar o teu pedido.", emailError: "Introduz um endereço de email válido com até 254 caracteres.", subjectLabel: "Assunto", subjectPlaceholder: "Algumas palavras", subjectHint: "Até 160 caracteres.", subjectError: "Introduz um assunto em texto simples com até 160 caracteres.", messageLabel: "Mensagem", messagePlaceholder: "O que nos queres dizer?", messageHint: "10–4.000 caracteres.", messageError: "Introduz uma mensagem entre 10 e 4.000 caracteres suportados.", honeypotLabel: "Site da empresa", sensitiveWarning: "Não incluas palavras-passe, dados de pagamento ou respostas privadas do Programa.", privacyNotice: "Aviso de Privacidade: usamos a informação enviada apenas para tratar o pedido e proteger o formulário contra abusos.", sentTitle: "Mensagem enviada.", sentCopy: "Recebemos o teu pedido.", failureTitle: "Não foi possível enviar a mensagem.", failureCopy: "Tenta novamente ou envia-nos um email diretamente.", sending: "A enviar…", submit: "Enviar mensagem", formNote: "Os dados de contacto são usados para tratar o pedido e proteger o formulário. As mensagens não alimentam ofertas nem classificações.",
  },
  "el-GR": {
    metadataTitle: "Επικοινωνία με το B4GAMBLE | Υποστήριξη και ερωτήματα", metadataDescription: "Επικοινώνησε με το B4GAMBLE για τον ιστότοπο, τεχνικά ζητήματα, συντακτικά σχόλια ή επιχειρηματικά ερωτήματα.", eyebrow: "Επικοινωνία", titleLead: "Μίλησε", titleEmphasis: "μαζί μας.", heroCopy: "Οι διορθώσεις, οι ερωτήσεις και οι διαφωνίες είναι ευπρόσδεκτες. Θα απαντήσουμε αφού η ομάδα εξετάσει το μήνυμά σου.", optionsLabel: "Επιλογές επικοινωνίας", otherWays: "Άλλοι τρόποι επικοινωνίας", emailTitle: "Email", correctionsTitle: "Διορθώσεις", correctionsCopy: "Εντόπισες λάθος σε αξιολόγηση; Γράψε «Διόρθωση» στο θέμα ώστε η συντακτική ομάδα να ελέγξει και να χρονολογήσει κάθε δημοσιευμένη αλλαγή.", helpTitle: "Χρειάζεσαι υποστήριξη και όχι εξυπηρέτηση πελατών;", helpCopy: "Η Προστατευμένη Βοήθεια είναι εμπιστευτική και χωρίς εμπορικό περιεχόμενο.", helpAction: "Άνοιγμα Βοήθειας →", responseTitle: "Χρόνος απάντησης", responseCopy: "Οι χρόνοι απάντησης διαφέρουν. Αν χρειάζεσαι άμεση υποστήριξη για τον τζόγο, χρησιμοποίησε την Προστατευμένη Βοήθεια και τις ανεξάρτητες διαδρομές υποστήριξης.", formLabel: "Γενική επικοινωνία", noScriptTitle: "Στείλε μας απευθείας email.", noScriptLead: "Η φόρμα χρειάζεται JavaScript. Μπορείς ακόμη να μας στείλεις απευθείας email.", noScriptPrivacy: "Διάβασε τη Δήλωση Απορρήτου.", nameLabel: "Το όνομά σου", nameAria: "Όνομα (προαιρετικό)", namePlaceholder: "Πώς να σε προσφωνούμε;", nameHint: "Το όνομα είναι προαιρετικό· έως 100 χαρακτήρες.", nameError: "Εισήγαγε όνομα απλού κειμένου έως 100 χαρακτήρες ή άφησε το πεδίο κενό.", emailLabel: "Email", emailPlaceholder: "Πού θα απαντήσουμε", emailHint: "Χρησιμοποιείται μόνο για τη διαχείριση του ερωτήματός σου.", emailError: "Εισήγαγε έγκυρη διεύθυνση email έως 254 χαρακτήρες.", subjectLabel: "Θέμα", subjectPlaceholder: "Λίγες λέξεις", subjectHint: "Έως 160 χαρακτήρες.", subjectError: "Εισήγαγε θέμα απλού κειμένου έως 160 χαρακτήρες.", messageLabel: "Μήνυμα", messagePlaceholder: "Τι θέλεις να μας πεις;", messageHint: "10–4.000 χαρακτήρες.", messageError: "Εισήγαγε μήνυμα από 10 έως 4.000 υποστηριζόμενους χαρακτήρες.", honeypotLabel: "Ιστότοπος εταιρείας", sensitiveWarning: "Μην συμπεριλάβεις κωδικούς πρόσβασης, στοιχεία πληρωμών ή ιδιωτικές απαντήσεις του Προγράμματος.", privacyNotice: "Δήλωση Απορρήτου: χρησιμοποιούμε τα στοιχεία μόνο για τη διαχείριση του ερωτήματος και την προστασία της φόρμας από κατάχρηση.", sentTitle: "Το μήνυμα στάλθηκε.", sentCopy: "Λάβαμε το ερώτημά σου.", failureTitle: "Δεν ήταν δυνατή η αποστολή του μηνύματος.", failureCopy: "Δοκίμασε ξανά ή στείλε μας απευθείας email.", sending: "Αποστολή…", submit: "Αποστολή μηνύματος", formNote: "Τα στοιχεία επικοινωνίας χρησιμοποιούνται για τη διαχείριση του ερωτήματος και την προστασία της φόρμας. Τα μηνύματα δεν τροφοδοτούν προσφορές ή κατατάξεις.",
  },
  "nl-NL": {
    metadataTitle: "Contact met B4GAMBLE | Ondersteuning en vragen", metadataDescription: "Neem contact op met B4GAMBLE over de website, technische problemen, redactionele feedback of zakelijke vragen.", eyebrow: "Contact", titleLead: "Praat", titleEmphasis: "met ons.", heroCopy: "Correcties, vragen en meningsverschillen zijn welkom. We antwoorden nadat het team je bericht heeft beoordeeld.", optionsLabel: "Contactmogelijkheden", otherWays: "Andere manieren om ons te bereiken", emailTitle: "E-mail", correctionsTitle: "Correcties", correctionsCopy: "Een fout in een review gezien? Zet ‘Correctie’ in het onderwerp, zodat de redactie een gepubliceerde wijziging kan beoordelen en dateren.", helpTitle: "Ondersteuning nodig, geen klantenservice?", helpCopy: "Beschermde Hulp is vertrouwelijk en vrij van commerciële inhoud.", helpAction: "Hulp openen →", responseTitle: "Reactietijd", responseCopy: "Reactietijden verschillen. Heb je direct ondersteuning rond gokken nodig, gebruik dan Beschermde Hulp en de onafhankelijke ondersteuningsroutes.", formLabel: "Algemeen contact", noScriptTitle: "E-mail ons rechtstreeks.", noScriptLead: "Het formulier heeft JavaScript nodig. Je kunt ons nog steeds rechtstreeks e-mailen.", noScriptPrivacy: "Lees onze Privacyverklaring.", nameLabel: "Je naam", nameAria: "Naam (optioneel)", namePlaceholder: "Hoe mogen we je aanspreken?", nameHint: "Naam is optioneel; maximaal 100 tekens.", nameError: "Voer een naam in gewone tekst van maximaal 100 tekens in of laat het veld leeg.", emailLabel: "E-mail", emailPlaceholder: "Waar we antwoorden", emailHint: "Alleen gebruikt om je vraag te behandelen.", emailError: "Voer een geldig e-mailadres van maximaal 254 tekens in.", subjectLabel: "Onderwerp", subjectPlaceholder: "Een paar woorden", subjectHint: "Maximaal 160 tekens.", subjectError: "Voer een onderwerp in gewone tekst van maximaal 160 tekens in.", messageLabel: "Bericht", messagePlaceholder: "Wat wil je ons vertellen?", messageHint: "10–4.000 tekens.", messageError: "Voer een bericht van 10 tot 4.000 ondersteunde tekens in.", honeypotLabel: "Bedrijfswebsite", sensitiveWarning: "Vermeld geen wachtwoorden, betaalgegevens of privéantwoorden uit het Programma.", privacyNotice: "Privacyverklaring: we gebruiken de verzonden informatie alleen om je vraag te behandelen en het formulier tegen misbruik te beschermen.", sentTitle: "Bericht verzonden.", sentCopy: "We hebben je vraag ontvangen.", failureTitle: "We konden je bericht niet verzenden.", failureCopy: "Probeer het opnieuw of e-mail ons rechtstreeks.", sending: "Verzenden…", submit: "Bericht verzenden", formNote: "Contactgegevens worden gebruikt om je vraag te behandelen en het formulier te beschermen. Berichten worden niet gebruikt voor aanbiedingen of ranglijsten.",
  },
  "sv-SE": {
    metadataTitle: "Kontakta B4GAMBLE | Support och frågor", metadataDescription: "Kontakta B4GAMBLE om webbplatsen, tekniska problem, redaktionell återkoppling eller affärsfrågor.", eyebrow: "Kontakt", titleLead: "Prata", titleEmphasis: "med oss.", heroCopy: "Rättelser, frågor och invändningar är välkomna. Vi svarar när teamet har granskat ditt meddelande.", optionsLabel: "Kontaktalternativ", otherWays: "Andra sätt att nå oss", emailTitle: "E-post", correctionsTitle: "Rättelser", correctionsCopy: "Har du hittat ett fel i en recension? Skriv ”Rättelse” i ämnesraden så att redaktionen kan granska och datera en publicerad ändring.", helpTitle: "Behöver du stöd, inte kundservice?", helpCopy: "Skyddad Hjälp är konfidentiell och fri från kommersiellt innehåll.", helpAction: "Öppna Hjälp →", responseTitle: "Svarstid", responseCopy: "Svarstider varierar. Om du behöver omedelbart stöd kring spel, använd Skyddad Hjälp och dess oberoende stödvägar.", formLabel: "Allmän kontakt", noScriptTitle: "Mejla oss direkt.", noScriptLead: "Formuläret kräver JavaScript. Du kan fortfarande mejla oss direkt.", noScriptPrivacy: "Läs vårt Integritetsmeddelande.", nameLabel: "Ditt namn", nameAria: "Namn (valfritt)", namePlaceholder: "Hur ska vi tilltala dig?", nameHint: "Namn är valfritt; högst 100 tecken.", nameError: "Ange ett namn i vanlig text med högst 100 tecken eller lämna fältet tomt.", emailLabel: "E-post", emailPlaceholder: "Där vi svarar", emailHint: "Används endast för att hantera din fråga.", emailError: "Ange en giltig e-postadress med högst 254 tecken.", subjectLabel: "Ämne", subjectPlaceholder: "Några ord", subjectHint: "Högst 160 tecken.", subjectError: "Ange ett ämne i vanlig text med högst 160 tecken.", messageLabel: "Meddelande", messagePlaceholder: "Vad vill du berätta?", messageHint: "10–4 000 tecken.", messageError: "Ange ett meddelande med 10 till 4 000 tecken som stöds.", honeypotLabel: "Företagets webbplats", sensitiveWarning: "Ange inte lösenord, betalningsuppgifter eller privata Program-svar.", privacyNotice: "Integritetsmeddelande: vi använder uppgifterna endast för att hantera frågan och skydda formuläret mot missbruk.", sentTitle: "Meddelandet har skickats.", sentCopy: "Vi har tagit emot din fråga.", failureTitle: "Vi kunde inte skicka ditt meddelande.", failureCopy: "Försök igen eller mejla oss direkt.", sending: "Skickar…", submit: "Skicka meddelande", formNote: "Kontaktuppgifter används för att hantera din fråga och skydda formuläret. Meddelanden används inte för erbjudanden eller rankningar.",
  },
  "da-DK": {
    metadataTitle: "Kontakt B4GAMBLE | Support og henvendelser", metadataDescription: "Kontakt B4GAMBLE om websitet, tekniske problemer, redaktionel feedback eller forretningshenvendelser.", eyebrow: "Kontakt", titleLead: "Tal", titleEmphasis: "med os.", heroCopy: "Rettelser, spørgsmål og uenighed er velkomne. Vi svarer, når teamet har gennemgået din besked.", optionsLabel: "Kontaktmuligheder", otherWays: "Andre måder at kontakte os", emailTitle: "E-mail", correctionsTitle: "Rettelser", correctionsCopy: "Har du fundet en fejl i en anmeldelse? Skriv “Rettelse” i emnefeltet, så redaktionen kan gennemgå og datere en offentliggjort ændring.", helpTitle: "Har du brug for støtte, ikke kundeservice?", helpCopy: "Beskyttet Hjælp er fortrolig og uden kommercielt indhold.", helpAction: "Åbn Hjælp →", responseTitle: "Svartid", responseCopy: "Svartider varierer. Hvis du har brug for øjeblikkelig støtte om spil, skal du bruge Beskyttet Hjælp og de uafhængige støttemuligheder.", formLabel: "Generel kontakt", noScriptTitle: "Send os en e-mail direkte.", noScriptLead: "Formularen kræver JavaScript. Du kan stadig sende os en e-mail direkte.", noScriptPrivacy: "Læs vores Privatlivsmeddelelse.", nameLabel: "Dit navn", nameAria: "Navn (valgfrit)", namePlaceholder: "Hvordan skal vi tiltale dig?", nameHint: "Navn er valgfrit; højst 100 tegn.", nameError: "Indtast et navn i almindelig tekst på højst 100 tegn, eller lad feltet være tomt.", emailLabel: "E-mail", emailPlaceholder: "Hvor vi svarer", emailHint: "Bruges kun til at behandle din henvendelse.", emailError: "Indtast en gyldig e-mailadresse på højst 254 tegn.", subjectLabel: "Emne", subjectPlaceholder: "Et par ord", subjectHint: "Højst 160 tegn.", subjectError: "Indtast et emne i almindelig tekst på højst 160 tegn.", messageLabel: "Besked", messagePlaceholder: "Hvad vil du fortælle os?", messageHint: "10–4.000 tegn.", messageError: "Indtast en besked på mellem 10 og 4.000 understøttede tegn.", honeypotLabel: "Virksomhedens website", sensitiveWarning: "Medtag ikke adgangskoder, betalingsoplysninger eller private Program-svar.", privacyNotice: "Privatlivsmeddelelse: Vi bruger kun oplysningerne til at behandle henvendelsen og beskytte formularen mod misbrug.", sentTitle: "Beskeden er sendt.", sentCopy: "Vi har modtaget din henvendelse.", failureTitle: "Vi kunne ikke sende din besked.", failureCopy: "Prøv igen, eller send os en e-mail direkte.", sending: "Sender…", submit: "Send besked", formNote: "Kontaktoplysninger bruges til at behandle din henvendelse og beskytte formularen. Beskeder bruges ikke til tilbud eller rangeringer.",
  },
  "fi-FI": {
    metadataTitle: "Ota yhteyttä B4GAMBLEen | Tuki ja tiedustelut", metadataDescription: "Ota yhteyttä B4GAMBLEen verkkosivustosta, teknisistä ongelmista, toimituksellisesta palautteesta tai liiketoimintakysymyksistä.", eyebrow: "Yhteydenotto", titleLead: "Puhu", titleEmphasis: "meille.", heroCopy: "Korjaukset, kysymykset ja eriävät näkemykset ovat tervetulleita. Vastaamme, kun tiimi on tarkistanut viestisi.", optionsLabel: "Yhteydenottotavat", otherWays: "Muut tavat tavoittaa meidät", emailTitle: "Sähköposti", correctionsTitle: "Korjaukset", correctionsCopy: "Huomasitko arvostelussa virheen? Kirjoita aiheeksi ”Korjaus”, jotta toimitus voi tarkistaa ja päivätä julkaistun muutoksen.", helpTitle: "Tarvitsetko tukea etkä asiakaspalvelua?", helpCopy: "Suojattu Ohje on luottamuksellinen eikä sisällä kaupallista sisältöä.", helpAction: "Avaa Ohje →", responseTitle: "Vastausaika", responseCopy: "Vastausajat vaihtelevat. Jos tarvitset välitöntä rahapelaamiseen liittyvää tukea, käytä Suojattua Ohjetta ja sen riippumattomia tukireittejä.", formLabel: "Yleinen yhteydenotto", noScriptTitle: "Lähetä meille sähköpostia.", noScriptLead: "Lomake tarvitsee JavaScriptin. Voit silti lähettää meille sähköpostia suoraan.", noScriptPrivacy: "Lue tietosuojailmoituksemme.", nameLabel: "Nimesi", nameAria: "Nimi (valinnainen)", namePlaceholder: "Miten puhuttelemme sinua?", nameHint: "Nimi on valinnainen; enintään 100 merkkiä.", nameError: "Anna enintään 100 merkin pituinen nimi pelkkänä tekstinä tai jätä kenttä tyhjäksi.", emailLabel: "Sähköposti", emailPlaceholder: "Osoite vastaustamme varten", emailHint: "Käytetään vain tiedustelusi käsittelyyn.", emailError: "Anna kelvollinen, enintään 254 merkin sähköpostiosoite.", subjectLabel: "Aihe", subjectPlaceholder: "Muutama sana", subjectHint: "Enintään 160 merkkiä.", subjectError: "Anna enintään 160 merkin aihe pelkkänä tekstinä.", messageLabel: "Viesti", messagePlaceholder: "Mitä haluat kertoa?", messageHint: "10–4 000 merkkiä.", messageError: "Anna 10–4 000 tuetun merkin pituinen viesti.", honeypotLabel: "Yrityksen verkkosivusto", sensitiveWarning: "Älä lisää salasanoja, maksutietoja tai yksityisiä Ohjelma-vastauksia.", privacyNotice: "Tietosuojailmoitus: käytämme lähettämiäsi tietoja vain tiedustelun käsittelyyn ja lomakkeen suojaamiseen väärinkäytöltä.", sentTitle: "Viesti lähetetty.", sentCopy: "Saimme tiedustelusi.", failureTitle: "Viestiä ei voitu lähettää.", failureCopy: "Yritä uudelleen tai lähetä meille sähköpostia suoraan.", sending: "Lähetetään…", submit: "Lähetä viesti", formNote: "Yhteystietoja käytetään tiedustelun käsittelyyn ja lomakkeen suojaamiseen. Viestejä ei käytetä tarjouksiin tai sijoituksiin.",
  },
  "nb-NO": {
    metadataTitle: "Kontakt B4GAMBLE | Støtte og henvendelser", metadataDescription: "Kontakt B4GAMBLE om nettstedet, tekniske problemer, redaksjonelle tilbakemeldinger eller forretningshenvendelser.", eyebrow: "Kontakt", titleLead: "Snakk", titleEmphasis: "med oss.", heroCopy: "Rettelser, spørsmål og uenighet er velkomne. Vi svarer etter at teamet har gjennomgått meldingen din.", optionsLabel: "Kontaktalternativer", otherWays: "Andre måter å nå oss på", emailTitle: "E-post", correctionsTitle: "Rettelser", correctionsCopy: "Har du oppdaget en feil i en anmeldelse? Skriv «Rettelse» i emnefeltet, slik at redaksjonen kan gjennomgå og datere en publisert endring.", helpTitle: "Trenger du støtte, ikke kundeservice?", helpCopy: "Beskyttet Hjelp er konfidensiell og uten kommersielt innhold.", helpAction: "Åpne Hjelp →", responseTitle: "Svartid", responseCopy: "Svartiden varierer. Hvis du trenger umiddelbar støtte knyttet til pengespill, kan du bruke Beskyttet Hjelp og de uavhengige støtterutene.", formLabel: "Generell kontakt", noScriptTitle: "Send oss e-post direkte.", noScriptLead: "Skjemaet krever JavaScript. Du kan fortsatt sende oss e-post direkte.", noScriptPrivacy: "Les personvernerklæringen vår.", nameLabel: "Navnet ditt", nameAria: "Navn (valgfritt)", namePlaceholder: "Hva skal vi kalle deg?", nameHint: "Navn er valgfritt; maksimalt 100 tegn.", nameError: "Skriv inn et navn i ren tekst på maksimalt 100 tegn, eller la feltet stå tomt.", emailLabel: "E-post", emailPlaceholder: "Adressen vi svarer til", emailHint: "Brukes bare til å behandle henvendelsen.", emailError: "Skriv inn en gyldig e-postadresse på maksimalt 254 tegn.", subjectLabel: "Emne", subjectPlaceholder: "Noen få ord", subjectHint: "Maksimalt 160 tegn.", subjectError: "Skriv inn et emne i ren tekst på maksimalt 160 tegn.", messageLabel: "Melding", messagePlaceholder: "Hva vil du fortelle oss?", messageHint: "10–4 000 tegn.", messageError: "Skriv inn en melding på mellom 10 og 4 000 støttede tegn.", honeypotLabel: "Bedriftens nettsted", sensitiveWarning: "Ikke ta med passord, betalingsopplysninger eller private Program-svar.", privacyNotice: "Personvernerklæring: Vi bruker bare opplysningene til å behandle henvendelsen og beskytte skjemaet mot misbruk.", sentTitle: "Meldingen er sendt.", sentCopy: "Vi har mottatt henvendelsen.", failureTitle: "Vi kunne ikke sende meldingen.", failureCopy: "Prøv igjen, eller send oss e-post direkte.", sending: "Sender…", submit: "Send melding", formNote: "Kontaktopplysninger brukes til å behandle henvendelsen og beskytte skjemaet. Meldinger brukes ikke til tilbud eller rangeringer.",
  },
};

export function contactMessages(locale: SupportedLocale): ContactMessages {
  if (locale === "es-PE") return catalog["es-ES"];
  return catalog[locale as EuropeanLocale] ?? catalog["en-GB"];
}
