import type { SupportedLocale } from "@/lib/market/registry";

type FaqItem = readonly [question: string, answer: string];
type FaqGroup = Readonly<{ title: string; items: readonly FaqItem[] }>;

export type FaqMessages = Readonly<{
  metadataTitle: string;
  metadataDescription: string;
  eyebrow: string;
  titleLead: string;
  titleEmphasis: string;
  groups: readonly FaqGroup[];
  railPrompt: string;
  contactLink: string;
  methodologyLink: string;
  affiliateLink: string;
}>;

const en: FaqMessages = {
  metadataTitle: "B4GAMBLE FAQ",
  metadataDescription: "Clear answers about B4GAMBLE.",
  eyebrow: "FAQ", titleLead: "Clear", titleEmphasis: "answers.", railPrompt: "Didn't find it?", contactLink: "Contact us →", methodologyLink: "Methodology", affiliateLink: "Affiliate Disclosure",
  groups: [
    { title: "About B4GAMBLE", items: [["What is B4GAMBLE?", "Three connected areas: a self-directed control Programme, educational and editorial casino information, and openly commercial discovery pages for adults who have decided to compare published records."], ["What does B4GAMBLE stand for?", "Before Gamble. ‘B4’ is short for ‘before’: know your limits and your patterns before you place a bet, not after a loss. The free 10-step Programme is built around that moment."], ["Who writes the reviews?", "The editorial team maintains review content. Commercial availability is handled separately, and every material source limitation should remain visible."]] },
    { title: "Programme", items: [["Is the Programme really free?", "The current Programme is free to use and has no paywall. One Mission, “Research responsibly”, ends by opening the casino, bonus and offer pages in your menu; using them is your choice."], ["Who can see what I say in the Programme?", "Your situation is used only to generate the Programme output you request. Programme and Help data is excluded from offers, rankings, ads and commercial personalisation; the Privacy page explains saved data and rights requests."], ["Do I need an account to start?", "No. You speak or type your situation first; registration with Google or email comes only after your Starting Point is ready, so you can save it."]] },
    { title: "Casinos & Offers", items: [["How do you evaluate casinos?", "B4GAMBLE applies the disclosed editorial framework to the evidence available for each published record. Source status, dates, missing fields and limitations remain part of the review."], ["Why do some casinos say ‘Review only’?", "No verified registration link is available right now, so we do not invent one. The review and available published information remain visible."], ["What happens when I click View Offer?", "A confirmation explains that you are leaving B4GAMBLE and repeats the commission disclosure. You can continue to the operator or stay."]] },
    { title: "Commercial model", items: [["How does B4GAMBLE make money?", "B4GAMBLE may earn commission when you use a clearly labelled affiliate link. Commercial links are labelled and explained before you leave the site."], ["Does commission affect rankings?", "Affiliate compensation does not determine Editor Score or natural editorial ranking. See the Affiliate Disclosure for how editorial and commercial content are kept separate."]] },
    { title: "Help & Privacy", items: [["What is protected Help?", "A commercial-free space linking to immediate independent support, blocking and self-exclusion options. Protected Help activity is not used for offers, rankings or commercial personalisation."], ["How do I request my data or deletion?", "Contact the controller using the Privacy page. Data may continue to be retained where applicable to meet legal obligations, prevent fraud or maintain backups."]] },
  ],
};

const baseCatalog: Record<Exclude<SupportedLocale, "es-PE">, FaqMessages> = {
  "en-GB": en,
  "de-DE": {
    metadataTitle: "B4GAMBLE FAQ", metadataDescription: "Klare Antworten zu B4GAMBLE.", eyebrow: "FAQ", titleLead: "Klare", titleEmphasis: "Antworten.", railPrompt: "Nicht gefunden?", contactLink: "Kontakt →", methodologyLink: "Methodik", affiliateLink: "Affiliate-Hinweis",
    groups: [
      { title: "Über B4GAMBLE", items: [["Was ist B4GAMBLE?", "Drei verbundene Bereiche: ein selbstbestimmtes Kontrollprogramm, Bildungs- und redaktionelle Informationen zu Glücksspielanbietern sowie offen kommerzielle Vergleichsseiten für Erwachsene, die veröffentlichte Einträge vergleichen möchten."], ["Wofür steht B4GAMBLE?", "Für „Before Gamble“, also „bevor du spielst“. „B4“ ist die englische Kurzform von „before“: Kenne deine Grenzen und Muster, bevor du einsetzt, nicht erst nach einem Verlust. Das kostenlose 10-Schritte-Programm setzt genau an diesem Moment an."], ["Wer schreibt die Bewertungen?", "Das Redaktionsteam pflegt die Bewertungen. Kommerzielle Verfügbarkeit wird getrennt behandelt; wesentliche Quellenbeschränkungen bleiben sichtbar."]] },
      { title: "Programm", items: [["Ist das Programm wirklich kostenlos?", "Das aktuelle Programm ist kostenlos nutzbar und hat keine Bezahlschranke. Eine Mission, „Informiere dich verantwortungsvoll“, endet damit, dass die Seiten zu Anbietern, Boni und Angeboten in deinem Menü geöffnet werden; ob du sie nutzt, entscheidest du."], ["Wer kann sehen, was ich im Programm sage?", "Deine Angaben werden nur für die angeforderte Programmausgabe verwendet. Programm- und Hilfedaten sind von Angeboten, Rankings, Werbung und kommerzieller Personalisierung ausgeschlossen; die Datenschutzseite erklärt gespeicherte Daten und Rechteanfragen."], ["Brauche ich zum Start ein Konto?", "Nein. Du sprichst oder schreibst zuerst über deine Situation. Die Anmeldung mit Google oder E-Mail folgt erst, wenn dein Ausgangspunkt zum Speichern bereit ist."]] },
      { title: "Glücksspielanbieter & Angebote", items: [["Wie bewertet ihr Glücksspielanbieter?", "B4GAMBLE wendet den offengelegten redaktionellen Rahmen auf die für jeden veröffentlichten Eintrag verfügbaren Nachweise an. Quellenstatus, Daten, fehlende Felder und Grenzen bleiben Teil der Bewertung."], ["Warum steht bei manchen Anbietern „Nur Bewertung“?", "Derzeit ist kein verifizierter Registrierungslink verfügbar. Die Bewertung und die verfügbaren veröffentlichten Informationen bleiben sichtbar."], ["Was geschieht bei „Angebot ansehen“?", "Eine Bestätigung erklärt, dass du B4GAMBLE verlässt, und wiederholt den Provisionshinweis. Du kannst fortfahren oder bleiben."]] },
      { title: "Geschäftsmodell", items: [["Wie verdient B4GAMBLE Geld?", "B4GAMBLE kann eine Provision erhalten, wenn du einen klar gekennzeichneten Affiliate-Link nutzt. Kommerzielle Links werden gekennzeichnet und erklärt, bevor du die Website verlässt."], ["Beeinflusst Provision die Rangfolge?", "Affiliate-Vergütung bestimmt weder Editor Score noch natürliche redaktionelle Rangfolge. Der Affiliate-Hinweis erklärt, wie redaktionelle und kommerzielle Inhalte getrennt bleiben."]] },
      { title: "Hilfe & Datenschutz", items: [["Was ist geschützte Hilfe?", "Ein werbefreier Bereich mit unabhängiger Soforthilfe sowie Sperr- und Selbstausschlussoptionen. Die Nutzung wird nicht für Angebote, Rankings oder kommerzielle Personalisierung verwendet."], ["Wie beantrage ich meine Daten oder Löschung?", "Kontaktiere den Verantwortlichen über die Datenschutzseite. Daten können weiterhin gespeichert werden, soweit dies für gesetzliche Pflichten, Betrugsprävention oder Sicherungskopien erforderlich ist."]] },
    ],
  },
  "it-IT": {
    metadataTitle: "FAQ B4GAMBLE", metadataDescription: "Risposte chiare su B4GAMBLE.", eyebrow: "FAQ", titleLead: "Risposte", titleEmphasis: "chiare.", railPrompt: "Non hai trovato?", contactLink: "Contattaci →", methodologyLink: "Metodologia", affiliateLink: "Informativa affiliati",
    groups: [
      { title: "B4GAMBLE", items: [["Che cos'è B4GAMBLE?", "Tre aree collegate: un Programma autonomo di controllo, informazioni educative ed editoriali sui casinò e pagine commerciali dichiarate per adulti che scelgono di confrontare dati pubblicati."], ["Cosa significa B4GAMBLE?", "Before Gamble, cioè «prima di giocare». «B4» in inglese si legge «before»: conosci i tuoi limiti e le tue abitudini prima di puntare, non dopo una perdita. Il Programma gratuito in 10 passi è costruito intorno a quel momento."], ["Chi scrive le recensioni?", "Il team editoriale cura le recensioni. La disponibilità commerciale è gestita separatamente e i limiti rilevanti delle fonti restano visibili."]] },
      { title: "Programma", items: [["Il Programma è davvero gratuito?", "Il Programma attuale è gratuito e non prevede accessi a pagamento. Una Missione, «Informati in modo responsabile», si conclude aprendo nel tuo menu le pagine di casinò, bonus e offerte; usarle è una tua scelta."], ["Chi può vedere ciò che dico nel Programma?", "La tua situazione serve solo a generare il risultato richiesto. I dati di Programma e Aiuto sono esclusi da offerte, classifiche, pubblicità e personalizzazione commerciale; la pagina Privacy spiega dati salvati e richieste sui diritti."], ["Serve un account per iniziare?", "No. Prima descrivi la situazione a voce o per iscritto; la registrazione con Google o email arriva solo quando il Punto di partenza è pronto per essere salvato."]] },
      { title: "Casinò e offerte", items: [["Come valutate i casinò?", "B4GAMBLE applica il metodo editoriale dichiarato alle prove disponibili per ogni record pubblicato. Stato delle fonti, date, campi mancanti e limiti restano parte della recensione."], ["Perché alcuni casinò indicano «Solo recensione»?", "Al momento non è disponibile alcun link verificato per registrarsi, quindi non ne mostriamo uno. La recensione e le informazioni pubblicate disponibili restano visibili."], ["Cosa accade quando seleziono Vedi offerta?", "Una conferma spiega che stai lasciando B4GAMBLE e ripete l'informativa sulla commissione. Puoi proseguire o restare."]] },
      { title: "Modello commerciale", items: [["Come guadagna B4GAMBLE?", "B4GAMBLE può ricevere una commissione quando utilizzi un link di affiliazione chiaramente indicato. I link commerciali sono identificati e spiegati prima che tu lasci il sito."], ["La commissione influenza le classifiche?", "Il compenso affiliato non determina l'Editor Score né la classifica editoriale naturale. Consulta l’Informativa affiliati per capire come vengono separati i contenuti editoriali e commerciali."]] },
      { title: "Aiuto e privacy", items: [["Che cos'è l'Aiuto protetto?", "Uno spazio senza contenuti commerciali con supporto indipendente immediato e opzioni di blocco e autoesclusione. L'uso dell'Aiuto protetto non alimenta offerte, classifiche o personalizzazione commerciale."], ["Come richiedo i miei dati o la cancellazione?", "Contatta il titolare tramite la pagina Privacy. I dati possono continuare a essere conservati per obblighi di legge, prevenzione delle frodi o nelle copie di sicurezza, ove applicabile."]] },
    ],
  },
  "es-ES": {
    metadataTitle: "Preguntas frecuentes de B4GAMBLE", metadataDescription: "Respuestas claras sobre B4GAMBLE.", eyebrow: "PREGUNTAS", titleLead: "Respuestas", titleEmphasis: "claras.", railPrompt: "¿No lo encuentras?", contactLink: "Contáctanos →", methodologyLink: "Metodología", affiliateLink: "Divulgación de afiliación",
    groups: [
      { title: "Sobre B4GAMBLE", items: [["¿Qué es B4GAMBLE?", "Tres áreas conectadas: un Programa de control autodirigido, información educativa y editorial sobre casinos y páginas comerciales abiertas para adultos que deciden comparar registros publicados."], ["¿Qué significa B4GAMBLE?", "Before Gamble, es decir, «antes de jugar». «B4» se lee «before» en inglés: conoce tus límites y tus hábitos antes de apostar, no después de una pérdida. El Programa gratuito de 10 pasos está pensado para ese momento."], ["¿Quién escribe las reseñas?", "El equipo editorial mantiene las reseñas. La disponibilidad comercial se gestiona por separado y las limitaciones relevantes de las fuentes permanecen visibles."]] },
      { title: "Programa", items: [["¿El Programa es realmente gratuito?", "El Programa actual es gratuito y no tiene muro de pago. Una Misión, «Investiga de forma responsable», termina abriendo en tu menú las páginas de casinos, bonos y ofertas; usarlas es decisión tuya."], ["¿Quién puede ver lo que digo en el Programa?", "Tu situación solo se usa para generar el resultado que solicitas. Los datos del Programa y de Ayuda quedan fuera de ofertas, clasificaciones, anuncios y personalización comercial; la página de Privacidad explica los datos guardados y las solicitudes de derechos."], ["¿Necesito una cuenta para empezar?", "No. Primero hablas o escribes sobre tu situación; el registro con Google o correo solo aparece cuando tu Punto de partida está listo para guardarse."]] },
      { title: "Casinos y ofertas", items: [["¿Cómo evaluáis los casinos?", "B4GAMBLE aplica el marco editorial divulgado a las pruebas disponibles de cada registro publicado. El estado de la fuente, las fechas, los campos ausentes y las limitaciones forman parte de la reseña."], ["¿Por qué algunos casinos indican «Solo reseña»?", "Significa que ahora mismo no hay ningún enlace verificado para registrarse, así que no inventamos uno. La reseña y la información publicada disponible siguen visibles."], ["¿Qué ocurre al pulsar Ver oferta?", "Una confirmación explica que sales de B4GAMBLE y repite la divulgación de comisión. Puedes continuar al operador o quedarte."]] },
      { title: "Modelo comercial", items: [["¿Cómo gana dinero B4GAMBLE?", "B4GAMBLE puede recibir una comisión cuando utilizas un enlace de afiliación claramente identificado. Los enlaces comerciales se identifican y explican antes de salir del sitio."], ["¿La comisión afecta a las clasificaciones?", "La compensación de afiliación no determina el Editor Score ni la clasificación editorial natural. Consulta la Divulgación de afiliación para saber cómo se mantienen separados el contenido editorial y el comercial."]] },
      { title: "Ayuda y privacidad", items: [["¿Qué es la Ayuda protegida?", "Un espacio sin contenido comercial con apoyo independiente inmediato y opciones de bloqueo y autoexclusión. Su uso no se emplea para ofertas, clasificaciones ni personalización comercial."], ["¿Cómo solicito mis datos o su eliminación?", "Contacta con el responsable mediante la página de Privacidad. Los datos pueden seguir conservándose, cuando corresponda, para cumplir obligaciones legales, prevenir el fraude o mantener copias de seguridad."]] },
    ],
  },
  "pt-PT": {
    metadataTitle: "Perguntas frequentes da B4GAMBLE", metadataDescription: "Respostas claras sobre a B4GAMBLE.", eyebrow: "PERGUNTAS", titleLead: "Respostas", titleEmphasis: "claras.", railPrompt: "Não encontraste?", contactLink: "Contacta-nos →", methodologyLink: "Metodologia", affiliateLink: "Divulgação de afiliados",
    groups: [
      { title: "Sobre a B4GAMBLE", items: [["O que é a B4GAMBLE?", "Três áreas ligadas: um Programa de controlo autónomo, informação educativa e editorial sobre casinos e páginas comerciais claramente identificadas para adultos que decidiram comparar registos publicados."], ["O que significa B4GAMBLE?", "Before Gamble, ou seja, «antes de jogar». «B4» lê-se «before» em inglês: conhece os teus limites e os teus padrões antes de apostar, não depois de uma perda. O Programa gratuito de 10 passos foi pensado para esse momento."], ["Quem escreve as análises?", "A equipa editorial mantém as análises. A disponibilidade comercial é tratada separadamente e as limitações relevantes das fontes permanecem visíveis."]] },
      { title: "Programa", items: [["O Programa é mesmo gratuito?", "O Programa atual é gratuito e não tem barreira de pagamento. Uma Missão, «Pesquisa de forma responsável», termina ao abrir no teu menu as páginas de casinos, bónus e ofertas; usá-las é uma escolha tua."], ["Quem pode ver o que digo no Programa?", "A tua situação só é usada para gerar o resultado pedido. Os dados do Programa e da Ajuda ficam excluídos de ofertas, classificações, anúncios e personalização comercial; a página de Privacidade explica dados guardados e pedidos de direitos."], ["Preciso de conta para começar?", "Não. Primeiro falas ou escreves sobre a tua situação; o registo com Google ou email surge apenas quando o Ponto de partida está pronto para guardar."]] },
      { title: "Casinos e ofertas", items: [["Como avaliam os casinos?", "A B4GAMBLE aplica o método editorial divulgado às provas disponíveis para cada registo publicado. Estado da fonte, datas, campos em falta e limitações continuam a fazer parte da análise."], ["Porque dizem alguns casinos «Apenas análise»?", "Neste momento, não existe uma ligação de registo verificada, por isso não apresentamos nenhuma. A análise e a informação publicada disponível continuam visíveis."], ["O que acontece ao selecionar Ver oferta?", "Uma confirmação explica que vais sair da B4GAMBLE e repete a divulgação da comissão. Podes continuar para o operador ou ficar."]] },
      { title: "Modelo comercial", items: [["Como ganha dinheiro a B4GAMBLE?", "A B4GAMBLE pode receber comissão quando utilizas uma ligação de afiliado claramente identificada. As ligações comerciais são identificadas e explicadas antes de saíres do site."], ["A comissão afeta as classificações?", "A remuneração de afiliado não determina o Editor Score nem a classificação editorial natural. Consulta a Divulgação de afiliados para saber como os conteúdos editorial e comercial são mantidos separados."]] },
      { title: "Ajuda e privacidade", items: [["O que é a Ajuda protegida?", "Um espaço sem conteúdo comercial com apoio independente imediato e opções de bloqueio e autoexclusão. A utilização deste espaço não alimenta ofertas, classificações nem personalização comercial."], ["Como peço os meus dados ou eliminação?", "Contacta o responsável através da página de Privacidade. Os dados podem continuar a ser conservados para cumprir obrigações legais, prevenir fraude ou em cópias de segurança, quando aplicável."]] },
    ],
  },
  "el-GR": {
    metadataTitle: "Συχνές ερωτήσεις B4GAMBLE", metadataDescription: "Σαφείς απαντήσεις για το B4GAMBLE.", eyebrow: "ΣΥΧΝΕΣ ΕΡΩΤΗΣΕΙΣ", titleLead: "Σαφείς", titleEmphasis: "απαντήσεις.", railPrompt: "Δεν το βρήκες;", contactLink: "Επικοινώνησε →", methodologyLink: "Μεθοδολογία", affiliateLink: "Γνωστοποίηση συνεργατών",
    groups: [
      { title: "Σχετικά με το B4GAMBLE", items: [["Τι είναι το B4GAMBLE;", "Τρεις συνδεδεμένοι τομείς: ένα αυτοκαθοδηγούμενο Πρόγραμμα ελέγχου, εκπαιδευτικές και συντακτικές πληροφορίες για καζίνο και εμφανώς εμπορικές σελίδες για ενήλικες που επέλεξαν να συγκρίνουν δημοσιευμένα στοιχεία."], ["Τι σημαίνει B4GAMBLE;", "Before Gamble, δηλαδή «πριν παίξεις». Το «B4» διαβάζεται «before» στα αγγλικά: γνώρισε τα όριά σου και τις συνήθειές σου πριν ποντάρεις, όχι μετά από μια απώλεια. Το δωρεάν Πρόγραμμα 10 βημάτων είναι φτιαγμένο γι’ αυτή τη στιγμή."], ["Ποιος γράφει τις αξιολογήσεις;", "Η συντακτική ομάδα συντηρεί τις αξιολογήσεις. Η εμπορική διαθεσιμότητα εξετάζεται χωριστά και οι ουσιώδεις περιορισμοί των πηγών παραμένουν ορατοί."]] },
      { title: "Πρόγραμμα", items: [["Είναι πράγματι δωρεάν το Πρόγραμμα;", "Το τρέχον Πρόγραμμα παρέχεται δωρεάν και δεν απαιτεί πληρωμή. Μία Αποστολή, «Κάνε υπεύθυνη έρευνα», ολοκληρώνεται ανοίγοντας στο μενού σου τις σελίδες για καζίνο, μπόνους και προσφορές· το αν θα τις χρησιμοποιήσεις είναι δική σου επιλογή."], ["Ποιος βλέπει όσα λέω στο Πρόγραμμα;", "Η κατάστασή σου χρησιμοποιείται μόνο για το αποτέλεσμα Προγράμματος που ζητάς. Τα δεδομένα Προγράμματος και Βοήθειας αποκλείονται από προσφορές, κατατάξεις, διαφημίσεις και εμπορική εξατομίκευση· η σελίδα Απορρήτου εξηγεί την αποθήκευση και τα αιτήματα δικαιωμάτων."], ["Χρειάζομαι λογαριασμό για να αρχίσω;", "Όχι. Πρώτα μιλάς ή γράφεις για την κατάστασή σου· η εγγραφή με Google ή email γίνεται μόνο όταν το Σημείο Εκκίνησης είναι έτοιμο για αποθήκευση."]] },
      { title: "Καζίνο και προσφορές", items: [["Πώς αξιολογούνται τα καζίνο στο B4GAMBLE;", "Το B4GAMBLE εφαρμόζει το δημοσιευμένο συντακτικό πλαίσιο στα διαθέσιμα στοιχεία κάθε εγγραφής. Κατάσταση πηγής, ημερομηνίες, ελλείψεις και περιορισμοί παραμένουν μέρος της αξιολόγησης."], ["Γιατί ορισμένα καζίνο γράφουν «Μόνο αξιολόγηση»;", "Σημαίνει ότι δεν υπάρχει προς το παρόν επαληθευμένος σύνδεσμος εγγραφής, οπότε δεν επινοούμε έναν. Η αξιολόγηση και οι διαθέσιμες δημοσιευμένες πληροφορίες μένουν ορατές."], ["Τι γίνεται όταν επιλέξω Προβολή προσφοράς;", "Μια επιβεβαίωση εξηγεί ότι φεύγεις από το B4GAMBLE και επαναλαμβάνει τη γνωστοποίηση προμήθειας. Μπορείς να συνεχίσεις ή να μείνεις."]] },
      { title: "Εμπορικό μοντέλο", items: [["Πώς κερδίζει χρήματα το B4GAMBLE;", "Το B4GAMBLE μπορεί να λάβει προμήθεια όταν χρησιμοποιείς έναν σαφώς επισημασμένο σύνδεσμο συνεργάτη. Οι εμπορικοί σύνδεσμοι επισημαίνονται και εξηγούνται πριν φύγεις από τον ιστότοπο."], ["Επηρεάζει η προμήθεια τις κατατάξεις;", "Η αμοιβή συνεργάτη δεν καθορίζει το Editor Score ή τη φυσική συντακτική κατάταξη. Δες τη Γνωστοποίηση συνεργατών για το πώς διαχωρίζονται το συντακτικό και το εμπορικό περιεχόμενο."]] },
      { title: "Βοήθεια και απόρρητο", items: [["Τι είναι η προστατευμένη Βοήθεια;", "Ένας χώρος χωρίς εμπορικό περιεχόμενο με άμεση ανεξάρτητη υποστήριξη και επιλογές αποκλεισμού και αυτοαποκλεισμού. Η χρήση του δεν τροφοδοτεί προσφορές, κατατάξεις ή εμπορική εξατομίκευση."], ["Πώς ζητώ τα δεδομένα μου ή διαγραφή;", "Επικοινώνησε με τον υπεύθυνο μέσω της σελίδας Απορρήτου. Τα δεδομένα ενδέχεται να συνεχίσουν να διατηρούνται, όπου απαιτείται, για νομικές υποχρεώσεις, πρόληψη απάτης ή αντίγραφα ασφαλείας."]] },
    ],
  },
  "nl-NL": {
    metadataTitle: "Veelgestelde vragen over B4GAMBLE", metadataDescription: "Heldere antwoorden over B4GAMBLE.", eyebrow: "VEELGESTELDE VRAGEN", titleLead: "Heldere", titleEmphasis: "antwoorden.", railPrompt: "Niet gevonden?", contactLink: "Neem contact op →", methodologyLink: "Methodologie", affiliateLink: "Affiliateverklaring",
    groups: [
      { title: "Over B4GAMBLE", items: [["Wat is B4GAMBLE?", "Drie verbonden gebieden: een zelfgestuurd controleprogramma, educatieve en redactionele casino-informatie en openlijk commerciële pagina's voor volwassenen die gepubliceerde gegevens willen vergelijken."], ["Waar staat B4GAMBLE voor?", "Voor Before Gamble, oftewel ‘voordat je speelt’. ‘B4’ spreek je in het Engels uit als ‘before’: ken je grenzen en patronen voordat je inzet, niet pas na een verlies. Het gratis Programma van 10 stappen is precies voor dat moment gemaakt."], ["Wie schrijft de recensies?", "Het redactieteam onderhoudt de recensies. Commerciële beschikbaarheid wordt afzonderlijk behandeld en belangrijke bronbeperkingen blijven zichtbaar."]] },
      { title: "Programma", items: [["Is het Programma echt gratis?", "Het huidige Programma is gratis te gebruiken en heeft geen betaalmuur. Eén Missie, ‘Doe verantwoord onderzoek’, eindigt met het openen van de pagina's over casino's, bonussen en aanbiedingen in je menu; of je ze gebruikt, bepaal je zelf."], ["Wie kan zien wat ik in het Programma zeg?", "Je situatie wordt alleen gebruikt voor de gevraagde Programma-uitkomst. Programma- en Helpgegevens zijn uitgesloten van aanbiedingen, ranglijsten, advertenties en commerciële personalisatie; de Privacypagina legt opslag en rechtenverzoeken uit."], ["Heb ik een account nodig om te beginnen?", "Nee. Je spreekt of typt eerst over je situatie; registratie met Google of e-mail volgt pas wanneer je Startpunt klaar is om op te slaan."]] },
      { title: "Casino's en aanbiedingen", items: [["Hoe beoordelen jullie casino's?", "B4GAMBLE past het gepubliceerde redactionele kader toe op het beschikbare bewijs voor elk gepubliceerd record. Bronstatus, datums, ontbrekende velden en beperkingen blijven onderdeel van de recensie."], ["Waarom staat bij sommige casino's ‘Alleen recensie’?", "Er is momenteel geen geverifieerde registratielink beschikbaar, dus we tonen er geen. De recensie en de beschikbare gepubliceerde informatie blijven zichtbaar."], ["Wat gebeurt er bij Aanbieding bekijken?", "Een bevestiging legt uit dat je B4GAMBLE verlaat en herhaalt de commissievermelding. Je kunt doorgaan naar de aanbieder of blijven."]] },
      { title: "Commercieel model", items: [["Hoe verdient B4GAMBLE geld?", "B4GAMBLE kan commissie ontvangen wanneer je een duidelijk gemarkeerde affiliatelink gebruikt. Commerciële links worden gemarkeerd en toegelicht voordat je de site verlaat."], ["Beïnvloedt commissie de ranglijst?", "Affiliatevergoeding bepaalt niet de Editor Score of natuurlijke redactionele rangschikking. Zie de Affiliateverklaring voor hoe redactionele en commerciële inhoud gescheiden blijven."]] },
      { title: "Help en privacy", items: [["Wat is beschermde Help?", "Een commercievrije ruimte met onmiddellijke onafhankelijke ondersteuning en blokkerings- en zelfuitsluitingsopties. Gebruik wordt niet ingezet voor aanbiedingen, ranglijsten of commerciële personalisatie."], ["Hoe vraag ik mijn gegevens of verwijdering aan?", "Neem via de Privacypagina contact op met de verwerkingsverantwoordelijke. Gegevens kunnen waar nodig langer worden bewaard vanwege wettelijke verplichtingen, fraudepreventie of back-ups."]] },
    ],
  },
  "sv-SE": {
    metadataTitle: "Vanliga frågor om B4GAMBLE", metadataDescription: "Tydliga svar om B4GAMBLE.", eyebrow: "VANLIGA FRÅGOR", titleLead: "Tydliga", titleEmphasis: "svar.", railPrompt: "Hittade du inte?", contactLink: "Kontakta oss →", methodologyLink: "Metod", affiliateLink: "Affiliateinformation",
    groups: [
      { title: "Om B4GAMBLE", items: [["Vad är B4GAMBLE?", "Tre sammanlänkade områden: ett självstyrt kontrollprogram, utbildande och redaktionell casinoinformation samt öppet kommersiella sidor för vuxna som valt att jämföra publicerade uppgifter."], ["Vad står B4GAMBLE för?", "Before Gamble, alltså ”innan du spelar”. ”B4” uttalas ”before” på engelska: känn dina gränser och mönster innan du satsar, inte först efter en förlust. Det kostnadsfria Programmet i 10 steg är byggt för just det ögonblicket."], ["Vem skriver recensionerna?", "Redaktionen underhåller recensionerna. Kommersiell tillgänglighet hanteras separat och viktiga källbegränsningar förblir synliga."]] },
      { title: "Programmet", items: [["Är Programmet verkligen gratis?", "Det nuvarande Programmet är kostnadsfritt och har ingen betalvägg. Ett Uppdrag, ”Undersök ansvarsfullt”, avslutas med att sidorna om kasinon, bonusar och erbjudanden öppnas i din meny; om du använder dem är ditt val."], ["Vem kan se vad jag säger i Programmet?", "Din situation används bara för Programresultatet du begär. Program- och Hjälpdata är uteslutna från erbjudanden, rankningar, annonser och kommersiell personalisering; Integritetssidan förklarar sparade data och rättighetsbegäranden."], ["Behöver jag ett konto för att börja?", "Nej. Du talar eller skriver först om din situation; registrering med Google eller e-post sker först när din Startpunkt är redo att sparas."]] },
      { title: "Casinon och erbjudanden", items: [["Hur bedömer ni casinon?", "B4GAMBLE tillämpar det redovisade redaktionella ramverket på tillgänglig evidens för varje publicerad post. Källstatus, datum, saknade fält och begränsningar förblir del av recensionen."], ["Varför står det ”Endast recension” på vissa casinon?", "Det finns ingen verifierad registreringslänk just nu, så vi visar ingen. Recensionen och den tillgängliga publicerade informationen förblir synliga."], ["Vad händer när jag väljer Visa erbjudande?", "En bekräftelse förklarar att du lämnar B4GAMBLE och upprepar provisionsinformationen. Du kan fortsätta eller stanna."]] },
      { title: "Kommersiell modell", items: [["Hur tjänar B4GAMBLE pengar?", "B4GAMBLE kan få provision när du använder en tydligt märkt affiliatelänk. Kommersiella länkar märks och förklaras innan du lämnar webbplatsen."], ["Påverkar provision rankningar?", "Affiliateersättning avgör inte Editor Score eller naturlig redaktionell rankning. Se Affiliateinformationen för hur redaktionellt och kommersiellt innehåll hålls åtskilt."]] },
      { title: "Hjälp och integritet", items: [["Vad är skyddad Hjälp?", "En kommersiellt fri yta med omedelbart oberoende stöd samt blockerings- och självavstängningsalternativ. Användningen påverkar inte erbjudanden, rankningar eller kommersiell personalisering."], ["Hur begär jag mina data eller radering?", "Kontakta personuppgiftsansvarig via Integritetssidan. Uppgifter kan där det krävs fortsätta att lagras på grund av lagkrav, bedrägeribekämpning eller säkerhetskopior."]] },
    ],
  },
  "da-DK": {
    metadataTitle: "Ofte stillede spørgsmål om B4GAMBLE", metadataDescription: "Klare svar om B4GAMBLE.", eyebrow: "SPØRGSMÅL", titleLead: "Klare", titleEmphasis: "svar.", railPrompt: "Fandt du det ikke?", contactLink: "Kontakt os →", methodologyLink: "Metode", affiliateLink: "Affiliateoplysning",
    groups: [
      { title: "Om B4GAMBLE", items: [["Hvad er B4GAMBLE?", "Tre forbundne områder: et selvstyret kontrolprogram, uddannende og redaktionel casinoinformation og åbent kommercielle sider for voksne, der har valgt at sammenligne offentliggjorte oplysninger."], ["Hvad står B4GAMBLE for?", "Before Gamble, altså »før du spiller«. »B4« udtales »before« på engelsk: kend dine grænser og mønstre, før du satser, ikke først efter et tab. Det gratis Program i 10 trin er bygget til netop det øjeblik."], ["Hvem skriver anmeldelserne?", "Redaktionen vedligeholder anmeldelserne. Kommerciel tilgængelighed håndteres separat, og væsentlige kildebegrænsninger forbliver synlige."]] },
      { title: "Programmet", items: [["Er Programmet virkelig gratis?", "Det nuværende Program er gratis og har ingen betalingsmur. Én Mission, ”Undersøg ansvarligt”, slutter med, at siderne om casinoer, bonusser og tilbud åbnes i din menu; om du bruger dem, er dit valg."], ["Hvem kan se, hvad jeg siger i Programmet?", "Din situation bruges kun til det Programresultat, du beder om. Program- og Hjælpedata er udelukket fra tilbud, rangeringer, annoncer og kommerciel personalisering; Privatlivssiden forklarer gemte data og rettighedsanmodninger."], ["Skal jeg have en konto for at begynde?", "Nej. Du taler eller skriver først om din situation; registrering med Google eller email kommer først, når dit Udgangspunkt er klar til at blive gemt."]] },
      { title: "Casinoer og tilbud", items: [["Hvordan vurderer I casinoer?", "B4GAMBLE anvender den offentliggjorte redaktionelle ramme på den tilgængelige evidens for hver udgivet post. Kildestatus, datoer, manglende felter og begrænsninger forbliver del af anmeldelsen."], ["Hvorfor står der »Kun anmeldelse« ved nogle casinoer?", "Der er ikke noget verificeret registreringslink tilgængeligt lige nu, så vi viser ikke et. Anmeldelsen og de tilgængelige offentliggjorte oplysninger forbliver synlige."], ["Hvad sker der ved Vis tilbud?", "En bekræftelse forklarer, at du forlader B4GAMBLE, og gentager provisionsoplysningen. Du kan fortsætte eller blive."]] },
      { title: "Kommerciel model", items: [["Hvordan tjener B4GAMBLE penge?", "B4GAMBLE kan modtage provision, når du bruger et tydeligt markeret affiliatelink. Kommercielle links markeres og forklares, før du forlader siden."], ["Påvirker provision rangeringer?", "Affiliatebetaling bestemmer ikke Editor Score eller naturlig redaktionel rangering. Se Affiliateoplysningen for, hvordan redaktionelt og kommercielt indhold holdes adskilt."]] },
      { title: "Hjælp og privatliv", items: [["Hvad er beskyttet Hjælp?", "Et kommercielt frit område med øjeblikkelig uafhængig støtte samt blokerings- og selvudelukkelsesmuligheder. Brug påvirker ikke tilbud, rangeringer eller kommerciel personalisering."], ["Hvordan anmoder jeg om mine data eller sletning?", "Kontakt den dataansvarlige via Privatlivssiden. Data kan fortsat blive opbevaret, hvor det er nødvendigt af hensyn til lovkrav, forebyggelse af svindel eller sikkerhedskopier."]] },
    ],
  },
  "fi-FI": {
    metadataTitle: "B4GAMBLE – usein kysyttyä", metadataDescription: "Selkeät vastaukset B4GAMBLEsta.", eyebrow: "USEIN KYSYTTYÄ", titleLead: "Selkeät", titleEmphasis: "vastaukset.", railPrompt: "Etkö löytänyt?", contactLink: "Ota yhteyttä →", methodologyLink: "Menetelmä", affiliateLink: "Kumppanuusseloste",
    groups: [
      { title: "Tietoa B4GAMBLEsta", items: [["Mikä B4GAMBLE on?", "Kolme toisiinsa liittyvää aluetta: omaehtoinen hallintaohjelma, kasinoita koskeva opetus- ja toimituksellinen tieto sekä avoimesti kaupalliset sivut aikuisille, jotka haluavat vertailla julkaistuja tietoja."], ["Mitä B4GAMBLE tarkoittaa?", "Before Gamble eli ”ennen pelaamista”. ”B4” lausutaan englanniksi ”before”: tunne rajasi ja tapasi ennen kuin pelaat, älä vasta tappion jälkeen. Maksuton 10 vaiheen Ohjelma on rakennettu juuri tätä hetkeä varten."], ["Kuka kirjoittaa arviot?", "Toimitus ylläpitää arvioita. Kaupallinen saatavuus käsitellään erikseen ja olennaiset lähderajoitukset pidetään näkyvissä."]] },
      { title: "Ohjelma", items: [["Onko Ohjelma todella maksuton?", "Nykyinen Ohjelma on maksuton eikä siinä ole maksumuuria. Yksi Tehtävä, ”Tutki vastuullisesti”, päättyy siihen, että kasino-, bonus- ja tarjoussivut avautuvat valikkoosi; niiden käyttö on oma valintasi."], ["Kuka voi nähdä, mitä sanon Ohjelmassa?", "Tilannettasi käytetään vain pyytämäsi Ohjelmatuloksen luomiseen. Ohjelma- ja Ohjetietoja ei käytetä tarjouksiin, sijoituksiin, mainoksiin tai kaupalliseen personointiin; Tietosuojasivu kertoo tallennuksesta ja oikeuspyynnöistä."], ["Tarvitsenko tilin aloittamiseen?", "Et. Puhut tai kirjoitat ensin tilanteestasi; rekisteröinti Googlella tai sähköpostilla tulee vasta, kun Lähtökohtasi on valmis tallennettavaksi."]] },
      { title: "Kasinot ja tarjoukset", items: [["Miten arvioitte kasinoita?", "B4GAMBLE soveltaa julkaistua toimituksellista kehystä kunkin julkaistun tietueen käytettävissä olevaan aineistoon. Lähteen tila, päivämäärät, puuttuvat kentät ja rajoitukset pysyvät osana arviota."], ["Miksi joissakin kasinoissa lukee ”Vain arvio”?", "Varmennettua rekisteröitymislinkkiä ei ole tällä hetkellä saatavilla, joten emme väitä muuta. Arvio ja saatavilla oleva julkaistu tieto pysyvät näkyvissä."], ["Mitä tapahtuu, kun valitsen Näytä tarjous?", "Vahvistus kertoo, että poistut B4GAMBLEsta, ja toistaa palkkioselosteen. Voit jatkaa toimijalle tai jäädä."]] },
      { title: "Kaupallinen malli", items: [["Miten B4GAMBLE ansaitsee?", "B4GAMBLE voi saada palkkion, kun käytät selvästi merkittyä kumppanilinkkiä. Kaupalliset linkit merkitään ja selitetään ennen sivustolta poistumista."], ["Vaikuttaako palkkio sijoituksiin?", "Kumppanikorvaus ei määrää Editor Scorea tai luonnollista toimituksellista järjestystä. Kumppanuusseloste kertoo, miten toimituksellinen ja kaupallinen sisältö pidetään erillään."]] },
      { title: "Ohje ja tietosuoja", items: [["Mikä on suojattu Ohje?", "Kaupallisuudesta vapaa alue, jossa on välitöntä riippumatonta tukea sekä esto- ja omaehtoisen poissulkemisen vaihtoehtoja. Käyttö ei vaikuta tarjouksiin, sijoituksiin tai kaupalliseen personointiin."], ["Miten pyydän tietoni tai poiston?", "Ota yhteys rekisterinpitäjään Tietosuojasivun kautta. Tietoja voidaan tarvittaessa säilyttää edelleen lakisääteisten velvoitteiden, petosten ehkäisemisen tai varmuuskopioiden vuoksi."]] },
    ],
  },
  "nb-NO": {
    metadataTitle: "Vanlige spørsmål om B4GAMBLE", metadataDescription: "Tydelige svar om B4GAMBLE.", eyebrow: "VANLIGE SPØRSMÅL", titleLead: "Tydelige", titleEmphasis: "svar.", railPrompt: "Fant du det ikke?", contactLink: "Kontakt oss →", methodologyLink: "Metode", affiliateLink: "Affiliateopplysning",
    groups: [
      { title: "Om B4GAMBLE", items: [["Hva er B4GAMBLE?", "Tre sammenknyttede områder: et selvstyrt kontrollprogram, lærerik og redaksjonell kasinoinformasjon og åpent kommersielle sider for voksne som har valgt å sammenligne publiserte opplysninger."], ["Hva står B4GAMBLE for?", "Before Gamble, altså «før du spiller». «B4» uttales «before» på engelsk: kjenn grensene og mønstrene dine før du satser, ikke først etter et tap. Det gratis Programmet i 10 steg er laget for akkurat det øyeblikket."], ["Hvem skriver anmeldelsene?", "Redaksjonen vedlikeholder anmeldelsene. Kommersiell tilgjengelighet behandles separat, og vesentlige kildebegrensninger forblir synlige."]] },
      { title: "Programmet", items: [["Er Programmet virkelig gratis?", "Det nåværende Programmet er gratis og har ingen betalingsmur. Ett Oppdrag, «Undersøk ansvarlig», avsluttes med at sidene om kasinoer, bonuser og tilbud åpnes i menyen din; om du bruker dem, er ditt valg."], ["Hvem kan se det jeg sier i Programmet?", "Situasjonen din brukes bare til Programresultatet du ber om. Program- og Hjelpedata er utelukket fra tilbud, rangeringer, annonser og kommersiell personalisering; Personvernsiden forklarer lagring og rettighetsforespørsler."], ["Trenger jeg en konto for å starte?", "Nei. Du snakker eller skriver først om situasjonen din; registrering med Google eller e-post kommer først når Utgangspunktet er klart til å lagres."]] },
      { title: "Kasinoer og tilbud", items: [["Hvordan vurderer dere kasinoer?", "B4GAMBLE bruker det offentliggjorte redaksjonelle rammeverket på tilgjengelig evidens for hver publiserte oppføring. Kildestatus, datoer, manglende felt og begrensninger forblir del av anmeldelsen."], ["Hvorfor står det «Kun anmeldelse» ved noen kasinoer?", "Det finnes ingen bekreftet registreringslenke akkurat nå, så vi viser ingen. Anmeldelsen og tilgjengelig publisert informasjon forblir synlig."], ["Hva skjer når jeg velger Vis tilbud?", "En bekreftelse forklarer at du forlater B4GAMBLE og gjentar provisjonsopplysningen. Du kan fortsette eller bli."]] },
      { title: "Kommersiell modell", items: [["Hvordan tjener B4GAMBLE penger?", "B4GAMBLE kan motta provisjon når du bruker en tydelig merket affiliatelenke. Kommersielle lenker merkes og forklares før du forlater nettstedet."], ["Påvirker provisjon rangeringer?", "Affiliatebetaling bestemmer ikke Editor Score eller naturlig redaksjonell rangering. Se Affiliateopplysningen for hvordan redaksjonelt og kommersielt innhold holdes atskilt."]] },
      { title: "Hjelp og personvern", items: [["Hva er beskyttet Hjelp?", "Et kommersielt fritt område med umiddelbar uavhengig støtte samt blokkerings- og selvutestengingsalternativer. Bruk påvirker ikke tilbud, rangeringer eller kommersiell personalisering."], ["Hvordan ber jeg om dataene mine eller sletting?", "Kontakt behandlingsansvarlig via Personvernsiden. Opplysninger kan fortsatt lagres der det er nødvendig på grunn av lovkrav, svindelforebygging eller sikkerhetskopier."]] },
    ],
  },
  "uk-UA": {
    metadataTitle: "Поширені запитання про B4GAMBLE", metadataDescription: "Чіткі відповіді про B4GAMBLE.", eyebrow: "ПОШИРЕНІ ЗАПИТАННЯ", titleLead: "Чіткі", titleEmphasis: "відповіді.", railPrompt: "Не знайшлося відповіді?", contactLink: "Написати нам →", methodologyLink: "Методологія", affiliateLink: "Розкриття партнерства",
    groups: [
      { title: "Про B4GAMBLE", items: [["Що таке B4GAMBLE?", "Три пов'язані частини: Програма контролю, яку ти проходиш самостійно, навчальна та редакційна інформація про казино і відкрито комерційні сторінки з добірками для повнолітніх, які вирішили порівняти опубліковані дані."], ["Що означає назва B4GAMBLE?", "Before Gamble, тобто «перед грою». «B4» англійською читається як «before»: знай свої межі та звички до того, як зробиш ставку, а не після програшу. Безкоштовна Програма з 10 кроків побудована навколо цього моменту."], ["Хто пише огляди?", "Вмістом оглядів опікується редакційна команда. Комерційна доступність розглядається окремо, а кожне істотне обмеження джерел має залишатися видимим."]] },
      { title: "Програма", items: [["Програма справді безкоштовна?", "Поточна Програма безкоштовна, платного доступу в ній немає. Одна Місія, «Досліджуй відповідально», завершується тим, що у твоєму меню відкриваються сторінки про казино, бонуси та пропозиції; користуватися ними чи ні — вирішуєш ти."], ["Хто може бачити те, що я кажу в Програмі?", "Твоя ситуація використовується лише для того, щоб створити результат Програми, який ти запитуєш. Дані Програми та Допомоги виключені з пропозицій, рейтингів, реклами та комерційної персоналізації; сторінка «Конфіденційність» пояснює, які дані зберігаються і як подати запит щодо своїх прав."], ["Чи потрібен акаунт, щоб почати?", "Ні. Спершу ти розповідаєш про свою ситуацію голосом або текстом; реєстрація через Google або електронну пошту з'являється лише після того, як твоя Відправна точка готова, щоб її можна було зберегти."]] },
      { title: "Казино та пропозиції", items: [["Як ви оцінюєте казино?", "B4GAMBLE застосовує оприлюднену редакційну систему оцінювання до підтверджень, доступних для кожного опублікованого запису. Статус джерел, дати, відсутні поля та обмеження залишаються частиною огляду."], ["Чому біля деяких казино написано «Лише огляд»?", "Зараз немає перевіреного посилання для реєстрації, тому ми його не вигадуємо. Огляд і доступна опублікована інформація залишаються видимими."], ["Що відбувається, коли я натискаю «Переглянути пропозицію»?", "Вікно підтвердження пояснює, що ти залишаєш B4GAMBLE, і ще раз розкриває інформацію про комісію. Ти можеш перейти до оператора або залишитися."]] },
      { title: "Комерційна модель", items: [["Як B4GAMBLE заробляє?", "B4GAMBLE може отримувати комісію, коли ти користуєшся чітко позначеним партнерським посиланням. Комерційні посилання позначаються та пояснюються до того, як ти залишиш сайт."], ["Чи впливає комісія на рейтинги?", "Партнерська винагорода не визначає ні Editor Score, ні природного редакційного рейтингу. У розділі «Розкриття партнерства» пояснено, як редакційний і комерційний вміст тримаються окремо."]] },
      { title: "Допомога та конфіденційність", items: [["Що таке Захищена допомога?", "Простір без комерційного вмісту з посиланнями на негайну незалежну підтримку, а також на засоби блокування та самовиключення. Активність у розділі «Захищена допомога» не використовується для пропозицій, рейтингів чи комерційної персоналізації."], ["Як запросити свої дані або їх видалення?", "Звернися до контролера даних через сторінку «Конфіденційність». Дані можуть і далі зберігатися, якщо це застосовно, для виконання юридичних обов'язків, запобігання шахрайству чи ведення резервних копій."]] },
    ],
  },
  "ru-RU": {
    metadataTitle: "Частые вопросы о B4GAMBLE", metadataDescription: "Понятные ответы о B4GAMBLE.", eyebrow: "ЧАСТЫЕ ВОПРОСЫ", titleLead: "Понятные", titleEmphasis: "ответы.", railPrompt: "Не нашлось ответа?", contactLink: "Написать нам →", methodologyLink: "Методология", affiliateLink: "Раскрытие партнёрства",
    groups: [
      { title: "О B4GAMBLE", items: [["Что такое B4GAMBLE?", "Три связанные части: Программа контроля, которую ты проходишь самостоятельно, обучающая и редакционная информация о казино и открыто коммерческие страницы с подборками для взрослых, которые решили сравнить опубликованные данные."], ["Что означает название B4GAMBLE?", "Before Gamble, то есть «до игры». «B4» — сокращение от английского «before»: знай свои лимиты и привычки до того, как сделаешь ставку, а не после проигрыша. Бесплатная Программа из 10 шагов построена вокруг этого момента."], ["Кто пишет обзоры?", "За содержание обзоров отвечает редакционная команда.Коммерческая доступность рассматривается отдельно, а каждое существенное ограничение источников должно оставаться на виду."]] },
      { title: "Программа", items: [["Программа действительно бесплатная?", "Текущая Программа бесплатна, платного доступа в ней нет. Одна Миссия, «Изучай ответственно», завершается тем, что в твоём меню открываются страницы о казино, бонусах и предложениях; пользоваться ими или нет — решаешь ты."], ["Кто может видеть то, что я говорю в Программе?", "Твоя ситуация используется только для того, чтобы создать результат Программы, который ты запрашиваешь. Данные Программы и Помощи исключены из предложений, рейтингов, рекламы и коммерческой персонализации; на странице «Конфиденциальность» объясняется, какие данные сохраняются и как подать запрос о своих правах."], ["Нужен ли аккаунт, чтобы начать?", "Нет. Сначала ты рассказываешь о своей ситуации голосом или текстом; регистрация через Google или электронную почту появляется только после того, как твоя Отправная точка готова, — чтобы её можно было сохранить."]] },
      { title: "Казино и предложения", items: [["Как B4GAMBLE оценивает казино?", "B4GAMBLE применяет раскрытую редакционную систему оценки к подтверждениям, доступным для каждой опубликованной записи. Статус источников, даты, отсутствующие поля и ограничения остаются частью обзора."], ["Почему у некоторых казино указано «Только обзор»?", "Сейчас нет проверенной ссылки для регистрации, поэтому мы её не выдумываем. Обзор и доступная опубликованная информация остаются на виду."], ["Что происходит, когда я нажимаю «Посмотреть предложение»?", "Окно подтверждения объясняет, что ты покидаешь B4GAMBLE, и ещё раз раскрывает информацию о комиссии. Ты можешь перейти к оператору или остаться."]] },
      { title: "Коммерческая модель", items: [["Как B4GAMBLE зарабатывает?", "B4GAMBLE может получать комиссию, когда ты пользуешься чётко обозначенной партнёрской ссылкой. Коммерческие ссылки обозначаются и объясняются до того, как ты покинешь сайт."], ["Влияет ли комиссия на рейтинги?", "Партнёрское вознаграждение не определяет ни Editor Score, ни естественный редакционный рейтинг. В разделе «Раскрытие партнёрства» объясняется, как редакционный и коммерческий контент остаются раздельными."]] },
      { title: "Помощь и конфиденциальность", items: [["Что такое Защищённая помощь?", "Пространство без коммерческого контента со ссылками на немедленную независимую поддержку, а также на средства блокировки и самоисключения. Активность в разделе «Защищённая помощь» не используется для предложений, рейтингов или коммерческой персонализации."], ["Как запросить свои данные или их удаление?", "Обратись к контролёру данных через страницу «Конфиденциальность». Данные могут и дальше храниться, если это применимо, для выполнения юридических обязательств, предотвращения мошенничества или ведения резервных копий."]] },
    ],
  },
  "en-CA": en,
  "fr-CA": en,
};

const catalog: Record<SupportedLocale, FaqMessages> = {
  ...baseCatalog,
  "es-PE": baseCatalog["es-ES"],
};

export function faqMessages(locale: SupportedLocale) {
  return catalog[locale];
}
