import type { SupportedLocale } from "@/lib/market/registry";

type FaqItem = readonly [question: string, answer: string];
type FaqGroup = Readonly<{ title: string; items: readonly FaqItem[] }>;

export type FaqMessages = Readonly<{
  metadataTitle: string;
  metadataDescription: string;
  eyebrow: string;
  titleLead: string;
  titleEmphasis: string;
  groups: readonly FaqGroup[];
  railPrompt: string;
  contactLink: string;
  methodologyLink: string;
  affiliateLink: string;
}>;

const en: FaqMessages = {
  metadataTitle: "B4GAMBLE FAQ",
  metadataDescription: "Clear answers about B4GAMBLE.",
  eyebrow: "FAQ", titleLead: "Clear", titleEmphasis: "answers.", railPrompt: "Didn't find it?", contactLink: "Contact us →", methodologyLink: "Methodology", affiliateLink: "Affiliate Disclosure",
  groups: [
    { title: "About B4GAMBLE", items: [["What is B4GAMBLE?", "Three connected areas: a self-directed control Programme, educational and editorial casino information, and openly commercial discovery pages for adults who have decided to compare published records."], ["Who writes the reviews?", "The editorial team maintains review content. Commercial availability is handled separately, and every material source limitation should remain visible."]] },
    { title: "Programme", items: [["Is the Programme really free?", "The current Programme is free to use and has no paywall or commercial upsell inside Missions."], ["Who can see what I say in the Programme?", "Your situation is used only to generate the Programme output you request. Programme and Help data is excluded from offers, rankings, ads and commercial personalisation; the Privacy page explains saved data and rights requests."], ["Do I need an account to start?", "No. You speak or type your situation first; registration with Google or email comes only after your Starting Point is ready, so you can save it."]] },
    { title: "Casinos & Offers", items: [["How do you evaluate casinos?", "B4GAMBLE applies the disclosed editorial framework to the evidence available for each published record. Source status, dates, missing fields and limitations remain part of the review."], ["Why do some casinos say ‘Review only’?", "It means we cannot offer a governed signup route right now, so we do not fake one. The review and available published information stay visible."], ["What happens when I click View Offer?", "A confirmation explains that you are leaving B4GAMBLE and repeats the commission disclosure. You can continue to the operator or stay."]] },
    { title: "Commercial model", items: [["How does B4GAMBLE make money?", "B4GAMBLE may earn a commission after a governed commercial link. Commercial actions are labelled and explained before you leave the site."], ["Does commission affect rankings?", "Affiliate compensation does not determine Editor Score or natural editorial ranking. See the Affiliate Disclosure for the product boundary."]] },
    { title: "Help & Privacy", items: [["What is protected Help?", "A commercial-free space linking to immediate independent support, blocking and self-exclusion options. Protected Help activity is not used for offers, rankings or commercial personalisation."], ["How do I request my data or deletion?", "Contact the controller using the Privacy page. Legal, fraud-prevention and backup retention may continue where applicable."]] },
  ],
};

const catalog: Record<SupportedLocale, FaqMessages> = {
  "en-GB": en,
  "de-DE": {
    metadataTitle: "B4GAMBLE FAQ", metadataDescription: "Klare Antworten zu B4GAMBLE.", eyebrow: "FAQ", titleLead: "Klare", titleEmphasis: "Antworten.", railPrompt: "Nicht gefunden?", contactLink: "Kontakt →", methodologyLink: "Methodik", affiliateLink: "Affiliate-Hinweis",
    groups: [
      { title: "Über B4GAMBLE", items: [["Was ist B4GAMBLE?", "Drei verbundene Bereiche: ein selbstbestimmtes Kontrollprogramm, Bildungs- und redaktionelle Informationen zu Glücksspielanbietern sowie offen kommerzielle Vergleichsseiten für Erwachsene, die veröffentlichte Einträge vergleichen möchten."], ["Wer schreibt die Bewertungen?", "Das Redaktionsteam pflegt die Bewertungen. Kommerzielle Verfügbarkeit wird getrennt behandelt; wesentliche Quellenbeschränkungen bleiben sichtbar."]] },
      { title: "Programm", items: [["Ist das Programm wirklich kostenlos?", "Das aktuelle Programm ist kostenlos nutzbar und enthält in den Missionen weder Bezahlschranke noch kommerzielles Upselling."], ["Wer kann sehen, was ich im Programm sage?", "Deine Angaben werden nur für die angeforderte Programmausgabe verwendet. Programm- und Hilfedaten sind von Angeboten, Rankings, Werbung und kommerzieller Personalisierung ausgeschlossen; die Datenschutzseite erklärt gespeicherte Daten und Rechteanfragen."], ["Brauche ich zum Start ein Konto?", "Nein. Du sprichst oder schreibst zuerst über deine Situation. Die Anmeldung mit Google oder E-Mail folgt erst, wenn dein Ausgangspunkt zum Speichern bereit ist."]] },
      { title: "Glücksspielanbieter & Angebote", items: [["Wie bewertet ihr Glücksspielanbieter?", "B4GAMBLE wendet den offengelegten redaktionellen Rahmen auf die für jeden veröffentlichten Eintrag verfügbaren Nachweise an. Quellenstatus, Daten, fehlende Felder und Grenzen bleiben Teil der Bewertung."], ["Warum steht bei manchen Anbietern „Nur Bewertung“?", "Derzeit gibt es keine kontrolliert freigegebene Anmelderoute; wir erfinden keine. Die Bewertung und verfügbare veröffentlichte Information bleiben sichtbar."], ["Was geschieht bei „Angebot ansehen“?", "Eine Bestätigung erklärt, dass du B4GAMBLE verlässt, und wiederholt den Provisionshinweis. Du kannst fortfahren oder bleiben."]] },
      { title: "Geschäftsmodell", items: [["Wie verdient B4GAMBLE Geld?", "B4GAMBLE kann nach einem kontrollierten kommerziellen Link Provision erhalten. Kommerzielle Aktionen werden gekennzeichnet und erklärt, bevor du die Website verlässt."], ["Beeinflusst Provision die Rangfolge?", "Affiliate-Vergütung bestimmt weder Editor Score noch natürliche redaktionelle Rangfolge. Der Affiliate-Hinweis erklärt die Produktgrenze."]] },
      { title: "Hilfe & Datenschutz", items: [["Was ist geschützte Hilfe?", "Ein werbefreier Bereich mit unabhängiger Soforthilfe sowie Sperr- und Selbstausschlussoptionen. Die Nutzung wird nicht für Angebote, Rankings oder kommerzielle Personalisierung verwendet."], ["Wie beantrage ich meine Daten oder Löschung?", "Kontaktiere den Verantwortlichen über die Datenschutzseite. Gesetzliche, Betrugspräventions- und Sicherungsfristen können weiter gelten."]] },
    ],
  },
  "it-IT": {
    metadataTitle: "FAQ B4GAMBLE", metadataDescription: "Risposte chiare su B4GAMBLE.", eyebrow: "FAQ", titleLead: "Risposte", titleEmphasis: "chiare.", railPrompt: "Non hai trovato?", contactLink: "Contattaci →", methodologyLink: "Metodologia", affiliateLink: "Informativa affiliati",
    groups: [
      { title: "B4GAMBLE", items: [["Che cos'è B4GAMBLE?", "Tre aree collegate: un Programma autonomo di controllo, informazioni educative ed editoriali sui casinò e pagine commerciali dichiarate per adulti che scelgono di confrontare dati pubblicati."], ["Chi scrive le recensioni?", "Il team editoriale cura le recensioni. La disponibilità commerciale è gestita separatamente e i limiti rilevanti delle fonti restano visibili."]] },
      { title: "Programma", items: [["Il Programma è davvero gratuito?", "Il Programma attuale è gratuito e non contiene paywall o proposte commerciali nelle Missioni."], ["Chi può vedere ciò che dico nel Programma?", "La tua situazione serve solo a generare il risultato richiesto. I dati di Programma e Aiuto sono esclusi da offerte, classifiche, pubblicità e personalizzazione commerciale; la pagina Privacy spiega dati salvati e richieste sui diritti."], ["Serve un account per iniziare?", "No. Prima descrivi la situazione a voce o per iscritto; la registrazione con Google o email arriva solo quando il Punto di partenza è pronto per essere salvato."]] },
      { title: "Casinò e offerte", items: [["Come valutate i casinò?", "B4GAMBLE applica il metodo editoriale dichiarato alle prove disponibili per ogni record pubblicato. Stato delle fonti, date, campi mancanti e limiti restano parte della recensione."], ["Perché alcuni casinò indicano «Solo recensione»?", "Significa che al momento non possiamo offrire un percorso di registrazione autorizzato, quindi non ne inventiamo uno. Recensione e informazioni pubblicate restano visibili."], ["Cosa accade quando seleziono Vedi offerta?", "Una conferma spiega che stai lasciando B4GAMBLE e ripete l'informativa sulla commissione. Puoi proseguire o restare."]] },
      { title: "Modello commerciale", items: [["Come guadagna B4GAMBLE?", "B4GAMBLE può ricevere una commissione dopo un link commerciale controllato. Le azioni commerciali sono indicate e spiegate prima di lasciare il sito."], ["La commissione influenza le classifiche?", "Il compenso affiliato non determina l'Editor Score né la classifica editoriale naturale. Consulta l'Informativa affiliati per il confine del prodotto."]] },
      { title: "Aiuto e privacy", items: [["Che cos'è l'Aiuto protetto?", "Uno spazio senza contenuti commerciali con supporto indipendente immediato e opzioni di blocco e autoesclusione. L'uso dell'Aiuto protetto non alimenta offerte, classifiche o personalizzazione commerciale."], ["Come richiedo i miei dati o la cancellazione?", "Contatta il titolare tramite la pagina Privacy. Possono continuare ad applicarsi conservazione legale, prevenzione frodi e copie di sicurezza."]] },
    ],
  },
  "es-ES": {
    metadataTitle: "Preguntas frecuentes de B4GAMBLE", metadataDescription: "Respuestas claras sobre B4GAMBLE.", eyebrow: "PREGUNTAS", titleLead: "Respuestas", titleEmphasis: "claras.", railPrompt: "¿No lo encuentras?", contactLink: "Contáctanos →", methodologyLink: "Metodología", affiliateLink: "Divulgación de afiliación",
    groups: [
      { title: "Sobre B4GAMBLE", items: [["¿Qué es B4GAMBLE?", "Tres áreas conectadas: un Programa de control autodirigido, información educativa y editorial sobre casinos y páginas comerciales abiertas para adultos que deciden comparar registros publicados."], ["¿Quién escribe las reseñas?", "El equipo editorial mantiene las reseñas. La disponibilidad comercial se gestiona por separado y las limitaciones relevantes de las fuentes permanecen visibles."]] },
      { title: "Programa", items: [["¿El Programa es realmente gratuito?", "El Programa actual es gratuito y no tiene muro de pago ni venta comercial dentro de las Misiones."], ["¿Quién puede ver lo que digo en el Programa?", "Tu situación solo se usa para generar el resultado que solicitas. Los datos del Programa y de Ayuda quedan fuera de ofertas, clasificaciones, anuncios y personalización comercial; la página de Privacidad explica los datos guardados y las solicitudes de derechos."], ["¿Necesito una cuenta para empezar?", "No. Primero hablas o escribes sobre tu situación; el registro con Google o correo solo aparece cuando tu Punto de partida está listo para guardarse."]] },
      { title: "Casinos y ofertas", items: [["¿Cómo evaluáis los casinos?", "B4GAMBLE aplica el marco editorial divulgado a las pruebas disponibles de cada registro publicado. El estado de la fuente, las fechas, los campos ausentes y las limitaciones forman parte de la reseña."], ["¿Por qué algunos casinos indican «Solo reseña»?", "Significa que ahora no podemos ofrecer una ruta de registro autorizada, así que no la fingimos. La reseña y la información publicada disponible siguen visibles."], ["¿Qué ocurre al pulsar Ver oferta?", "Una confirmación explica que sales de B4GAMBLE y repite la divulgación de comisión. Puedes continuar al operador o quedarte."]] },
      { title: "Modelo comercial", items: [["¿Cómo gana dinero B4GAMBLE?", "B4GAMBLE puede recibir una comisión tras un enlace comercial controlado. Las acciones comerciales se identifican y explican antes de salir del sitio."], ["¿La comisión afecta a las clasificaciones?", "La compensación de afiliación no determina el Editor Score ni la clasificación editorial natural. Consulta la Divulgación de afiliación para conocer el límite del producto."]] },
      { title: "Ayuda y privacidad", items: [["¿Qué es la Ayuda protegida?", "Un espacio sin contenido comercial con apoyo independiente inmediato y opciones de bloqueo y autoexclusión. Su uso no se emplea para ofertas, clasificaciones ni personalización comercial."], ["¿Cómo solicito mis datos o su eliminación?", "Contacta con el responsable mediante la página de Privacidad. Puede continuar la conservación legal, antifraude y de copias de seguridad cuando corresponda."]] },
    ],
  },
  "pt-PT": {
    metadataTitle: "Perguntas frequentes da B4GAMBLE", metadataDescription: "Respostas claras sobre a B4GAMBLE.", eyebrow: "PERGUNTAS", titleLead: "Respostas", titleEmphasis: "claras.", railPrompt: "Não encontraste?", contactLink: "Contacta-nos →", methodologyLink: "Metodologia", affiliateLink: "Divulgação de afiliados",
    groups: [
      { title: "Sobre a B4GAMBLE", items: [["O que é a B4GAMBLE?", "Três áreas ligadas: um Programa de controlo autónomo, informação educativa e editorial sobre casinos e páginas comerciais assumidas para adultos que decidiram comparar registos publicados."], ["Quem escreve as análises?", "A equipa editorial mantém as análises. A disponibilidade comercial é tratada separadamente e as limitações relevantes das fontes permanecem visíveis."]] },
      { title: "Programa", items: [["O Programa é mesmo gratuito?", "O Programa atual é gratuito e não tem barreira de pagamento nem promoção comercial dentro das Missões."], ["Quem pode ver o que digo no Programa?", "A tua situação só é usada para gerar o resultado pedido. Os dados do Programa e da Ajuda ficam excluídos de ofertas, classificações, anúncios e personalização comercial; a página de Privacidade explica dados guardados e pedidos de direitos."], ["Preciso de conta para começar?", "Não. Primeiro falas ou escreves sobre a tua situação; o registo com Google ou email surge apenas quando o Ponto de partida está pronto para guardar."]] },
      { title: "Casinos e ofertas", items: [["Como avaliam os casinos?", "A B4GAMBLE aplica o método editorial divulgado às provas disponíveis para cada registo publicado. Estado da fonte, datas, campos em falta e limitações continuam a fazer parte da análise."], ["Porque dizem alguns casinos «Apenas análise»?", "Significa que não podemos oferecer agora uma rota de registo autorizada, por isso não inventamos uma. A análise e a informação publicada disponível continuam visíveis."], ["O que acontece ao selecionar Ver oferta?", "Uma confirmação explica que vais sair da B4GAMBLE e repete a divulgação da comissão. Podes continuar para o operador ou ficar."]] },
      { title: "Modelo comercial", items: [["Como ganha dinheiro a B4GAMBLE?", "A B4GAMBLE pode receber comissão após uma ligação comercial controlada. As ações comerciais são identificadas e explicadas antes de saíres do site."], ["A comissão afeta as classificações?", "A remuneração de afiliado não determina o Editor Score nem a classificação editorial natural. Consulta a Divulgação de afiliados para o limite do produto."]] },
      { title: "Ajuda e privacidade", items: [["O que é a Ajuda protegida?", "Um espaço sem conteúdo comercial com apoio independente imediato e opções de bloqueio e autoexclusão. A sua utilização não serve ofertas, classificações nem personalização comercial."], ["Como peço os meus dados ou eliminação?", "Contacta o responsável através da página de Privacidade. A conservação legal, antifraude e em cópias de segurança pode continuar quando aplicável."]] },
    ],
  },
  "el-GR": {
    metadataTitle: "Συχνές ερωτήσεις B4GAMBLE", metadataDescription: "Σαφείς απαντήσεις για το B4GAMBLE.", eyebrow: "ΣΥΧΝΕΣ ΕΡΩΤΗΣΕΙΣ", titleLead: "Σαφείς", titleEmphasis: "απαντήσεις.", railPrompt: "Δεν το βρήκες;", contactLink: "Επικοινώνησε →", methodologyLink: "Μεθοδολογία", affiliateLink: "Γνωστοποίηση συνεργατών",
    groups: [
      { title: "Σχετικά με το B4GAMBLE", items: [["Τι είναι το B4GAMBLE;", "Τρεις συνδεδεμένοι τομείς: ένα αυτοκαθοδηγούμενο Πρόγραμμα ελέγχου, εκπαιδευτικές και συντακτικές πληροφορίες για καζίνο και εμφανώς εμπορικές σελίδες για ενήλικες που επέλεξαν να συγκρίνουν δημοσιευμένα στοιχεία."], ["Ποιος γράφει τις αξιολογήσεις;", "Η συντακτική ομάδα συντηρεί τις αξιολογήσεις. Η εμπορική διαθεσιμότητα εξετάζεται χωριστά και οι ουσιώδεις περιορισμοί των πηγών παραμένουν ορατοί."]] },
      { title: "Πρόγραμμα", items: [["Είναι πράγματι δωρεάν το Πρόγραμμα;", "Το τρέχον Πρόγραμμα παρέχεται δωρεάν και δεν έχει paywall ή εμπορική προώθηση μέσα στις Αποστολές."], ["Ποιος βλέπει όσα λέω στο Πρόγραμμα;", "Η κατάστασή σου χρησιμοποιείται μόνο για το αποτέλεσμα Προγράμματος που ζητάς. Τα δεδομένα Προγράμματος και Βοήθειας αποκλείονται από προσφορές, κατατάξεις, διαφημίσεις και εμπορική εξατομίκευση· η σελίδα Απορρήτου εξηγεί την αποθήκευση και τα αιτήματα δικαιωμάτων."], ["Χρειάζομαι λογαριασμό για να αρχίσω;", "Όχι. Πρώτα μιλάς ή γράφεις για την κατάστασή σου· η εγγραφή με Google ή email γίνεται μόνο όταν το Σημείο Εκκίνησης είναι έτοιμο για αποθήκευση."]] },
      { title: "Καζίνο και προσφορές", items: [["Πώς αξιολογείτε τα καζίνο;", "Το B4GAMBLE εφαρμόζει το δημοσιευμένο συντακτικό πλαίσιο στα διαθέσιμα στοιχεία κάθε εγγραφής. Κατάσταση πηγής, ημερομηνίες, ελλείψεις και περιορισμοί παραμένουν μέρος της αξιολόγησης."], ["Γιατί ορισμένα καζίνο γράφουν «Μόνο αξιολόγηση»;", "Σημαίνει ότι δεν υπάρχει τώρα εγκεκριμένη διαδρομή εγγραφής, οπότε δεν επινοούμε μία. Η αξιολόγηση και οι διαθέσιμες δημοσιευμένες πληροφορίες μένουν ορατές."], ["Τι γίνεται όταν επιλέξω Προβολή προσφοράς;", "Μια επιβεβαίωση εξηγεί ότι φεύγεις από το B4GAMBLE και επαναλαμβάνει τη γνωστοποίηση προμήθειας. Μπορείς να συνεχίσεις ή να μείνεις."]] },
      { title: "Εμπορικό μοντέλο", items: [["Πώς κερδίζει χρήματα το B4GAMBLE;", "Το B4GAMBLE μπορεί να λάβει προμήθεια μετά από ελεγχόμενο εμπορικό σύνδεσμο. Οι εμπορικές ενέργειες επισημαίνονται και εξηγούνται πριν φύγεις από τον ιστότοπο."], ["Επηρεάζει η προμήθεια τις κατατάξεις;", "Η αμοιβή συνεργάτη δεν καθορίζει το Editor Score ή τη φυσική συντακτική κατάταξη. Δες τη Γνωστοποίηση συνεργατών για το όριο του προϊόντος."]] },
      { title: "Βοήθεια και απόρρητο", items: [["Τι είναι η προστατευμένη Βοήθεια;", "Ένας χώρος χωρίς εμπορικό περιεχόμενο με άμεση ανεξάρτητη υποστήριξη και επιλογές αποκλεισμού και αυτοαποκλεισμού. Η χρήση του δεν τροφοδοτεί προσφορές, κατατάξεις ή εμπορική εξατομίκευση."], ["Πώς ζητώ τα δεδομένα μου ή διαγραφή;", "Επικοινώνησε με τον υπεύθυνο μέσω της σελίδας Απορρήτου. Νομική, αντι-απάτη και εφεδρική διατήρηση μπορεί να συνεχιστεί όπου ισχύει."]] },
    ],
  },
  "nl-NL": {
    metadataTitle: "Veelgestelde vragen over B4GAMBLE", metadataDescription: "Heldere antwoorden over B4GAMBLE.", eyebrow: "VEELGESTELDE VRAGEN", titleLead: "Heldere", titleEmphasis: "antwoorden.", railPrompt: "Niet gevonden?", contactLink: "Neem contact op →", methodologyLink: "Methodologie", affiliateLink: "Affiliateverklaring",
    groups: [
      { title: "Over B4GAMBLE", items: [["Wat is B4GAMBLE?", "Drie verbonden gebieden: een zelfgestuurd controleprogramma, educatieve en redactionele casino-informatie en openlijk commerciële pagina's voor volwassenen die gepubliceerde gegevens willen vergelijken."], ["Wie schrijft de recensies?", "Het redactieteam onderhoudt de recensies. Commerciële beschikbaarheid wordt afzonderlijk behandeld en belangrijke bronbeperkingen blijven zichtbaar."]] },
      { title: "Programma", items: [["Is het Programma echt gratis?", "Het huidige Programma is gratis te gebruiken en bevat geen betaalmuur of commerciële upsell in Missies."], ["Wie kan zien wat ik in het Programma zeg?", "Je situatie wordt alleen gebruikt voor de gevraagde Programma-uitkomst. Programma- en Helpgegevens zijn uitgesloten van aanbiedingen, ranglijsten, advertenties en commerciële personalisatie; de Privacypagina legt opslag en rechtenverzoeken uit."], ["Heb ik een account nodig om te beginnen?", "Nee. Je spreekt of typt eerst over je situatie; registratie met Google of e-mail volgt pas wanneer je Startpunt klaar is om op te slaan."]] },
      { title: "Casino's en aanbiedingen", items: [["Hoe beoordelen jullie casino's?", "B4GAMBLE past het gepubliceerde redactionele kader toe op het beschikbare bewijs voor elk gepubliceerd record. Bronstatus, datums, ontbrekende velden en beperkingen blijven onderdeel van de recensie."], ["Waarom staat bij sommige casino's ‘Alleen recensie’?", "Er is nu geen beheerste aanmeldroute beschikbaar, dus we doen niet alsof. De recensie en beschikbare gepubliceerde informatie blijven zichtbaar."], ["Wat gebeurt er bij Aanbieding bekijken?", "Een bevestiging legt uit dat je B4GAMBLE verlaat en herhaalt de commissievermelding. Je kunt doorgaan naar de aanbieder of blijven."]] },
      { title: "Commercieel model", items: [["Hoe verdient B4GAMBLE geld?", "B4GAMBLE kan commissie ontvangen na een beheerste commerciële link. Commerciële acties zijn gemarkeerd en worden uitgelegd voordat je de site verlaat."], ["Beïnvloedt commissie de ranglijst?", "Affiliatevergoeding bepaalt niet de Editor Score of natuurlijke redactionele rangschikking. Zie de Affiliateverklaring voor de productgrens."]] },
      { title: "Help en privacy", items: [["Wat is beschermde Help?", "Een commerciële-vrije ruimte met onmiddellijke onafhankelijke ondersteuning en blokkerings- en zelfuitsluitingsopties. Gebruik wordt niet ingezet voor aanbiedingen, ranglijsten of commerciële personalisatie."], ["Hoe vraag ik mijn gegevens of verwijdering aan?", "Neem via de Privacypagina contact op met de verwerkingsverantwoordelijke. Wettelijke, fraudepreventie- en back-upbewaring kan waar nodig doorgaan."]] },
    ],
  },
  "sv-SE": {
    metadataTitle: "Vanliga frågor om B4GAMBLE", metadataDescription: "Tydliga svar om B4GAMBLE.", eyebrow: "VANLIGA FRÅGOR", titleLead: "Tydliga", titleEmphasis: "svar.", railPrompt: "Hittade du inte?", contactLink: "Kontakta oss →", methodologyLink: "Metod", affiliateLink: "Affiliateinformation",
    groups: [
      { title: "Om B4GAMBLE", items: [["Vad är B4GAMBLE?", "Tre sammanlänkade områden: ett självstyrt kontrollprogram, utbildande och redaktionell casinoinformation samt öppet kommersiella sidor för vuxna som valt att jämföra publicerade uppgifter."], ["Vem skriver recensionerna?", "Redaktionen underhåller recensionerna. Kommersiell tillgänglighet hanteras separat och viktiga källbegränsningar förblir synliga."]] },
      { title: "Programmet", items: [["Är Programmet verkligen gratis?", "Det nuvarande Programmet är kostnadsfritt och har ingen betalvägg eller kommersiell merförsäljning i Uppdragen."], ["Vem kan se vad jag säger i Programmet?", "Din situation används bara för Programresultatet du begär. Program- och Hjälpdata är uteslutna från erbjudanden, rankningar, annonser och kommersiell personalisering; Integritetssidan förklarar sparade data och rättighetsbegäranden."], ["Behöver jag ett konto för att börja?", "Nej. Du talar eller skriver först om din situation; registrering med Google eller e-post sker först när din Startpunkt är redo att sparas."]] },
      { title: "Casinon och erbjudanden", items: [["Hur bedömer ni casinon?", "B4GAMBLE tillämpar det redovisade redaktionella ramverket på tillgänglig evidens för varje publicerad post. Källstatus, datum, saknade fält och begränsningar förblir del av recensionen."], ["Varför står det ”Endast recension” på vissa casinon?", "Det finns ingen styrd registreringsväg just nu, så vi låtsas inte att det gör det. Recensionen och tillgänglig publicerad information förblir synliga."], ["Vad händer när jag väljer Visa erbjudande?", "En bekräftelse förklarar att du lämnar B4GAMBLE och upprepar provisionsinformationen. Du kan fortsätta eller stanna."]] },
      { title: "Kommersiell modell", items: [["Hur tjänar B4GAMBLE pengar?", "B4GAMBLE kan få provision efter en styrd kommersiell länk. Kommersiella åtgärder märks och förklaras innan du lämnar webbplatsen."], ["Påverkar provision rankningar?", "Affiliateersättning avgör inte Editor Score eller naturlig redaktionell rankning. Se Affiliateinformationen för produktgränsen."]] },
      { title: "Hjälp och integritet", items: [["Vad är skyddad Hjälp?", "En kommersiellt fri yta med omedelbart oberoende stöd samt blockerings- och självavstängningsalternativ. Användningen påverkar inte erbjudanden, rankningar eller kommersiell personalisering."], ["Hur begär jag mina data eller radering?", "Kontakta personuppgiftsansvarig via Integritetssidan. Rättslig, bedrägeriförebyggande och säkerhetskopierad lagring kan fortsätta där det krävs."]] },
    ],
  },
  "da-DK": {
    metadataTitle: "Ofte stillede spørgsmål om B4GAMBLE", metadataDescription: "Klare svar om B4GAMBLE.", eyebrow: "SPØRGSMÅL", titleLead: "Klare", titleEmphasis: "svar.", railPrompt: "Fandt du det ikke?", contactLink: "Kontakt os →", methodologyLink: "Metode", affiliateLink: "Affiliateoplysning",
    groups: [
      { title: "Om B4GAMBLE", items: [["Hvad er B4GAMBLE?", "Tre forbundne områder: et selvstyret kontrolprogram, uddannende og redaktionel casinoinformation og åbent kommercielle sider for voksne, der har valgt at sammenligne offentliggjorte oplysninger."], ["Hvem skriver anmeldelserne?", "Redaktionen vedligeholder anmeldelserne. Kommerciel tilgængelighed håndteres separat, og væsentlige kildebegrænsninger forbliver synlige."]] },
      { title: "Programmet", items: [["Er Programmet virkelig gratis?", "Det nuværende Program er gratis og har ingen betalingsmur eller kommercielt mersalg i Missionerne."], ["Hvem kan se, hvad jeg siger i Programmet?", "Din situation bruges kun til det Programresultat, du beder om. Program- og Hjælpedata er udelukket fra tilbud, rangeringer, annoncer og kommerciel personalisering; Privatlivssiden forklarer gemte data og rettighedsanmodninger."], ["Skal jeg have en konto for at begynde?", "Nej. Du taler eller skriver først om din situation; registrering med Google eller email kommer først, når dit Udgangspunkt er klar til at blive gemt."]] },
      { title: "Casinoer og tilbud", items: [["Hvordan vurderer I casinoer?", "B4GAMBLE anvender den offentliggjorte redaktionelle ramme på den tilgængelige evidens for hver udgivet post. Kildestatus, datoer, manglende felter og begrænsninger forbliver del af anmeldelsen."], ["Hvorfor står der »Kun anmeldelse« ved nogle casinoer?", "Der findes ingen styret tilmeldingsrute nu, så vi foregiver ikke en. Anmeldelsen og tilgængelig offentliggjort information forbliver synlige."], ["Hvad sker der ved Vis tilbud?", "En bekræftelse forklarer, at du forlader B4GAMBLE, og gentager provisionsoplysningen. Du kan fortsætte eller blive."]] },
      { title: "Kommerciel model", items: [["Hvordan tjener B4GAMBLE penge?", "B4GAMBLE kan modtage provision efter et styret kommercielt link. Kommercielle handlinger mærkes og forklares, før du forlader siden."], ["Påvirker provision rangeringer?", "Affiliatebetaling bestemmer ikke Editor Score eller naturlig redaktionel rangering. Se Affiliateoplysningen for produktgrænsen."]] },
      { title: "Hjælp og privatliv", items: [["Hvad er beskyttet Hjælp?", "Et kommercielt frit område med øjeblikkelig uafhængig støtte samt blokerings- og selvudelukkelsesmuligheder. Brug påvirker ikke tilbud, rangeringer eller kommerciel personalisering."], ["Hvordan anmoder jeg om mine data eller sletning?", "Kontakt den dataansvarlige via Privatlivssiden. Juridisk, svindelforebyggende og sikkerhedskopieret opbevaring kan fortsætte, hvor det gælder."]] },
    ],
  },
  "fi-FI": {
    metadataTitle: "B4GAMBLE – usein kysyttyä", metadataDescription: "Selkeät vastaukset B4GAMBLEsta.", eyebrow: "USEIN KYSYTTYÄ", titleLead: "Selkeät", titleEmphasis: "vastaukset.", railPrompt: "Etkö löytänyt?", contactLink: "Ota yhteyttä →", methodologyLink: "Menetelmä", affiliateLink: "Kumppanuusseloste",
    groups: [
      { title: "Tietoa B4GAMBLEsta", items: [["Mikä B4GAMBLE on?", "Kolme toisiinsa liittyvää aluetta: omaehtoinen hallintaohjelma, kasinoita koskeva opetus- ja toimituksellinen tieto sekä avoimesti kaupalliset sivut aikuisille, jotka haluavat vertailla julkaistuja tietoja."], ["Kuka kirjoittaa arviot?", "Toimitus ylläpitää arvioita. Kaupallinen saatavuus käsitellään erikseen ja olennaiset lähderajoitukset pidetään näkyvissä."]] },
      { title: "Ohjelma", items: [["Onko Ohjelma todella maksuton?", "Nykyinen Ohjelma on maksuton eikä Tehtävissä ole maksumuuria tai kaupallista lisämyyntiä."], ["Kuka voi nähdä, mitä sanon Ohjelmassa?", "Tilannettasi käytetään vain pyytämäsi Ohjelmatuloksen luomiseen. Ohjelma- ja Ohjetietoja ei käytetä tarjouksiin, sijoituksiin, mainoksiin tai kaupalliseen personointiin; Tietosuojasivu kertoo tallennuksesta ja oikeuspyynnöistä."], ["Tarvitsenko tilin aloittamiseen?", "Et. Puhut tai kirjoitat ensin tilanteestasi; rekisteröinti Googlella tai sähköpostilla tulee vasta, kun Lähtökohtasi on valmis tallennettavaksi."]] },
      { title: "Kasinot ja tarjoukset", items: [["Miten arvioitte kasinoita?", "B4GAMBLE soveltaa julkaistua toimituksellista kehystä kunkin julkaistun tietueen saatavilla olevaan näyttöön. Lähteen tila, päivämäärät, puuttuvat kentät ja rajoitukset pysyvät osana arviota."], ["Miksi joissakin kasinoissa lukee ”Vain arvio”?", "Hyväksyttyä rekisteröitymisreittiä ei ole nyt saatavilla, joten emme teeskentele sellaista. Arvio ja saatavilla oleva julkaistu tieto pysyvät näkyvissä."], ["Mitä tapahtuu, kun valitsen Näytä tarjous?", "Vahvistus kertoo, että poistut B4GAMBLEsta, ja toistaa palkkioselosteen. Voit jatkaa toimijalle tai jäädä."]] },
      { title: "Kaupallinen malli", items: [["Miten B4GAMBLE ansaitsee?", "B4GAMBLE voi saada palkkion hallitun kaupallisen linkin jälkeen. Kaupalliset toiminnot merkitään ja selitetään ennen sivustolta poistumista."], ["Vaikuttaako palkkio sijoituksiin?", "Kumppanikorvaus ei määrää Editor Scorea tai luonnollista toimituksellista järjestystä. Tuoteraja selitetään Kumppanuusselosteessa."]] },
      { title: "Ohje ja tietosuoja", items: [["Mikä on suojattu Ohje?", "Kaupallisuudesta vapaa alue, jossa on välitöntä riippumatonta tukea sekä esto- ja omaehtoisen poissulkemisen vaihtoehtoja. Käyttö ei vaikuta tarjouksiin, sijoituksiin tai kaupalliseen personointiin."], ["Miten pyydän tietoni tai poiston?", "Ota yhteys rekisterinpitäjään Tietosuojasivun kautta. Lakisääteinen, petoksia ehkäisevä ja varmuuskopioiden säilytys voi jatkua soveltuvin osin."]] },
    ],
  },
  "nb-NO": {
    metadataTitle: "Vanlige spørsmål om B4GAMBLE", metadataDescription: "Tydelige svar om B4GAMBLE.", eyebrow: "VANLIGE SPØRSMÅL", titleLead: "Tydelige", titleEmphasis: "svar.", railPrompt: "Fant du det ikke?", contactLink: "Kontakt oss →", methodologyLink: "Metode", affiliateLink: "Affiliateopplysning",
    groups: [
      { title: "Om B4GAMBLE", items: [["Hva er B4GAMBLE?", "Tre sammenknyttede områder: et selvstyrt kontrollprogram, lærerik og redaksjonell kasinoinformasjon og åpent kommersielle sider for voksne som har valgt å sammenligne publiserte opplysninger."], ["Hvem skriver anmeldelsene?", "Redaksjonen vedlikeholder anmeldelsene. Kommersiell tilgjengelighet behandles separat, og vesentlige kildebegrensninger forblir synlige."]] },
      { title: "Programmet", items: [["Er Programmet virkelig gratis?", "Det nåværende Programmet er gratis og har ingen betalingsmur eller kommersielt mersalg i Oppdragene."], ["Hvem kan se det jeg sier i Programmet?", "Situasjonen din brukes bare til Programresultatet du ber om. Program- og Hjelpedata er utelukket fra tilbud, rangeringer, annonser og kommersiell personalisering; Personvernsiden forklarer lagring og rettighetsforespørsler."], ["Trenger jeg en konto for å starte?", "Nei. Du snakker eller skriver først om situasjonen din; registrering med Google eller e-post kommer først når Utgangspunktet er klart til å lagres."]] },
      { title: "Kasinoer og tilbud", items: [["Hvordan vurderer dere kasinoer?", "B4GAMBLE bruker det offentliggjorte redaksjonelle rammeverket på tilgjengelig evidens for hver publiserte oppføring. Kildestatus, datoer, manglende felt og begrensninger forblir del av anmeldelsen."], ["Hvorfor står det «Kun anmeldelse» ved noen kasinoer?", "Det finnes ingen styrt registreringsrute nå, så vi later ikke som. Anmeldelsen og tilgjengelig publisert informasjon forblir synlige."], ["Hva skjer når jeg velger Vis tilbud?", "En bekreftelse forklarer at du forlater B4GAMBLE og gjentar provisjonsopplysningen. Du kan fortsette eller bli."]] },
      { title: "Kommersiell modell", items: [["Hvordan tjener B4GAMBLE penger?", "B4GAMBLE kan motta provisjon etter en styrt kommersiell lenke. Kommersielle handlinger merkes og forklares før du forlater nettstedet."], ["Påvirker provisjon rangeringer?", "Affiliatebetaling bestemmer ikke Editor Score eller naturlig redaksjonell rangering. Se Affiliateopplysningen for produktgrensen."]] },
      { title: "Hjelp og personvern", items: [["Hva er beskyttet Hjelp?", "Et kommersielt fritt område med umiddelbar uavhengig støtte samt blokkerings- og selvutestengingsalternativer. Bruk påvirker ikke tilbud, rangeringer eller kommersiell personalisering."], ["Hvordan ber jeg om dataene mine eller sletting?", "Kontakt behandlingsansvarlig via Personvernsiden. Juridisk, svindelforebyggende og sikkerhetskopiert lagring kan fortsette der det gjelder."]] },
    ],
  },
  "en-CA": en,
  "fr-CA": en,
};

export function faqMessages(locale: SupportedLocale) {
  return catalog[locale];
}
