import type { SupportedLocale } from "@/lib/market/registry";

type EuropeanLocale = Exclude<SupportedLocale, "en-CA" | "fr-CA" | "es-PE">;

export const METHODOLOGY_SOURCE_COPY = [
  "Methodology",
  "Evidence before",
  "opinion.",
  "Every published score should be read with its dated source status and limitations. This page explains the evaluation framework and what current records can — and cannot — establish.",
  "01 · How we evaluate casinos",
  "One framework. Evidence disclosed.",
  "Published reviews use the evidence available for that operator and disclose important limitations. The public record, material terms, payment information and support evidence are assessed consistently; a review is not a guarantee of future operator behaviour.",
  "Where test or source records exist, dated findings and material limitations should be traceable to them. Record retention follows the applicable operational and legal schedule rather than an unqualified public promise.",
  "Source and test status",
  "A review identifies whether a finding comes from a public source, operator material or a dated test record. Missing evidence is not inferred and current jurisdiction eligibility must be checked separately.",
  "Payments and withdrawals",
  "Published payout information identifies its source and date where available. Times can vary by method, amount, verification, account history and jurisdiction; unavailable evidence remains unavailable.",
  "Terms read line by line",
  "Material terms include the wagering base, game weighting, maximum stake, win caps, expiry and exclusions. Current operator terms remain authoritative and must be checked before acting.",
  "Support and game information",
  "Support information and game data are compared with published rules where evidence is available. Availability, RTP variants and service levels can change and are not inferred from missing records.",
  "02 · What affects the score",
  "Judgement, informed by evidence.",
  "The Editor Score is editorial judgement grounded in available evidence — not the output of a fixed arithmetic formula, and no percentage weighting should be inferred from it. The ordering of influence, however, is stable and public: payout reliability weighs heaviest, honesty of terms second, everything else after.",
  "Some substantiated findings can cap an assessment rather than add weight, including unresolved non-payment evidence, material withdrawal failure or marketing that misrepresents operator terms.",
  "Payout speed & reliability",
  "weighs heaviest",
  "Honesty of bonus terms",
  "heavy",
  "Game library & live floor",
  "moderate",
  "Support quality",
  "Verification friction",
  "Commission we might earn",
  "never a factor",
  "03 · How Best Offers are selected",
  "When eligible published records exist, the #1 pick reflects the strongest current combination under the disclosed ranking method. Missing or incomplete evidence fails closed, and the selection can change when authoritative data changes.",
  "Alternatives are chosen to answer materially different needs — lower wagering, lower deposit floor — not to enumerate rank positions or pad the page. Use-case shortlists on Casinos and Bonuses follow the same rule, capped at three operators each. Affiliate compensation does not determine Editor Score or natural editorial ranking.",
  "04 · Editorial vs commercial",
  "Editorial scoring and commercial availability are separate application concerns. Affiliate compensation does not determine Editor Score or natural editorial ranking.",
  "Programme and Help activity is not used to target offers, personalise rankings or feed advertising. Current product controls keep those purposes separate.",
  "05 · Sources, freshness, corrections",
  "A review is only as useful as its source status and date. Published records show evidence dates where available, and credible corrections are assessed against authoritative sources.",
  "Evidence dates and limitations shown where the published record supports them.",
  "Material term changes should be reviewed and the affected text dated when corrected.",
  "Verified corrections are reviewed and dated when published. Spotted an error?",
  "Tell us",
  "— reports are logged, triaged and answered.",
  "Source and test records follow the applicable operational and legal retention schedule.",
  "06 · Limitations — read this part",
  "An honest methodology admits what it can't do. Findings reflect the disclosed sources or dated observations available for a particular jurisdiction and context — snapshots, not guarantees.",
  "An operator can change behaviour after we publish; your outcome may differ from ours.",
  "Payout times vary by method, jurisdiction, amount and account history.",
  "RTP spot checks compare published sheets; we cannot verify RTP empirically through play.",
  "We can't test every casino in every country. Absence of a review is not a verdict, and presence of one is not a claim of availability in your jurisdiction.",
] as const;

const enGB = [...METHODOLOGY_SOURCE_COPY];

const de = [
  "Methodik", "Belege vor", "Meinung.",
  "Jede veröffentlichte Bewertung ist zusammen mit dem Datum, Quellenstatus und den Einschränkungen zu lesen. Diese Seite erklärt den Bewertungsrahmen und was aktuelle Unterlagen belegen können — und was nicht.",
  "01 · So bewerten wir Glücksspielanbieter", "Ein Rahmen. Belege offengelegt.",
  "Veröffentlichte Bewertungen nutzen die für den Anbieter verfügbaren Belege und nennen wichtige Einschränkungen. Öffentliche Unterlagen, wesentliche Bedingungen, Zahlungsinformationen und Supportbelege werden einheitlich bewertet; eine Bewertung garantiert kein künftiges Verhalten des Anbieters.",
  "Wenn Test- oder Quellenunterlagen bestehen, sollen datierte Erkenntnisse und wesentliche Einschränkungen darauf zurückführbar sein. Die Aufbewahrung folgt den geltenden betrieblichen und rechtlichen Fristen statt einem uneingeschränkten öffentlichen Versprechen.",
  "Quellen- und Teststatus", "Eine Bewertung kennzeichnet, ob eine Feststellung aus einer öffentlichen Quelle, Anbietermaterial oder einem datierten Test stammt. Fehlende Belege werden nicht ergänzt; die aktuelle Zulässigkeit im jeweiligen Land ist separat zu prüfen.",
  "Zahlungen und Auszahlungen", "Veröffentlichte Auszahlungsangaben nennen, soweit verfügbar, Quelle und Datum. Zeiten können je nach Methode, Betrag, Verifizierung, Kontoverlauf und Land variieren; nicht verfügbare Belege bleiben als solche gekennzeichnet.",
  "Bedingungen Zeile für Zeile", "Wesentliche Bedingungen umfassen Einsatzbasis, Spielgewichtung, Höchsteinsatz, Gewinnlimits, Ablauf und Ausschlüsse. Die aktuellen Bedingungen des Anbieters sind maßgeblich und vor einer Entscheidung zu prüfen.",
  "Support- und Spielinformationen", "Support- und Spieldaten werden, soweit Belege vorliegen, mit veröffentlichten Regeln verglichen. Verfügbarkeit, RTP-Varianten und Serviceniveaus können sich ändern und werden bei fehlenden Unterlagen nicht angenommen.",
  "02 · Was die Bewertung beeinflusst", "Urteil auf Basis von Belegen.",
  "Der Editor Score ist ein redaktionelles Urteil auf Grundlage verfügbarer Belege — kein Ergebnis einer festen Rechenformel; prozentuale Gewichtungen dürfen nicht abgeleitet werden. Die Einflussreihenfolge ist jedoch stabil und öffentlich: Auszahlungszuverlässigkeit zählt am stärksten, ehrliche Bedingungen an zweiter Stelle, alles Weitere danach.",
  "Einige belegte Feststellungen können eine Bewertung deckeln statt Gewicht hinzuzufügen, darunter ungelöste Nichtzahlung, wesentliche Auszahlungsfehler oder Marketing, das Anbieterbedingungen falsch darstellt.",
  "Tempo und Zuverlässigkeit der Auszahlung", "höchstes Gewicht", "Ehrlichkeit der Bonusbedingungen", "hoch", "Spielauswahl und Live-Spiele", "mittel", "Supportqualität", "Verifizierungsaufwand", "Mögliche Provision", "nie ein Faktor",
  "03 · So werden die besten Angebote gewählt", "Wenn geeignete veröffentlichte Datensätze vorliegen, zeigt Platz 1 die aktuell stärkste Kombination nach der offengelegten Rankingmethode. Fehlende oder unvollständige Belege führen zum geschlossenen Zustand; die Auswahl kann sich mit maßgeblichen Daten ändern.",
  "Alternativen beantworten wesentlich andere Bedürfnisse — geringere Umsatzanforderung oder Mindesteinzahlung — und dienen nicht dazu, Ränge aufzuzählen oder Seiten zu füllen. Kurzlisten nach Anwendungsfall für Glücksspielanbieter und Boni folgen derselben Regel und sind auf drei Anbieter begrenzt. Affiliate-Vergütung bestimmt weder den Editor Score noch die natürliche redaktionelle Rangfolge.",
  "04 · Redaktion und Kommerz", "Redaktionelle Bewertung und kommerzielle Verfügbarkeit sind getrennte Anwendungsbereiche. Affiliate-Vergütung bestimmt weder den Editor Score noch die natürliche redaktionelle Rangfolge.",
  "Aktivitäten in Programm und Hilfe werden nicht für Angebote, personalisierte Rankings oder Werbung verwendet. Aktuelle Produktkontrollen trennen diese Zwecke.",
  "05 · Quellen, Aktualität, Korrekturen", "Eine Bewertung ist nur so nützlich wie Quellenstatus und Datum. Veröffentlichte Datensätze zeigen Belegdaten, soweit vorhanden; glaubhafte Korrekturen werden anhand maßgeblicher Quellen geprüft.",
  "Belegdaten und Einschränkungen werden gezeigt, soweit der veröffentlichte Datensatz sie stützt.", "Wesentliche Änderungen der Bedingungen sollen geprüft und der betroffene Text bei Korrektur datiert werden.", "Verifizierte Korrekturen werden bei Veröffentlichung geprüft und datiert. Fehler entdeckt?", "Sag uns Bescheid", "— Meldungen werden erfasst, eingeordnet und beantwortet.", "Quellen- und Testunterlagen folgen den geltenden betrieblichen und rechtlichen Aufbewahrungsfristen.",
  "06 · Einschränkungen — bitte lesen", "Eine ehrliche Methodik benennt ihre Grenzen. Feststellungen spiegeln die offengelegten Quellen oder datierten Beobachtungen für ein bestimmtes Land und einen bestimmten Kontext wider — Momentaufnahmen, keine Garantien.",
  "Ein Anbieter kann sein Verhalten nach Veröffentlichung ändern; dein Ergebnis kann abweichen.", "Auszahlungszeiten variieren nach Methode, Land, Betrag und Kontoverlauf.", "RTP-Stichproben vergleichen veröffentlichte Angaben; wir können RTP nicht empirisch durch Spielen prüfen.", "Wir können nicht jeden Glücksspielanbieter in jedem Land testen. Das Fehlen einer Bewertung ist kein Urteil; ihr Vorhandensein behauptet keine Verfügbarkeit in deinem Land.",
];

const it = [
  "Metodologia", "Le prove prima delle", "opinioni.", "Ogni punteggio pubblicato va letto insieme allo stato datato delle fonti e ai relativi limiti. Questa pagina spiega il quadro di valutazione e ciò che i dati attuali possono — e non possono — dimostrare.",
  "01 · Come valutiamo i casinò", "Un solo quadro. Prove dichiarate.", "Le recensioni pubblicate usano le prove disponibili per l'operatore e dichiarano i limiti importanti. Registri pubblici, condizioni rilevanti, informazioni sui pagamenti e prove sull'assistenza sono valutati in modo coerente; una recensione non garantisce il comportamento futuro dell'operatore.", "Quando esistono registri di test o fonti, i risultati datati e i limiti rilevanti dovrebbero essere riconducibili a essi. La conservazione segue i termini operativi e legali applicabili, non una promessa pubblica illimitata.",
  "Stato di fonti e test", "La recensione indica se un risultato deriva da una fonte pubblica, da materiale dell'operatore o da un test datato. Le prove mancanti non vengono dedotte e l'idoneità attuale nella giurisdizione va verificata separatamente.", "Pagamenti e prelievi", "Le informazioni pubblicate sui prelievi indicano fonte e data quando disponibili. I tempi variano per metodo, importo, verifica, storico del conto e giurisdizione; le prove non disponibili restano tali.", "Condizioni lette riga per riga", "Le condizioni rilevanti comprendono base di puntata, ponderazione dei giochi, puntata massima, limiti alle vincite, scadenza ed esclusioni. Fanno fede le condizioni attuali dell'operatore, da verificare prima di agire.", "Assistenza e informazioni sui giochi", "Le informazioni sull'assistenza e sui giochi vengono confrontate con le regole pubblicate quando esistono prove. Disponibilità, varianti RTP e livelli di servizio possono cambiare e non vengono dedotti da dati mancanti.",
  "02 · Cosa influenza il punteggio", "Giudizio basato sulle prove.", "L'Editor Score è un giudizio editoriale fondato sulle prove disponibili — non il risultato di una formula aritmetica fissa; non va dedotta alcuna ponderazione percentuale. L'ordine d'influenza è però stabile e pubblico: l'affidabilità dei prelievi pesa di più, l'onestà delle condizioni viene subito dopo, quindi tutto il resto.", "Alcuni risultati comprovati possono limitare una valutazione invece di aggiungere peso, tra cui mancati pagamenti irrisolti, gravi problemi di prelievo o marketing che travisa le condizioni dell'operatore.",
  "Velocità e affidabilità dei prelievi", "peso massimo", "Onestà delle condizioni bonus", "alto", "Catalogo giochi e live", "medio", "Qualità dell'assistenza", "Attrito nella verifica", "Commissione che potremmo ricevere", "mai un fattore",
  "03 · Come vengono selezionate le migliori offerte", "Quando esistono dati pubblicati idonei, la prima scelta riflette la combinazione attuale più solida secondo il metodo dichiarato. Prove mancanti o incomplete chiudono il risultato e la scelta può cambiare con i dati autorevoli.", "Le alternative rispondono a esigenze davvero diverse — requisiti di puntata o deposito minimo inferiori — e non servono a elencare posizioni o riempire la pagina. Le selezioni per caso d'uso in Casinò e Bonus seguono la stessa regola, con massimo tre operatori. Il compenso di affiliazione non determina l'Editor Score né l'ordine editoriale naturale.",
  "04 · Editoriale e commerciale", "Valutazione editoriale e disponibilità commerciale sono ambiti separati dell'applicazione. Il compenso di affiliazione non determina l'Editor Score né l'ordine editoriale naturale.", "Le attività nel Programma e nell'Aiuto non vengono usate per proporre offerte, personalizzare classifiche o alimentare pubblicità. I controlli attuali separano queste finalità.",
  "05 · Fonti, aggiornamento, correzioni", "Una recensione è utile quanto lo stato e la data delle sue fonti. I dati pubblicati mostrano le date delle prove quando disponibili; le correzioni credibili vengono valutate su fonti autorevoli.", "Date e limiti delle prove sono mostrati quando il dato pubblicato li supporta.", "Le modifiche rilevanti alle condizioni dovrebbero essere riesaminate e il testo interessato datato quando corretto.", "Le correzioni verificate vengono controllate e datate alla pubblicazione. Hai notato un errore?", "Segnalacelo", "— le segnalazioni vengono registrate e valutate, quindi ricevono risposta.", "I registri di fonti e test seguono i termini di conservazione operativi e legali applicabili.",
  "06 · Limiti — leggi questa parte", "Una metodologia onesta ammette ciò che non può fare. I risultati riflettono le fonti dichiarate o osservazioni datate in una specifica giurisdizione e contesto — istantanee, non garanzie.", "Un operatore può cambiare comportamento dopo la pubblicazione; il tuo risultato può essere diverso.", "I tempi di prelievo variano per metodo, giurisdizione, importo e storico del conto.", "I controlli RTP confrontano schede pubblicate; non possiamo verificare empiricamente l'RTP giocando.", "Non possiamo testare ogni casinò in ogni Paese. L'assenza di una recensione non è un giudizio e la sua presenza non dichiara disponibilità nella tua giurisdizione.",
];

const es = [
  "Metodología", "Pruebas antes que", "opiniones.", "Cada puntuación publicada debe leerse junto con el estado fechado de sus fuentes y sus limitaciones. Esta página explica el marco de evaluación y lo que los registros actuales pueden —y no pueden— demostrar.",
  "01 · Cómo evaluamos los casinos", "Un marco. Pruebas declaradas.", "Las reseñas publicadas usan las pruebas disponibles del operador y declaran las limitaciones importantes. El registro público, las condiciones relevantes, la información de pagos y las pruebas de atención se evalúan de forma coherente; una reseña no garantiza la conducta futura del operador.", "Cuando existen registros de pruebas o fuentes, los hallazgos fechados y las limitaciones relevantes deben poder rastrearse hasta ellos. La conservación sigue el calendario operativo y legal aplicable, no una promesa pública ilimitada.",
  "Estado de fuentes y pruebas", "La reseña indica si un hallazgo procede de una fuente pública, material del operador o una prueba fechada. No se deducen pruebas ausentes y la elegibilidad actual en la jurisdicción debe comprobarse por separado.", "Pagos y retiradas", "La información publicada sobre retiradas identifica fuente y fecha cuando están disponibles. Los plazos varían según método, importe, verificación, historial y jurisdicción; las pruebas no disponibles siguen sin estar disponibles.", "Condiciones, línea por línea", "Las condiciones relevantes incluyen la base de apuesta, ponderación de juegos, apuesta máxima, límites de ganancias, caducidad y exclusiones. Las condiciones actuales del operador son la autoridad y deben revisarse antes de actuar.", "Atención e información de juegos", "La información de atención y juegos se compara con reglas publicadas cuando hay pruebas. La disponibilidad, las variantes de RTP y el nivel de servicio pueden cambiar y no se deducen de registros ausentes.",
  "02 · Qué afecta a la puntuación", "Criterio informado por pruebas.", "El Editor Score es un criterio editorial basado en las pruebas disponibles —no el resultado de una fórmula aritmética fija— y no debe deducirse ninguna ponderación porcentual. El orden de influencia sí es estable y público: la fiabilidad de las retiradas pesa más, la honestidad de las condiciones va después y luego todo lo demás.", "Algunos hallazgos demostrados pueden limitar una evaluación en vez de añadir peso, como impagos sin resolver, fallos relevantes de retirada o marketing que tergiversa las condiciones del operador.",
  "Rapidez y fiabilidad de retiradas", "peso máximo", "Honestidad de las condiciones del bono", "alto", "Catálogo de juegos y casino en vivo", "medio", "Calidad de la atención", "Fricción de verificación", "Comisión que podríamos recibir", "nunca influye",
  "03 · Cómo se eligen las mejores ofertas", "Cuando existen registros publicados aptos, la primera opción refleja la combinación actual más sólida según el método de clasificación declarado. Si faltan pruebas o están incompletas, se cierra el resultado; la selección puede cambiar con los datos autorizados.", "Las alternativas responden a necesidades realmente distintas —menor requisito de apuesta o depósito mínimo— y no sirven para enumerar puestos ni rellenar la página. Las listas por caso de uso en Casinos y Bonos siguen la misma regla, con un máximo de tres operadores. La compensación de afiliación no determina el Editor Score ni la clasificación editorial natural.",
  "04 · Editorial y comercial", "La puntuación editorial y la disponibilidad comercial son ámbitos separados de la aplicación. La compensación de afiliación no determina el Editor Score ni la clasificación editorial natural.", "La actividad del Programa y de Ayuda no se usa para orientar ofertas, personalizar clasificaciones ni alimentar publicidad. Los controles actuales mantienen separadas esas finalidades.",
  "05 · Fuentes, vigencia y correcciones", "Una reseña solo es tan útil como el estado y la fecha de sus fuentes. Los registros publicados muestran fechas de las pruebas cuando están disponibles; las correcciones creíbles se contrastan con fuentes autorizadas.", "Se muestran fechas y limitaciones cuando el registro publicado las respalda.", "Los cambios relevantes de condiciones deben revisarse y el texto afectado debe fecharse al corregirse.", "Las correcciones verificadas se revisan y fechan al publicarse. ¿Has visto un error?", "Cuéntanoslo", "— los informes se registran, priorizan y responden.", "Los registros de fuentes y pruebas siguen el calendario de conservación operativo y legal aplicable.",
  "06 · Limitaciones — lee esta parte", "Una metodología honesta reconoce lo que no puede hacer. Los hallazgos reflejan las fuentes declaradas u observaciones fechadas disponibles para una jurisdicción y contexto concretos — instantáneas, no garantías.", "Un operador puede cambiar su conducta tras la publicación; tu resultado puede ser distinto.", "Los plazos de retirada varían según método, jurisdicción, importe e historial de la cuenta.", "Las comprobaciones de RTP comparan fichas publicadas; no podemos verificar empíricamente el RTP jugando.", "No podemos probar todos los casinos en todos los países. La ausencia de reseña no es un veredicto y su presencia no afirma disponibilidad en tu jurisdicción.",
];

const pt = [
  "Metodologia", "Provas antes da", "opinião.", "Cada pontuação publicada deve ser lida com o estado datado das fontes e as limitações. Esta página explica o quadro de avaliação e o que os registos atuais podem — e não podem — demonstrar.",
  "01 · Como avaliamos casinos", "Um quadro. Provas divulgadas.", "As análises publicadas usam as provas disponíveis para o operador e divulgam limitações importantes. O registo público, os termos relevantes, a informação de pagamentos e as provas de apoio são avaliados de forma consistente; uma análise não garante o comportamento futuro do operador.", "Quando existem registos de testes ou fontes, as conclusões datadas e limitações relevantes devem ser rastreáveis. A retenção segue o calendário operacional e legal aplicável, não uma promessa pública sem limites.",
  "Estado das fontes e testes", "Uma análise identifica se uma conclusão vem de fonte pública, material do operador ou teste datado. Não inferimos provas em falta e a elegibilidade atual na jurisdição deve ser verificada separadamente.", "Pagamentos e levantamentos", "A informação publicada sobre levantamentos identifica fonte e data quando disponíveis. Os prazos variam por método, montante, verificação, histórico da conta e jurisdição; provas indisponíveis continuam indisponíveis.", "Termos lidos linha a linha", "Os termos relevantes incluem base de apostas, ponderação dos jogos, aposta máxima, limites de ganhos, validade e exclusões. Os termos atuais do operador são determinantes e devem ser verificados antes de agir.", "Apoio e informação de jogos", "A informação de apoio e jogos é comparada com regras publicadas quando há provas. Disponibilidade, variantes de RTP e níveis de serviço podem mudar e não são inferidos de registos em falta.",
  "02 · O que afeta a pontuação", "Julgamento informado por provas.", "O Editor Score é um julgamento editorial baseado nas provas disponíveis — não resulta de uma fórmula aritmética fixa e não deve ser inferida qualquer ponderação percentual. A ordem de influência é estável e pública: a fiabilidade dos levantamentos pesa mais, a honestidade dos termos vem depois e tudo o resto a seguir.", "Algumas conclusões fundamentadas podem limitar uma avaliação em vez de somar peso, incluindo falta de pagamento não resolvida, falha relevante de levantamento ou marketing que deturpa os termos do operador.",
  "Rapidez e fiabilidade dos levantamentos", "maior peso", "Honestidade dos termos de bónus", "alto", "Biblioteca de jogos e casino ao vivo", "moderado", "Qualidade do apoio", "Dificuldade da verificação", "Comissão que podemos receber", "nunca influencia",
  "03 · Como são escolhidas as melhores ofertas", "Quando existem registos publicados elegíveis, a primeira escolha reflete a combinação atual mais forte segundo o método de classificação divulgado. Provas em falta ou incompletas fecham o resultado e a seleção pode mudar com dados autorizados.", "As alternativas respondem a necessidades realmente diferentes — menor requisito de apostas ou depósito mínimo — e não servem para enumerar posições nem preencher a página. As listas por utilização em Casinos e Bónus seguem a mesma regra, limitadas a três operadores. A remuneração de afiliado não determina o Editor Score nem a classificação editorial natural.",
  "04 · Editorial e comercial", "A pontuação editorial e a disponibilidade comercial são áreas separadas da aplicação. A remuneração de afiliado não determina o Editor Score nem a classificação editorial natural.", "A atividade no Programa e na Ajuda não é usada para orientar ofertas, personalizar classificações ou alimentar publicidade. Os controlos atuais mantêm estas finalidades separadas.",
  "05 · Fontes, atualidade, correções", "Uma análise é tão útil quanto o estado e a data das fontes. Os registos publicados mostram datas das provas quando disponíveis; correções credíveis são avaliadas com fontes autorizadas.", "As datas e limitações são mostradas quando o registo publicado as suporta.", "Alterações relevantes aos termos devem ser revistas e o texto afetado deve ser datado quando corrigido.", "As correções verificadas são revistas e datadas quando publicadas. Encontraste um erro?", "Diz-nos", "— as comunicações são registadas, triadas e respondidas.", "Os registos de fontes e testes seguem o calendário de retenção operacional e legal aplicável.",
  "06 · Limitações — lê esta parte", "Uma metodologia honesta admite o que não consegue fazer. As conclusões refletem as fontes divulgadas ou observações datadas disponíveis para uma jurisdição e contexto — instantâneos, não garantias.", "Um operador pode mudar de comportamento após a publicação; o teu resultado pode ser diferente.", "Os prazos de levantamento variam por método, jurisdição, montante e histórico da conta.", "As verificações de RTP comparam fichas publicadas; não podemos verificar empiricamente o RTP através do jogo.", "Não podemos testar todos os casinos em todos os países. A ausência de análise não é um veredicto e a sua presença não afirma disponibilidade na tua jurisdição.",
];

const el = [
  "Μεθοδολογία", "Πρώτα τα στοιχεία, μετά η", "άποψη.", "Κάθε δημοσιευμένη βαθμολογία πρέπει να διαβάζεται μαζί με τη χρονολογημένη κατάσταση πηγών και τους περιορισμούς της. Η σελίδα εξηγεί το πλαίσιο αξιολόγησης και τι μπορούν — και τι δεν μπορούν — να τεκμηριώσουν τα τρέχοντα αρχεία.",
  "01 · Πώς αξιολογούμε τα καζίνο", "Ένα πλαίσιο. Τα στοιχεία γνωστοποιούνται.", "Οι δημοσιευμένες αξιολογήσεις χρησιμοποιούν τα διαθέσιμα στοιχεία για τον πάροχο και γνωστοποιούν σημαντικούς περιορισμούς. Δημόσια αρχεία, ουσιώδεις όροι, πληροφορίες πληρωμών και στοιχεία υποστήριξης αξιολογούνται με συνέπεια· μια αξιολόγηση δεν εγγυάται τη μελλοντική συμπεριφορά του παρόχου.", "Όπου υπάρχουν αρχεία δοκιμών ή πηγών, τα χρονολογημένα ευρήματα και οι ουσιώδεις περιορισμοί πρέπει να είναι ανιχνεύσιμα σε αυτά. Η διατήρηση ακολουθεί το ισχύον λειτουργικό και νομικό χρονοδιάγραμμα, όχι μια απεριόριστη δημόσια υπόσχεση.",
  "Κατάσταση πηγών και δοκιμών", "Η αξιολόγηση προσδιορίζει αν ένα εύρημα προέρχεται από δημόσια πηγή, υλικό παρόχου ή χρονολογημένη δοκιμή. Δεν συνάγουμε στοιχεία που λείπουν και η τρέχουσα επιλεξιμότητα στη δικαιοδοσία πρέπει να ελέγχεται χωριστά.", "Πληρωμές και αναλήψεις", "Οι δημοσιευμένες πληροφορίες ανάληψης αναφέρουν πηγή και ημερομηνία όπου υπάρχουν. Οι χρόνοι διαφέρουν ανά μέθοδο, ποσό, επαλήθευση, ιστορικό λογαριασμού και δικαιοδοσία· τα μη διαθέσιμα στοιχεία παραμένουν μη διαθέσιμα.", "Ανάγνωση όρων γραμμή προς γραμμή", "Οι ουσιώδεις όροι περιλαμβάνουν βάση τζίρου, στάθμιση παιχνιδιών, μέγιστο ποντάρισμα, όρια κερδών, λήξη και εξαιρέσεις. Οι τρέχοντες όροι του παρόχου υπερισχύουν και πρέπει να ελέγχονται πριν από ενέργεια.", "Υποστήριξη και πληροφορίες παιχνιδιών", "Οι πληροφορίες υποστήριξης και παιχνιδιών συγκρίνονται με δημοσιευμένους κανόνες όπου υπάρχουν στοιχεία. Η διαθεσιμότητα, οι παραλλαγές RTP και τα επίπεδα υπηρεσίας μπορούν να αλλάξουν και δεν συνάγονται από αρχεία που λείπουν.",
  "02 · Τι επηρεάζει τη βαθμολογία", "Κρίση βασισμένη σε στοιχεία.", "Το Editor Score είναι συντακτική κρίση βασισμένη στα διαθέσιμα στοιχεία — όχι αποτέλεσμα σταθερού αριθμητικού τύπου, και δεν πρέπει να συνάγεται ποσοστιαία στάθμιση. Η σειρά επιρροής είναι σταθερή και δημόσια: η αξιοπιστία αναλήψεων έχει το μεγαλύτερο βάρος, η ειλικρίνεια των όρων ακολουθεί και μετά όλα τα άλλα.", "Ορισμένα τεκμηριωμένα ευρήματα μπορούν να περιορίσουν την αξιολόγηση αντί να προσθέσουν βάρος, όπως ανεπίλυτη μη πληρωμή, ουσιώδης αποτυχία ανάληψης ή μάρκετινγκ που παραποιεί τους όρους του παρόχου.",
  "Ταχύτητα και αξιοπιστία αναλήψεων", "μέγιστο βάρος", "Ειλικρίνεια όρων μπόνους", "υψηλό", "Βιβλιοθήκη παιχνιδιών και live casino", "μέτριο", "Ποιότητα υποστήριξης", "Δυσκολία επαλήθευσης", "Προμήθεια που ίσως λάβουμε", "ποτέ δεν επηρεάζει",
  "03 · Πώς επιλέγονται οι καλύτερες προσφορές", "Όταν υπάρχουν κατάλληλα δημοσιευμένα αρχεία, η πρώτη επιλογή αντανακλά τον ισχυρότερο τρέχοντα συνδυασμό βάσει της γνωστοποιημένης μεθόδου κατάταξης. Ελλιπή ή απόντα στοιχεία κλείνουν το αποτέλεσμα και η επιλογή μπορεί να αλλάξει με τα έγκυρα δεδομένα.", "Οι εναλλακτικές καλύπτουν ουσιωδώς διαφορετικές ανάγκες — χαμηλότερη απαίτηση τζίρου ή ελάχιστη κατάθεση — και δεν απαριθμούν θέσεις ούτε γεμίζουν τη σελίδα. Οι λίστες χρήσης σε Καζίνο και Μπόνους ακολουθούν τον ίδιο κανόνα, έως τρεις παρόχους. Η αμοιβή συνεργατών δεν καθορίζει το Editor Score ούτε τη φυσική συντακτική κατάταξη.",
  "04 · Συντακτικό και εμπορικό", "Η συντακτική βαθμολόγηση και η εμπορική διαθεσιμότητα είναι χωριστές λειτουργίες. Η αμοιβή συνεργατών δεν καθορίζει το Editor Score ούτε τη φυσική συντακτική κατάταξη.", "Η δραστηριότητα στο Πρόγραμμα και τη Βοήθεια δεν χρησιμοποιείται για στόχευση προσφορών, εξατομίκευση κατάταξης ή διαφήμιση. Οι τρέχοντες έλεγχοι διαχωρίζουν αυτούς τους σκοπούς.",
  "05 · Πηγές, επικαιρότητα, διορθώσεις", "Μια αξιολόγηση είναι τόσο χρήσιμη όσο η κατάσταση και η ημερομηνία των πηγών της. Τα δημοσιευμένα αρχεία δείχνουν ημερομηνίες στοιχείων όπου υπάρχουν· αξιόπιστες διορθώσεις εξετάζονται με έγκυρες πηγές.", "Οι ημερομηνίες και οι περιορισμοί εμφανίζονται όπου υποστηρίζονται από το δημοσιευμένο αρχείο.", "Οι ουσιώδεις αλλαγές όρων πρέπει να επανεξετάζονται και το σχετικό κείμενο να χρονολογείται όταν διορθώνεται.", "Οι επαληθευμένες διορθώσεις εξετάζονται και χρονολογούνται όταν δημοσιεύονται. Εντόπισες λάθος;", "Ενημέρωσέ μας", "— οι αναφορές καταγράφονται, αξιολογούνται και απαντώνται.", "Τα αρχεία πηγών και δοκιμών ακολουθούν το ισχύον λειτουργικό και νομικό χρονοδιάγραμμα διατήρησης.",
  "06 · Περιορισμοί — διάβασέ το", "Μια έντιμη μεθοδολογία παραδέχεται τι δεν μπορεί να κάνει. Τα ευρήματα αντανακλούν τις γνωστοποιημένες πηγές ή χρονολογημένες παρατηρήσεις για συγκεκριμένη δικαιοδοσία και πλαίσιο — στιγμιότυπα, όχι εγγυήσεις.", "Ένας πάροχος μπορεί να αλλάξει συμπεριφορά μετά τη δημοσίευση· το αποτέλεσμά σου μπορεί να διαφέρει.", "Οι χρόνοι ανάληψης διαφέρουν ανά μέθοδο, δικαιοδοσία, ποσό και ιστορικό λογαριασμού.", "Οι δειγματοληπτικοί έλεγχοι RTP συγκρίνουν δημοσιευμένα φύλλα· δεν μπορούμε να επαληθεύσουμε εμπειρικά το RTP παίζοντας.", "Δεν μπορούμε να δοκιμάσουμε κάθε καζίνο σε κάθε χώρα. Η απουσία αξιολόγησης δεν είναι ετυμηγορία και η παρουσία της δεν δηλώνει διαθεσιμότητα στη δικαιοδοσία σου.",
];

const nl = [
  "Methodologie", "Bewijs vóór", "mening.", "Lees elke gepubliceerde score samen met de gedateerde bronstatus en beperkingen. Deze pagina legt het beoordelingskader uit en wat de huidige gegevens wel — en niet — kunnen aantonen.",
  "01 · Zo beoordelen we casino's", "Eén kader. Bewijs bekendgemaakt.", "Gepubliceerde reviews gebruiken het beschikbare bewijs voor de aanbieder en vermelden belangrijke beperkingen. Openbare gegevens, wezenlijke voorwaarden, betaalinformatie en bewijs over ondersteuning worden consistent beoordeeld; een review garandeert geen toekomstig gedrag van de aanbieder.", "Waar test- of brongegevens bestaan, moeten gedateerde bevindingen en wezenlijke beperkingen ernaar te herleiden zijn. Bewaring volgt de toepasselijke operationele en wettelijke termijnen, niet een onbeperkte openbare belofte.",
  "Bron- en teststatus", "Een review vermeldt of een bevinding uit een openbare bron, materiaal van de aanbieder of een gedateerde test komt. Ontbrekend bewijs wordt niet ingevuld en actuele toelating in het rechtsgebied moet apart worden gecontroleerd.", "Betalingen en opnames", "Gepubliceerde opname-informatie vermeldt bron en datum indien beschikbaar. Tijden variëren per methode, bedrag, verificatie, accountgeschiedenis en rechtsgebied; niet-beschikbaar bewijs blijft niet beschikbaar.", "Voorwaarden regel voor regel", "Wezenlijke voorwaarden omvatten inzetbasis, spelweging, maximale inzet, winstlimieten, verloopdatum en uitsluitingen. De actuele voorwaarden van de aanbieder zijn leidend en moeten vooraf worden gecontroleerd.", "Ondersteuning en spelinformatie", "Informatie over ondersteuning en spellen wordt waar bewijs bestaat vergeleken met gepubliceerde regels. Beschikbaarheid, RTP-varianten en serviceniveaus kunnen wijzigen en worden niet afgeleid uit ontbrekende gegevens.",
  "02 · Wat de score beïnvloedt", "Oordeel op basis van bewijs.", "De Editor Score is een redactioneel oordeel op basis van beschikbaar bewijs — geen uitkomst van een vaste rekenformule; er mag geen procentuele weging uit worden afgeleid. De volgorde van invloed is wel stabiel en openbaar: betrouwbaarheid van opnames weegt het zwaarst, eerlijkheid van voorwaarden daarna en vervolgens al het overige.", "Sommige onderbouwde bevindingen kunnen een beoordeling begrenzen in plaats van gewicht toevoegen, waaronder onopgeloste niet-betaling, wezenlijke opnameproblemen of marketing die voorwaarden verkeerd voorstelt.",
  "Snelheid en betrouwbaarheid van opnames", "weegt het zwaarst", "Eerlijkheid van bonusvoorwaarden", "hoog", "Spelaanbod en livecasino", "gemiddeld", "Kwaliteit van ondersteuning", "Moeite met verificatie", "Commissie die we mogelijk ontvangen", "nooit een factor",
  "03 · Zo worden beste aanbiedingen gekozen", "Als geschikte gepubliceerde gegevens bestaan, weerspiegelt keuze nummer één de sterkste actuele combinatie volgens de bekendgemaakte rangschikkingsmethode. Ontbrekend of onvolledig bewijs sluit het resultaat; de selectie kan veranderen met gezaghebbende gegevens.", "Alternatieven beantwoorden wezenlijk andere behoeften — lagere inzetvereisten of minimale storting — en dienen niet om posities op te sommen of de pagina te vullen. Selecties per gebruik op Casino's en Bonussen volgen dezelfde regel, tot drie aanbieders. Affiliatevergoeding bepaalt de Editor Score of natuurlijke redactionele rangschikking niet.",
  "04 · Redactioneel en commercieel", "Redactionele beoordeling en commerciële beschikbaarheid zijn gescheiden toepassingsgebieden. Affiliatevergoeding bepaalt de Editor Score of natuurlijke redactionele rangschikking niet.", "Activiteit in Programma en Hulp wordt niet gebruikt voor aanbiedingen, gepersonaliseerde rangschikkingen of advertenties. Huidige productcontroles houden die doelen gescheiden.",
  "05 · Bronnen, actualiteit, correcties", "Een review is slechts zo bruikbaar als de status en datum van de bronnen. Gepubliceerde gegevens tonen bewijsdatums waar beschikbaar; geloofwaardige correcties worden aan gezaghebbende bronnen getoetst.", "Bewijsdatums en beperkingen worden getoond waar het gepubliceerde dossier dit ondersteunt.", "Wezenlijke wijzigingen in voorwaarden moeten worden beoordeeld en de betreffende tekst moet bij correctie worden gedateerd.", "Geverifieerde correcties worden bij publicatie beoordeeld en gedateerd. Een fout gezien?", "Laat het ons weten", "— meldingen worden vastgelegd, beoordeeld en beantwoord.", "Bron- en testgegevens volgen de toepasselijke operationele en wettelijke bewaartermijnen.",
  "06 · Beperkingen — lees dit", "Een eerlijke methodologie erkent wat zij niet kan. Bevindingen weerspiegelen bekendgemaakte bronnen of gedateerde waarnemingen voor een specifiek rechtsgebied en context — momentopnamen, geen garanties.", "Een aanbieder kan na publicatie van gedrag veranderen; jouw resultaat kan afwijken.", "Opnametijden variëren per methode, rechtsgebied, bedrag en accountgeschiedenis.", "RTP-steekproeven vergelijken gepubliceerde fiches; we kunnen RTP niet empirisch via spelen verifiëren.", "We kunnen niet elk casino in elk land testen. Geen review is geen oordeel en een review betekent niet dat het casino in jouw rechtsgebied beschikbaar is.",
];

const sv = [
  "Metod", "Belägg före", "åsikt.", "Varje publicerat betyg ska läsas tillsammans med daterad källstatus och begränsningar. Sidan förklarar bedömningsramen och vad aktuella underlag kan — och inte kan — fastställa.",
  "01 · Så bedömer vi kasinon", "Ett ramverk. Beläggen redovisas.", "Publicerade recensioner använder tillgängliga belägg för operatören och redovisar viktiga begränsningar. Offentliga uppgifter, väsentliga villkor, betalningsinformation och supportunderlag bedöms konsekvent; en recension garanterar inte operatörens framtida agerande.", "När test- eller källunderlag finns ska daterade resultat och väsentliga begränsningar kunna spåras till dem. Lagring följer tillämpliga operativa och rättsliga tidsplaner, inte ett obegränsat offentligt löfte.",
  "Käll- och teststatus", "En recension anger om ett resultat kommer från en offentlig källa, operatörsmaterial eller ett daterat test. Saknade belägg antas inte och aktuell behörighet i jurisdiktionen måste kontrolleras separat.", "Betalningar och uttag", "Publicerad uttagsinformation anger källa och datum när det finns. Tider kan variera efter metod, belopp, verifiering, kontohistorik och jurisdiktion; otillgängliga belägg förblir otillgängliga.", "Villkor rad för rad", "Väsentliga villkor omfattar omsättningsbas, spelviktning, högsta insats, vinsttak, giltighetstid och undantag. Operatörens aktuella villkor gäller och måste kontrolleras innan du agerar.", "Support- och spelinformation", "Support- och spelinformation jämförs med publicerade regler när belägg finns. Tillgänglighet, RTP-varianter och servicenivåer kan ändras och antas inte utifrån saknade uppgifter.",
  "02 · Vad som påverkar betyget", "Bedömning grundad på belägg.", "Editor Score är en redaktionell bedömning grundad på tillgängliga belägg — inte resultatet av en fast matematisk formel, och ingen procentuell viktning ska antas. Påverkansordningen är ändå stabil och offentlig: uttagens tillförlitlighet väger tyngst, ärliga villkor därefter och sedan allt annat.", "Vissa belagda resultat kan begränsa en bedömning i stället för att lägga till vikt, bland annat olöst utebliven betalning, väsentligt uttagsfel eller marknadsföring som förvränger operatörens villkor.",
  "Uttagens snabbhet och tillförlitlighet", "väger tyngst", "Bonusvillkorens ärlighet", "hög", "Spelutbud och livecasino", "måttlig", "Supportkvalitet", "Verifieringsfriktion", "Provision vi kan få", "aldrig en faktor",
  "03 · Så väljs bästa erbjudanden", "När lämpliga publicerade uppgifter finns speglar förstavalet den starkaste aktuella kombinationen enligt den redovisade rankningsmetoden. Saknade eller ofullständiga belägg stänger resultatet; urvalet kan ändras när auktoritativa uppgifter ändras.", "Alternativ svarar på väsentligt olika behov — lägre omsättningskrav eller minimiinsättning — och används inte för att räkna positioner eller fylla sidan. Urval efter användning på Kasinon och Bonusar följer samma regel, högst tre operatörer. Affiliateersättning styr inte Editor Score eller naturlig redaktionell rankning.",
  "04 · Redaktionellt och kommersiellt", "Redaktionell poäng och kommersiell tillgänglighet är separata delar av tjänsten. Affiliateersättning styr inte Editor Score eller naturlig redaktionell rankning.", "Aktivitet i Programmet och Hjälpen används inte för erbjudanden, personlig rankning eller annonsering. Nuvarande produktkontroller håller syftena åtskilda.",
  "05 · Källor, aktualitet, rättelser", "En recension är bara så användbar som källornas status och datum. Publicerade uppgifter visar beläggens datum när det finns; trovärdiga rättelser bedöms mot auktoritativa källor.", "Beläggens datum och begränsningar visas när det publicerade underlaget stöder dem.", "Väsentliga villkorsändringar bör granskas och berörd text dateras när den rättas.", "Verifierade rättelser granskas och dateras när de publiceras. Hittat ett fel?", "Berätta för oss", "— rapporter registreras, bedöms och besvaras.", "Käll- och testunderlag följer tillämpliga operativa och rättsliga lagringstider.",
  "06 · Begränsningar — läs detta", "En ärlig metod medger vad den inte kan göra. Resultaten speglar redovisade källor eller daterade observationer för en viss jurisdiktion och kontext — ögonblicksbilder, inte garantier.", "En operatör kan ändra beteende efter publicering; ditt resultat kan skilja sig.", "Uttagstider varierar efter metod, jurisdiktion, belopp och kontohistorik.", "RTP-stickprov jämför publicerade datablad; vi kan inte verifiera RTP empiriskt genom spel.", "Vi kan inte testa varje kasino i varje land. Avsaknad av recension är inget omdöme och en recension påstår inte att kasinot är tillgängligt i din jurisdiktion.",
];

const da = [
  "Metode", "Dokumentation før", "holdning.", "Hver offentliggjort bedømmelse skal læses sammen med dateret kildestatus og begrænsninger. Siden forklarer vurderingsrammen og hvad aktuelle oplysninger kan — og ikke kan — fastslå.",
  "01 · Sådan vurderer vi casinoer", "Én ramme. Dokumentation oplyst.", "Offentliggjorte anmeldelser bruger den tilgængelige dokumentation for operatøren og oplyser vigtige begrænsninger. Offentlige registre, væsentlige vilkår, betalingsoplysninger og supportdokumentation vurderes ensartet; en anmeldelse garanterer ikke operatørens fremtidige adfærd.", "Hvor test- eller kilderegistre findes, bør daterede resultater og væsentlige begrænsninger kunne spores til dem. Opbevaring følger den gældende driftsmæssige og juridiske tidsplan, ikke et ubegrænset offentligt løfte.",
  "Kilde- og teststatus", "En anmeldelse oplyser, om et resultat kommer fra en offentlig kilde, operatørmateriale eller en dateret test. Manglende dokumentation antages ikke, og aktuel berettigelse i jurisdiktionen skal kontrolleres særskilt.", "Betalinger og udbetalinger", "Offentliggjorte udbetalingsoplysninger angiver kilde og dato, hvor de findes. Tider varierer efter metode, beløb, verifikation, kontohistorik og jurisdiktion; utilgængelig dokumentation forbliver utilgængelig.", "Vilkår linje for linje", "Væsentlige vilkår omfatter omsætningsgrundlag, spilvægtning, maksimal indsats, gevinstloft, udløb og undtagelser. Operatørens aktuelle vilkår er gældende og skal kontrolleres før handling.", "Support- og spiloplysninger", "Support- og spiloplysninger sammenlignes med offentliggjorte regler, hvor dokumentation findes. Tilgængelighed, RTP-varianter og serviceniveauer kan ændre sig og antages ikke ud fra manglende registre.",
  "02 · Hvad påvirker bedømmelsen", "Vurdering baseret på dokumentation.", "Editor Score er en redaktionel vurdering baseret på tilgængelig dokumentation — ikke resultatet af en fast matematisk formel, og der må ikke udledes procentvis vægtning. Rækkefølgen er dog stabil og offentlig: pålidelige udbetalinger vejer tungest, ærlige vilkår næsttungest og derefter alt andet.", "Visse dokumenterede resultater kan begrænse en vurdering frem for at tilføje vægt, herunder uløst manglende betaling, væsentlig udbetalingsfejl eller markedsføring, der fordrejer operatørens vilkår.",
  "Udbetalingshastighed og pålidelighed", "vejer tungest", "Bonusvilkårenes ærlighed", "høj", "Spiludvalg og livecasino", "moderat", "Supportkvalitet", "Verifikationsbesvær", "Provision vi kan modtage", "aldrig en faktor",
  "03 · Sådan vælges de bedste tilbud", "Når egnede offentliggjorte registre findes, afspejler førstevalget den stærkeste aktuelle kombination efter den oplyste rangeringsmetode. Manglende eller ufuldstændig dokumentation lukker resultatet; valget kan ændre sig med autoritative data.", "Alternativer dækker væsentligt forskellige behov — lavere omsætningskrav eller minimumsindbetaling — og bruges ikke til at opremse placeringer eller fylde siden. Udvalg efter behov på Casinoer og Bonusser følger samme regel, højst tre operatører. Affiliatebetaling bestemmer ikke Editor Score eller naturlig redaktionel rangering.",
  "04 · Redaktionelt og kommercielt", "Redaktionel bedømmelse og kommerciel tilgængelighed er separate dele af applikationen. Affiliatebetaling bestemmer ikke Editor Score eller naturlig redaktionel rangering.", "Aktivitet i Programmet og Hjælp bruges ikke til tilbud, personlige rangeringer eller annoncering. De aktuelle produktkontroller holder formålene adskilt.",
  "05 · Kilder, aktualitet, rettelser", "En anmeldelse er kun så nyttig som kildernes status og dato. Offentliggjorte registre viser dokumentationsdatoer, hvor de findes; troværdige rettelser vurderes mod autoritative kilder.", "Dokumentationsdatoer og begrænsninger vises, hvor det offentliggjorte register understøtter dem.", "Væsentlige ændringer i vilkår bør gennemgås, og berørt tekst dateres ved rettelse.", "Verificerede rettelser gennemgås og dateres ved offentliggørelse. Fundet en fejl?", "Fortæl os det", "— henvendelser registreres, vurderes og besvares.", "Kilde- og testregistre følger gældende driftsmæssige og juridiske opbevaringsperioder.",
  "06 · Begrænsninger — læs dette", "En ærlig metode erkender, hvad den ikke kan. Resultater afspejler oplyste kilder eller daterede observationer for en bestemt jurisdiktion og kontekst — øjebliksbilleder, ikke garantier.", "En operatør kan ændre adfærd efter offentliggørelse; dit resultat kan afvige.", "Udbetalingstider varierer efter metode, jurisdiktion, beløb og kontohistorik.", "RTP-stikprøver sammenligner offentliggjorte datablade; vi kan ikke verificere RTP empirisk gennem spil.", "Vi kan ikke teste hvert casino i hvert land. Fravær af en anmeldelse er ingen dom, og dens tilstedeværelse påstår ikke tilgængelighed i din jurisdiktion.",
];

const fi = [
  "Menetelmä", "Näyttö ennen", "mielipidettä.", "Jokainen julkaistu arvio on luettava yhdessä päivätyn lähdetilan ja rajoitusten kanssa. Tämä sivu kertoo arviointikehyksen ja mitä nykyiset tiedot voivat — ja eivät voi — osoittaa.",
  "01 · Näin arvioimme kasinoita", "Yksi kehys. Näyttö kerrotaan.", "Julkaistuissa arvosteluissa käytetään operaattorista saatavilla olevaa näyttöä ja kerrotaan olennaiset rajoitukset. Julkiset tiedot, olennaiset ehdot, maksutiedot ja tukinäyttö arvioidaan johdonmukaisesti; arvostelu ei takaa operaattorin tulevaa toimintaa.", "Jos testi- tai lähdetietoja on, päivättyjen havaintojen ja olennaisten rajoitusten pitäisi olla jäljitettävissä niihin. Säilytys noudattaa sovellettavaa toiminnallista ja oikeudellista aikataulua, ei rajoittamatonta julkista lupausta.",
  "Lähde- ja testitila", "Arvostelu kertoo, perustuuko havainto julkiseen lähteeseen, operaattorin aineistoon vai päivättyyn testiin. Puuttuvaa näyttöä ei oleteta, ja ajantasainen kelpoisuus oikeusalueella on tarkistettava erikseen.", "Maksut ja nostot", "Julkaistu nostotieto ilmoittaa lähteen ja päivämäärän, kun ne ovat saatavilla. Ajat vaihtelevat menetelmän, summan, vahvistuksen, tilihistorian ja oikeusalueen mukaan; puuttuva näyttö pysyy puuttuvana.", "Ehdot rivi riviltä", "Olennaisiin ehtoihin kuuluvat kierrätyspohja, pelien painotus, enimmäispanos, voittokatot, voimassaolo ja poissulut. Operaattorin nykyiset ehdot ovat määrääviä ja ne on tarkistettava ennen toimintaa.", "Tuki- ja pelitiedot", "Tuki- ja pelitietoja verrataan julkaistuihin sääntöihin, kun näyttöä on. Saatavuus, RTP-versiot ja palvelutasot voivat muuttua, eikä niitä oleteta puuttuvista tiedoista.",
  "02 · Mikä vaikuttaa arvioon", "Näyttöön perustuva harkinta.", "Editor Score on saatavilla olevaan näyttöön perustuva toimituksellinen harkinta — ei kiinteän laskukaavan tulos, eikä siitä pidä päätellä prosenttipainoja. Vaikutusjärjestys on silti vakaa ja julkinen: nostojen luotettavuus painaa eniten, ehtojen rehellisyys toiseksi ja muu sen jälkeen.", "Osa perustelluista havainnoista voi rajata arviota painon lisäämisen sijaan, kuten ratkaisematon maksamatta jättäminen, olennainen nostovirhe tai operaattorin ehtoja vääristävä markkinointi.",
  "Nostojen nopeus ja luotettavuus", "suurin paino", "Bonusehtojen rehellisyys", "suuri", "Pelivalikoima ja livekasino", "kohtalainen", "Tuen laatu", "Vahvistamisen vaiva", "Mahdollinen saamamme provisio", "ei koskaan vaikuta",
  "03 · Näin parhaat tarjoukset valitaan", "Kun kelvollisia julkaistuja tietoja on, ykkösvalinta kuvastaa vahvinta nykyistä yhdistelmää ilmoitetun järjestysmenetelmän mukaan. Puuttuva tai keskeneräinen näyttö sulkee tuloksen; valinta voi muuttua luotettavien tietojen muuttuessa.", "Vaihtoehdot vastaavat olennaisesti eri tarpeisiin — pienempi kierrätys tai minimitalletus — eivätkä luettele sijoja tai täytä sivua. Kasinoiden ja Bonusten käyttötapauslistat noudattavat samaa sääntöä, enintään kolme operaattoria. Kumppanipalkkio ei määritä Editor Scorea eikä luonnollista toimituksellista järjestystä.",
  "04 · Toimituksellinen ja kaupallinen", "Toimituksellinen arviointi ja kaupallinen saatavuus ovat sovelluksen erillisiä alueita. Kumppanipalkkio ei määritä Editor Scorea eikä luonnollista toimituksellista järjestystä.", "Ohjelman ja Ohjeen toimintaa ei käytetä tarjousten kohdentamiseen, sijoitusten personointiin tai mainontaan. Nykyiset tuotehallinnat pitävät tarkoitukset erillään.",
  "05 · Lähteet, ajantasaisuus, korjaukset", "Arvostelu on vain lähdetilansa ja päivämääränsä veroinen. Julkaistuissa tiedoissa näytetään näytön päivämäärät, jos niitä on; uskottavat korjaukset arvioidaan luotettavia lähteitä vasten.", "Näytön päivämäärät ja rajoitukset näytetään, jos julkaistu tieto tukee niitä.", "Olennaiset ehtomuutokset pitäisi tarkistaa ja korjattu teksti päivätä.", "Vahvistetut korjaukset tarkistetaan ja päivätään julkaistaessa. Huomasitko virheen?", "Kerro meille", "— ilmoitukset kirjataan, arvioidaan ja niihin vastataan.", "Lähde- ja testitiedot noudattavat sovellettavia toiminnallisia ja oikeudellisia säilytysaikoja.",
  "06 · Rajoitukset — lue tämä", "Rehellinen menetelmä myöntää rajansa. Havainnot kuvastavat ilmoitettuja lähteitä tai päivättyjä havaintoja tietyllä oikeusalueella ja tietyssä yhteydessä — tilannekuvia, eivät takuita.", "Operaattori voi muuttaa toimintaansa julkaisemisen jälkeen; tuloksesi voi poiketa.", "Nostoajat vaihtelevat menetelmän, oikeusalueen, summan ja tilihistorian mukaan.", "RTP-pistokokeissa verrataan julkaistuja tietoja; emme voi vahvistaa RTP:tä empiirisesti pelaamalla.", "Emme voi testata jokaista kasinoa kaikissa maissa. Arvostelun puuttuminen ei ole tuomio, eikä sen olemassaolo väitä kasinon olevan saatavilla oikeusalueellasi.",
];

const nb = [
  "Metode", "Dokumentasjon før", "mening.", "Hver publisert vurdering må leses sammen med datert kildestatus og begrensninger. Denne siden forklarer vurderingsrammen og hva dagens opplysninger kan — og ikke kan — fastslå.",
  "01 · Slik vurderer vi kasinoer", "Ett rammeverk. Dokumentasjon oppgis.", "Publiserte anmeldelser bruker tilgjengelig dokumentasjon for operatøren og oppgir viktige begrensninger. Offentlige registre, vesentlige vilkår, betalingsinformasjon og dokumentasjon om støtte vurderes konsekvent; en anmeldelse garanterer ikke operatørens framtidige atferd.", "Når test- eller kilderegistre finnes, bør daterte funn og vesentlige begrensninger kunne spores til dem. Oppbevaring følger gjeldende driftsmessige og juridiske tidsplaner, ikke et ubegrenset offentlig løfte.",
  "Kilde- og teststatus", "En anmeldelse oppgir om et funn kommer fra en offentlig kilde, operatørmateriale eller en datert test. Manglende dokumentasjon antas ikke, og gjeldende berettigelse i jurisdiksjonen må kontrolleres separat.", "Betalinger og uttak", "Publisert uttaksinformasjon oppgir kilde og dato der det finnes. Tider varierer etter metode, beløp, verifisering, kontohistorikk og jurisdiksjon; utilgjengelig dokumentasjon forblir utilgjengelig.", "Vilkår linje for linje", "Vesentlige vilkår omfatter omsetningsgrunnlag, spillvekting, maksimal innsats, gevinsttak, utløp og unntak. Operatørens gjeldende vilkår er autoritative og må kontrolleres før handling.", "Støtte- og spillinformasjon", "Støtte- og spillinformasjon sammenlignes med publiserte regler der dokumentasjon finnes. Tilgjengelighet, RTP-varianter og servicenivåer kan endres og antas ikke ut fra manglende registre.",
  "02 · Hva påvirker vurderingen", "Skjønn basert på dokumentasjon.", "Editor Score er en redaksjonell vurdering basert på tilgjengelig dokumentasjon — ikke resultatet av en fast matematisk formel, og ingen prosentvis vekting skal utledes. Påvirkningsrekkefølgen er likevel stabil og offentlig: pålitelige uttak veier tyngst, ærlige vilkår deretter og så alt annet.", "Enkelte dokumenterte funn kan begrense en vurdering i stedet for å legge til vekt, inkludert uløst manglende betaling, vesentlig uttaksfeil eller markedsføring som feilrepresenterer operatørens vilkår.",
  "Uttakshastighet og pålitelighet", "veier tyngst", "Ærlige bonusvilkår", "høy", "Spillutvalg og livekasino", "moderat", "Kvalitet på støtte", "Verifiseringsfriksjon", "Provisjon vi kan motta", "aldri en faktor",
  "03 · Slik velges de beste tilbudene", "Når egnede publiserte registre finnes, gjenspeiler førstevalget den sterkeste nåværende kombinasjonen etter den oppgitte rangeringsmetoden. Manglende eller ufullstendig dokumentasjon lukker resultatet; utvalget kan endres med autoritative data.", "Alternativer svarer på vesentlig forskjellige behov — lavere omsetningskrav eller minimumsinnskudd — og brukes ikke til å ramse opp plasseringer eller fylle siden. Utvalg etter bruk på Kasinoer og Bonuser følger samme regel, høyst tre operatører. Affiliatebetaling avgjør ikke Editor Score eller naturlig redaksjonell rangering.",
  "04 · Redaksjonelt og kommersielt", "Redaksjonell vurdering og kommersiell tilgjengelighet er separate deler av applikasjonen. Affiliatebetaling avgjør ikke Editor Score eller naturlig redaksjonell rangering.", "Aktivitet i Programmet og Hjelp brukes ikke til tilbud, personlige rangeringer eller annonsering. Dagens produktkontroller holder formålene adskilt.",
  "05 · Kilder, aktualitet, rettelser", "En anmeldelse er bare så nyttig som kildenes status og dato. Publiserte registre viser dokumentasjonsdatoer der de finnes; troverdige rettelser vurderes mot autoritative kilder.", "Dokumentasjonsdatoer og begrensninger vises der det publiserte registeret støtter dem.", "Vesentlige vilkårsendringer bør gjennomgås, og berørt tekst dateres når den rettes.", "Verifiserte rettelser gjennomgås og dateres ved publisering. Funnet en feil?", "Fortell oss", "— meldinger registreres, vurderes og besvares.", "Kilde- og testregistre følger gjeldende driftsmessige og juridiske oppbevaringstider.",
  "06 · Begrensninger — les dette", "En ærlig metode erkjenner hva den ikke kan. Funn gjenspeiler oppgitte kilder eller daterte observasjoner for en bestemt jurisdiksjon og kontekst — øyeblikksbilder, ikke garantier.", "En operatør kan endre atferd etter publisering; resultatet ditt kan avvike.", "Uttakstider varierer etter metode, jurisdiksjon, beløp og kontohistorikk.", "RTP-stikkprøver sammenligner publiserte datablad; vi kan ikke verifisere RTP empirisk gjennom spill.", "Vi kan ikke teste hvert kasino i hvert land. Fravær av en anmeldelse er ingen dom, og dens tilstedeværelse hevder ikke tilgjengelighet i din jurisdiksjon.",
];

const catalog: Record<EuropeanLocale, readonly string[]> = {
  "en-GB": enGB,
  "de-DE": de,
  "it-IT": it,
  "es-ES": es,
  "pt-PT": pt,
  "el-GR": el,
  "nl-NL": nl,
  "sv-SE": sv,
  "da-DK": da,
  "fi-FI": fi,
  "nb-NO": nb,
};

export type MethodologyMessages = Readonly<{
  metadataTitle: string;
  metadataDescription: string;
  copy: ReadonlyMap<string, string>;
}>;

export function methodologyMessages(locale: SupportedLocale): MethodologyMessages {
  const effectiveLocale = locale === "es-PE" ? "es-ES" : locale;
  const translated = catalog[effectiveLocale as EuropeanLocale] ?? enGB;
  if (translated.length !== METHODOLOGY_SOURCE_COPY.length) {
    throw new Error(`Methodology translation coverage mismatch for ${locale}: ${translated.length}/${METHODOLOGY_SOURCE_COPY.length}`);
  }
  return {
    metadataTitle: translated[0] === "Methodology" ? "Review Methodology | B4GAMBLE" : `${translated[0]} | B4GAMBLE`,
    metadataDescription: translated[3],
    copy: new Map(METHODOLOGY_SOURCE_COPY.map((source, index) => [source, translated[index]])),
  };
}
