import type { SupportedLocale } from "@/lib/market/registry";

export const TEN_STEPS_SOURCE_COPY = [
  "The Programme, step by step", "Ten steps.", "One", "plan.",
  "Each mission takes 5–15 minutes and ends with something you keep. Here's exactly what happens — no surprises, no fine print.",
  "Start Mission 01", "Why B4GAMBLE →", "01–03 Understand", "04–07 Build", "08–10 Apply", "Scroll ↓",
  "What you will build", "Three things you'll have at the end.", "A clear picture", "Your triggers, patterns and the moments decisions actually happen.",
  "Working boundaries", "Limits you design, test in real weeks, and adjust until they hold.", "A reviewable plan", "One document that says how you play — yours to revisit any time.", "The path",
  "Get started", "Say what's happening; get your Starting Point.", "Set your limits", "First pass at time and money lines.",
  "Understand your triggers", "Map the moments that start sessions.", "Build one boundary", "One limit you can keep this week.",
  "Reality check", "An honest week-two look at the numbers.", "Decision framework", "A simple rule for yes, no and not-tonight.",
  "Play plan", "Write the plan you'll actually follow.", "Safer play", "Reduce friction, judge operators, protect your plan.",
  "Review &amp; adjust", "See what held. Fix what didn't.", "Long-term control", "Turn ten missions into a habit that lasts.",
  "Start private", "What you say here,", "stays here.", "Your situation and plan are never used for offers, rankings or ads.",
  "Request export or deletion through account support; legal and backup retention may apply.", "No mission ever asks you to deposit, claim or play.",
  "Mission 01 takes about", "one minute.", "No registration until your starting point is ready.",
  "Ten lanterns along a dark path, first ones lit — sequence and destination",
] as const;

export type TenStepsTranslation = Readonly<{
  metadataTitle: string;
  metadataDescription: string;
  text: readonly string[];
}>;

const en: TenStepsTranslation = {
  metadataTitle: "The B4GAMBLE 10-Step Programme",
  metadataDescription: "See how ten self-directed missions build a personal Starting Point and control plan.",
  text: TEN_STEPS_SOURCE_COPY,
};

const catalog: Record<SupportedLocale, TenStepsTranslation> = {
  "en-GB": en,
  "de-DE": { metadataTitle: "Das 10-Schritte-Programm von B4GAMBLE", metadataDescription: "Sieh, wie zehn selbstbestimmte Missionen einen persönlichen Ausgangspunkt und Kontrollplan aufbauen.", text: [
    "Das Programm, Schritt für Schritt", "Zehn Schritte.", "Ein", "Plan.", "Jede Mission dauert 5–15 Minuten und endet mit etwas, das du behältst. Hier siehst du genau, was geschieht — ohne Überraschungen und Kleingedrucktes.", "Mission 01 starten", "Warum B4GAMBLE →", "01–03 Verstehen", "04–07 Aufbauen", "08–10 Anwenden", "Scrollen ↓",
    "Was du aufbaust", "Drei Dinge, die du am Ende hast.", "Ein klares Bild", "Deine Auslöser, Muster und die Momente, in denen Entscheidungen wirklich fallen.", "Tragfähige Grenzen", "Grenzen, die du entwirfst, in echten Wochen testest und anpasst, bis sie halten.", "Ein überprüfbarer Plan", "Ein Dokument darüber, wie du spielst — jederzeit von dir überprüfbar.", "Der Weg",
    "Loslegen", "Sag, was geschieht, und erhalte deinen Ausgangspunkt.", "Setze deine Grenzen", "Ein erster Entwurf für Zeit- und Geldgrenzen.", "Verstehe deine Auslöser", "Ordne die Momente zu, die Spielsitzungen auslösen.", "Baue eine Grenze", "Eine Grenze, die du diese Woche einhalten kannst.", "Realitätscheck", "Ein ehrlicher Blick auf die Zahlen in Woche zwei.", "Entscheidungsrahmen", "Eine einfache Regel für Ja, Nein und Nicht-heute.", "Spielplan", "Schreibe den Plan, dem du tatsächlich folgen wirst.", "Kontrollierteres Spiel", "Verringere Reibung, beurteile Anbieter und schütze deinen Plan.", "Prüfen und anpassen", "Sieh, was gehalten hat. Repariere, was nicht hielt.", "Langfristige Kontrolle", "Mach aus zehn Missionen eine dauerhafte Gewohnheit.",
    "Privat beginnen", "Was du hier sagst,", "bleibt hier.", "Deine Situation und dein Plan werden nie für Angebote, Rankings oder Werbung verwendet.", "Fordere Export oder Löschung über den Kontosupport an; gesetzliche Aufbewahrung und Sicherungskopien können gelten.", "Keine Mission fordert dich je zu Einzahlung, Bonusannahme oder Spiel auf.", "Mission 01 dauert etwa", "eine Minute.", "Keine Registrierung, bis dein Ausgangspunkt bereit ist.", "Zehn Laternen entlang eines dunklen Weges, die ersten leuchten — Abfolge und Ziel",
  ] },
  "it-IT": { metadataTitle: "Il Programma B4GAMBLE in 10 passi", metadataDescription: "Scopri come dieci missioni autonome costruiscono un Punto di partenza personale e un piano di controllo.", text: [
    "Il Programma, passo dopo passo", "Dieci passi.", "Un", "piano.", "Ogni missione dura 5–15 minuti e termina con qualcosa che conservi. Ecco cosa accade, senza sorprese né clausole nascoste.", "Inizia la Missione 01", "Perché B4GAMBLE →", "01–03 Comprendi", "04–07 Costruisci", "08–10 Applica", "Scorri ↓",
    "Cosa costruirai", "Tre cose che avrai alla fine.", "Un quadro chiaro", "I tuoi fattori scatenanti, gli schemi e i momenti in cui avvengono davvero le decisioni.", "Limiti pratici", "Limiti che progetti, provi in settimane reali e regoli finché funzionano.", "Un piano verificabile", "Un documento che descrive come giochi — da rivedere quando vuoi.", "Il percorso",
    "Inizia", "Descrivi cosa succede e ottieni il tuo Punto di partenza.", "Definisci i tuoi limiti", "Una prima definizione dei limiti di tempo e denaro.", "Comprendi i tuoi fattori scatenanti", "Individua i momenti che avviano le sessioni.", "Costruisci un limite", "Un limite che puoi rispettare questa settimana.", "Verifica della realtà", "Uno sguardo onesto ai numeri della seconda settimana.", "Schema decisionale", "Una regola semplice per sì, no e non stasera.", "Piano di gioco", "Scrivi il piano che seguirai davvero.", "Gioco più controllato", "Riduci gli ostacoli, valuta gli operatori e proteggi il tuo piano.", "Rivedi e adatta", "Vedi cosa ha funzionato. Correggi ciò che non ha funzionato.", "Controllo a lungo termine", "Trasforma dieci missioni in un'abitudine duratura.",
    "Inizia in privato", "Quello che dici qui", "resta qui.", "La tua situazione e il tuo piano non vengono mai usati per offerte, classifiche o pubblicità.", "Richiedi esportazione o cancellazione all'assistenza account; possono valere conservazione legale e copie di sicurezza.", "Nessuna missione ti chiede di depositare, accettare bonus o giocare.", "La Missione 01 richiede circa", "un minuto.", "Nessuna registrazione finché il Punto di partenza non è pronto.", "Dieci lanterne lungo un sentiero buio, le prime accese — sequenza e destinazione",
  ] },
  "es-ES": { metadataTitle: "El Programa de 10 pasos de B4GAMBLE", metadataDescription: "Descubre cómo diez misiones autodirigidas construyen un Punto de partida personal y un plan de control.", text: [
    "El Programa, paso a paso", "Diez pasos.", "Un", "plan.", "Cada misión dura entre 5 y 15 minutos y termina con algo que conservas. Esto es exactamente lo que ocurre, sin sorpresas ni letra pequeña.", "Iniciar la Misión 01", "Por qué B4GAMBLE →", "01–03 Comprender", "04–07 Construir", "08–10 Aplicar", "Desplázate ↓",
    "Lo que construirás", "Tres cosas que tendrás al final.", "Una imagen clara", "Tus desencadenantes, patrones y los momentos en que realmente se toman decisiones.", "Límites prácticos", "Límites que diseñas, pruebas en semanas reales y ajustas hasta que funcionan.", "Un plan revisable", "Un documento que explica cómo juegas, para revisarlo cuando quieras.", "El recorrido",
    "Empezar", "Cuenta qué está pasando y obtén tu Punto de partida.", "Establece tus límites", "Un primer borrador de límites de tiempo y dinero.", "Comprende tus desencadenantes", "Identifica los momentos que inician las sesiones.", "Crea un límite", "Un límite que puedas mantener esta semana.", "Comprobación de la realidad", "Una mirada honesta a las cifras de la segunda semana.", "Marco de decisión", "Una regla sencilla para sí, no y hoy no.", "Plan de juego", "Escribe el plan que realmente seguirás.", "Juego con más control", "Reduce la fricción, evalúa operadores y protege tu plan.", "Revisar y ajustar", "Observa qué funcionó. Corrige lo que no.", "Control a largo plazo", "Convierte diez misiones en un hábito duradero.",
    "Empieza en privado", "Lo que dices aquí", "se queda aquí.", "Tu situación y tu plan nunca se usan para ofertas, clasificaciones ni anuncios.", "Solicita la exportación o eliminación al soporte de cuenta; pueden aplicarse conservación legal y copias de seguridad.", "Ninguna misión te pide depositar, aceptar una promoción ni jugar.", "La Misión 01 tarda aproximadamente", "un minuto.", "No hay registro hasta que tu Punto de partida esté listo.", "Diez faroles a lo largo de un camino oscuro, los primeros encendidos — secuencia y destino",
  ] },
  "pt-PT": { metadataTitle: "O Programa de 10 passos da B4GAMBLE", metadataDescription: "Vê como dez missões autónomas criam um Ponto de partida pessoal e um plano de controlo.", text: [
    "O Programa, passo a passo", "Dez passos.", "Um", "plano.", "Cada missão demora 5–15 minutos e termina com algo que guardas. Aqui está exatamente o que acontece — sem surpresas nem letras pequenas.", "Iniciar a Missão 01", "Porquê B4GAMBLE →", "01–03 Compreender", "04–07 Construir", "08–10 Aplicar", "Deslizar ↓",
    "O que vais construir", "Três coisas que terás no final.", "Uma imagem clara", "Os teus gatilhos, padrões e os momentos em que as decisões realmente acontecem.", "Limites práticos", "Limites que defines, testas em semanas reais e ajustas até funcionarem.", "Um plano revisto", "Um documento que descreve como jogas — para reveres quando quiseres.", "O percurso",
    "Começar", "Diz o que está a acontecer e recebe o teu Ponto de partida.", "Define os teus limites", "Uma primeira versão dos limites de tempo e dinheiro.", "Compreende os teus gatilhos", "Mapeia os momentos que iniciam sessões.", "Cria um limite", "Um limite que consegues manter esta semana.", "Teste à realidade", "Uma análise honesta aos números da segunda semana.", "Estrutura de decisão", "Uma regra simples para sim, não e hoje não.", "Plano de jogo", "Escreve o plano que vais realmente seguir.", "Jogo com mais controlo", "Reduz a fricção, avalia operadores e protege o teu plano.", "Rever e ajustar", "Vê o que resultou. Corrige o que não resultou.", "Controlo a longo prazo", "Transforma dez missões num hábito duradouro.",
    "Começa em privado", "O que dizes aqui", "fica aqui.", "A tua situação e o teu plano nunca são usados para ofertas, classificações ou anúncios.", "Pede exportação ou eliminação ao apoio da conta; podem aplicar-se conservação legal e cópias de segurança.", "Nenhuma missão te pede para depositar, aceitar promoções ou jogar.", "A Missão 01 demora cerca de", "um minuto.", "Sem registo até o teu Ponto de partida estar pronto.", "Dez lanternas ao longo de um caminho escuro, as primeiras acesas — sequência e destino",
  ] },
  "el-GR": { metadataTitle: "Το Πρόγραμμα 10 βημάτων του B4GAMBLE", metadataDescription: "Δες πώς δέκα αυτοκαθοδηγούμενες Αποστολές δημιουργούν ένα προσωπικό Σημείο Εκκίνησης και σχέδιο ελέγχου.", text: [
    "Το Πρόγραμμα, βήμα προς βήμα", "Δέκα βήματα.", "Ένα", "σχέδιο.", "Κάθε Αποστολή διαρκεί 5–15 λεπτά και τελειώνει με κάτι που κρατάς. Δες ακριβώς τι συμβαίνει — χωρίς εκπλήξεις ή ψιλά γράμματα.", "Έναρξη Αποστολής 01", "Γιατί B4GAMBLE →", "01–03 Κατανόηση", "04–07 Δημιουργία", "08–10 Εφαρμογή", "Κύλιση ↓",
    "Τι θα δημιουργήσεις", "Τρία πράγματα που θα έχεις στο τέλος.", "Μια καθαρή εικόνα", "Τα ερεθίσματα, τα μοτίβα και οι στιγμές όπου παίρνονται πραγματικά οι αποφάσεις.", "Λειτουργικά όρια", "Όρια που σχεδιάζεις, δοκιμάζεις σε πραγματικές εβδομάδες και προσαρμόζεις ώσπου να λειτουργούν.", "Ένα αναθεωρήσιμο σχέδιο", "Ένα έγγραφο που περιγράφει πώς παίζεις — για να το εξετάζεις όποτε θέλεις.", "Η διαδρομή",
    "Ξεκίνα", "Πες τι συμβαίνει και λάβε το Σημείο Εκκίνησής σου.", "Θέσε τα όριά σου", "Μια πρώτη εκδοχή ορίων χρόνου και χρημάτων.", "Κατανόησε τα ερεθίσματά σου", "Χαρτογράφησε τις στιγμές που ξεκινούν συνεδρίες.", "Δημιούργησε ένα όριο", "Ένα όριο που μπορείς να τηρήσεις αυτή την εβδομάδα.", "Έλεγχος πραγματικότητας", "Μια ειλικρινής ματιά στους αριθμούς της δεύτερης εβδομάδας.", "Πλαίσιο απόφασης", "Ένας απλός κανόνας για ναι, όχι και όχι-απόψε.", "Σχέδιο παιχνιδιού", "Γράψε το σχέδιο που θα ακολουθήσεις πραγματικά.", "Παιχνίδι με περισσότερο έλεγχο", "Μείωσε την τριβή, αξιολόγησε παρόχους και προστάτεψε το σχέδιό σου.", "Αναθεώρηση και προσαρμογή", "Δες τι άντεξε. Διόρθωσε ό,τι δεν άντεξε.", "Μακροπρόθεσμος έλεγχος", "Μετέτρεψε δέκα Αποστολές σε συνήθεια που διαρκεί.",
    "Ξεκίνα ιδιωτικά", "Όσα λες εδώ", "μένουν εδώ.", "Η κατάστασή σου και το σχέδιό σου δεν χρησιμοποιούνται ποτέ για προσφορές, κατατάξεις ή διαφημίσεις.", "Ζήτησε εξαγωγή ή διαγραφή από την υποστήριξη λογαριασμού· μπορεί να ισχύει νομική διατήρηση και αντίγραφα ασφαλείας.", "Καμία Αποστολή δεν σου ζητά να καταθέσεις, να αποδεχτείς προσφορά ή να παίξεις.", "Η Αποστολή 01 διαρκεί περίπου", "ένα λεπτό.", "Καμία εγγραφή μέχρι να είναι έτοιμο το Σημείο Εκκίνησής σου.", "Δέκα φανάρια σε ένα σκοτεινό μονοπάτι, τα πρώτα αναμμένα — σειρά και προορισμός",
  ] },
  "nl-NL": { metadataTitle: "Het 10-stappenprogramma van B4GAMBLE", metadataDescription: "Bekijk hoe tien zelfgestuurde Missies een persoonlijk Startpunt en controleplan opbouwen.", text: [
    "Het Programma, stap voor stap", "Tien stappen.", "Eén", "plan.", "Elke Missie duurt 5–15 minuten en eindigt met iets dat je bewaart. Dit is precies wat er gebeurt — zonder verrassingen of kleine lettertjes.", "Start Missie 01", "Waarom B4GAMBLE →", "01–03 Begrijpen", "04–07 Opbouwen", "08–10 Toepassen", "Scroll ↓",
    "Wat je opbouwt", "Drie dingen die je aan het einde hebt.", "Een helder beeld", "Je triggers, patronen en de momenten waarop beslissingen echt plaatsvinden.", "Werkbare grenzen", "Grenzen die je ontwerpt, in echte weken test en aanpast tot ze standhouden.", "Een herzienbaar plan", "Eén document dat beschrijft hoe je speelt — wanneer je wilt opnieuw te bekijken.", "Het pad",
    "Beginnen", "Vertel wat er gebeurt en ontvang je Startpunt.", "Stel je grenzen in", "Een eerste versie van tijd- en geldgrenzen.", "Begrijp je triggers", "Breng de momenten in kaart die sessies starten.", "Bouw één grens", "Eén grens die je deze week kunt volhouden.", "Realiteitscheck", "Een eerlijke blik op de cijfers van week twee.", "Besliskader", "Een eenvoudige regel voor ja, nee en vanavond-niet.", "Speelplan", "Schrijf het plan dat je werkelijk gaat volgen.", "Spelen met meer controle", "Verminder frictie, beoordeel aanbieders en bescherm je plan.", "Beoordelen en aanpassen", "Bekijk wat standhield. Herstel wat niet werkte.", "Controle op lange termijn", "Maak van tien Missies een blijvende gewoonte.",
    "Begin privé", "Wat je hier zegt,", "blijft hier.", "Je situatie en plan worden nooit gebruikt voor aanbiedingen, ranglijsten of advertenties.", "Vraag export of verwijdering aan via accountondersteuning; wettelijke bewaring en back-ups kunnen van toepassing zijn.", "Geen Missie vraagt je om te storten, een aanbieding te claimen of te spelen.", "Missie 01 duurt ongeveer", "één minuut.", "Geen registratie voordat je Startpunt klaar is.", "Tien lantaarns langs een donker pad, de eerste branden — volgorde en bestemming",
  ] },
  "sv-SE": { metadataTitle: "B4GAMBLEs 10-stegsprogram", metadataDescription: "Se hur tio självstyrda Uppdrag bygger en personlig Startpunkt och kontrollplan.", text: [
    "Programmet, steg för steg", "Tio steg.", "En", "plan.", "Varje Uppdrag tar 5–15 minuter och slutar med något du behåller. Här är exakt vad som händer — utan överraskningar eller finstilt.", "Starta Uppdrag 01", "Varför B4GAMBLE →", "01–03 Förstå", "04–07 Bygg", "08–10 Tillämpa", "Rulla ↓",
    "Det du kommer att bygga", "Tre saker du har när du är klar.", "En tydlig bild", "Dina utlösare, mönster och de stunder då beslut faktiskt fattas.", "Fungerande gränser", "Gränser som du utformar, testar under verkliga veckor och justerar tills de håller.", "En plan som kan granskas", "Ett dokument som beskriver hur du spelar — att återvända till när du vill.", "Vägen",
    "Kom igång", "Berätta vad som händer och få din Startpunkt.", "Sätt dina gränser", "Ett första utkast till tids- och pengagränser.", "Förstå dina utlösare", "Kartlägg de stunder som startar spelsessioner.", "Bygg en gräns", "En gräns du kan hålla den här veckan.", "Verklighetskontroll", "En ärlig titt på siffrorna under vecka två.", "Beslutsram", "En enkel regel för ja, nej och inte-ikväll.", "Spelplan", "Skriv planen du faktiskt kommer att följa.", "Spel med mer kontroll", "Minska friktion, bedöm operatörer och skydda din plan.", "Granska och justera", "Se vad som höll. Rätta det som inte gjorde det.", "Långsiktig kontroll", "Gör tio Uppdrag till en vana som består.",
    "Börja privat", "Det du säger här", "stannar här.", "Din situation och plan används aldrig för erbjudanden, rankningar eller annonser.", "Begär export eller radering via kontosupport; rättslig lagring och säkerhetskopior kan gälla.", "Inget Uppdrag ber dig att sätta in, hämta ett erbjudande eller spela.", "Uppdrag 01 tar ungefär", "en minut.", "Ingen registrering förrän din Startpunkt är klar.", "Tio lyktor längs en mörk stig, de första tända — följd och mål",
  ] },
  "da-DK": { metadataTitle: "B4GAMBLEs 10-trinsprogram", metadataDescription: "Se hvordan ti selvstyrede Missioner bygger et personligt Udgangspunkt og en kontrolplan.", text: [
    "Programmet, trin for trin", "Ti trin.", "Én", "plan.", "Hver Mission tager 5–15 minutter og slutter med noget, du beholder. Her er præcis, hvad der sker — uden overraskelser eller småt skrift.", "Begynd Mission 01", "Hvorfor B4GAMBLE →", "01–03 Forstå", "04–07 Byg", "08–10 Anvend", "Rul ↓",
    "Det du bygger", "Tre ting du har til sidst.", "Et klart billede", "Dine udløsere, mønstre og de øjeblikke, hvor beslutninger faktisk træffes.", "Holdbare grænser", "Grænser du udformer, tester i virkelige uger og justerer, indtil de holder.", "En plan der kan gennemgås", "Ét dokument om, hvordan du spiller — dit at vende tilbage til når som helst.", "Vejen",
    "Kom i gang", "Fortæl hvad der sker, og få dit Udgangspunkt.", "Sæt dine grænser", "Et første udkast til tids- og pengegrænser.", "Forstå dine udløsere", "Kortlæg de øjeblikke der starter spilsessioner.", "Byg én grænse", "Én grænse du kan holde i denne uge.", "Virkelighedstjek", "Et ærligt blik på tallene i uge to.", "Beslutningsramme", "En enkel regel for ja, nej og ikke-i-aften.", "Spilleplan", "Skriv den plan du faktisk vil følge.", "Spil med mere kontrol", "Reducer friktion, vurder operatører og beskyt din plan.", "Gennemgå og juster", "Se hvad der holdt. Ret det der ikke gjorde.", "Langsigtet kontrol", "Gør ti Missioner til en vane der holder.",
    "Start privat", "Det du siger her", "bliver her.", "Din situation og plan bruges aldrig til tilbud, rangeringer eller annoncer.", "Anmod om eksport eller sletning via kontosupport; juridisk opbevaring og sikkerhedskopier kan gælde.", "Ingen Mission beder dig om at indbetale, hente et tilbud eller spille.", "Mission 01 tager cirka", "ét minut.", "Ingen registrering før dit Udgangspunkt er klar.", "Ti lanterner langs en mørk sti, de første tændt — rækkefølge og mål",
  ] },
  "fi-FI": { metadataTitle: "B4GAMBLEn 10 vaiheen Ohjelma", metadataDescription: "Katso, miten kymmenen omaehtoista Tehtävää rakentaa henkilökohtaisen Lähtökohdan ja hallintasuunnitelman.", text: [
    "Ohjelma vaihe vaiheelta", "Kymmenen vaihetta.", "Yksi", "suunnitelma.", "Jokainen Tehtävä kestää 5–15 minuuttia ja päättyy johonkin, jonka säilytät. Näet tarkalleen mitä tapahtuu — ilman yllätyksiä tai pienellä painettua tekstiä.", "Aloita Tehtävä 01", "Miksi B4GAMBLE →", "01–03 Ymmärrä", "04–07 Rakenna", "08–10 Sovella", "Vieritä ↓",
    "Mitä rakennat", "Kolme asiaa, jotka sinulla on lopuksi.", "Selkeä kuva", "Laukaisijasi, mallisi ja hetket, jolloin päätökset todella tapahtuvat.", "Toimivat rajat", "Rajat, jotka suunnittelet, testaat oikeissa viikoissa ja säädät toimiviksi.", "Tarkistettava suunnitelma", "Yksi asiakirja siitä, miten pelaat — voit palata siihen milloin tahansa.", "Polku",
    "Aloita", "Kerro mitä tapahtuu ja saat Lähtökohtasi.", "Aseta rajasi", "Ensimmäinen versio aika- ja raharajoista.", "Ymmärrä laukaisijasi", "Kartoita hetket, jotka aloittavat pelikerrat.", "Rakenna yksi raja", "Yksi raja, jonka voit pitää tällä viikolla.", "Todellisuustarkistus", "Rehellinen katsaus toisen viikon lukuihin.", "Päätösmalli", "Yksinkertainen sääntö kyllä-, ei- ja ei-tänä-iltana -päätöksille.", "Pelisuunnitelma", "Kirjoita suunnitelma, jota todella noudatat.", "Pelaa hallitummin", "Vähennä kitkaa, arvioi toimijoita ja suojaa suunnitelmasi.", "Tarkista ja säädä", "Katso mikä piti. Korjaa se mikä ei pitänyt.", "Pitkäaikainen hallinta", "Muuta kymmenen Tehtävää pysyväksi tavaksi.",
    "Aloita yksityisesti", "Se mitä sanot täällä", "pysyy täällä.", "Tilannettasi ja suunnitelmaasi ei koskaan käytetä tarjouksiin, sijoituksiin tai mainoksiin.", "Pyydä vientiä tai poistamista tilituen kautta; lakisääteinen säilytys ja varmuuskopiot voivat koskea tietoja.", "Mikään Tehtävä ei pyydä tallettamaan, lunastamaan tarjousta tai pelaamaan.", "Tehtävä 01 kestää noin", "minuutin.", "Ei rekisteröitymistä ennen kuin Lähtökohtasi on valmis.", "Kymmenen lyhtyä pimeän polun varrella, ensimmäiset sytytettyinä — järjestys ja päämäärä",
  ] },
  "nb-NO": { metadataTitle: "B4GAMBLEs 10-trinnsprogram", metadataDescription: "Se hvordan ti selvstyrte Oppdrag bygger et personlig Utgangspunkt og en kontrollplan.", text: [
    "Programmet, trinn for trinn", "Ti trinn.", "Én", "plan.", "Hvert Oppdrag tar 5–15 minutter og avsluttes med noe du beholder. Her er nøyaktig hva som skjer — uten overraskelser eller liten skrift.", "Start Oppdrag 01", "Hvorfor B4GAMBLE →", "01–03 Forstå", "04–07 Bygg", "08–10 Bruk", "Rull ↓",
    "Det du skal bygge", "Tre ting du har til slutt.", "Et klart bilde", "Utløserne, mønstrene og øyeblikkene der beslutninger faktisk tas.", "Holdbare grenser", "Grenser du utformer, tester i virkelige uker og justerer til de holder.", "En plan som kan vurderes", "Ett dokument om hvordan du spiller — ditt å gå tilbake til når som helst.", "Veien",
    "Kom i gang", "Fortell hva som skjer, og få Utgangspunktet ditt.", "Sett grensene dine", "Et første utkast til tids- og pengegrenser.", "Forstå utløserne dine", "Kartlegg øyeblikkene som starter spilløkter.", "Bygg én grense", "Én grense du kan holde denne uken.", "Virkelighetssjekk", "Et ærlig blikk på tallene i uke to.", "Beslutningsramme", "En enkel regel for ja, nei og ikke-i-kveld.", "Spilleplan", "Skriv planen du faktisk vil følge.", "Spill med mer kontroll", "Reduser friksjon, vurder operatører og beskytt planen din.", "Gjennomgå og juster", "Se hva som holdt. Rett det som ikke gjorde det.", "Langsiktig kontroll", "Gjør ti Oppdrag til en vane som varer.",
    "Start privat", "Det du sier her", "blir her.", "Situasjonen og planen din brukes aldri til tilbud, rangeringer eller annonser.", "Be om eksport eller sletting via kontostøtte; juridisk lagring og sikkerhetskopier kan gjelde.", "Ingen Oppdrag ber deg om å sette inn, hente et tilbud eller spille.", "Oppdrag 01 tar omtrent", "ett minutt.", "Ingen registrering før Utgangspunktet ditt er klart.", "Ti lykter langs en mørk sti, de første tent — rekkefølge og mål",
  ] },
  "en-CA": en,
  "fr-CA": en,
};

export function tenStepsTranslation(locale: SupportedLocale) {
  const translation = catalog[locale];
  if (translation.text.length !== TEN_STEPS_SOURCE_COPY.length) {
    throw new Error(`Incomplete ${locale} 10 Steps translation`);
  }
  return translation;
}
