import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { assertAgentStageProposal, assertHumanCommercialStageTransition } from "../lib/commercial/stage-policy";
import { assertPartnerOperationsCommercialFirewall, PartnerOperationsInputSchema, PartnerOperationsResultSchema, PartnerSafeCrmOperationSchema, validatePartnerOperationsEvidenceReferences } from "../shared/commercial/partner-operations-contract";

const facts = (overrides: Partial<{ qualificationRationale: string | null; nextActionSummary: string | null; evidenceCategories: string[]; applicationStates: string[] }> = {}) => ({ qualificationRationale: null, nextActionSummary: null, evidenceCategories: [], applicationStates: [], ...overrides });
const transition = (target: Parameters<typeof assertHumanCommercialStageTransition>[0]["target"], stageFacts = facts(), reason = "Explicit human decision") => assertHumanCommercialStageTransition({ current: "PROSPECT", target, reason, facts: stageFacts });

test("valid PROSPECT does not imply a relationship", () => assert.doesNotThrow(() => transition("PROSPECT")));
test("QUALIFIED requires rationale and qualification evidence", () => { assert.throws(() => transition("QUALIFIED")); assert.doesNotThrow(() => transition("QUALIFIED", facts({ qualificationRationale: "Fit documented", evidenceCategories: ["QUALIFICATION"] }))); });
test("draft outreach does not establish APPLIED", () => assert.throws(() => transition("APPLIED", facts({ applicationStates: ["DRAFT"] }))));
test("APPLIED requires an actual external action", () => assert.doesNotThrow(() => transition("APPLIED", facts({ applicationStates: ["SENT"], evidenceCategories: ["EXTERNAL_ACTION"] }))));
test("NEGOTIATING requires negotiation evidence", () => { assert.throws(() => transition("NEGOTIATING")); assert.doesNotThrow(() => transition("NEGOTIATING", facts({ evidenceCategories: ["NEGOTIATION"] }))); });
test("APPROVED requires direct approval evidence", () => { assert.throws(() => transition("APPROVED", facts({ evidenceCategories: ["APPLICATION_PATH"] }))); assert.doesNotThrow(() => transition("APPROVED", facts({ evidenceCategories: ["APPROVAL"] }))); });
test("a public affiliate application page cannot imply APPROVED", () => assert.throws(() => transition("APPROVED", facts({ evidenceCategories: ["APPLICATION_PATH", "MARKET_RELEVANCE"] }))));
test("ACTIVE is impossible through ordinary CRM transition", () => assert.throws(() => transition("ACTIVE"), /separate commercial activation authority/));
test("REJECTED requires rejection evidence and ON_HOLD requires reason", () => { assert.throws(() => transition("REJECTED")); assert.doesNotThrow(() => transition("REJECTED", facts({ evidenceCategories: ["REJECTION"] }))); assert.throws(() => transition("ON_HOLD", facts(), "")); });
test("Agent stage proposals exclude APPROVED and ACTIVE", () => { assert.doesNotThrow(() => assertAgentStageProposal("QUALIFIED")); assert.throws(() => assertAgentStageProposal("APPROVED")); assert.throws(() => assertAgentStageProposal("ACTIVE")); });

const validOperation = { operationId: "op-1", idempotencyKey: "case-idempotency-1", type: "CREATE_DRAFT_OUTREACH", payload: { title: "Introduction", draftText: "Truthful draft", channel: "EMAIL", followUpAt: null } };
test("closed safe operation accepts a draft but not fake send/approval/activation", () => {
  assert.equal(PartnerSafeCrmOperationSchema.safeParse(validOperation).success, true);
  for (const type of ["SEND_EMAIL", "SUBMIT_APPLICATION", "SET_APPROVED", "SET_ACTIVE", "ACCEPT_TERMS", "ENABLE_TRACKING"]) assert.equal(PartnerSafeCrmOperationSchema.safeParse({ ...validOperation, type }).success, false);
});
test("strict operation payload rejects arbitrary Prisma fields", () => assert.equal(PartnerSafeCrmOperationSchema.safeParse({ ...validOperation, payload: { ...validOperation.payload, affiliateProgramStatus: "ACTIVE" } }).success, false));
test("strict Partner Operations input rejects private field injection", () => assert.equal(PartnerOperationsInputSchema.safeParse({ request: "Review", opportunity: {}, evidence: [], contacts: [], applications: [], programmeNarrative: "private" }).success, false));
test("commercial firewall rejects vulnerability and Programme inputs", () => { assert.throws(() => assertPartnerOperationsCommercialFirewall({ request: "Use mission answers for partner ranking" })); assert.throws(() => assertPartnerOperationsCommercialFirewall({ request: "Target vulnerable people" })); assert.doesNotThrow(() => assertPartnerOperationsCommercialFirewall({ request: "Review supplied public partner evidence" })); });

const validResult = { agent: "partner-operations", status: "NEEDS_REVIEW", recommendation: "REVIEW", summary: "Evidence remains incomplete.", findings: [{ classification: "UNKNOWN", statement: "GB relevance is unknown.", evidenceIds: [] }], evidenceGaps: [{ claim: "GB relevance", requiredEvidence: "Exact official scope evidence", impact: "Cannot qualify GB relevance" }], qualification: { strategicFit: "UNKNOWN", gbRelevance: "UNKNOWN", applicationAccess: "UNKNOWN", evidenceQuality: "LOW", rationale: "Insufficient evidence", evidenceIds: [] }, nextActions: [{ priority: "NOW", description: "Obtain official evidence" }], stageRecommendation: null, draftApplication: null, draftOutreach: null, followUp: null, detectedResponses: [], commercialTerms: [], activationReadiness: { status: "NOT_READY", summary: "Founder and RFC-015 gates remain outstanding.", evidenceIds: [] }, proposedCrmOperations: [validOperation] };
test("structured Partner Operations output validates", () => assert.equal(PartnerOperationsResultSchema.safeParse(validResult).success, true));
test("detected claims require evidence", () => assert.equal(PartnerOperationsResultSchema.safeParse({ ...validResult, findings: [{ classification: "DETECTED", statement: "Programme exists", evidenceIds: [] }] }).success, false));
test("output evidence references must exist in the CRM snapshot", () => { const result = PartnerOperationsResultSchema.parse({ ...validResult, findings: [{ classification: "DETECTED", statement: "Application path detected", evidenceIds: ["11111111-1111-4111-8111-111111111111"] }] }); assert.throws(() => validatePartnerOperationsEvidenceReferences(result, new Set())); assert.doesNotThrow(() => validatePartnerOperationsEvidenceReferences(result, new Set(["11111111-1111-4111-8111-111111111111"]))); });
test("activation packets are preparation-only", () => { const operation = PartnerSafeCrmOperationSchema.parse({ operationId: "packet-1", idempotencyKey: "packet-key-0001", type: "PREPARE_ACTIVATION_PACKET", payload: { status: "READY_FOR_FOUNDER_REVIEW", summary: "Prepared, not activated", checklist: { founderDecision: "UNKNOWN" }, evidenceIds: [] } }); assert.equal(operation.type, "PREPARE_ACTIVATION_PACKET"); assert.equal(JSON.stringify(operation).includes("ACTIVATED"), false); });

test("commercial implementation has no Programme-domain or public DTO coupling", async () => {
  const repository = await readFile(new URL("../lib/repositories/commercial.repository.ts", import.meta.url), "utf8");
  const provider = await readFile(new URL("../lib/commercial/partner-operations-provider.ts", import.meta.url), "utf8");
  assert.doesNotMatch(repository, /programme|userProgress|help usage/i); assert.doesNotMatch(provider, /from ["'][^"']*programme/i);
});
test("CRM code cannot mutate affiliate runtime authority", async () => { const repository = await readFile(new URL("../lib/repositories/commercial.repository.ts", import.meta.url), "utf8"); assert.doesNotMatch(repository, /affiliateProgram\.(update|create)|affiliateOffer\.(update|create)|affiliateTrackingLink\.(update|create)/); });
test("prospect, child records, runs and operations have durable idempotency constraints", async () => { const schema = await readFile(new URL("../prisma/schema.prisma", import.meta.url), "utf8"); assert.match(schema, /creationIdempotencyKey\s+String\?\s+@unique/); assert.ok((schema.match(/@@unique\(\[opportunityId, idempotencyKey\]\)/g) ?? []).length >= 6); assert.match(schema, /model CommercialAgentOperation[\s\S]*@@unique\(\[idempotencyKey\]\)/); });
test("commercial terms have a required evidence relation and create new records", async () => { const schema = await readFile(new URL("../prisma/schema.prisma", import.meta.url), "utf8"); const repository = await readFile(new URL("../lib/repositories/commercial.repository.ts", import.meta.url), "utf8"); assert.match(schema, /model CommercialTerm[\s\S]*evidenceId\s+String\s+@db\.Uuid/); assert.match(repository, /commercialTerm\.create/); assert.doesNotMatch(repository, /commercialTerm\.upsert/); });
test("stage history records actor, evidence, previous/new stage and reason", async () => { const repository = await readFile(new URL("../lib/repositories/commercial.repository.ts", import.meta.url), "utf8"); assert.match(repository, /previousStage: current\.stage/); assert.match(repository, /newStage: target/); assert.match(repository, /evidenceId: evidenceIds\[0\]/); assert.match(repository, /reason,/); });
test("Analytics copy explicitly refuses fabricated metrics", async () => { const page = await readFile(new URL("../app/admin/(protected)/commercial/analytics/page.tsx", import.meta.url), "utf8"); assert.match(page, /no verified clicks, registrations, FTDs, revenue or commission/i); });
