import { notFound } from "next/navigation";
import Link from "next/link";
import { Badge, Card } from "@/components/ui";
import { AdminPageShell } from "@/components/admin/AdminShell";
import { CommercialDetailActions } from "@/components/admin/commercial/CommercialActions";
import { CommercialNav } from "@/components/admin/commercial/CommercialNav";
import { commercialService } from "@/lib/commercial/commercial-service";

export const dynamic = "force-dynamic";
const date = (value: Date | null) => value ? value.toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" }) : "Not recorded";

export default async function CommercialPartnerDetailPage({ params }: { params: Promise<{ opportunityId: string }> }) {
  const { opportunityId } = await params; const record = await commercialService.get(opportunityId).catch(() => null); if (!record) notFound(); const latestRun = record.agentRuns[0]; const latestPacket = record.activationPackets[0];
  return <AdminPageShell area="commercial" title={record.displayName} intro="Complete internal relationship record. Evidence and human authority remain distinct from public commercial activation." actions={<Link className="button ghost" href="/admin/commercial">Back to pipeline</Link>}>
    <CommercialNav />
    <section className="commercialDetailGrid">
      <Card className="adminPanel"><div className="commercialSectionHead"><div><p className="eyebrow">Overview</p><h2>Identity and operating state</h2></div><Badge tone={record.stage === "APPROVED" ? "warning" : "neutral"}>{record.stage}</Badge></div><dl className="commercialFacts"><div><dt>Legal identity</dt><dd>{record.legalName || "UNKNOWN"}</dd></div><div><dt>Organisation type</dt><dd>{record.organizationType}</dd></div><div><dt>Priority</dt><dd>{record.priority}</dd></div><div><dt>Owner</dt><dd>{record.owner?.name || "Unassigned"}</dd></div><div><dt>Waiting on</dt><dd>{record.waitingOn}</dd></div><div><dt>Next action</dt><dd>{record.nextActionSummary || "Not set"}</dd></div></dl><div className="commercialBoundary"><strong>Activation boundary</strong><p>CRM APPROVED does not activate AffiliateProgram, AffiliateOffer, tracking, or a GB route. No ordinary ACTIVE transition is exposed.</p></div></Card>
      <Card className="adminPanel"><p className="eyebrow">Canonical links</p><h2>Established identities</h2><dl className="commercialFacts"><div><dt>Operator</dt><dd>{record.operator?.legalName || record.operator?.name || "Not linked"}</dd></div><div><dt>Brand</dt><dd>{record.brand?.name || "Not linked"}</dd></div><div><dt>Casino</dt><dd>{record.casino?.title || "Not linked"}</dd></div><div><dt>Affiliate network</dt><dd>{record.affiliateNetwork?.name || "Not linked"}</dd></div><div><dt>Affiliate programme</dt><dd>{record.affiliateProgram ? `${record.affiliateProgram.name} (${record.affiliateProgram.status})` : "Not linked"}</dd></div></dl></Card>
    </section>
    <Card className="adminPanel"><div className="commercialSectionHead"><div><p className="eyebrow">Evidence</p><h2>Claims and provenance</h2></div><Badge>{record.evidence.length}</Badge></div>{record.evidence.length ? <div className="commercialEvidenceList">{record.evidence.map((item) => <article key={item.id}><div><Badge tone={item.classification === "CONTRADICTION" ? "warning" : "neutral"}>{item.classification}</Badge><small>{item.category}</small></div><h3>{item.title}</h3><p>{item.claim}</p><small>{item.sourceType} · observed {date(item.observedAt)} · status {item.status}</small>{item.sourceUrl ? <a href={item.sourceUrl} rel="noreferrer" target="_blank">Open source</a> : null}</article>)}</div> : <div className="commercialEmpty"><h3>No evidence recorded</h3><p className="muted">Material identity, market, approval and terms claims remain UNKNOWN.</p></div>}</Card>
    <section className="commercialDetailGrid">
      <Card className="adminPanel"><div className="commercialSectionHead"><h2>Contacts</h2><Badge>{record.contacts.length}</Badge></div>{record.contacts.length ? record.contacts.map((item) => <div className="commercialLine" key={item.id}><span><strong>{item.name}</strong><small>{item.roleTitle || "Role not recorded"}</small></span><span>{item.businessEmail || "No business email"}</span></div>) : <p className="muted">No bounded B2B contacts recorded.</p>}</Card>
      <Card className="adminPanel"><div className="commercialSectionHead"><h2>Tasks</h2><Badge>{record.tasks.length}</Badge></div>{record.tasks.length ? record.tasks.map((item) => <div className="commercialLine" key={item.id}><span><strong>{item.title}</strong><small>{item.type}</small></span><span>{item.completedAt ? "Completed" : date(item.dueAt)}</span></div>) : <p className="muted">No next-action tasks recorded.</p>}</Card>
    </section>
    <section className="commercialDetailGrid">
      <Card className="adminPanel"><div className="commercialSectionHead"><h2>Application & outreach</h2><Badge>{record.applications.length}</Badge></div>{record.applications.length ? record.applications.map((item) => <article className="commercialDocument" key={item.id}><div><strong>{item.title}</strong><Badge>{item.state}</Badge></div><small>{item.type} · {item.channel}</small>{item.draftText ? <pre>{item.draftText}</pre> : null}</article>) : <p className="muted">No drafts or evidenced external actions.</p>}</Card>
      <Card className="adminPanel"><div className="commercialSectionHead"><h2>Commercial terms</h2><Badge>{record.terms.length}</Badge></div>{record.terms.length ? record.terms.map((item) => <div className="commercialLine" key={item.id}><span><strong>{item.model} · {item.status}</strong><small>Evidence {item.evidenceId.slice(0, 8)}…</small></span><span>{item.amount ? `${item.currency || ""} ${item.amount}` : item.percentage ? `${item.percentage}%` : "Unquantified"}</span></div>) : <p className="muted">No evidenced terms. Missing values are not filled with assumptions.</p>}</Card>
    </section>
    <Card className="adminPanel"><div className="commercialSectionHead"><div><p className="eyebrow">Partner Operations</p><h2>Last bounded run</h2></div>{latestRun ? <Badge>{latestRun.status}</Badge> : <Badge>NOT RUN</Badge>}</div>{latestRun ? <><p>{latestRun.summary}</p><dl className="commercialFacts"><div><dt>Recommendation</dt><dd>{latestRun.recommendation}</dd></div><div><dt>Model route</dt><dd>{latestRun.modelTier || "Not invoked"}</dd></div><div><dt>Operations</dt><dd>{latestRun.appliedOperationCount} applied / {latestRun.rejectedOperationCount} rejected</dd></div><div><dt>Run time</dt><dd>{date(latestRun.completedAt)}</dd></div></dl></> : <p className="muted">The CRM is fully usable without the provider. A live run requires an existing server-side credential.</p>}</Card>
    <Card className="adminPanel"><div className="commercialSectionHead"><div><p className="eyebrow">Activation readiness</p><h2>Preparation only</h2></div><Badge tone={latestPacket?.status === "READY_FOR_FOUNDER_REVIEW" ? "warning" : "neutral"}>{latestPacket?.status || "NOT_PREPARED"}</Badge></div><p>{latestPacket?.summary || "No activation packet exists. RFC-015 remains the independent runtime authority."}</p><div className="commercialBoundary"><strong>No activation control</strong><p>Preparation cannot set CRM ACTIVE, change an affiliate record, enable tracking, or publish a route.</p></div></Card>
    <Card className="adminPanel"><p className="eyebrow">Auditable actions</p><h2>Evidence, human decisions, and Agent review</h2><CommercialDetailActions opportunityId={record.id} evidence={record.evidence.map((item) => ({ id: item.id, title: item.title, category: item.category }))} /></Card>
    <Card className="adminPanel"><div className="commercialSectionHead"><h2>Activity timeline</h2><Badge>{record.activities.length}</Badge></div>{record.activities.length ? <ol className="commercialTimeline">{record.activities.map((item) => <li key={item.id}><span>{date(item.occurredAt)}</span><div><strong>{item.summary}</strong><small>{item.actorKind} · {item.type}{item.reason ? ` · ${item.reason}` : ""}</small></div></li>)}</ol> : <p className="muted">No activity has been recorded.</p>}</Card>
  </AdminPageShell>;
}
