import { randomUUID } from "node:crypto";

import { z } from "zod";
import { commercialRepository } from "@/lib/repositories/commercial.repository";
import { assertHumanCommercialStageTransition, CommercialStagePolicyError } from "@/lib/commercial/stage-policy";
import { NotFoundError, ValidationError } from "@/lib/services/service-error";
import { PartnerOperationsResultSchema, validatePartnerOperationsEvidenceReferences, type PartnerOperationsResult } from "@/shared/commercial/partner-operations-contract";

const CreateProspectSchema = z.object({ displayName: z.string().min(1).max(200), legalName: z.string().max(200).nullable().optional(), organizationType: z.enum(["DIRECT_OPERATOR", "AFFILIATE_NETWORK", "GROUP", "PLATFORM", "OTHER"]).default("OTHER"), priority: z.enum(["LOW", "MEDIUM", "HIGH", "URGENT"]).default("MEDIUM"), possibleDuplicateOfId: z.string().uuid().nullable().optional(), idempotencyKey: z.string().min(8).max(160).optional() }).strict();
const EvidenceSchema = z.object({ sourceType: z.enum(["PUBLIC_WEB", "OFFICIAL_OPERATOR_SOURCE", "REGULATOR_SOURCE", "EMAIL", "APPLICATION_PORTAL", "AGREEMENT", "INTERNAL_RECORD", "OTHER"]), sourceAuthority: z.enum(["REGULATOR_OFFICIAL", "ORGANISATION_OFFICIAL", "DIRECT_INTERNAL_RECORD", "OTHER"]).nullable().default(null), classification: z.enum(["DETECTED", "INFERRED", "PROPOSED", "UNKNOWN", "CONTRADICTION"]), category: z.enum(["IDENTITY", "MARKET_RELEVANCE", "APPLICATION_PATH", "QUALIFICATION", "EXTERNAL_ACTION", "DUE_DILIGENCE", "NEGOTIATION", "APPROVAL", "REJECTION", "COMMERCIAL_TERMS", "CONTACT", "ACTIVATION", "FOUNDER_DECISION", "OTHER"]), sourceUrl: z.url().nullable().default(null), sourceReference: z.string().max(500).nullable().default(null), title: z.string().min(1).max(200), claim: z.string().min(1).max(2_000), notes: z.string().max(2_000).nullable().default(null), observedAt: z.iso.datetime({ offset: true }).nullable().default(null), recheckAt: z.iso.datetime({ offset: true }).nullable().default(null), idempotencyKey: z.string().min(8).max(160).optional() }).strict().superRefine((value, context) => { if (value.sourceType === "PUBLIC_WEB" && !value.observedAt) context.addIssue({ code: "custom", message: "Public-web commercial evidence requires observedAt.", path: ["observedAt"] }); });

function asValidationError(error: unknown): never {
  if (error instanceof z.ZodError) throw new ValidationError("Commercial input is invalid", { issues: z.treeifyError(error) });
  if (error instanceof CommercialStagePolicyError) throw new ValidationError(error.message);
  throw error;
}

async function assertOwnedEvidence(opportunityId: string, evidenceId: string | null | undefined) {
  if (!evidenceId) return;
  const record = await commercialRepository.findById(opportunityId);
  if (!record || !record.evidence.some((item) => item.id === evidenceId)) throw new ValidationError("Evidence must belong to this commercial opportunity.");
}

export const commercialService = {
  list: commercialRepository.list,
  async get(id: string) { const record = await commercialRepository.findById(id); if (!record) throw new NotFoundError("Commercial opportunity", { id }); return record; },
  async createProspect(value: unknown, actorId: string) { try { const input = CreateProspectSchema.parse(value); return await commercialRepository.createProspect({ ...input, idempotencyKey: input.idempotencyKey ?? `human:${randomUUID()}` }, actorId); } catch (error) { return asValidationError(error); } },
  async updateProfile(opportunityId: string, value: unknown, actorId: string) { try { const input = z.object({ strategicFit: z.string().max(2_000).nullable().optional(), marketRelevance: z.string().max(2_000).nullable().optional(), productFit: z.string().max(2_000).nullable().optional(), integrationBurden: z.string().max(2_000).nullable().optional(), qualificationRationale: z.string().max(2_000).nullable().optional(), commercialNotes: z.string().max(4_000).nullable().optional(), riskNotes: z.string().max(2_000).nullable().optional(), nextActionSummary: z.string().max(1_000).nullable().optional(), nextActionDueAt: z.iso.datetime({ offset: true }).nullable().optional(), waitingOn: z.enum(["NONE", "INTERNAL_ACTION", "EXTERNAL_PARTY", "EVIDENCE", "FOUNDER_DECISION"]).optional() }).strict().parse(value); return await commercialRepository.updateProfile(opportunityId, { ...input, nextActionDueAt: input.nextActionDueAt ? new Date(input.nextActionDueAt) : null }, actorId); } catch (error) { return asValidationError(error); } },
  async addEvidence(opportunityId: string, value: unknown, actorId: string) { try { await this.get(opportunityId); const input = EvidenceSchema.parse(value); return await commercialRepository.addEvidence(opportunityId, input, actorId, input.idempotencyKey ?? `human:${randomUUID()}`); } catch (error) { return asValidationError(error); } },
  async transition(opportunityId: string, value: unknown, actorId: string) {
    try {
      const input = z.object({ target: z.enum(["PROSPECT", "QUALIFIED", "APPLICATION_READY", "APPLIED", "DUE_DILIGENCE", "NEGOTIATING", "APPROVED", "REJECTED", "ON_HOLD"]), reason: z.string().min(1).max(2_000), evidenceIds: z.array(z.string().uuid()).max(10).default([]) }).strict().parse(value);
      const record = await this.get(opportunityId);
      const ownedEvidence = new Set(record.evidence.map((item) => item.id));
      if (input.evidenceIds.some((id) => !ownedEvidence.has(id))) throw new ValidationError("Stage evidence must belong to this opportunity.");
      assertHumanCommercialStageTransition({ current: record.stage, target: input.target, reason: input.reason, facts: { qualificationRationale: record.qualificationRationale, nextActionSummary: record.nextActionSummary, evidenceCategories: record.evidence.filter((item) => input.evidenceIds.includes(item.id)).map((item) => item.category), applicationStates: record.applications.map((item) => item.state) } });
      return await commercialRepository.transitionStage(opportunityId, input.target, input.reason, input.evidenceIds, actorId);
    } catch (error) { return asValidationError(error); }
  },
  async addContact(opportunityId: string, value: unknown, actorId: string) { try { const input = z.object({ name: z.string().min(1).max(200), roleTitle: z.string().max(200).nullable().optional(), businessEmail: z.email().nullable().optional(), businessPhone: z.string().max(80).nullable().optional(), organizationName: z.string().max(200).nullable().optional(), operationalNotes: z.string().max(2_000).nullable().optional(), evidenceId: z.string().uuid().nullable().optional(), idempotencyKey: z.string().min(8).max(160).optional() }).strict().parse(value); await assertOwnedEvidence(opportunityId, input.evidenceId); return await commercialRepository.addContact(opportunityId, input, actorId, input.idempotencyKey ?? `human:${randomUUID()}`); } catch (error) { return asValidationError(error); } },
  async addApplication(opportunityId: string, value: unknown, actorId: string) { try { const input = z.object({ type: z.enum(["APPLICATION", "OUTREACH"]), channel: z.enum(["EMAIL", "APPLICATION_PORTAL", "WEB_FORM", "MEETING", "OTHER"]), state: z.enum(["DRAFT", "PREPARED", "SUBMITTED", "SENT"]), title: z.string().min(1).max(200), draftText: z.string().max(12_000).nullable().optional(), evidenceId: z.string().uuid().nullable().optional(), followUpAt: z.iso.datetime({ offset: true }).nullable().optional(), idempotencyKey: z.string().min(8).max(160).optional() }).strict().parse(value); if (["SUBMITTED", "SENT"].includes(input.state) && !input.evidenceId) throw new ValidationError("External application/outreach states require evidence."); await assertOwnedEvidence(opportunityId, input.evidenceId); return await commercialRepository.addApplication(opportunityId, { ...input, followUpAt: input.followUpAt ? new Date(input.followUpAt) : null }, actorId, input.idempotencyKey ?? `human:${randomUUID()}`); } catch (error) { return asValidationError(error); } },
  async addTerm(opportunityId: string, value: unknown, actorId: string) { try { const input = z.object({ evidenceId: z.string().uuid(), model: z.enum(["CPA", "REV_SHARE", "HYBRID", "OTHER"]), status: z.enum(["PROPOSED", "RECEIVED", "CONFIRMED", "SUPERSEDED"]), amount: z.number().nonnegative().nullable().optional(), percentage: z.number().min(0).max(100).nullable().optional(), currency: z.string().length(3).nullable().optional(), notes: z.string().max(2_000).nullable().optional(), supersedesTermId: z.string().uuid().nullable().optional(), idempotencyKey: z.string().min(8).max(160).optional() }).strict().parse(value); await assertOwnedEvidence(opportunityId, input.evidenceId); return await commercialRepository.addTerm(opportunityId, input, actorId, input.idempotencyKey ?? `human:${randomUUID()}`); } catch (error) { return asValidationError(error); } },
  async addTask(opportunityId: string, value: unknown, actorId: string) { try { const input = z.object({ type: z.enum(["RESEARCH", "EVIDENCE_GAP", "APPLICATION", "OUTREACH", "FOLLOW_UP", "DUE_DILIGENCE", "NEGOTIATION", "ACTIVATION", "OTHER"]), title: z.string().min(1).max(500), dueAt: z.iso.datetime({ offset: true }).nullable().optional(), idempotencyKey: z.string().min(8).max(160).optional() }).strict().parse(value); return await commercialRepository.addTask(opportunityId, { ...input, dueAt: input.dueAt ? new Date(input.dueAt) : null }, actorId, input.idempotencyKey ?? `human:${randomUUID()}`); } catch (error) { return asValidationError(error); } },
  async applyPartnerOperations(opportunityId: string, value: unknown, actorId: string, metadata: { idempotencyKey: string; model?: string; modelTier?: string; providerInvoked: boolean; usage?: { inputTokens: number; outputTokens: number; totalTokens: number; requests: number } }) {
    try { const result = PartnerOperationsResultSchema.parse(value); const record = await this.get(opportunityId); validatePartnerOperationsEvidenceReferences(result, new Set(record.evidence.map((item) => item.id))); return await commercialRepository.applyPartnerOperations({ opportunityId, result, actorId, runIdempotencyKey: metadata.idempotencyKey, model: metadata.model, modelTier: metadata.modelTier, providerInvoked: metadata.providerInvoked, usage: metadata.usage }); } catch (error) { return asValidationError(error); }
  },
};

export type { PartnerOperationsResult };
