import type { Metadata } from "next";
import Link from "next/link";
import { absoluteUrl } from "@/lib/site";
import styles from "./FAQPage.module.css";

export const metadata:Metadata={title:"B4GAMBLE FAQ",description:"Clear answers about B4GAMBLE.",alternates:{ canonical: absoluteUrl("/faq") }};
const groups=[
  ["About B4GAMBLE",[["What is B4GAMBLE?","Three things in one product: a free private control Programme, independent casino research funded by real-money testing, and openly commercial discovery pages (Best Offers, Casinos, Bonuses) for people who have decided to play."],["Who writes the reviews?","The editorial team that runs the tests. Nobody on the commercial side edits reviews, and no review is sponsored or ghost-written by an operator."]]],
  ["Programme",[["Is the Programme really free?","Yes — free now and always, with no paywall or upsell inside missions. It exists because a trustworthy site needs to be more than a funnel."],["Who can see what I say in the Programme?","Only you and the systems that generate your plan. Programme and Help data is never used for offers, rankings, ads or any commercial purpose, and you can delete everything in one action."],["Do I need an account to start?","No. You speak or type your situation first; registration with Google comes only after your Starting Point is ready, so you can save it."]]],
  ["Casinos & Offers",[["How do you test casinos?","Ordinary accounts, our own money, at least four weeks per casino: three withdrawal methods, terms transcribed line by line, support tested at unsociable hours. The full procedure is on the Methodology page."],["Why do some casinos say “Review only”?","It means we can’t offer a governed signup route right now, so we don’t fake one. The review and test results stay available."],["What happens when I click View Offer?","A short confirmation that you’re leaving B4GAMBLE, with the commission disclosure — then you continue to the operator, or stay."]]],
  ["Commercial model",[["How does B4GAMBLE make money?","We may earn a commission when you sign up at a casino through our links. That’s the whole model — no paid placements, no sponsored scores, no selling data."],["Does commission affect rankings?","No. Scores are locked before commercial terms are discussed, and several casinos we earn nothing from outrank ones we do. See the Affiliate Disclosure."]]],
  ["Help & Privacy",[["What is protected Help?","A commercial-free space with immediate actions — pause, self-exclusion, access controls — and human support. Nothing you do there is used commercially."],["How do I delete my data?","One action in your Programme settings removes your situation, plan and history. Legal record-keeping obligations aside, gone means gone."]]],
] as const;
export default function FAQPage(){return <article className={styles.page}><header><div><p><span aria-hidden="true" />FAQ</p><h1>Clear <em>answers.</em></h1></div></header><div className={styles.paint} /><main>{groups.map(([name,items],groupIndex)=><section key={name}><h2>{name}</h2><div>{items.map(([q,a],index)=><details key={q} open={groupIndex===0&&index===0}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>)}<aside className={styles.contactRail}><span>Didn&apos;t find it?</span><Link href="/contact">Contact us →</Link><Link href="/methodology">Methodology</Link><Link href="/affiliate-disclosure">Affiliate Disclosure</Link></aside></main></article>}
