"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";

async function postJson(url: string, body: unknown) {
  const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const result = await response.json() as { ok?: boolean; error?: string; record?: { id?: string } };
  if (!response.ok || !result.ok) throw new Error(result.error || "The commercial operation failed.");
  return result;
}

export function CommercialCreateProspectForm() {
  const router = useRouter(); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setMessage(null); const form = new FormData(event.currentTarget);
    try { const result = await postJson("/api/admin/commercial/opportunities", { displayName: form.get("displayName"), legalName: form.get("legalName") || null, organizationType: form.get("organizationType"), priority: form.get("priority") }); event.currentTarget.reset(); router.push(`/admin/commercial/partners/${result.record?.id}`); router.refresh(); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create prospect."); } finally { setBusy(false); }
  }
  return <form className="commercialInlineForm" onSubmit={submit}>
    <label>Display name<input required name="displayName" maxLength={200} /></label>
    <label>Legal name, if known<input name="legalName" maxLength={200} /></label>
    <label>Organisation type<select name="organizationType" defaultValue="OTHER"><option>DIRECT_OPERATOR</option><option>AFFILIATE_NETWORK</option><option>GROUP</option><option>PLATFORM</option><option>OTHER</option></select></label>
    <label>Priority<select name="priority" defaultValue="MEDIUM"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select></label>
    <button className="button gold" disabled={busy}>{busy ? "Creating…" : "Create prospect"}</button>{message ? <p className="adminFormError" role="alert">{message}</p> : null}
  </form>;
}

export function CommercialDetailActions({ opportunityId, evidence }: { opportunityId: string; evidence: Array<{ id: string; title: string; category: string }> }) {
  const router = useRouter(); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false); const endpoint = `/api/admin/commercial/opportunities/${opportunityId}`;
  async function act(action: string, payload: unknown) { setBusy(true); setMessage(null); try { await postJson(endpoint, { action, payload }); setMessage("Saved."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save."); } finally { setBusy(false); } }
  async function addEvidence(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await act("add_evidence", { sourceType: form.get("sourceType"), sourceAuthority: null, classification: form.get("classification"), category: form.get("category"), sourceUrl: form.get("sourceUrl") || null, sourceReference: null, title: form.get("title"), claim: form.get("claim"), notes: null, observedAt: form.get("observedAt") ? new Date(String(form.get("observedAt"))).toISOString() : null, recheckAt: null }); }
  async function transition(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const evidenceId = String(form.get("evidenceId") || ""); await act("transition_stage", { target: form.get("target"), reason: form.get("reason"), evidenceIds: evidenceId ? [evidenceId] : [] }); }
  async function updateProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await act("update_profile", { strategicFit: form.get("strategicFit") || null, marketRelevance: form.get("marketRelevance") || null, qualificationRationale: form.get("qualificationRationale") || null, nextActionSummary: form.get("nextActionSummary") || null, nextActionDueAt: form.get("nextActionDueAt") ? new Date(String(form.get("nextActionDueAt"))).toISOString() : null, waitingOn: form.get("waitingOn") }); }
  async function addContact(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await act("add_contact", { name: form.get("name"), roleTitle: form.get("roleTitle") || null, businessEmail: form.get("businessEmail") || null, organizationName: form.get("organizationName") || null, evidenceId: form.get("evidenceId") || null }); }
  async function addTask(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await act("add_task", { type: form.get("taskType"), title: form.get("taskTitle"), dueAt: form.get("taskDueAt") ? new Date(String(form.get("taskDueAt"))).toISOString() : null }); }
  async function addApplication(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await act("add_application", { type: form.get("applicationType"), channel: form.get("channel"), state: form.get("applicationState"), title: form.get("applicationTitle"), draftText: form.get("draftText") || null, evidenceId: form.get("applicationEvidenceId") || null }); }
  async function addTerm(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const amount = String(form.get("amount") || ""); const percentage = String(form.get("percentage") || ""); await act("add_term", { evidenceId: form.get("termEvidenceId"), model: form.get("termModel"), status: form.get("termStatus"), amount: amount ? Number(amount) : null, percentage: percentage ? Number(percentage) : null, currency: form.get("currency") || null, notes: form.get("termNotes") || null }); }
  async function runAgent() { setBusy(true); setMessage(null); try { await postJson(`${endpoint}/partner-operations`, { request: "Review current evidence, identify gaps, and prepare the safest next internal actions." }); setMessage("Partner Operations completed and bounded operations were applied."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Partner Operations failed safely."); } finally { setBusy(false); } }
  return <div className="commercialActionGrid">
    <form className="commercialInlineForm" onSubmit={updateProfile}><h3>Operating profile</h3><label>Strategic fit<textarea name="strategicFit" rows={2} /></label><label>Market relevance<textarea name="marketRelevance" rows={2} /></label><label>Qualification rationale<textarea name="qualificationRationale" rows={2} /></label><label>Next action<input name="nextActionSummary" /></label><label>Due at<input name="nextActionDueAt" type="datetime-local" /></label><label>Waiting on<select name="waitingOn"><option>NONE</option><option>INTERNAL_ACTION</option><option>EXTERNAL_PARTY</option><option>EVIDENCE</option><option>FOUNDER_DECISION</option></select></label><button className="button" disabled={busy}>Save profile</button></form>
    <form className="commercialInlineForm" onSubmit={addEvidence}><h3>Add evidence</h3><label>Title<input name="title" required /></label><label>Claim<textarea name="claim" required rows={3} /></label><label>Source type<select name="sourceType"><option>PUBLIC_WEB</option><option>OFFICIAL_OPERATOR_SOURCE</option><option>REGULATOR_SOURCE</option><option>EMAIL</option><option>APPLICATION_PORTAL</option><option>AGREEMENT</option><option>INTERNAL_RECORD</option><option>OTHER</option></select></label><label>Classification<select name="classification"><option>DETECTED</option><option>INFERRED</option><option>PROPOSED</option><option>UNKNOWN</option><option>CONTRADICTION</option></select></label><label>Category<select name="category"><option>IDENTITY</option><option>MARKET_RELEVANCE</option><option>APPLICATION_PATH</option><option>QUALIFICATION</option><option>EXTERNAL_ACTION</option><option>DUE_DILIGENCE</option><option>NEGOTIATION</option><option>APPROVAL</option><option>REJECTION</option><option>COMMERCIAL_TERMS</option><option>CONTACT</option><option>ACTIVATION</option><option>OTHER</option></select></label><label>Source URL<input name="sourceUrl" type="url" /></label><label>Observed at<input name="observedAt" type="datetime-local" /></label><button className="button gold" disabled={busy}>Record evidence</button></form>
    <form className="commercialInlineForm" onSubmit={transition}><h3>Human stage decision</h3><p className="muted">Server policy checks the evidence and transition semantics. ACTIVE is unavailable here.</p><label>Target<select name="target"><option>PROSPECT</option><option>QUALIFIED</option><option>APPLICATION_READY</option><option>APPLIED</option><option>DUE_DILIGENCE</option><option>NEGOTIATING</option><option>APPROVED</option><option>REJECTED</option><option>ON_HOLD</option></select></label><label>Supporting evidence<select name="evidenceId"><option value="">None</option>{evidence.map((item) => <option value={item.id} key={item.id}>{item.category} — {item.title}</option>)}</select></label><label>Reason<textarea name="reason" required rows={3} /></label><button className="button" disabled={busy}>Validate and record</button></form>
    <form className="commercialInlineForm" onSubmit={addContact}><h3>Add B2B contact</h3><label>Name<input name="name" required /></label><label>Role/title<input name="roleTitle" /></label><label>Business email<input name="businessEmail" type="email" /></label><label>Organisation<input name="organizationName" /></label><label>Source evidence<select name="evidenceId"><option value="">None</option>{evidence.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label><button className="button" disabled={busy}>Add contact</button></form>
    <form className="commercialInlineForm" onSubmit={addTask}><h3>Create task</h3><label>Type<select name="taskType"><option>RESEARCH</option><option>EVIDENCE_GAP</option><option>APPLICATION</option><option>OUTREACH</option><option>FOLLOW_UP</option><option>DUE_DILIGENCE</option><option>NEGOTIATION</option><option>ACTIVATION</option><option>OTHER</option></select></label><label>Task<input name="taskTitle" required /></label><label>Due at<input name="taskDueAt" type="datetime-local" /></label><button className="button" disabled={busy}>Create task</button></form>
    <form className="commercialInlineForm" onSubmit={addApplication}><h3>Application / outreach</h3><label>Type<select name="applicationType"><option>APPLICATION</option><option>OUTREACH</option></select></label><label>Channel<select name="channel"><option>EMAIL</option><option>APPLICATION_PORTAL</option><option>WEB_FORM</option><option>MEETING</option><option>OTHER</option></select></label><label>State<select name="applicationState"><option>DRAFT</option><option>PREPARED</option><option>SUBMITTED</option><option>SENT</option></select></label><label>Title<input name="applicationTitle" required /></label><label>Draft/reference<textarea name="draftText" rows={3} /></label><label>External-action evidence<select name="applicationEvidenceId"><option value="">None</option>{evidence.map((item) => <option value={item.id} key={item.id}>{item.category} — {item.title}</option>)}</select></label><button className="button" disabled={busy}>Record item</button></form>
    <form className="commercialInlineForm" onSubmit={addTerm}><h3>Record evidenced terms</h3><label>Evidence<select name="termEvidenceId" required><option value="">Select evidence</option>{evidence.map((item) => <option value={item.id} key={item.id}>{item.category} — {item.title}</option>)}</select></label><label>Model<select name="termModel"><option>CPA</option><option>REV_SHARE</option><option>HYBRID</option><option>OTHER</option></select></label><label>Status<select name="termStatus"><option>PROPOSED</option><option>RECEIVED</option><option>CONFIRMED</option><option>SUPERSEDED</option></select></label><label>Amount<input name="amount" type="number" min="0" step="0.01" /></label><label>Percentage<input name="percentage" type="number" min="0" max="100" step="0.01" /></label><label>Currency<input name="currency" maxLength={3} placeholder="GBP" /></label><label>Notes<textarea name="termNotes" rows={2} /></label><button className="button" disabled={busy}>Record terms</button></form>
    <div className="commercialInlineForm"><h3>Partner Operations</h3><p className="muted">Runs a strict, no-tools structured analysis. It may add drafts, notes, tasks and preparation records only.</p><button className="button" type="button" onClick={runAgent} disabled={busy}>Run bounded review</button></div>
    {message ? <p className={message === "Saved." ? "muted" : "adminFormError"} role="status">{message}</p> : null}
  </div>;
}
