import {
  learningArticles,
  learningCategories,
  type LearningArticle,
  type LearningCategory,
  type LearningDifficulty,
} from "@/lib/learning-center";
import type { SupportedLocale } from "@/lib/market/registry";

type EuropeanLocale = Exclude<SupportedLocale, "en-CA" | "fr-CA" | "es-PE">;

const HUB_SOURCE = [
  "Guides & insights", "Learn.", "Play smarter.", "Plain answers to the questions the industry prefers you didn't ask.",
  "Written by the team that runs the tests", "Educational guides · commercial links disclosed", "Publication dates shown on every guide",
  "Start here", "Four guides that answer 80% of questions", "All guides", "Search guides", "guides", "All topics", "Bonuses", "Banking", "Casinos", "Games", "Responsible play", "Industry", "Read →",
  "Beyond reading", "Knowledge is half of it.", "The plan is the other half.", "Ten missions that turn what you've read into boundaries that hold. Free to use. Privacy explained.", "Start Programme",
] as const;

type ArticleCopy = readonly [title: string, summary: string];
type LearningTemplate = Readonly<{
  takeaways: readonly [string, string, string];
  sections: readonly [readonly [string, string], readonly [string, string], readonly [string, string]];
  examples: readonly [string, string];
  callout: readonly [string, string];
  faq: readonly [readonly [string, string], readonly [string, string]];
}>;
type LearningUi = Readonly<{
  metadataTitle: string; metadataDescription: string; learningGuide: string; home: string; learn: string; learningCenter: string;
  breadcrumb: string; neutralArticle: string; author: string; editor: string; updated: string; readingTime: string;
  directAnswer: string; onThisPage: string; workedExamples: string; putInContext: string; sourceStatus: string;
  evidenceState: string; sourceUnavailable: string; noClaimSource: string; sourceUnavailableCopy: string;
  questions: string; readLimits: string; relatedReading: string; continueContext: string;
  optionalTransition: string; afterAnswer: string; applyChecklist: string; comparisonCopy: string; compareCasinos: string; commercialDisclosure: string;
  controlSupport: string; neutralNextStep: string; responsibleNoTransition: string; exploreResponsible: string; openHelp: string;
  searchPlaceholder: string; oneShown: string; manyShown: string; noneShown: string;
  difficulty: Readonly<Record<LearningDifficulty, string>>;
}>;
type Pack = Readonly<{ categories: readonly string[]; articles: readonly ArticleCopy[]; hub: readonly string[]; template: LearningTemplate; ui: LearningUi }>;

const enTemplate: LearningTemplate = {
  takeaways: ["Start with the concept before comparing casino offers.", "Use B4GAMBLE methodology and responsible gambling context together.", "Review current operator terms before registering or depositing."],
  sections: [["What this topic covers", "{{title}} explains the core ideas a reader should understand before relying on casino comparisons, bonus pages, or operator information."], ["Why it matters", "Casino information can be fragmented or promotional. A structured guide helps readers compare terms, risks, and practical details in a calmer way."], ["How to use it on B4GAMBLE", "Read the guide, follow related category links, review the methodology, and use the 10-Step Program or self-check when decisions feel unclear."]],
  examples: ["A reader checks the glossary term first, then opens a detailed guide and a related casino review.", "A reader compares the concept against their own budget, time limit, and local availability before continuing."],
  callout: ["Editorial note", "This article is educational. It does not guarantee outcomes, operator conduct, withdrawals, or dispute results."],
  faq: [["Is this advice?", "No. This is educational information designed to support clearer comparison and decision-making."], ["Where should I go next?", "Use the related articles and learning paths at the end of the guide."]],
};

const enUi: LearningUi = {
  metadataTitle: "Learn | B4GAMBLE", metadataDescription: "Plain-language guides to casino bonuses, banking, games, reviews and responsible play.", learningGuide: "Learning Guide | B4GAMBLE", home: "Home", learn: "Learn", learningCenter: "Learning Center", breadcrumb: "Breadcrumb", neutralArticle: "Neutral learning article", author: "Author", editor: "Editor", updated: "Updated", readingTime: "Reading time", directAnswer: "Direct answer", onThisPage: "On this page", workedExamples: "Worked examples", putInContext: "PUT THE IDEA INTO CONTEXT.", sourceStatus: "Source status", evidenceState: "Evidence state", sourceUnavailable: "SOURCE STATUS: UNAVAILABLE.", noClaimSource: "No claim-level source record is included.", sourceUnavailableCopy: "The current Learning article model does not provide source links, a source owner, a review-due date or a compliance-review status. This page therefore makes no ‘verified’ or compliance-reviewed claim.", questions: "Questions", readLimits: "READ THE LIMITS TOO.", relatedReading: "Related reading", continueContext: "CONTINUE WITH CONTEXT.", optionalTransition: "Optional comparison transition", afterAnswer: "After the educational answer", applyChecklist: "READY TO APPLY THE CHECKLIST?", comparisonCopy: "Compare current B4GAMBLE records only when the educational context is clear. This is an internal navigation link, not a personalised recommendation.", compareCasinos: "Compare casinos", commercialDisclosure: "Commercial disclosure: B4GAMBLE may receive compensation from some outbound links reached later. Rankings remain editorial.", controlSupport: "Control and support", neutralNextStep: "KEEP THE NEXT STEP NEUTRAL.", responsibleNoTransition: "This responsible-gambling learning article does not transition into casino, bonus or comparison content.", exploreResponsible: "Explore Responsible Gambling", openHelp: "Open protected Help", searchPlaceholder: "Search guides — wagering, payouts, RTP…", oneShown: "guide shown.", manyShown: "guides shown.", noneShown: "No guides match. Clear the search or choose All topics.", difficulty: { Beginner: "Beginner", Intermediate: "Intermediate", Advanced: "Advanced" },
};

const categoriesEn = learningCategories.map((category) => category.title);
const articlesEn = learningArticles.map((article) => [article.title, article.summary] as const);

const de: Pack = {
  categories: ["Grundlagen zu Glücksspielanbietern", "Glücksspielboni", "Verantwortungsvolles Spielen", "Anbieterbewertungen", "Anbietersicherheit", "Zahlungen", "Lizenzen", "Spielanleitungen", "Sportwetten-Grundlagen", "Krypto-Glücksspielanbieter", "Länderleitfäden", "Glücksspielglossar", "Branchennachrichten"],
  articles: [
    ["Online-Grundlagen zu Glücksspielanbietern", "Ein verständlicher Einstieg in Konten, Bedingungen, Spiele, Zahlungen und Vergleichspunkte."],
    ["So funktionieren Willkommensbonus-Bedingungen", "Verstehe Umsatzanforderungen, Ablauf, Spielbeiträge, Höchsteinsätze und Auszahlungseinschränkungen."],
    ["Werkzeuge für verantwortungsvolles Spielen erklärt", "So können Einzahlungslimits, Sitzungshinweise, Pausen und Selbstausschluss funktionieren."],
    ["So funktionieren Anbieterbewertungen", "Ein Leitfaden zu redaktioneller Bewertung, Kriterien, Einschränkungen und verantwortungsvollem Vergleich."],
    ["Checkliste zur Anbietersicherheit", "Eine praktische Prüfung von Lizenzen, Bedingungen, Zahlungen, Sicherheit und Supportinformationen."],
    ["Zahlungsmethoden bei Glücksspielanbietern erklärt", "Vergleiche Ein- und Auszahlungen, Verifizierung, Bearbeitungszeiten, Gebühren und Währungen."],
    ["Lizenzen von Glücksspielanbietern erklärt", "Was Lizenzen anzeigen können, was sie nicht beweisen und welche Angaben zu prüfen sind."],
    ["RTP und Volatilität erklärt", "Verstehe zwei geläufige Spielbegriffe und warum sie keine Ergebnisgarantie sind."],
    ["Grundlagen zu Sportwettenquoten", "Eine nicht werbliche Einführung in Quotenformate, implizite Wahrscheinlichkeit und Wettbegriffe."],
    ["Krypto-Zahlungen bei Glücksspielanbietern", "Verstehe Krypto-Einzahlungen, Auszahlungen, Wallets, Volatilität und Einschränkungen."],
    ["So sind Länderleitfäden zu Glücksspielanbietern zu lesen", "Nutze Angaben zu Verfügbarkeit, Zahlungen und Lizenzen auf Länderebene verantwortungsvoll."],
    ["Einstieg ins Glücksspielglossar", "Grundbegriffe wie Umsatzanforderung, KYC, RTP, Volatilität und Selbstausschluss."],
    ["So liest du Nachrichten aus der Glücksspielbranche", "Ordne regulatorische Meldungen und Anbieterankündigungen ein und prüfe sie anhand von Quellen."],
  ],
  hub: ["Leitfäden & Einblicke", "Lernen.", "Klüger spielen.", "Klare Antworten auf Fragen, die die Branche lieber nicht hört.", "Vom Team hinter den Prüfungen", "Bildungsleitfäden · kommerzielle Links offengelegt", "Veröffentlichungsdatum bei jedem Leitfaden", "Hier starten", "Vier Leitfäden für 80 % der Fragen", "Alle Leitfäden", "Leitfäden durchsuchen", "Leitfäden", "Alle Themen", "Boni", "Zahlungen", "Glücksspielanbieter", "Spiele", "Verantwortungsvolles Spielen", "Branche", "Lesen →", "Mehr als Lesen", "Wissen ist die eine Hälfte.", "Der Plan ist die andere.", "Zehn Missionen machen aus Wissen tragfähige Grenzen. Kostenlos nutzbar. Datenschutz erklärt.", "Programm starten"],
  template: { takeaways: ["Verstehe zuerst das Konzept, bevor du Angebote von Glücksspielanbietern vergleichst.", "Nutze B4GAMBLE-Methodik und Kontext zu verantwortungsvollem Spielen gemeinsam.", "Prüfe aktuelle Anbieterbedingungen vor Registrierung oder Einzahlung."], sections: [["Was dieses Thema abdeckt", "{{title}} erklärt die Grundlagen, die vor Anbietervergleichen, Bonusseiten oder Anbieterinformationen wichtig sind."], ["Warum es wichtig ist", "Informationen zu Glücksspielanbietern können verstreut oder werblich sein. Ein strukturierter Leitfaden hilft, Bedingungen, Risiken und praktische Details ruhiger zu vergleichen."], ["So nutzt du es bei B4GAMBLE", "Lies den Leitfaden und verwandte Kategorien, prüfe die Methodik und nutze das 10-Schritte-Programm oder den Selbsttest, wenn Entscheidungen unklar sind."]], examples: ["Eine Person prüft zuerst den Glossarbegriff und öffnet dann einen ausführlichen Leitfaden und eine passende Anbieterbewertung.", "Eine Person vergleicht das Konzept mit Budget, Zeitlimit und lokaler Verfügbarkeit, bevor sie fortfährt."], callout: ["Redaktioneller Hinweis", "Dieser Artikel dient der Bildung. Er garantiert keine Ergebnisse, kein Anbieterverhalten, keine Auszahlungen und keine Streitbeilegung."], faq: [["Ist das eine Beratung?", "Nein. Diese Bildungsinformation unterstützt klarere Vergleiche und Entscheidungen."], ["Wie geht es weiter?", "Nutze die verwandten Artikel und Lernpfade am Ende des Leitfadens."]] },
  ui: { ...enUi, metadataTitle: "Lernen | B4GAMBLE", metadataDescription: "Verständliche Leitfäden zu Glücksspielboni, Zahlungen, Spielen, Bewertungen und verantwortungsvollem Spielen.", learningGuide: "Lernleitfaden | B4GAMBLE", home: "Startseite", learningCenter: "Lernzentrum", breadcrumb: "Brotkrümelnavigation", neutralArticle: "Neutraler Lernartikel", author: "Autor", editor: "Redaktion", updated: "Aktualisiert", readingTime: "Lesezeit", directAnswer: "Direkte Antwort", onThisPage: "Auf dieser Seite", workedExamples: "Beispiele", putInContext: "DIE IDEE IN KONTEXT SETZEN.", sourceStatus: "Quellenstatus", evidenceState: "Belegstatus", sourceUnavailable: "QUELLENSTATUS: NICHT VERFÜGBAR.", noClaimSource: "Es ist kein Beleg auf Aussageebene enthalten.", sourceUnavailableCopy: "Das aktuelle Artikelmodell enthält keine Quellenlinks, Quellenverantwortung, Prüffrist oder Compliance-Freigabe. Die Seite erhebt daher keinen Anspruch auf ‘verifiziert’ oder Compliance-geprüft.", questions: "Fragen", readLimits: "AUCH DIE GRENZEN LESEN.", relatedReading: "Weiterführende Artikel", continueContext: "MIT KONTEXT FORTFAHREN.", optionalTransition: "Optionaler Übergang zum Vergleich", afterAnswer: "Nach der Einordnung", applyChecklist: "BEREIT FÜR DIE CHECKLISTE?", comparisonCopy: "Vergleiche aktuelle B4GAMBLE-Datensätze nur bei klarem Bildungskontext. Dies ist interne Navigation, keine persönliche Empfehlung.", compareCasinos: "Glücksspielanbieter vergleichen", commercialDisclosure: "Kommerzieller Hinweis: B4GAMBLE kann bei später erreichten externen Links eine Vergütung erhalten. Rankings bleiben redaktionell.", controlSupport: "Kontrolle und Unterstützung", neutralNextStep: "DER NÄCHSTE SCHRITT BLEIBT NEUTRAL.", responsibleNoTransition: "Dieser Lernartikel zu verantwortungsvollem Spielen führt nicht zu Anbieter-, Bonus- oder Vergleichsinhalten.", exploreResponsible: "Verantwortungsvolles Spielen öffnen", openHelp: "Geschützte Hilfe öffnen", searchPlaceholder: "Leitfäden durchsuchen — Umsatz, Auszahlungen, RTP…", oneShown: "Leitfaden angezeigt.", manyShown: "Leitfäden angezeigt.", noneShown: "Keine passenden Leitfäden. Suche löschen oder Alle Themen wählen.", difficulty: { Beginner: "Einsteiger", Intermediate: "Mittel", Advanced: "Fortgeschritten" } },
};

const it: Pack = {
  categories: ["Basi dei casinò", "Bonus dei casinò", "Gioco responsabile", "Recensioni di casinò", "Sicurezza dei casinò", "Pagamenti", "Licenze", "Guide ai giochi", "Basi delle scommesse sportive", "Casinò crypto", "Guide per Paese", "Glossario dei casinò", "Notizie di settore"],
  articles: [
    ["Basi dei casinò online", "Introduzione semplice ad account, condizioni, giochi, pagamenti e punti di confronto."], ["Come funzionano i termini del bonus di benvenuto", "Comprendi requisiti di puntata, scadenza, contributo dei giochi, puntata massima e limiti di prelievo."], ["Strumenti per il gioco responsabile", "Come possono funzionare limiti di deposito, promemoria, pause e autoesclusione."], ["Come funzionano le recensioni di casinò", "Guida a punteggi editoriali, criteri, limiti e confronto responsabile."], ["Lista di controllo per la sicurezza", "Controlli pratici su licenze, condizioni, pagamenti, sicurezza e assistenza."], ["Metodi di pagamento dei casinò", "Confronta depositi, prelievi, verifica, tempi, commissioni e valute."], ["Licenze dei casinò spiegate", "Cosa possono indicare, cosa non provano e quali dati verificare."], ["RTP e volatilità spiegati", "Due termini comuni e perché non garantiscono risultati."], ["Basi delle quote sportive", "Introduzione non promozionale a formati delle quote, probabilità implicita e terminologia."], ["Pagamenti crypto nei casinò", "Depositi, prelievi, wallet, volatilità e restrizioni dell'operatore."], ["Come leggere le guide ai casinò per Paese", "Usa responsabilmente disponibilità, pagamenti e licenze a livello nazionale."], ["Glossario essenziale dei casinò", "Termini comuni: requisiti di puntata, KYC, RTP, volatilità e autoesclusione."], ["Come leggere le notizie sui casinò", "Comprendi aggiornamenti normativi e annunci verificandoli con le fonti."],
  ],
  hub: ["Guide e approfondimenti", "Impara.", "Gioca con più consapevolezza.", "Risposte chiare alle domande che il settore preferisce evitare.", "Scritto dal team che svolge i controlli", "Guide educative · link commerciali dichiarati", "Data di pubblicazione su ogni guida", "Inizia qui", "Quattro guide per l'80% delle domande", "Tutte le guide", "Cerca guide", "guide", "Tutti gli argomenti", "Bonus", "Pagamenti", "Casinò", "Giochi", "Gioco responsabile", "Settore", "Leggi →", "Oltre la lettura", "La conoscenza è metà del lavoro.", "Il piano è l'altra metà.", "Dieci missioni trasformano ciò che hai letto in limiti solidi. Uso gratuito. Privacy spiegata.", "Avvia Programma"],
  template: { takeaways: ["Comprendi il concetto prima di confrontare offerte.", "Usa insieme metodologia B4GAMBLE e contesto di gioco responsabile.", "Controlla i termini attuali prima di registrarti o depositare."], sections: [["Cosa tratta questo argomento", "{{title}} spiega le idee essenziali da comprendere prima di affidarsi a confronti, bonus o informazioni sugli operatori."], ["Perché è importante", "Le informazioni sui casinò possono essere frammentarie o promozionali. Una guida strutturata aiuta a confrontare con calma termini, rischi e dettagli pratici."], ["Come usarlo su B4GAMBLE", "Leggi la guida e le categorie correlate, consulta la metodologia e usa il Programma in 10 passi o l'autovalutazione quando le decisioni non sono chiare."]], examples: ["Il lettore controlla prima un termine del glossario, poi apre una guida dettagliata e una recensione correlata.", "Il lettore confronta il concetto con budget, limite di tempo e disponibilità locale prima di proseguire."], callout: ["Nota editoriale", "Questo articolo è educativo. Non garantisce risultati, condotta dell'operatore, prelievi o esiti di controversie."], faq: [["È una consulenza?", "No. Sono informazioni educative per confronti e decisioni più chiari."], ["Dove proseguo?", "Usa gli articoli correlati e i percorsi formativi alla fine della guida."]] },
  ui: { ...enUi, metadataTitle: "Impara | B4GAMBLE", metadataDescription: "Guide chiare su bonus, pagamenti, giochi, recensioni e gioco responsabile.", learningGuide: "Guida formativa | B4GAMBLE", home: "Home", learningCenter: "Centro didattico", breadcrumb: "Percorso", neutralArticle: "Articolo didattico neutrale", author: "Autore", editor: "Revisore", updated: "Aggiornato", readingTime: "Tempo di lettura", directAnswer: "Risposta diretta", onThisPage: "In questa pagina", workedExamples: "Esempi", putInContext: "METTI L'IDEA NEL CONTESTO.", sourceStatus: "Stato delle fonti", evidenceState: "Stato delle prove", sourceUnavailable: "STATO DELLE FONTI: NON DISPONIBILE.", noClaimSource: "Non è incluso alcun riferimento per le singole affermazioni.", sourceUnavailableCopy: "L'attuale modello non fornisce link alle fonti, responsabile, data della prossima revisione o stato di verifica di conformità. La pagina non dichiara quindi contenuti ‘verificati’ o approvati per conformità.", questions: "Domande", readLimits: "LEGGI ANCHE I LIMITI.", relatedReading: "Letture correlate", continueContext: "CONTINUA CON IL CONTESTO.", optionalTransition: "Passaggio facoltativo al confronto", afterAnswer: "Dopo la risposta educativa", applyChecklist: "PRONTO AD APPLICARE LA LISTA?", comparisonCopy: "Confronta i dati B4GAMBLE attuali solo quando il contesto educativo è chiaro. È navigazione interna, non un consiglio personalizzato.", compareCasinos: "Confronta casinò", commercialDisclosure: "Dichiarazione commerciale: B4GAMBLE può ricevere compensi da alcuni link esterni raggiunti in seguito. Le classifiche restano editoriali.", controlSupport: "Controllo e supporto", neutralNextStep: "MANTIENI NEUTRALE IL PASSO SUCCESSIVO.", responsibleNoTransition: "Questo articolo sul gioco responsabile non conduce a contenuti su casinò, bonus o confronti.", exploreResponsible: "Esplora Gioco responsabile", openHelp: "Apri Aiuto protetto", searchPlaceholder: "Cerca guide — requisiti, prelievi, RTP…", oneShown: "guida mostrata.", manyShown: "guide mostrate.", noneShown: "Nessuna guida corrisponde. Cancella la ricerca o scegli Tutti gli argomenti.", difficulty: { Beginner: "Principiante", Intermediate: "Intermedio", Advanced: "Avanzato" } },
};

const es: Pack = {
  categories: ["Conceptos básicos de casino", "Bonos de casino", "Juego responsable", "Reseñas de casinos", "Seguridad de casinos", "Pagos", "Licencias", "Guías de juegos", "Conceptos básicos de apuestas deportivas", "Casinos con cripto", "Guías por país", "Glosario de casino", "Noticias del sector"],
  articles: [["Conceptos básicos del casino en línea", "Introducción sencilla a cuentas, condiciones, juegos, pagos y puntos de comparación."], ["Cómo funcionan las condiciones del bono de bienvenida", "Comprende requisitos de apuesta, caducidad, contribución de juegos, apuesta máxima y límites de retirada."], ["Herramientas de juego responsable", "Cómo pueden funcionar límites de depósito, recordatorios, pausas y autoexclusión."], ["Cómo funcionan las reseñas de casinos", "Guía de puntuación editorial, criterios, limitaciones y comparación responsable."], ["Lista de seguridad del casino", "Comprobación práctica de licencias, condiciones, pagos, seguridad y atención."], ["Métodos de pago de casino", "Compara depósitos, retiradas, verificación, plazos, comisiones y monedas."], ["Licencias de casino explicadas", "Qué pueden indicar, qué no demuestran y qué datos debes comprobar."], ["RTP y volatilidad explicados", "Comprende dos términos habituales y por qué no garantizan resultados."], ["Conceptos básicos de cuotas deportivas", "Introducción no promocional a formatos de cuotas, probabilidad implícita y terminología."], ["Pagos con cripto en casinos", "Comprende depósitos, retiradas, monederos, volatilidad y restricciones."], ["Cómo leer guías de casino por país", "Usa responsablemente la disponibilidad, pagos y licencias a nivel nacional."], ["Glosario básico de casino", "Términos como requisito de apuesta, KYC, RTP, volatilidad y autoexclusión."], ["Cómo leer noticias del sector del casino", "Comprende novedades normativas y anuncios, y contrástalos con fuentes."]],
  hub: ["Guías e información", "Aprende.", "Juega con más criterio.", "Respuestas claras a las preguntas que el sector prefiere evitar.", "Escrito por el equipo que realiza las comprobaciones", "Guías educativas · enlaces comerciales declarados", "Fecha de publicación en cada guía", "Empieza aquí", "Cuatro guías que responden al 80 % de las preguntas", "Todas las guías", "Buscar guías", "guías", "Todos los temas", "Bonos", "Pagos", "Casinos", "Juegos", "Juego responsable", "Sector", "Leer →", "Más allá de la lectura", "Saber es la mitad.", "El plan es la otra mitad.", "Diez misiones convierten lo aprendido en límites que se mantienen. Uso gratuito. Privacidad explicada.", "Iniciar Programa"],
  template: { takeaways: ["Entiende el concepto antes de comparar ofertas.", "Usa conjuntamente la metodología B4GAMBLE y el contexto de juego responsable.", "Revisa las condiciones actuales antes de registrarte o depositar."], sections: [["Qué cubre este tema", "{{title}} explica las ideas esenciales que debes entender antes de confiar en comparadores, bonos o información de operadores."], ["Por qué importa", "La información de casinos puede estar fragmentada o ser promocional. Una guía estructurada ayuda a comparar con calma condiciones, riesgos y detalles prácticos."], ["Cómo usarlo en B4GAMBLE", "Lee la guía y las categorías relacionadas, revisa la metodología y usa el Programa de 10 pasos o la autoevaluación cuando la decisión no esté clara."]], examples: ["La persona consulta primero un término del glosario y después abre una guía detallada y una reseña relacionada.", "La persona contrasta el concepto con su presupuesto, límite de tiempo y disponibilidad local antes de seguir."], callout: ["Nota editorial", "Este artículo es educativo. No garantiza resultados, conducta del operador, retiradas ni resolución de disputas."], faq: [["¿Es asesoramiento?", "No. Es información educativa para facilitar comparaciones y decisiones más claras."], ["¿Dónde continúo?", "Usa los artículos relacionados y rutas de aprendizaje al final de la guía."]] },
  ui: { ...enUi, metadataTitle: "Aprende | B4GAMBLE", metadataDescription: "Guías claras sobre bonos, pagos, juegos, reseñas y juego responsable.", learningGuide: "Guía de aprendizaje | B4GAMBLE", home: "Inicio", learningCenter: "Centro de aprendizaje", breadcrumb: "Migas de pan", neutralArticle: "Artículo educativo neutral", author: "Autor", editor: "Editor", updated: "Actualizado", readingTime: "Tiempo de lectura", directAnswer: "Respuesta directa", onThisPage: "En esta página", workedExamples: "Ejemplos", putInContext: "PON LA IDEA EN CONTEXTO.", sourceStatus: "Estado de fuentes", evidenceState: "Estado de las pruebas", sourceUnavailable: "ESTADO DE FUENTES: NO DISPONIBLE.", noClaimSource: "No se incluye una fuente para cada afirmación.", sourceUnavailableCopy: "El modelo actual no aporta enlaces a fuentes, responsable de fuente, fecha de próxima revisión ni estado de revisión de cumplimiento. Por ello, la página no afirma estar ‘verificada’ ni revisada para cumplimiento.", questions: "Preguntas", readLimits: "LEE TAMBIÉN LOS LÍMITES.", relatedReading: "Lecturas relacionadas", continueContext: "CONTINÚA CON CONTEXTO.", optionalTransition: "Transición opcional a la comparación", afterAnswer: "Después de la respuesta educativa", applyChecklist: "¿LISTO PARA APLICAR LA LISTA?", comparisonCopy: "Compara registros actuales de B4GAMBLE solo cuando el contexto educativo esté claro. Es navegación interna, no una recomendación personalizada.", compareCasinos: "Comparar casinos", commercialDisclosure: "Declaración comercial: B4GAMBLE puede recibir compensación de algunos enlaces externos posteriores. Las clasificaciones siguen siendo editoriales.", controlSupport: "Control y apoyo", neutralNextStep: "MANTÉN NEUTRAL EL SIGUIENTE PASO.", responsibleNoTransition: "Este artículo sobre juego responsable no conduce a contenidos de casino, bonos o comparación.", exploreResponsible: "Explorar Juego responsable", openHelp: "Abrir Ayuda protegida", searchPlaceholder: "Buscar guías — requisitos, retiradas, RTP…", oneShown: "guía mostrada.", manyShown: "guías mostradas.", noneShown: "No hay coincidencias. Borra la búsqueda o elige Todos los temas.", difficulty: { Beginner: "Principiante", Intermediate: "Intermedio", Advanced: "Avanzado" } },
};

const pt: Pack = {
  categories: ["Noções básicas de casino", "Bónus de casino", "Jogo responsável", "Análises de casinos", "Segurança de casinos", "Pagamentos", "Licenças", "Guias de jogos", "Noções de apostas desportivas", "Casinos de criptomoedas", "Guias por país", "Glossário de casino", "Notícias do setor"],
  articles: [["Noções básicas de casino online", "Introdução simples a contas, termos, jogos, pagamentos e pontos de comparação."], ["Como funcionam os termos do bónus de boas-vindas", "Compreende requisitos de apostas, validade, contribuição dos jogos, aposta máxima e restrições de levantamento."], ["Ferramentas de jogo responsável", "Como podem funcionar limites de depósito, lembretes, pausas e autoexclusão."], ["Como funcionam as análises de casinos", "Guia de pontuação editorial, critérios, limitações e comparação responsável."], ["Lista de segurança do casino", "Verificação prática de licenças, termos, pagamentos, segurança e apoio."], ["Métodos de pagamento de casinos", "Compara depósitos, levantamentos, verificação, prazos, taxas e moedas."], ["Licenças de casino explicadas", "O que podem indicar, o que não provam e quais os dados a verificar."], ["RTP e volatilidade explicados", "Compreende dois termos comuns e porque não garantem resultados."], ["Noções básicas de probabilidades desportivas", "Introdução não promocional a formatos, probabilidade implícita e terminologia."], ["Pagamentos com criptomoedas em casinos", "Compreende depósitos, levantamentos, carteiras, volatilidade e restrições."], ["Como ler guias de casino por país", "Usa responsavelmente a disponibilidade, os pagamentos e as licenças nacionais."], ["Glossário inicial de casino", "Termos como requisitos de apostas, KYC, RTP, volatilidade e autoexclusão."], ["Como ler notícias do setor dos casinos", "Compreende alterações regulatórias e anúncios, verificando-os nas fontes."]],
  hub: ["Guias e conhecimentos", "Aprende.", "Joga com mais critério.", "Respostas claras às perguntas que o setor prefere evitar.", "Escrito pela equipa que faz as verificações", "Guias educativos · ligações comerciais divulgadas", "Data de publicação em todos os guias", "Começa aqui", "Quatro guias que respondem a 80% das perguntas", "Todos os guias", "Pesquisar guias", "guias", "Todos os temas", "Bónus", "Pagamentos", "Casinos", "Jogos", "Jogo responsável", "Setor", "Ler →", "Para além da leitura", "O conhecimento é metade.", "O plano é a outra metade.", "Dez missões transformam o que leste em limites sólidos. Utilização gratuita. Privacidade explicada.", "Iniciar Programa"],
  template: { takeaways: ["Compreende o conceito antes de comparar ofertas.", "Usa em conjunto a metodologia B4GAMBLE e o contexto de jogo responsável.", "Revê os termos atuais antes de te registares ou depositares."], sections: [["O que este tema abrange", "{{title}} explica as ideias essenciais antes de depender de comparações, páginas de bónus ou informação de operadores."], ["Porque é importante", "A informação de casinos pode estar dispersa ou ser promocional. Um guia estruturado ajuda a comparar com calma termos, riscos e detalhes práticos."], ["Como usar no B4GAMBLE", "Lê o guia e as categorias relacionadas, consulta a metodologia e usa o Programa de 10 passos ou a autoavaliação quando as decisões não forem claras."]], examples: ["A pessoa verifica primeiro o termo no glossário e depois abre um guia detalhado e uma análise relacionada.", "A pessoa compara o conceito com o seu orçamento, limite de tempo e disponibilidade local antes de continuar."], callout: ["Nota editorial", "Este artigo é educativo. Não garante resultados, comportamento do operador, levantamentos ou resolução de conflitos."], faq: [["Isto é aconselhamento?", "Não. É informação educativa para comparações e decisões mais claras."], ["Onde continuo?", "Usa os artigos relacionados e percursos de aprendizagem no fim do guia."]] },
  ui: { ...enUi, metadataTitle: "Aprende | B4GAMBLE", metadataDescription: "Guias claros sobre bónus, pagamentos, jogos, análises e jogo responsável.", learningGuide: "Guia de aprendizagem | B4GAMBLE", home: "Início", learningCenter: "Centro de aprendizagem", breadcrumb: "Navegação estrutural", neutralArticle: "Artigo educativo neutro", author: "Autor", editor: "Editor", updated: "Atualizado", readingTime: "Tempo de leitura", directAnswer: "Resposta direta", onThisPage: "Nesta página", workedExamples: "Exemplos", putInContext: "COLOCA A IDEIA EM CONTEXTO.", sourceStatus: "Estado das fontes", evidenceState: "Estado das provas", sourceUnavailable: "ESTADO DAS FONTES: INDISPONÍVEL.", noClaimSource: "Não está incluída uma fonte ao nível de cada afirmação.", sourceUnavailableCopy: "O modelo atual não fornece ligações de fontes, responsável, data de nova revisão ou estado de revisão de conformidade. Por isso, a página não afirma estar ‘verificada’ nem revista para conformidade.", questions: "Perguntas", readLimits: "LÊ TAMBÉM OS LIMITES.", relatedReading: "Leituras relacionadas", continueContext: "CONTINUA COM CONTEXTO.", optionalTransition: "Transição opcional para comparação", afterAnswer: "Depois da resposta educativa", applyChecklist: "PRONTO PARA APLICAR A LISTA?", comparisonCopy: "Compara registos atuais do B4GAMBLE apenas quando o contexto educativo for claro. É navegação interna, não recomendação personalizada.", compareCasinos: "Comparar casinos", commercialDisclosure: "Divulgação comercial: o B4GAMBLE pode receber compensação de algumas ligações externas posteriores. As classificações continuam editoriais.", controlSupport: "Controlo e apoio", neutralNextStep: "MANTÉM O PRÓXIMO PASSO NEUTRO.", responsibleNoTransition: "Este artigo sobre jogo responsável não conduz a conteúdos de casino, bónus ou comparação.", exploreResponsible: "Explorar Jogo responsável", openHelp: "Abrir Ajuda protegida", searchPlaceholder: "Pesquisar guias — requisitos, levantamentos, RTP…", oneShown: "guia apresentado.", manyShown: "guias apresentados.", noneShown: "Nenhum guia corresponde. Limpa a pesquisa ou escolhe Todos os temas.", difficulty: { Beginner: "Iniciante", Intermediate: "Intermédio", Advanced: "Avançado" } },
};

const el: Pack = {
  categories: ["Βασικά για καζίνο", "Μπόνους καζίνο", "Υπεύθυνο παιχνίδι", "Αξιολογήσεις καζίνο", "Ασφάλεια καζίνο", "Πληρωμές", "Άδειες", "Οδηγοί παιχνιδιών", "Βασικά αθλητικού στοιχήματος", "Καζίνο κρυπτονομισμάτων", "Οδηγοί χωρών", "Γλωσσάρι καζίνο", "Νέα κλάδου"],
  articles: [["Βασικά για online καζίνο", "Απλή εισαγωγή σε λογαριασμούς, όρους, παιχνίδια, πληρωμές και σημεία σύγκρισης."], ["Πώς λειτουργούν οι όροι μπόνους καλωσορίσματος", "Κατανόησε τζίρο, λήξη, συνεισφορά παιχνιδιών, μέγιστο ποντάρισμα και περιορισμούς ανάληψης."], ["Εργαλεία υπεύθυνου παιχνιδιού", "Πώς μπορούν να λειτουργούν τα όρια κατάθεσης, οι υπενθυμίσεις, τα διαλείμματα και ο αυτοαποκλεισμός."], ["Πώς λειτουργούν οι αξιολογήσεις καζίνο", "Οδηγός για συντακτική βαθμολόγηση, κριτήρια, περιορισμούς και υπεύθυνη σύγκριση."], ["Λίστα ελέγχου ασφάλειας καζίνο", "Πρακτικός έλεγχος αδειών, όρων, πληρωμών, ασφάλειας και υποστήριξης."], ["Μέθοδοι πληρωμής καζίνο", "Σύγκρινε καταθέσεις, αναλήψεις, επαλήθευση, χρόνους, χρεώσεις και νομίσματα."], ["Επεξήγηση αδειών καζίνο", "Τι μπορούν να δείξουν, τι δεν αποδεικνύουν και ποια στοιχεία πρέπει να ελέγξεις."], ["Επεξήγηση RTP και μεταβλητότητας", "Κατανόησε δύο κοινούς όρους και γιατί δεν εγγυώνται αποτελέσματα."], ["Βασικά για αποδόσεις αθλητικού στοιχήματος", "Μη προωθητική εισαγωγή σε μορφές αποδόσεων, πιθανότητες και ορολογία."], ["Πληρωμές καζίνο με κρυπτονομίσματα", "Κατανόησε καταθέσεις, αναλήψεις, πορτοφόλια, μεταβλητότητα και περιορισμούς."], ["Πώς διαβάζονται οι οδηγοί καζίνο ανά χώρα", "Χρησιμοποίησε υπεύθυνα διαθεσιμότητα, πληρωμές και άδειες ανά χώρα."], ["Αρχικό γλωσσάρι καζίνο", "Όροι όπως τζίρος, KYC, RTP, μεταβλητότητα και αυτοαποκλεισμός."], ["Πώς διαβάζονται τα νέα του κλάδου", "Κατανόησε ρυθμιστικές ενημερώσεις και ανακοινώσεις και έλεγξέ τες στις πηγές."]],
  hub: ["Οδηγοί και γνώσεις", "Μάθε.", "Παίξε πιο συνειδητά.", "Καθαρές απαντήσεις στις ερωτήσεις που ο κλάδος προτιμά να αποφεύγει.", "Από την ομάδα που κάνει τους ελέγχους", "Εκπαιδευτικοί οδηγοί · γνωστοποιούνται εμπορικοί σύνδεσμοι", "Ημερομηνία δημοσίευσης σε κάθε οδηγό", "Ξεκίνα εδώ", "Τέσσερις οδηγοί για το 80% των ερωτήσεων", "Όλοι οι οδηγοί", "Αναζήτηση οδηγών", "οδηγοί", "Όλα τα θέματα", "Μπόνους", "Πληρωμές", "Καζίνο", "Παιχνίδια", "Υπεύθυνο παιχνίδι", "Κλάδος", "Διάβασε →", "Πέρα από την ανάγνωση", "Η γνώση είναι η μισή διαδρομή.", "Το σχέδιο είναι η άλλη μισή.", "Δέκα αποστολές μετατρέπουν όσα διάβασες σε σταθερά όρια. Δωρεάν χρήση. Επεξήγηση απορρήτου.", "Έναρξη Προγράμματος"],
  template: { takeaways: ["Κατανόησε πρώτα την έννοια πριν συγκρίνεις προσφορές.", "Χρησιμοποίησε μαζί τη μεθοδολογία B4GAMBLE και το πλαίσιο υπεύθυνου παιχνιδιού.", "Έλεγξε τους τρέχοντες όρους πριν εγγραφείς ή καταθέσεις."], sections: [["Τι καλύπτει το θέμα", "Ο οδηγός «{{title}}» εξηγεί τις βασικές έννοιες πριν βασιστείς σε συγκρίσεις, σελίδες μπόνους ή πληροφορίες παρόχων."], ["Γιατί έχει σημασία", "Οι πληροφορίες καζίνο μπορεί να είναι αποσπασματικές ή προωθητικές. Ένας δομημένος οδηγός βοηθά σε ήρεμη σύγκριση όρων, κινδύνων και πρακτικών λεπτομερειών."], ["Πώς να το χρησιμοποιήσεις στο B4GAMBLE", "Διάβασε τον οδηγό και τις σχετικές κατηγορίες, έλεγξε τη μεθοδολογία και χρησιμοποίησε το Πρόγραμμα 10 βημάτων ή τον αυτοέλεγχο όταν η απόφαση δεν είναι σαφής."]], examples: ["Ο αναγνώστης ελέγχει πρώτα τον όρο στο γλωσσάρι και μετά ανοίγει λεπτομερή οδηγό και σχετική αξιολόγηση.", "Ο αναγνώστης συγκρίνει την έννοια με τον προϋπολογισμό, το χρονικό όριο και την τοπική διαθεσιμότητα πριν συνεχίσει."], callout: ["Συντακτική σημείωση", "Το άρθρο είναι εκπαιδευτικό. Δεν εγγυάται αποτελέσματα, συμπεριφορά παρόχου, αναλήψεις ή επίλυση διαφορών."], faq: [["Είναι συμβουλή;", "Όχι. Είναι εκπαιδευτική πληροφορία για σαφέστερη σύγκριση και λήψη αποφάσεων."], ["Πού συνεχίζω;", "Χρησιμοποίησε τα σχετικά άρθρα και τις διαδρομές μάθησης στο τέλος."]] },
  ui: { ...enUi, metadataTitle: "Μάθε | B4GAMBLE", metadataDescription: "Απλοί οδηγοί για μπόνους, πληρωμές, παιχνίδια, αξιολογήσεις και υπεύθυνο παιχνίδι.", learningGuide: "Οδηγός μάθησης | B4GAMBLE", home: "Αρχική", learningCenter: "Κέντρο μάθησης", breadcrumb: "Διαδρομή", neutralArticle: "Ουδέτερο εκπαιδευτικό άρθρο", author: "Συντάκτης", editor: "Επιμελητής", updated: "Ενημερώθηκε", readingTime: "Χρόνος ανάγνωσης", directAnswer: "Άμεση απάντηση", onThisPage: "Σε αυτή τη σελίδα", workedExamples: "Παραδείγματα", putInContext: "ΒΑΛΕ ΤΗΝ ΙΔΕΑ ΣΕ ΠΛΑΙΣΙΟ.", sourceStatus: "Κατάσταση πηγών", evidenceState: "Κατάσταση στοιχείων", sourceUnavailable: "ΚΑΤΑΣΤΑΣΗ ΠΗΓΩΝ: ΜΗ ΔΙΑΘΕΣΙΜΗ.", noClaimSource: "Δεν περιλαμβάνεται πηγή για κάθε ισχυρισμό.", sourceUnavailableCopy: "Το τρέχον μοντέλο δεν παρέχει συνδέσμους πηγών, υπεύθυνο πηγής, ημερομηνία επανεξέτασης ή κατάσταση ελέγχου συμμόρφωσης. Επομένως η σελίδα δεν ισχυρίζεται ότι είναι ‘επαληθευμένη’ ή ελεγμένη για συμμόρφωση.", questions: "Ερωτήσεις", readLimits: "ΔΙΑΒΑΣΕ ΚΑΙ ΤΑ ΟΡΙΑ.", relatedReading: "Σχετική ανάγνωση", continueContext: "ΣΥΝΕΧΙΣΕ ΜΕ ΠΛΑΙΣΙΟ.", optionalTransition: "Προαιρετική μετάβαση σε σύγκριση", afterAnswer: "Μετά την εκπαιδευτική απάντηση", applyChecklist: "ΕΤΟΙΜΟΣ ΓΙΑ ΤΗ ΛΙΣΤΑ ΕΛΕΓΧΟΥ;", comparisonCopy: "Σύγκρινε τρέχοντα αρχεία B4GAMBLE μόνο όταν το εκπαιδευτικό πλαίσιο είναι σαφές. Είναι εσωτερική πλοήγηση, όχι εξατομικευμένη πρόταση.", compareCasinos: "Σύγκριση καζίνο", commercialDisclosure: "Εμπορική γνωστοποίηση: το B4GAMBLE μπορεί να λάβει αμοιβή από ορισμένους εξωτερικούς συνδέσμους. Η κατάταξη παραμένει συντακτική.", controlSupport: "Έλεγχος και υποστήριξη", neutralNextStep: "ΚΡΑΤΗΣΕ ΤΟ ΕΠΟΜΕΝΟ ΒΗΜΑ ΟΥΔΕΤΕΡΟ.", responsibleNoTransition: "Αυτό το άρθρο υπεύθυνου παιχνιδιού δεν οδηγεί σε περιεχόμενο καζίνο, μπόνους ή σύγκρισης.", exploreResponsible: "Εξερεύνηση Υπεύθυνου παιχνιδιού", openHelp: "Άνοιγμα Προστατευμένης Βοήθειας", searchPlaceholder: "Αναζήτηση οδηγών — τζίρος, αναλήψεις, RTP…", oneShown: "οδηγός εμφανίζεται.", manyShown: "οδηγοί εμφανίζονται.", noneShown: "Δεν βρέθηκαν οδηγοί. Καθάρισε την αναζήτηση ή επίλεξε Όλα τα θέματα.", difficulty: { Beginner: "Αρχάριος", Intermediate: "Μέσος", Advanced: "Προχωρημένος" } },
};

const nl: Pack = {
  categories: ["Casinobasis", "Casinobonussen", "Verantwoord gokken", "Casinoreviews", "Casinoveiligheid", "Betalingen", "Licenties", "Spelgidsen", "Basis van sportweddenschappen", "Cryptocasino's", "Landengidsen", "Casinowoordenlijst", "Branchenieuws"],
  articles: [["Basis van online casino's", "Een heldere introductie tot accounts, voorwaarden, spellen, betalingen en vergelijkingspunten."], ["Zo werken welkomstbonusvoorwaarden", "Begrijp inzetvereisten, verloop, spelbijdragen, maximale inzet en opnamebeperkingen."], ["Hulpmiddelen voor verantwoord gokken", "Zo kunnen stortingslimieten, herinneringen, pauzes en zelfuitsluiting werken."], ["Zo werken casinoreviews", "Een gids over redactionele scores, criteria, beperkingen en verantwoord vergelijken."], ["Controlelijst voor casinoveiligheid", "Een praktische controle van licenties, voorwaarden, betalingen, beveiliging en ondersteuning."], ["Betaalmethoden bij casino's", "Vergelijk stortingen, opnames, verificatie, verwerkingstijden, kosten en valuta."], ["Casinolicenties uitgelegd", "Wat licenties kunnen aangeven, niet bewijzen en welke gegevens je moet controleren."], ["RTP en volatiliteit uitgelegd", "Begrijp twee gebruikelijke speltermen en waarom ze geen uitkomsten garanderen."], ["Basis van sportweddenschappen", "Een niet-promotionele introductie tot quoteringen, impliciete kans en termen."], ["Cryptobetalingen bij casino's", "Begrijp stortingen, opnames, wallets, volatiliteit en beperkingen."], ["Zo lees je casinogidsen per land", "Gebruik informatie over beschikbaarheid, betalingen en licenties verantwoord."], ["Startgids voor de casinowoordenlijst", "Begrippen zoals inzetvereisten, KYC, RTP, volatiliteit en zelfuitsluiting."], ["Zo lees je nieuws over de casino-industrie", "Begrijp regelgeving en aankondigingen en controleer ze aan de hand van bronnen."]],
  hub: ["Gidsen en inzichten", "Leer.", "Speel bewuster.", "Duidelijke antwoorden op vragen die de branche liever vermijdt.", "Geschreven door het team dat de controles uitvoert", "Educatieve gidsen · commerciële links vermeld", "Publicatiedatum bij elke gids", "Begin hier", "Vier gidsen voor 80% van de vragen", "Alle gidsen", "Gidsen zoeken", "gidsen", "Alle onderwerpen", "Bonussen", "Betalingen", "Casino's", "Spellen", "Verantwoord gokken", "Branche", "Lezen →", "Verder dan lezen", "Kennis is de helft.", "Het plan is de andere helft.", "Tien missies zetten wat je leest om in grenzen die standhouden. Gratis te gebruiken. Privacy uitgelegd.", "Programma starten"],
  template: { takeaways: ["Begrijp eerst het concept voordat je aanbiedingen vergelijkt.", "Gebruik de B4GAMBLE-methodologie samen met context over verantwoord gokken.", "Controleer actuele voorwaarden vóór registratie of storting."], sections: [["Wat dit onderwerp behandelt", "{{title}} legt de basis uit die nodig is vóór je vertrouwt op vergelijkingen, bonuspagina's of aanbiederinformatie."], ["Waarom het belangrijk is", "Casino-informatie kan versnipperd of promotioneel zijn. Een gestructureerde gids helpt voorwaarden, risico's en praktische details rustig te vergelijken."], ["Zo gebruik je dit op B4GAMBLE", "Lees de gids en verwante categorieën, bekijk de methodologie en gebruik het 10-stappenprogramma of de zelftest wanneer beslissingen onduidelijk zijn."]], examples: ["Een lezer controleert eerst de term in de woordenlijst en opent daarna een uitgebreide gids en verwante review.", "Een lezer vergelijkt het concept met budget, tijdslimiet en lokale beschikbaarheid voordat die verdergaat."], callout: ["Redactionele opmerking", "Dit artikel is educatief. Het garandeert geen uitkomsten, gedrag van aanbieders, opnames of geschilresultaten."], faq: [["Is dit advies?", "Nee. Dit is educatieve informatie voor duidelijker vergelijken en beslissen."], ["Waar ga ik verder?", "Gebruik de verwante artikelen en leerpaden aan het einde van de gids."]] },
  ui: { ...enUi, metadataTitle: "Leren | B4GAMBLE", metadataDescription: "Heldere gidsen over bonussen, betalingen, spellen, reviews en verantwoord gokken.", learningGuide: "Leergids | B4GAMBLE", home: "Home", learningCenter: "Leercentrum", breadcrumb: "Kruimelpad", neutralArticle: "Neutraal leerartikel", author: "Auteur", editor: "Redacteur", updated: "Bijgewerkt", readingTime: "Leestijd", directAnswer: "Direct antwoord", onThisPage: "Op deze pagina", workedExamples: "Voorbeelden", putInContext: "PLAATS HET IDEE IN CONTEXT.", sourceStatus: "Bronstatus", evidenceState: "Bewijsstatus", sourceUnavailable: "BRONSTATUS: NIET BESCHIKBAAR.", noClaimSource: "Er is geen bron per bewering opgenomen.", sourceUnavailableCopy: "Het huidige artikelmodel bevat geen bronlinks, broneigenaar, volgende beoordelingsdatum of compliancestatus. De pagina beweert daarom niet ‘geverifieerd’ of op compliance beoordeeld te zijn.", questions: "Vragen", readLimits: "LEES OOK DE BEPERKINGEN.", relatedReading: "Verder lezen", continueContext: "GA VERDER MET CONTEXT.", optionalTransition: "Optionele overgang naar vergelijking", afterAnswer: "Na het educatieve antwoord", applyChecklist: "KLAAR OM DE LIJST TOE TE PASSEN?", comparisonCopy: "Vergelijk actuele B4GAMBLE-gegevens alleen wanneer de educatieve context duidelijk is. Dit is interne navigatie, geen persoonlijk advies.", compareCasinos: "Casino's vergelijken", commercialDisclosure: "Commerciële melding: B4GAMBLE kan vergoeding ontvangen via sommige latere externe links. Rangschikkingen blijven redactioneel.", controlSupport: "Controle en ondersteuning", neutralNextStep: "HOUD DE VOLGENDE STAP NEUTRAAL.", responsibleNoTransition: "Dit artikel over verantwoord gokken leidt niet naar casino-, bonus- of vergelijkingsinhoud.", exploreResponsible: "Verantwoord gokken bekijken", openHelp: "Beschermde Hulp openen", searchPlaceholder: "Gidsen zoeken — inzet, opnames, RTP…", oneShown: "gids getoond.", manyShown: "gidsen getoond.", noneShown: "Geen passende gidsen. Wis de zoekopdracht of kies Alle onderwerpen.", difficulty: { Beginner: "Beginner", Intermediate: "Gemiddeld", Advanced: "Gevorderd" } },
};

const sv: Pack = {
  categories: ["Kasinogrunder", "Kasinobonusar", "Ansvarsfullt spel", "Kasinorecensioner", "Kasinosäkerhet", "Betalningar", "Licenser", "Spelguider", "Grunder i sportspel", "Kryptokasinon", "Landsguider", "Kasinordlista", "Branschnyheter"],
  articles: [["Grunder i nätkasino", "En tydlig introduktion till konton, villkor, spel, betalningar och jämförelsepunkter."], ["Så fungerar villkor för välkomstbonus", "Förstå omsättningskrav, giltighetstid, spelbidrag, högsta insats och uttagsbegränsningar."], ["Verktyg för ansvarsfullt spel", "Så kan insättningsgränser, påminnelser, pauser och självavstängning fungera."], ["Så fungerar kasinorecensioner", "Guide till redaktionella betyg, kriterier, begränsningar och ansvarsfull jämförelse."], ["Checklista för kasinosäkerhet", "Praktisk kontroll av licenser, villkor, betalningar, säkerhet och support."], ["Betalningsmetoder på kasino", "Jämför insättningar, uttag, verifiering, tider, avgifter och valutor."], ["Kasinolicenser förklarade", "Vad licenser kan visa, inte bevisa och vilka uppgifter som bör kontrolleras."], ["RTP och volatilitet förklarade", "Förstå två vanliga speltermer och varför de inte garanterar resultat."], ["Grunder i odds för sportspel", "En saklig introduktion till oddsformat, sannolikhet och terminologi — utan marknadsföring."], ["Kryptobetalningar på kasino", "Förstå insättningar, uttag, plånböcker, volatilitet och begränsningar."], ["Så läser du kasinoguider per land", "Använd uppgifter om tillgänglighet, betalningar och licenser ansvarsfullt."], ["Startguide till kasinordlistan", "Termer som omsättningskrav, KYC, RTP, volatilitet och självavstängning."], ["Så läser du nyheter om kasinobranschen", "Förstå regeländringar och meddelanden och kontrollera dem mot källor."]],
  hub: ["Guider och insikter", "Lär.", "Spela mer medvetet.", "Tydliga svar på frågor branschen helst undviker.", "Skrivet av teamet som gör kontrollerna", "Utbildande guider · kommersiella länkar redovisas", "Publiceringsdatum på varje guide", "Börja här", "Fyra guider som svarar på 80 % av frågorna", "Alla guider", "Sök guider", "guider", "Alla ämnen", "Bonusar", "Betalningar", "Kasinon", "Spel", "Ansvarsfullt spel", "Branschen", "Läs →", "Mer än läsning", "Kunskap är halva vägen.", "Planen är den andra halvan.", "Tio uppdrag gör kunskapen till gränser som håller. Gratis att använda. Integritet förklaras.", "Starta Programmet"],
  template: { takeaways: ["Förstå begreppet innan du jämför erbjudanden.", "Använd B4GAMBLEs metod tillsammans med sammanhang för ansvarsfullt spel.", "Kontrollera aktuella villkor före registrering eller insättning."], sections: [["Vad ämnet omfattar", "{{title}} förklarar grunderna innan du förlitar dig på jämförelser, bonussidor eller operatörsinformation."], ["Varför det spelar roll", "Kasinoinformation kan vara splittrad eller marknadsförande. En strukturerad guide hjälper dig jämföra villkor, risker och praktiska detaljer lugnt."], ["Så använder du det på B4GAMBLE", "Läs guiden och relaterade kategorier, granska metoden och använd 10-stegsprogrammet eller självtestet när beslut känns oklara."]], examples: ["En läsare kontrollerar först ordet i ordlistan och öppnar sedan en utförlig guide och relaterad recension.", "En läsare jämför begreppet med budget, tidsgräns och lokal tillgänglighet innan hen fortsätter."], callout: ["Redaktionell anmärkning", "Artikeln är utbildande. Den garanterar inte resultat, operatörers agerande, uttag eller tvistlösning."], faq: [["Är detta rådgivning?", "Nej. Det är utbildande information för tydligare jämförelser och beslut."], ["Vart går jag sedan?", "Använd relaterade artiklar och lärvägar i slutet av guiden."]] },
  ui: { ...enUi, metadataTitle: "Lär dig | B4GAMBLE", metadataDescription: "Tydliga guider om bonusar, betalningar, spel, recensioner och ansvarsfullt spel.", learningGuide: "Lärguide | B4GAMBLE", home: "Start", learningCenter: "Lärcenter", breadcrumb: "Sökväg", neutralArticle: "Neutral utbildningsartikel", author: "Författare", editor: "Redaktör", updated: "Uppdaterad", readingTime: "Lästid", directAnswer: "Direkt svar", onThisPage: "På sidan", workedExamples: "Exempel", putInContext: "SÄTT IDÉN I ETT SAMMANHANG.", sourceStatus: "Källstatus", evidenceState: "Beläggsstatus", sourceUnavailable: "KÄLLSTATUS: INTE TILLGÄNGLIG.", noClaimSource: "Ingen källa på påståendenivå ingår.", sourceUnavailableCopy: "Den nuvarande artikelmodellen har inga källänkar, källansvarig, nästa granskningsdatum eller status för regelefterlevnad. Sidan gör därför inget anspråk på att vara ‘verifierad’ eller efterlevnadsgranskad.", questions: "Frågor", readLimits: "LÄS OCKSÅ BEGRÄNSNINGARNA.", relatedReading: "Relaterad läsning", continueContext: "FORTSÄTT MED SAMMANHANG.", optionalTransition: "Valfri övergång till jämförelse", afterAnswer: "Efter utbildningssvaret", applyChecklist: "REDO ATT ANVÄNDA CHECKLISTAN?", comparisonCopy: "Jämför aktuella B4GAMBLE-poster bara när utbildningssammanhanget är tydligt. Det är intern navigering, inte personlig rådgivning.", compareCasinos: "Jämför kasinon", commercialDisclosure: "Kommersiell upplysning: B4GAMBLE kan få ersättning från vissa externa länkar senare. Rankningar förblir redaktionella.", controlSupport: "Kontroll och stöd", neutralNextStep: "HÅLL NÄSTA STEG NEUTRALT.", responsibleNoTransition: "Den här artikeln om ansvarsfullt spel leder inte vidare till kasino-, bonus- eller jämförelseinnehåll.", exploreResponsible: "Utforska Ansvarsfullt spel", openHelp: "Öppna skyddad Hjälp", searchPlaceholder: "Sök guider — omsättning, uttag, RTP…", oneShown: "guide visas.", manyShown: "guider visas.", noneShown: "Inga guider matchar. Rensa sökningen eller välj Alla ämnen.", difficulty: { Beginner: "Nybörjare", Intermediate: "Medel", Advanced: "Avancerad" } },
};

const da: Pack = {
  categories: ["Grundlæggende casino", "Casinobonusser", "Ansvarligt spil", "Casinoanmeldelser", "Casinosikkerhed", "Betalinger", "Licenser", "Spilguider", "Grundlæggende sportsvæddemål", "Kryptocasinoer", "Landeguider", "Casinoordliste", "Branchenyt"],
  articles: [["Grundlæggende onlinecasino", "En klar introduktion til konti, vilkår, spil, betalinger og sammenligning."], ["Sådan fungerer vilkår for velkomstbonus", "Forstå omsætningskrav, udløb, spilbidrag, maksimal indsats og udbetalingsbegrænsninger."], ["Værktøjer til ansvarligt spil", "Sådan kan indbetalingsgrænser, påmindelser, pauser og selvudelukkelse fungere."], ["Sådan fungerer casinoanmeldelser", "Guide til redaktionelle bedømmelser, kriterier, begrænsninger og ansvarlig sammenligning."], ["Tjekliste til casinosikkerhed", "Praktisk kontrol af licenser, vilkår, betalinger, sikkerhed og support."], ["Betalingsmetoder på casino", "Sammenlign indbetalinger, udbetalinger, verifikation, tider, gebyrer og valutaer."], ["Casinolicenser forklaret", "Hvad licenser kan vise, ikke bevise, og hvilke oplysninger der skal kontrolleres."], ["RTP og volatilitet forklaret", "Forstå to almindelige spiludtryk, og hvorfor de ikke garanterer resultater."], ["Grundlæggende odds i sportsvæddemål", "En ikke-promoverende introduktion til oddsformater, sandsynlighed og terminologi."], ["Kryptobetalinger på casino", "Forstå indbetalinger, udbetalinger, wallets, volatilitet og begrænsninger."], ["Sådan læses casinoguider efter land", "Brug oplysninger om tilgængelighed, betalinger og licenser ansvarligt."], ["Startguide til casinoordlisten", "Udtryk som omsætningskrav, KYC, RTP, volatilitet og selvudelukkelse."], ["Sådan læses nyheder om casinobranchen", "Forstå lovændringer og meddelelser, og kontrollér dem mod kilder."]],
  hub: ["Guider og indsigt", "Lær.", "Spil mere bevidst.", "Klare svar på spørgsmål, branchen helst undgår.", "Skrevet af teamet, der udfører kontrollen", "Læringsguider · kommercielle links oplyses", "Udgivelsesdato på hver guide", "Start her", "Fire guider, der besvarer 80 % af spørgsmålene", "Alle guider", "Søg i guider", "guider", "Alle emner", "Bonusser", "Betalinger", "Casinoer", "Spil", "Ansvarligt spil", "Branchen", "Læs →", "Ud over læsning", "Viden er den ene halvdel.", "Planen er den anden.", "Ti missioner gør det læste til grænser, der holder. Gratis at bruge. Privatliv forklaret.", "Start Programmet"],
  template: { takeaways: ["Forstå begrebet, før du sammenligner tilbud.", "Brug B4GAMBLEs metode sammen med kontekst om ansvarligt spil.", "Kontrollér aktuelle vilkår før registrering eller indbetaling."], sections: [["Hvad emnet dækker", "{{title}} forklarer det grundlæggende, før du bruger sammenligninger, bonussider eller operatøroplysninger."], ["Hvorfor det er vigtigt", "Casinooplysninger kan være spredte eller promoverende. En struktureret guide hjælper med roligt at sammenligne vilkår, risici og praktiske detaljer."], ["Sådan bruger du det på B4GAMBLE", "Læs guiden og relaterede kategorier, gennemgå metoden, og brug 10-trinsprogrammet eller selvtesten, når beslutninger er uklare."]], examples: ["En læser tjekker først ordet i ordlisten og åbner derefter en detaljeret guide og relateret anmeldelse.", "En læser sammenholder begrebet med budget, tidsgrænse og lokal tilgængelighed, før vedkommende fortsætter."], callout: ["Redaktionel bemærkning", "Artiklen er læringsindhold. Den garanterer ikke resultater, operatøradfærd, udbetalinger eller tvistresultater."], faq: [["Er dette rådgivning?", "Nej. Det er læringsinformation til klarere sammenligninger og beslutninger."], ["Hvor går jeg videre?", "Brug relaterede artikler og læringsforløb nederst i guiden."]] },
  ui: { ...enUi, metadataTitle: "Lær | B4GAMBLE", metadataDescription: "Klare guider om bonusser, betalinger, spil, anmeldelser og ansvarligt spil.", learningGuide: "Læringsguide | B4GAMBLE", home: "Forside", learningCenter: "Læringscenter", breadcrumb: "Brødkrummer", neutralArticle: "Neutral læringsartikel", author: "Forfatter", editor: "Redaktør", updated: "Opdateret", readingTime: "Læsetid", directAnswer: "Direkte svar", onThisPage: "På denne side", workedExamples: "Eksempler", putInContext: "SÆT IDÉEN I KONTEKST.", sourceStatus: "Kildestatus", evidenceState: "Dokumentationsstatus", sourceUnavailable: "KILDESTATUS: IKKE TILGÆNGELIG.", noClaimSource: "Der er ingen kilde for hvert udsagn.", sourceUnavailableCopy: "Den aktuelle artikelmodel indeholder ingen kildelinks, kildeansvarlig, næste vurderingsdato eller status for compliancegennemgang. Siden hævder derfor ikke at være ‘verificeret’ eller compliancegodkendt.", questions: "Spørgsmål", readLimits: "LÆS OGSÅ BEGRÆNSNINGERNE.", relatedReading: "Relateret læsning", continueContext: "FORTSÆT MED KONTEKST.", optionalTransition: "Valgfri overgang til sammenligning", afterAnswer: "Efter læringssvaret", applyChecklist: "KLAR TIL AT BRUGE TJEKLISTEN?", comparisonCopy: "Sammenlign kun aktuelle B4GAMBLE-poster, når læringskonteksten er tydelig. Det er intern navigation, ikke personlig anbefaling.", compareCasinos: "Sammenlign casinoer", commercialDisclosure: "Kommerciel oplysning: B4GAMBLE kan modtage betaling fra nogle senere eksterne links. Rangeringer forbliver redaktionelle.", controlSupport: "Kontrol og støtte", neutralNextStep: "HOLD NÆSTE SKRIDT NEUTRALT.", responsibleNoTransition: "Denne artikel om ansvarligt spil fører ikke til casino-, bonus- eller sammenligningsindhold.", exploreResponsible: "Udforsk Ansvarligt spil", openHelp: "Åbn beskyttet Hjælp", searchPlaceholder: "Søg guider — omsætning, udbetalinger, RTP…", oneShown: "guide vist.", manyShown: "guider vist.", noneShown: "Ingen guider matcher. Ryd søgningen eller vælg Alle emner.", difficulty: { Beginner: "Begynder", Intermediate: "Mellem", Advanced: "Avanceret" } },
};

const fi: Pack = {
  categories: ["Kasinon perusteet", "Kasinobonukset", "Vastuullinen pelaaminen", "Kasinoarvostelut", "Kasinoturvallisuus", "Maksut", "Lisenssit", "Pelioppaat", "Urheiluvedonlyönnin perusteet", "Kryptokasinot", "Maaoppaat", "Kasinon sanasto", "Alan uutiset"],
  articles: [["Nettikasinon perusteet", "Selkeä johdanto tileihin, ehtoihin, peleihin, maksuihin ja vertailukohtiin."], ["Näin tervetuliaisbonuksen ehdot toimivat", "Ymmärrä kierrätys, voimassaolo, pelien vaikutus, enimmäispanos ja nostorajoitukset."], ["Vastuullisen pelaamisen työkalut", "Näin talletusrajat, muistutukset, tauot ja pelikielto voivat toimia."], ["Näin kasinoarvostelut toimivat", "Opas toimituksellisiin arvioihin, kriteereihin, rajoituksiin ja vastuulliseen vertailuun."], ["Kasinoturvallisuuden tarkistuslista", "Käytännön tarkistus lisensseistä, ehdoista, maksuista, turvallisuudesta ja tuesta."], ["Kasinon maksutavat", "Vertaa talletuksia, nostoja, vahvistusta, käsittelyaikoja, kuluja ja valuuttoja."], ["Kasinolisenssit selitetty", "Mitä lisenssit voivat kertoa, mitä ne eivät todista ja mitä tietoja tarkistaa."], ["RTP ja volatiliteetti selitetty", "Ymmärrä kaksi yleistä pelitermiä ja miksi ne eivät takaa tuloksia."], ["Urheiluvedonlyönnin kertoimien perusteet", "Ei-mainonnallinen johdanto kerroinmuotoihin, todennäköisyyteen ja termeihin."], ["Kryptomaksut kasinoilla", "Ymmärrä talletukset, nostot, lompakot, volatiliteetti ja rajoitukset."], ["Näin maakohtaisia kasino-oppaita luetaan", "Käytä saatavuus-, maksu- ja lisenssitietoja vastuullisesti."], ["Kasinon sanaston alkeet", "Termit kuten kierrätys, KYC, RTP, volatiliteetti ja pelikielto."], ["Näin luet kasinoalan uutisia", "Ymmärrä sääntelymuutokset ja ilmoitukset ja tarkista ne lähteistä."]],
  hub: ["Oppaat ja näkökulmat", "Opi.", "Pelaa harkitummin.", "Selkeitä vastauksia kysymyksiin, joita ala mieluummin välttää.", "Tarkistuksia tekevän tiimin kirjoittama", "Koulutusoppaat · kaupalliset linkit ilmoitetaan", "Julkaisupäivä jokaisessa oppaassa", "Aloita tästä", "Neljä opasta vastaa 80 prosenttiin kysymyksistä", "Kaikki oppaat", "Hae oppaita", "opasta", "Kaikki aiheet", "Bonukset", "Maksut", "Kasinot", "Pelit", "Vastuullinen pelaaminen", "Ala", "Lue →", "Lukemista pidemmälle", "Tieto on puolet.", "Suunnitelma on toinen puoli.", "Kymmenen tehtävää muuttaa tiedon pitäviksi rajoiksi. Käyttö on maksutonta. Tietosuojasta kerrotaan avoimesti.", "Aloita Ohjelma"],
  template: { takeaways: ["Ymmärrä käsite ennen tarjousten vertailua.", "Käytä B4GAMBLE-menetelmää vastuullisen pelaamisen asiayhteydessä.", "Tarkista nykyiset ehdot ennen rekisteröitymistä tai talletusta."], sections: [["Mitä aihe kattaa", "{{title}} selittää perusteet ennen kuin käytät kasinovertailuja, bonussivuja tai operaattoritietoja."], ["Miksi sillä on väliä", "Kasinotieto voi olla hajanaista tai mainonnallista. Jäsennelty opas auttaa vertaamaan ehtoja, riskejä ja käytännön tietoja rauhallisesti."], ["Näin käytät sitä B4GAMBLEssa", "Lue opas ja liittyvät kategoriat, tarkista menetelmä ja käytä 10 askeleen Ohjelmaa tai itsearviointia, kun päätös tuntuu epäselvältä."]], examples: ["Lukija tarkistaa ensin sanastotermin ja avaa sitten yksityiskohtaisen oppaan ja siihen liittyvän arvostelun.", "Lukija vertaa käsitettä budjettiinsa, aikarajaansa ja paikalliseen saatavuuteen ennen jatkamista."], callout: ["Toimituksellinen huomautus", "Artikkeli on koulutussisältöä. Se ei takaa tuloksia, operaattorin toimintaa, nostoja tai riitojen ratkaisuja."], faq: [["Onko tämä neuvontaa?", "Ei. Tämä on koulutustietoa selkeämpää vertailua ja päätöksentekoa varten."], ["Mihin jatkan?", "Käytä oppaan lopussa olevia liittyviä artikkeleita ja oppimispolkuja."]] },
  ui: { ...enUi, metadataTitle: "Opi | B4GAMBLE", metadataDescription: "Selkeitä oppaita bonuksista, maksuista, peleistä, arvosteluista ja vastuullisesta pelaamisesta.", learningGuide: "Oppimisopas | B4GAMBLE", home: "Etusivu", learningCenter: "Oppimiskeskus", breadcrumb: "Murupolku", neutralArticle: "Neutraali oppimisartikkeli", author: "Kirjoittaja", editor: "Toimittaja", updated: "Päivitetty", readingTime: "Lukuaika", directAnswer: "Suora vastaus", onThisPage: "Tällä sivulla", workedExamples: "Esimerkit", putInContext: "ASETA AJATUS YHTEYTEEN.", sourceStatus: "Lähdetila", evidenceState: "Näytön tila", sourceUnavailable: "LÄHDETILA: EI SAATAVILLA.", noClaimSource: "Väitekohtaista lähdettä ei ole mukana.", sourceUnavailableCopy: "Nykyinen artikkelimalli ei sisällä lähdelinkkejä, lähdevastaavaa, seuraavaa tarkistuspäivää tai vaatimustenmukaisuuden tarkistustilaa. Sivu ei siksi väitä olevansa ‘vahvistettu’ tai vaatimustenmukaisuustarkastettu.", questions: "Kysymykset", readLimits: "LUE MYÖS RAJOITUKSET.", relatedReading: "Liittyvät artikkelit", continueContext: "HUOMIOI ASIAYHTEYS JATKAESSASI.", optionalTransition: "Valinnainen siirtymä vertailuun", afterAnswer: "Koulutusvastauksen jälkeen", applyChecklist: "VALMIS KÄYTTÄMÄÄN LISTAA?", comparisonCopy: "Vertaa nykyisiä B4GAMBLE-tietoja vain, kun koulutuksellinen asiayhteys on selvä. Tämä on sisäinen linkki, ei henkilökohtainen suositus.", compareCasinos: "Vertaa kasinoita", commercialDisclosure: "Kaupallinen ilmoitus: B4GAMBLE voi saada korvausta joistakin myöhemmistä ulkoisista linkeistä. Järjestys pysyy toimituksellisena.", controlSupport: "Hallinta ja tuki", neutralNextStep: "PIDÄ SEURAAVA ASKEL NEUTRAALINA.", responsibleNoTransition: "Tämä vastuullisen pelaamisen artikkeli ei johda kasino-, bonus- tai vertailusisältöön.", exploreResponsible: "Tutustu Vastuulliseen pelaamiseen", openHelp: "Avaa Suojattu Ohje", searchPlaceholder: "Hae oppaita — kierrätys, nostot, RTP…", oneShown: "opas näkyy.", manyShown: "opasta näkyy.", noneShown: "Oppaita ei löytynyt. Tyhjennä haku tai valitse Kaikki aiheet.", difficulty: { Beginner: "Aloittelija", Intermediate: "Keskitaso", Advanced: "Edistynyt" } },
};

const nb: Pack = {
  categories: ["Grunnleggende casino", "Casinobonuser", "Ansvarlig spill", "Casinoanmeldelser", "Casinosikkerhet", "Betalinger", "Lisenser", "Spillguider", "Grunnleggende sportsspill", "Kryptocasinoer", "Landguider", "Casinoordliste", "Bransjenyheter"],
  articles: [["Grunnleggende nettcasino", "En tydelig innføring i kontoer, vilkår, spill, betalinger og sammenligning."], ["Slik fungerer vilkår for velkomstbonus", "Forstå omsetningskrav, utløp, spillbidrag, maksimal innsats og uttaksbegrensninger."], ["Verktøy for ansvarlig spill", "Slik kan innskuddsgrenser, påminnelser, pauser og selvutestengelse fungere."], ["Slik fungerer casinoanmeldelser", "Guide til redaksjonelle vurderinger, kriterier, begrensninger og ansvarlig sammenligning."], ["Sjekkliste for casinosikkerhet", "Praktisk kontroll av lisenser, vilkår, betalinger, sikkerhet og støtte."], ["Betalingsmetoder på casino", "Sammenlign innskudd, uttak, verifisering, tider, gebyrer og valutaer."], ["Casinolisenser forklart", "Hva lisenser kan vise, ikke bevise, og hvilke opplysninger som må sjekkes."], ["RTP og volatilitet forklart", "Forstå to vanlige spilluttrykk og hvorfor de ikke garanterer resultater."], ["Grunnleggende odds i sportsspill", "En ikke-reklamende innføring i oddsformater, sannsynlighet og terminologi."], ["Kryptobetalinger på casino", "Forstå innskudd, uttak, lommebøker, volatilitet og begrensninger."], ["Slik leses casinoguider etter land", "Bruk opplysninger om tilgjengelighet, betalinger og lisenser ansvarlig."], ["Startguide til casinoordlisten", "Uttrykk som omsetningskrav, KYC, RTP, volatilitet og selvutestengelse."], ["Slik leses nyheter om casinobransjen", "Forstå regelendringer og kunngjøringer og sjekk dem mot kilder."]],
  hub: ["Guider og innsikt", "Lær.", "Spill mer bevisst.", "Tydelige svar på spørsmål bransjen helst unngår.", "Skrevet av teamet som gjør kontrollene", "Læringsguider · kommersielle lenker oppgis", "Publiseringsdato på hver guide", "Start her", "Fire guider som svarer på 80 % av spørsmålene", "Alle guider", "Søk i guider", "guider", "Alle emner", "Bonuser", "Betalinger", "Casinoer", "Spill", "Ansvarlig spill", "Bransjen", "Les →", "Mer enn lesing", "Kunnskap er den ene halvdelen.", "Planen er den andre.", "Ti oppdrag gjør det du har lest til grenser som holder. Gratis å bruke. Personvern forklart.", "Start Programmet"],
  template: { takeaways: ["Forstå begrepet før du sammenligner tilbud.", "Bruk B4GAMBLEs metode sammen med kontekst om ansvarlig spill.", "Sjekk gjeldende vilkår før registrering eller innskudd."], sections: [["Hva emnet dekker", "{{title}} forklarer det grunnleggende før du bruker sammenligninger, bonussider eller operatøropplysninger."], ["Hvorfor det er viktig", "Casinoopplysninger kan være spredte eller reklamepregede. En strukturert guide hjelper deg å sammenligne vilkår, risiko og praktiske detaljer rolig."], ["Slik bruker du det på B4GAMBLE", "Les guiden og relaterte kategorier, gjennomgå metoden, og bruk 10-trinnsprogrammet eller selvtesten når avgjørelser er uklare."]], examples: ["En leser sjekker først ordet i ordlisten og åpner så en detaljert guide og relatert anmeldelse.", "En leser sammenholder begrepet med budsjett, tidsgrense og lokal tilgjengelighet før fortsettelse."], callout: ["Redaksjonell merknad", "Artikkelen er læringsinnhold. Den garanterer ikke resultater, operatøratferd, uttak eller tvisteløsning."], faq: [["Er dette rådgivning?", "Nei. Det er læringsinformasjon for tydeligere sammenligning og beslutninger."], ["Hvor går jeg videre?", "Bruk relaterte artikler og læringsløp nederst i guiden."]] },
  ui: { ...enUi, metadataTitle: "Lær | B4GAMBLE", metadataDescription: "Tydelige guider om bonuser, betalinger, spill, anmeldelser og ansvarlig spill.", learningGuide: "Læringsguide | B4GAMBLE", home: "Forside", learningCenter: "Læringssenter", breadcrumb: "Brødsmuler", neutralArticle: "Nøytral læringsartikkel", author: "Forfatter", editor: "Redaktør", updated: "Oppdatert", readingTime: "Lesetid", directAnswer: "Direkte svar", onThisPage: "På denne siden", workedExamples: "Eksempler", putInContext: "SETT IDEEN I SAMMENHENG.", sourceStatus: "Kildestatus", evidenceState: "Dokumentasjonsstatus", sourceUnavailable: "KILDESTATUS: IKKE TILGJENGELIG.", noClaimSource: "Ingen kilde på påstandsnivå er inkludert.", sourceUnavailableCopy: "Dagens artikkelmodell har ingen kildelenker, kildeansvarlig, neste vurderingsdato eller status for samsvarskontroll. Siden hevder derfor ikke å være ‘verifisert’ eller samsvarsgodkjent.", questions: "Spørsmål", readLimits: "LES OGSÅ BEGRENSNINGENE.", relatedReading: "Relatert lesing", continueContext: "FORTSETT MED SAMMENHENG.", optionalTransition: "Valgfri overgang til sammenligning", afterAnswer: "Etter læringssvaret", applyChecklist: "KLAR TIL Å BRUKE SJEKKLISTEN?", comparisonCopy: "Sammenlign bare gjeldende B4GAMBLE-poster når læringskonteksten er tydelig. Dette er intern navigasjon, ikke personlig anbefaling.", compareCasinos: "Sammenlign casinoer", commercialDisclosure: "Kommersiell opplysning: B4GAMBLE kan motta betaling fra enkelte senere eksterne lenker. Rangeringer forblir redaksjonelle.", controlSupport: "Kontroll og støtte", neutralNextStep: "HOLD NESTE TRINN NØYTRALT.", responsibleNoTransition: "Denne artikkelen om ansvarlig spill fører ikke til casino-, bonus- eller sammenligningsinnhold.", exploreResponsible: "Utforsk Ansvarlig spill", openHelp: "Åpne beskyttet Hjelp", searchPlaceholder: "Søk i guider — omsetning, uttak, RTP…", oneShown: "guide vist.", manyShown: "guider vist.", noneShown: "Ingen guider passer. Tøm søket eller velg Alle emner.", difficulty: { Beginner: "Nybegynner", Intermediate: "Middels", Advanced: "Avansert" } },
};

const en: Pack = { categories: categoriesEn, articles: articlesEn, hub: HUB_SOURCE, template: enTemplate, ui: enUi };
const catalog: Record<EuropeanLocale, Pack> = { "en-GB": en, "de-DE": de, "it-IT": it, "es-ES": es, "pt-PT": pt, "el-GR": el, "nl-NL": nl, "sv-SE": sv, "da-DK": da, "fi-FI": fi, "nb-NO": nb };
const learnLabels: Record<EuropeanLocale, string> = { "en-GB": "Learn", "de-DE": "Lernen", "it-IT": "Impara", "es-ES": "Aprende", "pt-PT": "Aprende", "el-GR": "Μάθε", "nl-NL": "Leren", "sv-SE": "Lär dig", "da-DK": "Lær", "fi-FI": "Opi", "nb-NO": "Lær" };

export function learningMessages(locale: SupportedLocale) {
  const effectiveLocale = locale === "es-PE" ? "es-ES" : locale;
  const pack = catalog[effectiveLocale as EuropeanLocale] ?? en;
  if (pack.categories.length !== learningCategories.length || pack.articles.length !== learningArticles.length || pack.hub.length !== HUB_SOURCE.length) {
    throw new Error(`Learning translation coverage mismatch for ${locale}`);
  }
  return {
    ...pack,
    ui: { ...pack.ui, learn: learnLabels[effectiveLocale as EuropeanLocale] ?? enUi.learn },
    hubCopy: new Map(HUB_SOURCE.map((source, index) => [source, pack.hub[index]])),
  };
}

export type LearningMessages = ReturnType<typeof learningMessages>;

export function localizedLearningCategories(locale: SupportedLocale): LearningCategory[] {
  const messages = learningMessages(locale);
  return learningCategories.map((category, index) => ({ ...category, title: messages.categories[index] }));
}

export function localizedLearningArticles(locale: SupportedLocale): LearningArticle[] {
  const messages = learningMessages(locale);
  return learningArticles.map((article, index) => {
    const [title, summary] = messages.articles[index];
    const template = messages.template;
    return {
      ...article,
      title,
      summary,
      readingTime: new Intl.NumberFormat(locale).format(6) + " min",
      takeaways: [...template.takeaways],
      sections: template.sections.map(([sectionTitle, body]) => ({ title: sectionTitle, body: body.replace("{{title}}", title) })),
      examples: [...template.examples],
      callout: { title: template.callout[0], text: template.callout[1] },
      faq: template.faq.map(([question, answer]) => [question, answer] as [string, string]),
    };
  });
}

export function localizedLearningArticle(article: LearningArticle, locale: SupportedLocale) {
  return localizedLearningArticles(locale).find((candidate) => candidate.slug === article.slug) ?? article;
}

export function localizedLearningCategory(category: LearningCategory, locale: SupportedLocale) {
  return localizedLearningCategories(locale).find((candidate) => candidate.slug === category.slug) ?? category;
}
