import type { SupportedLocale } from "@/lib/market/registry";

export type PublicErrorMessages = Readonly<{
  eyebrow: string; title: string; copy: string; retry: string; home: string; help: string;
  compareKicker: string; compareTitle: string; compareCopy: string; browse: string; protectedHelp: string;
  notFoundLost: string; notFoundBack: string; notFoundHome: string; notFoundAbout: string;
}>;

const en: PublicErrorMessages = { eyebrow: "Something went wrong", title: "We couldn't load this page.", copy: "Try again, or return to a safe starting point.", retry: "Try again", home: "Go home", help: "Open Help", compareKicker: "Comparison unavailable · fail closed", compareTitle: "The published comparison could not load.", compareCopy: "No cached, legacy or invented commercial record is substituted. Public reviews and protected Help remain available.", browse: "Browse reviews", protectedHelp: "Open protected Help", notFoundLost: "This route is lost.", notFoundBack: "Let's get you back on course.", notFoundHome: "Go to homepage", notFoundAbout: "About the Programme →" };

const catalog: Partial<Record<SupportedLocale, PublicErrorMessages>> = {
  "en-GB": en,
  "de-DE": { eyebrow: "Etwas ist schiefgelaufen", title: "Diese Seite konnte nicht geladen werden.", copy: "Versuche es erneut oder kehre zu einem sicheren Ausgangspunkt zurück.", retry: "Erneut versuchen", home: "Zur Startseite", help: "Hilfe öffnen", compareKicker: "Vergleich nicht verfügbar · geschlossen", compareTitle: "Der veröffentlichte Vergleich konnte nicht geladen werden.", compareCopy: "Es wird kein zwischengespeicherter, alter oder erfundener kommerzieller Datensatz eingesetzt. Öffentliche Bewertungen und geschützte Hilfe bleiben verfügbar.", browse: "Bewertungen ansehen", protectedHelp: "Geschützte Hilfe öffnen", notFoundLost: "Diese Route ist verloren gegangen.", notFoundBack: "Wir bringen dich zurück auf Kurs.", notFoundHome: "Zur Startseite", notFoundAbout: "Über das Programm →" },
  "it-IT": { eyebrow: "Si è verificato un problema", title: "Non è stato possibile caricare la pagina.", copy: "Riprova o torna a un punto di partenza sicuro.", retry: "Riprova", home: "Vai alla home", help: "Apri Aiuto", compareKicker: "Confronto non disponibile · chiusura sicura", compareTitle: "Non è stato possibile caricare il confronto pubblicato.", compareCopy: "Non viene sostituito alcun dato commerciale in cache, precedente o inventato. Le recensioni pubbliche e l'Aiuto protetto restano disponibili.", browse: "Sfoglia le recensioni", protectedHelp: "Apri Aiuto protetto", notFoundLost: "Questo percorso si è perso.", notFoundBack: "Torniamo sulla strada giusta.", notFoundHome: "Vai alla home", notFoundAbout: "Informazioni sul Programma →" },
  "es-ES": { eyebrow: "Algo ha salido mal", title: "No hemos podido cargar esta página.", copy: "Inténtalo de nuevo o vuelve a un punto de inicio seguro.", retry: "Intentar de nuevo", home: "Ir al inicio", help: "Abrir Ayuda", compareKicker: "Comparación no disponible · cierre seguro", compareTitle: "No se ha podido cargar la comparación publicada.", compareCopy: "No se sustituye por ningún registro comercial almacenado, antiguo o inventado. Las reseñas públicas y la Ayuda protegida siguen disponibles.", browse: "Ver reseñas", protectedHelp: "Abrir Ayuda protegida", notFoundLost: "Esta ruta se ha perdido.", notFoundBack: "Volvamos al camino correcto.", notFoundHome: "Ir a la página de inicio", notFoundAbout: "Sobre el Programa →" },
  "pt-PT": { eyebrow: "Algo correu mal", title: "Não foi possível carregar esta página.", copy: "Tenta novamente ou volta a um ponto de partida seguro.", retry: "Tentar novamente", home: "Ir para o início", help: "Abrir Ajuda", compareKicker: "Comparação indisponível · estado fechado", compareTitle: "Não foi possível carregar a comparação publicada.", compareCopy: "Nenhum registo comercial em cache, antigo ou inventado é usado. As análises públicas e a Ajuda protegida continuam disponíveis.", browse: "Ver análises", protectedHelp: "Abrir Ajuda protegida", notFoundLost: "Este caminho perdeu-se.", notFoundBack: "Vamos voltar ao rumo certo.", notFoundHome: "Ir para a página inicial", notFoundAbout: "Sobre o Programa →" },
  "el-GR": { eyebrow: "Κάτι πήγε στραβά", title: "Δεν ήταν δυνατή η φόρτωση της σελίδας.", copy: "Δοκίμασε ξανά ή επέστρεψε σε ασφαλές σημείο εκκίνησης.", retry: "Δοκίμασε ξανά", home: "Αρχική", help: "Άνοιγμα Βοήθειας", compareKicker: "Η σύγκριση δεν είναι διαθέσιμη · ασφαλές κλείσιμο", compareTitle: "Η δημοσιευμένη σύγκριση δεν φορτώθηκε.", compareCopy: "Δεν υποκαθίσταται κανένα αποθηκευμένο, παλιό ή επινοημένο εμπορικό αρχείο. Οι δημόσιες αξιολογήσεις και η Προστατευμένη Βοήθεια παραμένουν διαθέσιμες.", browse: "Προβολή αξιολογήσεων", protectedHelp: "Άνοιγμα Προστατευμένης Βοήθειας", notFoundLost: "Αυτή η διαδρομή χάθηκε.", notFoundBack: "Ας επιστρέψουμε στη σωστή πορεία.", notFoundHome: "Μετάβαση στην αρχική", notFoundAbout: "Σχετικά με το Πρόγραμμα →" },
  "nl-NL": { eyebrow: "Er is iets misgegaan", title: "We konden deze pagina niet laden.", copy: "Probeer opnieuw of ga terug naar een veilig beginpunt.", retry: "Opnieuw proberen", home: "Naar home", help: "Hulp openen", compareKicker: "Vergelijking niet beschikbaar · veilig gesloten", compareTitle: "De gepubliceerde vergelijking kon niet worden geladen.", compareCopy: "Er wordt geen opgeslagen, verouderd of verzonnen commercieel gegeven gebruikt. Openbare reviews en Beschermde Hulp blijven beschikbaar.", browse: "Reviews bekijken", protectedHelp: "Beschermde Hulp openen", notFoundLost: "Deze route is verdwaald.", notFoundBack: "We brengen je terug op koers.", notFoundHome: "Naar de homepage", notFoundAbout: "Over het Programma →" },
  "sv-SE": { eyebrow: "Något gick fel", title: "Sidan kunde inte laddas.", copy: "Försök igen eller återvänd till en trygg startpunkt.", retry: "Försök igen", home: "Gå till startsidan", help: "Öppna Hjälp", compareKicker: "Jämförelsen är inte tillgänglig · säkert stängd", compareTitle: "Den publicerade jämförelsen kunde inte laddas.", compareCopy: "Ingen lagrad, äldre eller påhittad kommersiell uppgift används. Offentliga recensioner och Skyddad Hjälp är fortfarande tillgängliga.", browse: "Visa recensioner", protectedHelp: "Öppna Skyddad Hjälp", notFoundLost: "Den här vägen kom bort.", notFoundBack: "Vi hjälper dig tillbaka på rätt spår.", notFoundHome: "Gå till startsidan", notFoundAbout: "Om Programmet →" },
  "da-DK": { eyebrow: "Noget gik galt", title: "Siden kunne ikke indlæses.", copy: "Prøv igen, eller gå tilbage til et sikkert udgangspunkt.", retry: "Prøv igen", home: "Gå til forsiden", help: "Åbn Hjælp", compareKicker: "Sammenligning utilgængelig · sikkert lukket", compareTitle: "Den offentliggjorte sammenligning kunne ikke indlæses.", compareCopy: "Ingen gemt, ældre eller opdigtet kommerciel oplysning bruges. Offentlige anmeldelser og Beskyttet Hjælp er fortsat tilgængelige.", browse: "Se anmeldelser", protectedHelp: "Åbn Beskyttet Hjælp", notFoundLost: "Denne rute er blevet væk.", notFoundBack: "Vi får dig tilbage på rette spor.", notFoundHome: "Gå til forsiden", notFoundAbout: "Om Programmet →" },
  "fi-FI": { eyebrow: "Jokin meni vikaan", title: "Sivua ei voitu ladata.", copy: "Yritä uudelleen tai palaa turvalliseen aloituspisteeseen.", retry: "Yritä uudelleen", home: "Etusivulle", help: "Avaa Ohje", compareKicker: "Vertailu ei ole saatavilla · turvallisesti suljettu", compareTitle: "Julkaistua vertailua ei voitu ladata.", compareCopy: "Tilalle ei käytetä välimuistissa olevaa, vanhaa tai keksittyä kaupallista tietoa. Julkiset arvostelut ja Suojattu Ohje ovat edelleen saatavilla.", browse: "Selaa arvosteluja", protectedHelp: "Avaa Suojattu Ohje", notFoundLost: "Tämä reitti on kadonnut.", notFoundBack: "Palataan oikealle reitille.", notFoundHome: "Siirry etusivulle", notFoundAbout: "Tietoa Ohjelmasta →" },
  "nb-NO": { eyebrow: "Noe gikk galt", title: "Siden kunne ikke lastes.", copy: "Prøv igjen, eller gå tilbake til et trygt utgangspunkt.", retry: "Prøv igjen", home: "Gå til forsiden", help: "Åpne Hjelp", compareKicker: "Sammenligning utilgjengelig · trygt lukket", compareTitle: "Den publiserte sammenligningen kunne ikke lastes.", compareCopy: "Ingen lagret, eldre eller oppdiktet kommersiell opplysning brukes. Offentlige anmeldelser og Beskyttet Hjelp er fortsatt tilgjengelige.", browse: "Se anmeldelser", protectedHelp: "Åpne Beskyttet Hjelp", notFoundLost: "Denne ruten har gått seg bort.", notFoundBack: "Vi får deg tilbake på rett spor.", notFoundHome: "Gå til forsiden", notFoundAbout: "Om Programmet →" },
};

export function publicErrorMessages(locale: SupportedLocale) {
  return catalog[locale] ?? en;
}
