import type { SupportedLocale } from "@/lib/market/registry";

export type PublicErrorMessages = Readonly<{
  eyebrow: string; title: string; copy: string; retry: string; home: string; help: string;
  compareKicker: string; compareTitle: string; compareCopy: string; browse: string; protectedHelp: string;
  notFoundLost: string; notFoundBack: string; notFoundHome: string; notFoundAbout: string;
}>;

const en: PublicErrorMessages = { eyebrow: "Something went wrong", title: "We couldn't load this page.", copy: "Try again, or return to a safe starting point.", retry: "Try again", home: "Go home", help: "Open Help", compareKicker: "Comparison temporarily unavailable", compareTitle: "The published comparison could not load.", compareCopy: "We won't show another comparison without checking it first. You can still read published reviews or open protected Help.", browse: "Browse reviews", protectedHelp: "Open protected Help", notFoundLost: "We couldn't find this page.", notFoundBack: "Let's get you back on course.", notFoundHome: "Go to homepage", notFoundAbout: "About the Programme →" };

const catalog: Partial<Record<SupportedLocale, PublicErrorMessages>> = {
  "en-GB": en,
  "de-DE": { eyebrow: "Etwas ist schiefgelaufen", title: "Diese Seite konnte nicht geladen werden.", copy: "Versuche es erneut oder kehre zu einem sicheren Ausgangspunkt zurück.", retry: "Erneut versuchen", home: "Zur Startseite", help: "Hilfe öffnen", compareKicker: "Vergleich derzeit nicht verfügbar", compareTitle: "Der veröffentlichte Vergleich konnte nicht geladen werden.", compareCopy: "Wir zeigen keinen ungeprüften Ersatz. Du kannst weiterhin veröffentlichte Bewertungen lesen oder die geschützte Hilfe öffnen.", browse: "Bewertungen ansehen", protectedHelp: "Geschützte Hilfe öffnen", notFoundLost: "Diese Seite konnten wir nicht finden.", notFoundBack: "Wir bringen dich zurück auf Kurs.", notFoundHome: "Zur Startseite", notFoundAbout: "Über das Programm →" },
  "it-IT": { eyebrow: "Si è verificato un problema", title: "Non è stato possibile caricare la pagina.", copy: "Riprova o torna a un punto di partenza sicuro.", retry: "Riprova", home: "Vai alla home", help: "Apri Aiuto", compareKicker: "Confronto temporaneamente non disponibile", compareTitle: "Non è stato possibile caricare il confronto pubblicato.", compareCopy: "Non mostriamo un altro confronto senza averlo prima verificato. Puoi comunque leggere le recensioni pubblicate o aprire l'Aiuto protetto.", browse: "Sfoglia le recensioni", protectedHelp: "Apri Aiuto protetto", notFoundLost: "Non abbiamo trovato questa pagina.", notFoundBack: "Torniamo sulla strada giusta.", notFoundHome: "Vai alla home", notFoundAbout: "Informazioni sul Programma →" },
  "es-ES": { eyebrow: "Algo ha salido mal", title: "No hemos podido cargar esta página.", copy: "Inténtalo de nuevo o vuelve a un punto de inicio seguro.", retry: "Intentar de nuevo", home: "Ir al inicio", help: "Abrir Ayuda", compareKicker: "Comparación temporalmente no disponible", compareTitle: "No se ha podido cargar la comparación publicada.", compareCopy: "No mostramos otra comparación sin comprobarla antes. Puedes seguir leyendo las reseñas publicadas o abrir la Ayuda protegida.", browse: "Ver reseñas", protectedHelp: "Abrir Ayuda protegida", notFoundLost: "No hemos encontrado esta página.", notFoundBack: "Volvamos al camino correcto.", notFoundHome: "Ir a la página de inicio", notFoundAbout: "Sobre el Programa →" },
  "pt-PT": { eyebrow: "Algo correu mal", title: "Não foi possível carregar esta página.", copy: "Tenta novamente ou volta a um ponto de partida seguro.", retry: "Tentar novamente", home: "Ir para o início", help: "Abrir Ajuda", compareKicker: "Comparação temporariamente indisponível", compareTitle: "Não foi possível carregar a comparação publicada.", compareCopy: "Não mostramos outra comparação sem a verificar primeiro. Podes continuar a ler as análises publicadas ou abrir a Ajuda protegida.", browse: "Ver análises", protectedHelp: "Abrir Ajuda protegida", notFoundLost: "Não encontrámos esta página.", notFoundBack: "Vamos voltar ao rumo certo.", notFoundHome: "Ir para a página inicial", notFoundAbout: "Sobre o Programa →" },
  "el-GR": { eyebrow: "Κάτι πήγε στραβά", title: "Δεν ήταν δυνατή η φόρτωση της σελίδας.", copy: "Δοκίμασε ξανά ή επέστρεψε σε ασφαλές σημείο εκκίνησης.", retry: "Δοκίμασε ξανά", home: "Αρχική", help: "Άνοιγμα Βοήθειας", compareKicker: "Η σύγκριση δεν είναι διαθέσιμη προς το παρόν", compareTitle: "Η δημοσιευμένη σύγκριση δεν φορτώθηκε.", compareCopy: "Δεν εμφανίζουμε άλλη σύγκριση χωρίς να την ελέγξουμε πρώτα. Μπορείς να συνεχίσεις να διαβάζεις τις δημοσιευμένες αξιολογήσεις ή να ανοίξεις την Προστατευμένη Βοήθεια.", browse: "Προβολή αξιολογήσεων", protectedHelp: "Άνοιγμα Προστατευμένης Βοήθειας", notFoundLost: "Δεν βρήκαμε αυτή τη σελίδα.", notFoundBack: "Ας επιστρέψουμε στη σωστή πορεία.", notFoundHome: "Μετάβαση στην αρχική", notFoundAbout: "Σχετικά με το Πρόγραμμα →" },
  "nl-NL": { eyebrow: "Er is iets misgegaan", title: "We konden deze pagina niet laden.", copy: "Probeer opnieuw of ga terug naar een veilig beginpunt.", retry: "Opnieuw proberen", home: "Naar home", help: "Hulp openen", compareKicker: "Vergelijking tijdelijk niet beschikbaar", compareTitle: "De gepubliceerde vergelijking kon niet worden geladen.", compareCopy: "We tonen geen andere vergelijking zonder die eerst te controleren. Je kunt nog steeds gepubliceerde reviews lezen of Beschermde Hulp openen.", browse: "Reviews bekijken", protectedHelp: "Beschermde Hulp openen", notFoundLost: "We konden deze pagina niet vinden.", notFoundBack: "We brengen je terug op koers.", notFoundHome: "Naar de homepage", notFoundAbout: "Over het Programma →" },
  "sv-SE": { eyebrow: "Något gick fel", title: "Sidan kunde inte laddas.", copy: "Försök igen eller återvänd till en trygg startpunkt.", retry: "Försök igen", home: "Gå till startsidan", help: "Öppna Hjälp", compareKicker: "Jämförelsen är tillfälligt inte tillgänglig", compareTitle: "Den publicerade jämförelsen kunde inte laddas.", compareCopy: "Vi visar ingen annan jämförelse utan att först kontrollera den. Du kan fortfarande läsa publicerade recensioner eller öppna Skyddad Hjälp.", browse: "Visa recensioner", protectedHelp: "Öppna Skyddad Hjälp", notFoundLost: "Vi kunde inte hitta den här sidan.", notFoundBack: "Vi hjälper dig tillbaka på rätt spår.", notFoundHome: "Gå till startsidan", notFoundAbout: "Om Programmet →" },
  "da-DK": { eyebrow: "Noget gik galt", title: "Siden kunne ikke indlæses.", copy: "Prøv igen, eller gå tilbage til et sikkert udgangspunkt.", retry: "Prøv igen", home: "Gå til forsiden", help: "Åbn Hjælp", compareKicker: "Sammenligningen er midlertidigt utilgængelig", compareTitle: "Den offentliggjorte sammenligning kunne ikke indlæses.", compareCopy: "Vi viser ikke en anden sammenligning uden først at kontrollere den. Du kan stadig læse offentliggjorte anmeldelser eller åbne Beskyttet Hjælp.", browse: "Se anmeldelser", protectedHelp: "Åbn Beskyttet Hjælp", notFoundLost: "Vi kunne ikke finde denne side.", notFoundBack: "Vi får dig tilbage på rette spor.", notFoundHome: "Gå til forsiden", notFoundAbout: "Om Programmet →" },
  "fi-FI": { eyebrow: "Jokin meni vikaan", title: "Sivua ei voitu ladata.", copy: "Yritä uudelleen tai palaa turvalliseen aloituspisteeseen.", retry: "Yritä uudelleen", home: "Etusivulle", help: "Avaa Ohje", compareKicker: "Vertailu ei ole juuri nyt saatavilla", compareTitle: "Julkaistua vertailua ei voitu ladata.", compareCopy: "Emme näytä toista vertailua tarkistamatta sitä ensin. Voit edelleen lukea julkaistuja arvioita tai avata suojatun Ohjeen.", browse: "Selaa arvioita", protectedHelp: "Avaa suojattu Ohje", notFoundLost: "Sivua ei löytynyt.", notFoundBack: "Palataan oikealle reitille.", notFoundHome: "Siirry etusivulle", notFoundAbout: "Tietoa Ohjelmasta →" },
  "nb-NO": { eyebrow: "Noe gikk galt", title: "Siden kunne ikke lastes.", copy: "Prøv igjen, eller gå tilbake til et trygt utgangspunkt.", retry: "Prøv igjen", home: "Gå til forsiden", help: "Åpne Hjelp", compareKicker: "Sammenligningen er midlertidig utilgjengelig", compareTitle: "Den publiserte sammenligningen kunne ikke lastes.", compareCopy: "Vi viser ikke en annen sammenligning uten å kontrollere den først. Du kan fortsatt lese publiserte anmeldelser eller åpne beskyttet Hjelp.", browse: "Se anmeldelser", protectedHelp: "Åpne beskyttet Hjelp", notFoundLost: "Vi fant ikke denne siden.", notFoundBack: "Vi får deg tilbake på rett spor.", notFoundHome: "Gå til forsiden", notFoundAbout: "Om Programmet →" },
};

const comparisonUnavailableKickers: Partial<Record<SupportedLocale, string>> = {
  "en-GB": "Comparison temporarily unavailable",
  "de-DE": "Vergleich derzeit nicht verfügbar",
  "it-IT": "Confronto temporaneamente non disponibile",
  "es-ES": "Comparación temporalmente no disponible",
  "pt-PT": "Comparação temporariamente indisponível",
  "el-GR": "Η σύγκριση δεν είναι διαθέσιμη προς το παρόν",
  "nl-NL": "Vergelijking tijdelijk niet beschikbaar",
  "sv-SE": "Jämförelsen är tillfälligt inte tillgänglig",
  "da-DK": "Sammenligningen er midlertidigt utilgængelig",
  "fi-FI": "Vertailu ei ole juuri nyt saatavilla",
  "nb-NO": "Sammenligningen er midlertidig utilgjengelig",
};

export function publicErrorMessages(locale: SupportedLocale) {
  const messages = catalog[locale] ?? en;
  return { ...messages, compareKicker: comparisonUnavailableKickers[locale] ?? messages.compareKicker };
}
