import Link from "next/link";
import styles from "./BonusGuidePage.module.css";

const sources=[
  ["UK Gambling Commission","LCCP 5.1.1 — Rewards and bonuses","https://www.gamblingcommission.gov.uk/licensees-and-businesses/lccp/condition/5-1-1-sr-code"],
  ["ASA / CAP","Gambling, betting and gaming: Free bets and bonuses","https://www.asa.org.uk/advice-online/gambling-betting-and-gaming-free-bets-and-bonuses.html"],
] as const;

export function BonusGuideDocument(){return <article className={`${styles.page} bonusGuidePage`} data-bonus-guide>
  <header className={styles.hero}><div><nav><Link href="/learn">Learn</Link><span>→</span><span>Bonuses</span></nav><h1>Wagering requirements,<br/><em>explained with real numbers.</em></h1><p>What 35x actually costs you, when a smaller bonus is the better deal, and the three terms that quietly decide everything.</p><footer><span>By the B4GAMBLE test team</span><span>9 min read</span><span>Updated Aug 2026</span><span>Not sponsored · real-money tested</span></footer></div></header>
  <main className={styles.reading}>
    <aside><nav><strong>In this guide</strong><a href="#meaning">01 What 35x really means</a><a href="#maths">02 The maths on a real offer</a><a href="#weighting">03 Game weighting — the quiet tax</a><a href="#smaller">04 When smaller wins</a><a href="#checklist">05 The checklist</a></nav><div><strong>Control &amp; support</strong><p>Reading this because bonuses stopped feeling optional?</p><Link href="/help">Open Help — no offers there →</Link></div></aside>
    <div className={`${styles.prose} bonusGuideProse`}>
      <p className={styles.lead}>A casino advertises «100% up to €200». The number everyone reads is 200. The number that decides what you keep is printed two clicks deeper: <strong>35x wagering</strong>.</p>
      <p>Wagering requirements are the total amount you must bet before bonus money becomes withdrawable. They are not a scam — they are the price of the bonus. The problem is that the price is quoted in a currency most players never convert.</p>
      <section id="meaning"><h2><span>01</span>What 35x really means</h2><p>«35x» applies to the bonus amount — sometimes to bonus <em>plus deposit</em>, which doubles the real cost. Take the €200 bonus at 35x on bonus only:</p><dl className={styles.conversion}><div><dt>Bonus received</dt><dd>€200</dd></div><div><dt>Required turnover — 200 × 35</dt><dd>€7 000</dd></div><div><dt>Expected loss at 96% RTP slots</dt><dd>≈ €280</dd></div><div><dt>Expected value of the «free» €200</dt><dd>−€80</dd></div></dl><p>Statistically, clearing this bonus on standard slots costs more than the bonus is worth. That is not an accident of one operator — it is how 35x is designed to work at typical RTP.</p><blockquote>«A bonus is a loan you repay in turnover. Read the interest rate first.»</blockquote></section>
      <section id="maths"><h2><span>02</span>The maths on a real offer</h2><p>Three offers from our current test set, converted to the same currency — expected cost of clearing:</p><div aria-label="Illustrative bonus-cost comparison; scroll horizontally on narrow screens" className={`${styles.table} bonusGuideTable`} role="region" tabIndex={0}><div><b>Offer</b><b>Wagering</b><b>Turnover</b><b>Exp. cost</b></div><div><span>«€200 + 100 spins»</span><span>35x B</span><span>€7 000</span><strong>−€80</strong></div><div><span>«€50 low-wager»</span><span>10x B</span><span>€500</span><strong>+€30</strong></div><div><span>«€500 mega match»</span><span>40x D+B</span><span>€40 000</span><strong>−€1 100</strong></div></div><p>The €50 offer beats the €500 one by four figures. Headline size and player value are close to uncorrelated — which is why our rankings ignore the headline entirely.</p></section>
      <section id="weighting"><h2><span>03</span>Game weighting — the quiet tax</h2><p>Slots usually count 100% towards wagering. Blackjack often counts 10%, roulette 20%, some games 0%. Clear a 35x requirement on blackjack at 10% weighting and your effective requirement is <strong>350x</strong>.</p><aside className={styles.trap}><strong>Trap term</strong><p>«Max bet while wagering: €5.» Exceed it once — even accidentally — and most operators may void the bonus and winnings. Check this line before your first spin, not after.</p></aside></section>
      <section id="smaller"><h2><span>04</span>When smaller wins</h2><p>A useful rule of thumb: divide the bonus by the turnover it demands. Anything below 3% is expensive; above 8% is genuinely competitive. The best offers in our directory are almost always the modest ones with 10–15x on bonus only.</p></section>
      <section id="checklist"><h2><span>05</span>The checklist</h2><div className={styles.checklist}><strong>Before you accept any bonus</strong><ul><li>Wagering applies to bonus only — not deposit + bonus</li><li>Turnover ÷ bonus ratio is 12.5x or better</li><li>Your games count at 100% weighting</li><li>Max bet rule found and noted</li><li>Expiry gives you at least 14 days</li></ul></div><p>If an offer fails two or more of these, skip it. The deposit you keep is worth more than the bonus you clear.</p></section>
      <section className={styles.sources}><h2>Current source record</h2><p>The Draft Preview preserves the supplied article above. Current GB regulatory sources remain attached for the claims review.</p>{sources.map(([authority,title,url])=><a aria-label={`${authority}: ${title} (opens in a new tab)`} href={url} key={url} rel="noopener noreferrer" target="_blank"><span>{authority}</span><strong>{title}</strong><small>Checked 07 Aug 2026 ↗</small></a>)}</section>
    </div>
  </main>
  <section className={styles.readNext}><header><h2>Read next</h2><Link href="/learn">All guides →</Link></header><div><article><small>Bonuses</small><strong>Free spins: value, weighting and the fine print</strong><span>6 min read</span></article><article><small>Banking</small><strong>How casino payouts really work — and why they stall</strong><span>7 min read</span></article><article><small>Responsible play</small><strong>Session limits that actually hold</strong><span>6 min read</span></article></div></section>
  <section className={styles.bridge}><p>Beyond reading</p><h2>Knowledge is half of it.<br/><em>The plan is the other half.</em></h2><span>Ten missions that turn what you&apos;ve read into boundaries that hold. Free and private.</span><Link href="/program">Start Programme</Link></section>
</article>}
