import Link from "next/link";
import styles from "./BonusGuidePage.module.css";

const sources=[
  ["UK Gambling Commission","LCCP 5.1.1 — Rewards and bonuses","https://www.gamblingcommission.gov.uk/licensees-and-businesses/lccp/condition/5-1-1-sr-code"],
  ["ASA / CAP","Gambling, betting and gaming: Free bets and bonuses","https://www.asa.org.uk/advice-online/gambling-betting-and-gaming-free-bets-and-bonuses.html"],
] as const;

export function BonusGuideDocument(){return <article className={`${styles.page} bonusGuidePage`} data-bonus-guide>
  <header className={styles.hero}><div><nav><Link href="/learn">Learn</Link><span>→</span><span>Bonuses</span></nav><h1>Wagering requirements,<br/><em>explained with real numbers.</em></h1><p>How wagering changes required turnover, why a smaller bonus can require less play, and which material terms to check first.</p><footer><span>By the B4GAMBLE editorial team</span><span>9 min read</span><span>Reviewed Aug 2026</span><span>Educational examples · not current offers</span></footer></div></header>
  <main className={styles.reading}>
    <aside><nav><strong>In this guide</strong><a href="#meaning">01 The hypothetical 35x example</a><a href="#maths">02 Comparing fictional examples</a><a href="#weighting">03 Game weighting</a><a href="#smaller">04 Comparing turnover</a><a href="#checklist">05 The checklist</a></nav><div><strong>Control &amp; support</strong><p>Reading this because bonuses stopped feeling optional?</p><Link href="/help">Open Help — no offers there →</Link></div></aside>
    <div className={`${styles.prose} bonusGuideProse`}>
      <p className={styles.lead}>A fictional cross-market example advertises «100% up to €200». The headline is 200; the term that changes the required play is <strong>35x wagering</strong>.</p>
      <aside className={styles.trap}><strong>Current GB rule</strong><p>For GB-licensed operators, LCCP Social Responsibility Code 5.1.1 now prohibits wagering requirements over 10 times the incentive. The 35x figures below are hypothetical educational examples, not current eligible GB offers.</p></aside>
      <p>Wagering requirements are the total amount that must be bet before bonus funds become withdrawable. Convert that requirement into turnover and check the operator&apos;s current terms before deciding whether to accept any bonus.</p>
      <section id="meaning"><h2><span>01</span>What 35x means in a hypothetical example</h2><p>«35x» can apply to the bonus amount or, in some markets, to bonus <em>plus deposit</em>. Take a fictional €200 bonus at 35x on bonus only:</p><dl className={styles.conversion}><div><dt>Bonus received</dt><dd>€200</dd></div><div><dt>Required turnover — 200 × 35</dt><dd>€7 000</dd></div><div><dt>Simplified theoretical loss at 96% RTP</dt><dd>≈ €280</dd></div><div><dt>Simplified bonus less theoretical loss</dt><dd>−€80</dd></div></dl><p>This simplified expected-value illustration excludes variance, game weighting, maximum bets, win caps, expiry and other restrictions. It is not a prediction of an individual outcome.</p><blockquote>«Convert the requirement into turnover before accepting a bonus.»</blockquote></section>
      <section id="maths"><h2><span>02</span>Comparing fictional examples</h2><p>These fictional records show why the wagering base and multiplier matter. They are not current promotions or test results:</p><div aria-label="Illustrative bonus-cost comparison; scroll horizontally on narrow screens" className={`${styles.table} bonusGuideTable`} role="region" tabIndex={0}><div><b>Example</b><b>Wagering</b><b>Turnover</b><b>Simplified value</b></div><div><span>«€200 example»</span><span>35x B</span><span>€7 000</span><strong>−€80</strong></div><div><span>«€50 example»</span><span>10x B</span><span>€500</span><strong>+€30</strong></div><div><span>«€500 example»</span><span>40x D+B</span><span>€40 000</span><strong>−€1 100</strong></div></div><p>A larger headline can still require much more turnover. Compare every current material term rather than treating the illustrative values as an offer ranking.</p></section>
      <section id="weighting"><h2><span>03</span>Game weighting — the quiet tax</h2><p>Slots usually count 100% towards wagering. Blackjack often counts 10%, roulette 20%, some games 0%. Clear a 35x requirement on blackjack at 10% weighting and your effective requirement is <strong>350x</strong>.</p><aside className={styles.trap}><strong>Trap term</strong><p>«Max bet while wagering: €5.» Exceed it once — even accidentally — and most operators may void the bonus and winnings. Check this line before your first spin, not after.</p></aside></section>
      <section id="smaller"><h2><span>04</span>When smaller can mean less turnover</h2><p>Calculate the required turnover from the bonus amount, wagering base and multiplier. A smaller headline with a lower requirement can demand less play; eligibility, game weighting, maximum bet, expiry and withdrawal restrictions still matter.</p></section>
      <section id="checklist"><h2><span>05</span>The checklist</h2><div className={styles.checklist}><strong>Before you accept any bonus</strong><ul><li>Check whether wagering applies to bonus only or deposit + bonus</li><li>For GB-licensed operators, verify the requirement is no more than 10x the incentive</li><li>Check how your games contribute</li><li>Find and note any maximum bet and win-cap rules</li><li>Check eligibility, expiry and withdrawal restrictions</li></ul></div><p>If material terms are missing or unclear, do not rely on the headline. Verify the current operator terms or skip the incentive.</p></section>
      <section className={styles.sources}><h2>Current source record</h2><p>Current GB regulatory and advertising sources govern the statements above. The examples remain explicitly fictional and educational.</p>{sources.map(([authority,title,url])=><a aria-label={`${authority}: ${title} (opens in a new tab)`} href={url} key={url} rel="noopener noreferrer" target="_blank"><span>{authority}</span><strong>{title}</strong><small>Checked 18 Aug 2026 ↗</small></a>)}</section>
    </div>
  </main>
  <section className={styles.readNext}><header><h2>Read next</h2><Link href="/learn">All guides →</Link></header><div><Link href="/learn/casino-bonuses/welcome-bonus-terms"><small>Bonuses</small><strong>How Welcome Bonus Terms Work</strong><span>6 min read</span></Link><Link href="/learn/payments/casino-payment-methods"><small>Payments</small><strong>Casino Payment Methods Explained</strong><span>6 min read</span></Link><Link href="/learn/responsible-gambling/responsible-gambling-tools"><small>Responsible gambling</small><strong>Responsible Gambling Tools Explained</strong><span>6 min read</span></Link></div></section>
  <section className={styles.bridge}><p>Beyond reading</p><h2>Knowledge is half of it.<br/><em>The plan is the other half.</em></h2><span>Ten missions that turn what you&apos;ve read into boundaries that hold. Free and private.</span><Link href="/program">Start Programme</Link></section>
</article>}
