import Link from "next/link";
import styles from "./AffiliateDisclosurePage.module.css";

export function AffiliateDisclosureDocument(){return <article className={styles.page} data-affiliate-disclosure-document>
  <header className={styles.hero} data-affiliate-section="hero"><div><p className={styles.eyebrow}>Affiliate Disclosure</p><h1>How we&apos;re <em>funded.</em></h1><span>We may earn commission from clearly labelled affiliate links. Here is what that can—and cannot—change.</span></div></header>
  <main className={styles.document}>
    <section><h2>1. The commercial relationship</h2><p>Some links to gambling operators are affiliate links. If you follow an eligible affiliate link and complete a qualifying action—such as registering or depositing—the operator or affiliate network may pay 7BE Inc. a commission. The payment comes from the commercial partner; it does not add a separate B4GAMBLE charge to you.</p><p>A working affiliate route exists only when the operator, market, licence, offer, agreement and destination have passed the applicable B4GAMBLE controls. Otherwise the action remains unavailable.</p></section>
    <section><h2>2. How we label commercial content</h2><p>An active commercial action is labelled next to the link: <strong>Affiliate link · We may earn commission.</strong> A paid placement, if introduced, must be labelled <strong>Advertisement · Sponsored placement</strong> before the user engages with it. Editorial links use labels such as Read review or Methodology and do not present themselves as an offer.</p><p>The outbound confirmation repeats that you are leaving B4GAMBLE and that we may earn commission. The operator&apos;s terms, privacy notice and eligibility decisions apply after you leave.</p></section>
    <section><h2>3. What compensation can influence</h2><p>Compensation can affect whether an otherwise eligible operator or offer has an active outbound affiliate route. It can also fund B4GAMBLE. If there is no approved route, the review may remain available but the commercial action is disabled.</p></section>
    <section><h2>4. What compensation does not determine</h2><p>Affiliate compensation does not determine Editor Score or natural editorial ranking. Commercial availability and editorial assessment are separate application concerns. A commercial relationship is not a licence, safety, quality or suitability guarantee.</p><p>Programme, protected Help, pause, self-check and vulnerability information is not used to choose, rank or personalise casinos, bonuses, sponsored placements or affiliate destinations. We do not sell that data.</p></section>
    <section><h2>5. Offers and significant conditions</h2><p>Offer headlines are summaries. Age, territory, new-customer status, deposit, wagering, game weighting, maximum stake, minimum odds, expiry, payment-method and withdrawal conditions may apply. We show material conditions before an available action and link to full operator terms. Check the operator&apos;s current terms before acting; do not assume “free” or “risk-free” where your own money is at risk.</p></section>
    <section><h2>6. Sponsored and demonstration content</h2><p>Any future sponsored placement must be visually separate and obviously identifiable as advertising. Sponsorship must not be presented as an editorial conclusion or change Editor Score. Fictional demonstration records are labelled as demonstration data, have no gambling or affiliate link, and are not current operators, offers or partners.</p></section>
    <section><h2>7. Method and corrections</h2><p>Read the <Link href="/methodology">Methodology</Link> for how evidence, limitations and scores are presented. If a disclosure is missing or you believe a commercial relationship has influenced editorial output, <Link href="/contact">contact us</Link>. Corrections are reviewed and dated when published.</p></section>
    <footer className={styles.effective}><span>Effective 19 August 2026</span><span>18+ · Gambling involves financial risk</span></footer>
  </main>
</article>}
