import Link from "next/link";
import styles from "./AffiliateDisclosurePage.module.css";

export function AffiliateDisclosureDocument(){return <article className={styles.page} data-affiliate-disclosure-document>
  <header className={styles.hero} data-affiliate-section="hero"><div><p className={styles.eyebrow}>Affiliate Disclosure</p><h1>How we&apos;re <em>funded.</em></h1><span>Commission may fund us. It never sets a score. Here is exactly where the line runs.</span></div></header>
  <main className={styles.document}>
    <section><h2>1. How B4GAMBLE is funded</h2><p>When you follow a commercial link on this site — View Offer, Visit Casino, Claim Offer — and subsequently register or deposit at the operator, we may receive a commission from that operator. This is the site&apos;s only revenue model. We do not sell paid placements, sponsored reviews, advertising slots or user data.</p><p>The Programme, Help, Learn and all trust pages generate no revenue and carry no commercial links.</p></section>
    <section><h2>2. What commission can influence</h2><p>Which operators appear with an active outbound route. If no commercial agreement or governed link exists, the page shows &quot;Review only&quot; or &quot;Offer unavailable&quot; instead of a working button. Commission also determines whether the site can afford to keep testing — that is its entire legitimate role.</p></section>
    <section><h2>3. What commission cannot influence</h2><p>Affiliate compensation does not determine Editor Score or natural editorial ranking. That boundary covers review text, use-case shortlists and the Best Offers selection. Scores are locked before commercial terms are discussed; reviewers are not told operator-specific commission rates before a score is final. Several operators from whom we earn nothing outrank operators from whom we do.</p><p>Programme and Help data is never used to target offers or personalise rankings, in either direction.</p></section>
    <section><h2>4. How commercial links are identified</h2><p>Every commercial action passes through an outbound confirmation that states you are leaving B4GAMBLE and repeats this disclosure. Buttons labelled View Offer, Visit Casino or Claim Offer are always commercial; editorial links (Read Review, guides, methodology) never are. We do not disguise commercial links as editorial ones.</p></section>
    <section><h2>5. Corrections and further reading</h2><p>How we test and score is documented in the <Link href="/methodology">Methodology</Link>. Errors are corrected within 48 hours of verification and noted in the affected text. If you believe a commercial relationship has influenced our editorial output, <Link href="/contact">tell us</Link> — that report goes to the editorial side, not the commercial one.</p></section>
    <footer className={styles.effective}><span>Effective 12 August 2026</span><span>18+ · BeGambleAware.org</span></footer>
  </main>
</article>}
