import Link from "next/link";
import styles from "./MethodologyPage.module.css";

export const methodologyFaqItems = [
  ["Does commission affect scores?","No. Scores and reviews are completed before commercial terms are discussed."],
  ["Are test results guarantees?","No. They are dated observations from particular methods and jurisdictions."],
] as const;

export function MethodologyDocument(){return <article className={styles.page}>
  <header className={styles.hero}><div><p className={styles.eyebrow}>Methodology</p><h1>Evidence before <em>opinion.</em></h1><span>Every score on this site traces back to a test we ran with our own money. This page shows the whole machine — including its limits.</span></div></header>
  <section className={styles.band}><div className={styles.split}>
    <article><p>01 · How we evaluate casinos</p><h2>One cycle. Every casino. No exceptions.</h2><p>Every operator on this site went through the same evaluation cycle: an ordinary player account, our own money, and at least four weeks of observation before a single word is published. No press accounts, no operator assistance, no shortcuts for anyone.</p><p>The cycle produces raw records — deposit and withdrawal timestamps, transcribed terms, support transcripts — which we keep for at least 24 months after publication. Every claim in a review traces back to one of them.</p></article>
    <article><ul><li>Real accounts, real deposits</li><li>Three withdrawal methods, four weeks</li><li>Terms read line by line</li><li>Support and games, tested at 3 a.m.</li></ul></article>
  </div></section>
  <section className={styles.band}><div className={styles.split}>
    <article><p>02 · What affects the score</p><h2>Judgement, informed by tests.</h2><p>The Editor Score is editorial judgement grounded in test results — not the output of a fixed arithmetic formula, and no percentage weighting should be inferred from it. The ordering of influence, however, is stable and public: payout reliability weighs heaviest, honesty of terms second, everything else after.</p><p>Some findings act as caps, not weights: an unresolved verified non-payment, a withdrawal we couldn&apos;t complete during the observation window, or marketing that misrepresents the operator&apos;s own terms means no recommendation — regardless of how good everything else looks.</p></article>
    <div className={styles.scoreList}><div><strong>Payout speed &amp; reliability</strong><span>weighs heaviest</span></div><div><strong>Honesty of bonus terms</strong><span>heavy</span></div><div><strong>Game library &amp; live floor</strong><span>moderate</span></div><div><strong>Support quality</strong><span>moderate</span></div><div><strong>Verification friction</strong><span>moderate</span></div><div><strong>Commission we might earn</strong><span>never a factor</span></div></div>
  </div></section>
  <section className={styles.band}><div className={styles.cards}>
    <article><p>03 · How Best Offers are selected</p><p>The #1 pick is the casino with the strongest current combination of verified payout results and realistic bonus net value — the interval we measured, applied to the terms we transcribed. It changes when the evidence changes: not on a schedule, not in rotation, and never because of a commercial negotiation.</p><p>Alternatives are chosen to answer materially different needs — lower wagering, lower deposit floor — not to enumerate rank positions or pad the page. Use-case shortlists on Casinos and Bonuses follow the same rule, capped at three operators each. There is no mechanism, at any price, by which an operator can buy a position.</p></article>
    <article><p>04 · Editorial vs commercial</p><p>Affiliate compensation does not determine Editor Score or natural editorial ranking. Scores and reviews are finished before commercial terms are discussed. The people who negotiate partnerships have no editing access to reviews; the people who write reviews are not told operator-specific commission rates until after a score is locked.</p><p>The same wall protects you in the other direction: Programme and Help activity is never used to target offers, personalise rankings or feed advertising — it stays on its side of the product, permanently.</p></article>
  </div></section>
  <section className={styles.band}><div className={styles.split}>
    <article><p>05 · Sources, freshness, corrections</p><p>A review is only as good as its date. Every published review carries the day its material facts were last verified, and re-verification runs on a rolling basis — immediately when credible information suggests an operator changed behaviour or terms.</p><ul><li>Last-verified date visible next to every score.</li><li>Material term changes trigger a re-review and a noted correction in the affected text.</li><li>Corrections ship within 48 hours of verification. Spotted an error? <Link href="/contact">Tell us</Link>.</li><li>Raw test records are retained for 24 months after the review they support.</li></ul></article>
    <article><p>06 · Limitations — read this part</p><p>An honest methodology admits what it can&apos;t do. Our findings are observations of operator behaviour at particular moments, from particular jurisdictions, with particular payment instruments and amounts — snapshots, not guarantees.</p><ul><li>An operator can change behaviour after we publish; your outcome may differ from ours.</li><li>Payout times vary by method, jurisdiction, amount and account history.</li><li>RTP spot checks compare published sheets; we cannot verify RTP empirically through play.</li><li>We can&apos;t test every casino in every country. Absence of a review is not a verdict, and presence of one is not a claim of availability in your jurisdiction.</li></ul></article>
  </div></section>
</article>}
